<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>Foundgine.Execution</RootNamespace>
    <AssemblyName>Foundgine.Execution</AssemblyName>
    <IsPackable>true</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Foundgine.Abstractions/Foundgine.Abstractions.csproj" />
    <ProjectReference Include="../Foundgine.Planning/Foundgine.Planning.csproj" />
  </ItemGroup>
</Project>
