<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk"  />
    <PackageReference Include="xunit"  />
    <PackageReference Include="xunit.runner.visualstudio"  />
    <PackageReference Include="Npgsql"  />
    <ProjectReference Include="../../samples/Foundgine.HighAssurance.Postgres/Foundgine.HighAssurance.Postgres.csproj" />
    <ProjectReference Include="../../samples/Foundgine.HighAssurance.Banking/Foundgine.HighAssurance.Banking.csproj" />
    <ProjectReference Include="../../src/Foundgine.Security.Authority/Foundgine.Security.Authority.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Update="schema.sql" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
