// using CoffeeBeanery.GraphQL.Core.Mapping;
// using Microsoft.EntityFrameworkCore;
//
// namespace CoffeeBeanery.GraphQL.Core.Sql;
//
// public sealed class NodeBuilder<TContext>
//     where TContext : DbContext
// {
//     private readonly EfEntityMetadata<TContext> _metadata;
//
//     public NodeBuilder(EfEntityMetadata<TContext> metadata)
//     {
//         _metadata = metadata;
//     }
//
//     public Graph Build()
//     {
//         var graph = new Graph();
//         var all = MappingRegistry.GetAll();
//
//         foreach (var (_, map) in all)
//             InferModelChildren(map);
//
//         foreach (var (_, map) in all)
//             GenerateReflectedFieldMaps(map);
//
//         foreach (var (_, map) in all)
//             ResolveFieldMapAliases(map);
//
//         foreach (var (_, map) in all)
//             BuildNodes(graph, map);
//
//         BuildRoleAliasClones(graph, all);
//
//         // NEW: resolve auto-generated ChildAttachments (join column +
//         // owning entity) now that every map's EntityType/canonical alias
//         // is known. Must run before BuildEdges, which is what actually
//         // turns ChildAttachments into graph edges.
//         ResolveAutoChildAttachments(all);
//         
//         Console.WriteLine("=== ChildAttachments after resolution ===");
//         foreach (var (alias, m) in all)
//         {
//             foreach (var att in m.ChildAttachments)
//             {
//                 Console.WriteLine($"  Parent={alias}, Field={att.FieldName}, ToModel={att.ToModelName}, " +
//                                   $"Resolved={!string.IsNullOrWhiteSpace(att.ParentJoinColumn)}, " +
//                                   $"ParentJoinColumn={att.ParentJoinColumn}, ChildEntityType={att.ChildEntityType?.Name}, ChildJoinColumn={att.ChildJoinColumn}");
//             }
//         }
//
//         foreach (var (_, map) in all)
//         {
//             BuildEdges(graph, map);
//             RegisterFieldLookups(map);
//         }
//
//         CloneRoleAliasFieldLookups(all);
//
//         return graph;
//     }
//
//     // ------------------------------------------------------------
//     // CHILD ATTACHMENTS (cross-model nesting, e.g. Customer -> Product)
//     // ------------------------------------------------------------
//
//     /// <summary>
//     /// For every NodeMap's ChildAttachments list, fill in the join column
//     /// details for any entry that's auto-generated and not yet resolved
//     /// (ParentJoinColumn left blank by the generator). Hand-written entries
//     /// (IsAutoGenerated == false) are left untouched - they're expected to
//     /// carry their own ParentJoinColumn/ChildEntityType/ChildJoinColumn.
//     ///
//     /// Convention: the parent's primary entity is expected to have a column
//     /// named "{ParentModelTypeName}Key" (matches the pattern already used
//     /// throughout the mappings - CustomerKey, AccountKey, ContractKey, etc).
//     /// The child model's own ModelToEntity list is then searched for any
//     /// composite entity that has a column of that same name - that entity
//     /// is the one carrying the FK back to the parent (e.g. Product's
//     /// CustomerBankingRelationship link, which has a CustomerKey column).
//     ///
//     /// Attachments that don't match this convention are left unresolved
//     /// (ParentJoinColumn stays blank) and are skipped by BuildEdges - they
//     /// require a hand-written ChildAttachment instead.
//     /// </summary>
//     private void ResolveAutoChildAttachments(IReadOnlyDictionary<string, NodeMap> allMaps)
//     {
//         foreach (var (_, parentMap) in allMaps)
//         {
//             if (parentMap.EntityType is null)
//                 continue;
//
//             foreach (var attachment in parentMap.ChildAttachments)
//             {
//                 if (!attachment.IsAutoGenerated)
//                     continue;
//
//                 if (!string.IsNullOrWhiteSpace(attachment.ParentJoinColumn))
//                     continue;
//
//                 if (!allMaps.TryGetValue(attachment.ToModelName, out var childMap) || childMap.EntityType is null)
//                     continue;
//
//                 var parentJoinColumn = $"{parentMap.ModelType.Name}Key";
//
//                 if (parentMap.EntityType.GetProperty(parentJoinColumn) is null)
//                     continue;
//
//                 var match = childMap.ModelToEntity
//                     .FirstOrDefault(link => link.EntityType.GetProperty(parentJoinColumn) is not null);
//
//                 if (match is null)
//                     continue; // no composite entity on the child side carries this FK
//
//                 attachment.ParentEntityType = parentMap.EntityType;
//                 attachment.ParentJoinColumn = parentJoinColumn;
//                 attachment.ChildEntityType = match.EntityType;
//                 attachment.ChildJoinColumn = parentJoinColumn;
//             }
//         }
//     }
//
//     private void CloneRoleAliasFieldLookups(IReadOnlyDictionary<string, NodeMap> allMaps)
//     {
//         foreach (var (_, map) in allMaps)
//         {
//             foreach (var link in map.ModelToEntity)
//             {
//                 if (string.IsNullOrEmpty(link.AliasProperty))
//                     continue;
//
//                 var resolvedAlias = $"{link.AliasProperty}{link.EntityType.Name}";
//                 var canonicalAlias = link.EntityType.Name;
//
//                 if (resolvedAlias == canonicalAlias)
//                     continue;
//
//                 foreach (var kvp in NodeRegistry.ColumnByField.ToList())
//                 {
//                     if (kvp.Key.Alias != canonicalAlias) continue;
//
//                     var key = (resolvedAlias, kvp.Key.Field);
//                     if (!NodeRegistry.ColumnByField.ContainsKey(key))
//                         NodeRegistry.ColumnByField[key] = new List<(string EntityAlias, string EntityColumn)>(kvp.Value);
//                 }
//
//                 foreach (var kvp in NodeRegistry.EnumByField.ToList())
//                 {
//                     if (kvp.Key.Alias != canonicalAlias) continue;
//
//                     var key = (resolvedAlias, kvp.Key.Field);
//                     if (!NodeRegistry.EnumByField.ContainsKey(key))
//                         NodeRegistry.EnumByField[key] = kvp.Value;
//                 }
//             }
//         }
//     }
//
//     private void BuildRoleAliasClones(Graph graph, IReadOnlyDictionary<string, NodeMap> allMaps)
//      {
//          foreach (var (_, map) in allMaps)
//          {
//              foreach (var link in map.ModelToEntity)
//              {
//                  var resolvedAlias = $"{link.AliasProperty}{link.EntityType.Name}";
//
//                  if (NodeRegistry.EntityTrees.ContainsKey(resolvedAlias))
//                      continue;
//
//                  var canonicalAlias = link.EntityType.Name;
//
//                  if (!NodeRegistry.EntityTrees.TryGetValue(canonicalAlias, out var canonical))
//                      continue;
//
//                  graph.Nodes.TryAdd(resolvedAlias, new GraphNode
//                  {
//                      Alias = resolvedAlias,
//                      Name = canonical.Name,
//                  });
//
//                  NodeRegistry.EntityTrees.TryAdd(resolvedAlias, new EntityNodeTree
//                  {
//                      Alias = resolvedAlias,
//                      ModelName = canonical.ModelName,
//                      Name = canonical.Name,
//                      Schema = canonical.Schema,
//                      Prefix = canonical.Prefix,
//                      NodeMap = canonical.NodeMap,
//                      EntityType = canonical.EntityType,
//                      ModelType = canonical.ModelType,
//                      IsGraph = canonical.IsGraph,
//                      IsEntity = canonical.IsEntity,
//                      IsModel = canonical.IsModel,
//                      GraphMap = canonical.GraphMap,
//                      EntityChildren = canonical.EntityChildren,
//                      EntityChildrenRelated = canonical.EntityChildrenRelated,
//                      ModelToEntity = canonical.ModelToEntity,
//                      Mapping = canonical.Mapping,
//                      UpsertKeys = canonical.UpsertKeys
//                  });
//              }
//          }
//      }
//
//     private void BuildNodes(Graph graph, NodeMap map)
//     {
//         if (map.IsModel)
//         {
//             graph.Nodes.TryAdd(map.Alias, new GraphNode
//             {
//                 Alias = map.Alias,
//                 Name = map.ModelType.Name,
//             });
//
//             NodeRegistry.ModelTrees.TryAdd(map.Alias, new ModelNodeTree
//             {
//                 Alias = map.Alias,
//                 ModelName = map.ModelName ?? map.ModelType.Name,
//                 ModelType = map.ModelType,
//                 EntityType = map.IsEntity ? map.EntityType : null
//             });
//         }
//
//         if (map.IsEntity)
//         {
//             var primaryLink = map.ModelToEntity.FirstOrDefault(l => l.EntityType == map.EntityType);
//
//             var canonicalAlias = primaryLink != null
//                 ? $"{primaryLink.AliasProperty}{primaryLink.EntityType.Name}"
//                 : map.EntityType.Name;
//
//             graph.Nodes.TryAdd(canonicalAlias, new GraphNode
//             {
//                 Alias = canonicalAlias,
//                 Name = map.EntityType.Name,
//             });
//
//             NodeRegistry.EntityTrees.TryAdd(canonicalAlias, new EntityNodeTree
//             {
//                 Alias = canonicalAlias,
//                 ModelName = map.ModelName ?? map.ModelType?.Name ?? map.EntityType.Name,
//                 Name = map.EntityType.Name,
//                 Schema = map.Schema,
//                 Prefix = map.Prefix,
//                 NodeMap = map,
//                 EntityType = map.EntityType,
//                 ModelType = map.ModelType,
//                 IsGraph = map.IsGraph,
//                 IsEntity = map.IsEntity,
//                 IsModel = map.IsModel,
//                 GraphMap = map.GraphMap,
//                 EntityChildren = map.EntityChildren,
//                 EntityChildrenRelated = map.EntityChildrenRelated,
//                 ModelToEntity = map.ModelToEntity,
//                 Mapping = map.FieldMaps,
//                 UpsertKeys = map.UpsertKeys.Select(k => k.Key).ToList()
//             });
//
//             NodeRegistry.CanonicalEntityAliasByModelAlias[map.Alias] = canonicalAlias;
//         }
//     }
//
//     private void BuildEdges(Graph graph, NodeMap map)
//     {
//         var fromAlias = NormalizeAlias(map.Alias);
//
//         var canonicalAlias =
//             NodeRegistry.CanonicalEntityAliasByModelAlias.TryGetValue(fromAlias, out var ca)
//                 ? NormalizeAlias(ca)
//                 : null;
//
//         foreach (var field in map.FieldMaps)
//         {
//             var toAlias = ResolveDestinationAlias(map, field);
//             var fieldName = NodeRegistry.ToGraphQlFieldName(field.SourceName);
//
//             AddScalarEdgeAndLeaf(graph, fromAlias, toAlias, fieldName, field.DestinationName);
//
//             if (canonicalAlias != null && canonicalAlias != fromAlias)
//                 AddScalarEdgeAndLeaf(graph, canonicalAlias, toAlias, fieldName, field.DestinationName);
//         }
//
//         var seenModelToEntityKeys = new HashSet<(string, string)>();
//
//         foreach (var link in map.ModelToEntity)
//         {
//             var fieldName = NodeRegistry.ToGraphQlFieldName(link.AliasProperty);
//
//             if (string.IsNullOrWhiteSpace(fieldName))
//                 fieldName = NodeRegistry.ToGraphQlFieldName(link.FromColumn);
//
//             var key = (fromAlias.ToLowerInvariant(), fieldName.ToLowerInvariant());
//
//             if (!seenModelToEntityKeys.Add(key))
//                 continue;
//
//             var toAlias = $"{link.AliasProperty}{link.EntityType.Name}";
//
//             AddModelToEntityEdge(graph, fromAlias, toAlias, fieldName, link);
//             RegisterModelToEntityLeaf(fromAlias, fieldName, link, toAlias);
//
//             if (canonicalAlias != null && canonicalAlias != fromAlias)
//             {
//                 AddModelToEntityEdge(graph, canonicalAlias, toAlias, fieldName, link);
//                 RegisterModelToEntityLeaf(canonicalAlias, fieldName, link, toAlias);
//             }
//         }
//
//         // NEW: ChildAttachments -> graph edges. Lets a model nest under a
//         // different parent model even with no EF navigation to discover it.
//         foreach (var attachment in map.ChildAttachments)
//         {
//             if (string.IsNullOrWhiteSpace(attachment.ParentJoinColumn) || attachment.ChildEntityType is null)
//                 continue; // unresolved - convention didn't match, needs a hand-written entry
//
//             // The child's NodeMap.Alias may differ from attachment.ToModelName
//             // if the child registered under a prefix/role alias; ToModelName
//             // is expected to be the child map's own canonical Alias as set in
//             // BaseMappingRegistration.Register() (RegistrationKey), which for
//             // an unprefixed model (the common case, e.g. "Product") is just
//             // the model type name - matching what ModelChildrenInference and
//             // the EmitChildAttachments generator block both assume.
//             var toAlias = attachment.ToModelName;
//
//             var key = (fromAlias.ToLowerInvariant(), attachment.FieldName.ToLowerInvariant());
//             if (!seenModelToEntityKeys.Add(key))
//                 continue;
//
//             var syntheticLink = new EntityKey
//             {
//                 EntityType = attachment.ChildEntityType,
//                 FromColumn = attachment.ParentJoinColumn,
//                 ToColumn = attachment.ChildJoinColumn,
//                 To = attachment.ChildEntityType.Name,
//                 AliasProperty = string.Empty
//             };
//
//             AddModelToEntityEdge(graph, fromAlias, toAlias, attachment.FieldName, syntheticLink);
//             RegisterModelToEntityLeaf(fromAlias, attachment.FieldName, syntheticLink, toAlias);
//
//             if (canonicalAlias != null && canonicalAlias != fromAlias)
//             {
//                 AddModelToEntityEdge(graph, canonicalAlias, toAlias, attachment.FieldName, syntheticLink);
//                 RegisterModelToEntityLeaf(canonicalAlias, attachment.FieldName, syntheticLink, toAlias);
//             }
//         }
//     }
//
//     private static string NormalizeAlias(string alias)
//     {
//         if (string.IsNullOrWhiteSpace(alias))
//             return alias;
//
//         return alias.Trim();
//     }
//
//     private void RegisterModelToEntityLeaf(
//         string alias,
//         string fieldName,
//         EntityKey link,
//         string targetAlias)
//     {
//         var key = (alias, fieldName);
//
//         if (!NodeRegistry.ColumnByField.TryGetValue(key, out var cols))
//         {
//             cols = new List<(string EntityAlias, string EntityColumn)>();
//             NodeRegistry.ColumnByField[key] = cols;
//         }
//
//         cols.Add((link.EntityType.Name, link.FromColumn));
//     }
//
//     private void AddScalarEdgeAndLeaf(Graph graph, string fromAlias, string toAlias, string fieldName, string destinationName)
//     {
//         graph.Edges.Add(new GraphEdge
//         {
//             FromAlias = fromAlias,
//             ToAlias = toAlias,
//             FieldName = string.IsNullOrEmpty(fieldName) ?  destinationName : fieldName,
//             Kind = GraphEdgeKind.ScalarField
//         });
//
//         var key = (fromAlias, fieldName);
//         if (!NodeRegistry.ColumnByField.TryGetValue(key, out var cols))
//         {
//             cols = new List<(string EntityAlias, string EntityColumn)>();
//             NodeRegistry.ColumnByField[key] = cols;
//         }
//         cols.Add((toAlias, destinationName));
//     }
//
//     private void AddModelToEntityEdge(Graph graph, string fromAlias, string toAlias, string fieldName, EntityKey link)
//     {
//         graph.Edges.Add(new GraphEdge
//         {
//             FromAlias = fromAlias,
//             ToAlias = toAlias,
//             FieldName = string.IsNullOrEmpty(fieldName) ?  link.FromColumn : fieldName,
//             Kind = GraphEdgeKind.ModelToEntity,
//             FromColumn = link.FromColumn,
//             ToColumn = link.ToColumn,
//             Path = link.Path
//         });
//     }
//
//     private string ResolveDestinationAlias(NodeMap map, FieldMap field)
//     {
//         var key = (map.Alias, field.SourceName);
//         if (NodeRegistry.ChildAliasByField.TryGetValue(key, out var alias))
//             return alias;
//
//         if (!string.IsNullOrWhiteSpace(field.DestinationEntity))
//             return field.DestinationEntity;
//
//         return map.Alias;
//     }
//
//     private void GenerateReflectedFieldMaps(NodeMap map)
//     {
//         if (map.ModelType is null || map.EntityType is null)
//             return;
//
//         if (map.ModelProperties.Count == 0)
//             foreach (var p in map.ModelType.GetProperties())
//                 map.ModelProperties[p.Name] = p;
//
//         if (map.EntityProperties.Count == 0)
//             foreach (var p in map.EntityType.GetProperties())
//                 map.EntityProperties[p.Name] = p;
//
//         var alreadyMapped = new HashSet<string>(
//             map.FieldMaps.Select(f => f.SourceName),
//             StringComparer.OrdinalIgnoreCase);
//
//         var excluded = new HashSet<string>(
//             map.ExcludedFieldMappings.Select(f => f.SourceName),
//             StringComparer.OrdinalIgnoreCase);
//
//         var fkSourceColumns = new HashSet<string>(
//             map.ModelToEntity
//                 .Where(k => k.EntityType != map.EntityType)
//                 .Select(k => k.FromColumn),
//             StringComparer.OrdinalIgnoreCase);
//
//         foreach (var (name, _) in map.ModelProperties)
//         {
//             if (alreadyMapped.Contains(name) || excluded.Contains(name) || fkSourceColumns.Contains(name))
//                 continue;
//
//             if (!map.EntityProperties.TryGetValue(name, out var entityProp))
//                 continue;
//
//             map.FieldMaps.Add(new FieldMap
//             {
//                 SourceName = name,
//                 DestinationEntity = map.EntityType.Name,
//                 DestinationName = entityProp.Name
//             });
//         }
//     }
//
//     private void ResolveFieldMapAliases(NodeMap map)
//     {
//         foreach (var field in map.FieldMaps)
//         {
//             field.SourceAlias = map.Alias;
//
//             if (string.IsNullOrEmpty(field.DestinationEntity))
//             {
//                 field.DestinationAlias = map.Alias;
//                 continue;
//             }
//
//             var link = map.ModelToEntity
//                 .FirstOrDefault(l => l.EntityType.Name == field.DestinationEntity);
//
//             field.DestinationAlias = link != null
//                 ? $"{link.AliasProperty}{link.EntityType.Name}"
//                 : field.DestinationEntity;
//         }
//     }
//
//     private void RegisterFieldLookups(NodeMap map)
//     {
//         string? canonicalAlias =
//             map.IsEntity &&
//             NodeRegistry.CanonicalEntityAliasByModelAlias.TryGetValue(map.Alias, out var ca) &&
//             ca != map.Alias
//                 ? ca
//                 : null;
//
//         foreach (var field in map.FieldMaps)
//         {
//             var key = (field.SourceAlias, field.SourceName);
//
//             if (!NodeRegistry.ColumnByField.TryGetValue(key, out var cols))
//             {
//                 cols = new List<(string EntityAlias, string EntityColumn)>();
//                 NodeRegistry.ColumnByField[key] = cols;
//             }
//
//             cols.Add((field.DestinationAlias, field.DestinationName));
//
//             if (field.ToEnum != null && field.ToEnum.Count > 0)
//                 NodeRegistry.EnumByField[key] = field.ToEnum;
//
//             if (canonicalAlias != null && canonicalAlias != field.SourceAlias)
//             {
//                 var canonicalKey = (canonicalAlias, field.SourceName);
//
//                 if (!NodeRegistry.ColumnByField.TryGetValue(canonicalKey, out var canonicalCols))
//                 {
//                     canonicalCols = new List<(string EntityAlias, string EntityColumn)>();
//                     NodeRegistry.ColumnByField[canonicalKey] = canonicalCols;
//                 }
//
//                 canonicalCols.Add((field.DestinationAlias, field.DestinationName));
//
//                 if (field.ToEnum != null && field.ToEnum.Count > 0)
//                     NodeRegistry.EnumByField[canonicalKey] = field.ToEnum;
//             }
//         }
//
//         foreach (var link in map.ModelToEntity)
//         {
//             var key = (map.Alias, link.AliasProperty);
//             NodeRegistry.ChildAliasByField[key] = $"{link.AliasProperty}{link.EntityType.Name}";
//         }
//     }
//
//     public void BuildFromMappings()
//     {
//         var graph = Build();
//         NodeRegistry.Register(graph);
//         NodeRegistry.Freeze();
//     }
//
//     private void InferModelChildren(NodeMap map) { }
// }