<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>Foundgine.HighAssurance.Postgres</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Foundgine.HighAssurance.Banking/Foundgine.HighAssurance.Banking.csproj" />
    <ProjectReference Include="../../src/Foundgine.Execution/Foundgine.Execution.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Npgsql" Version="9.0.4" />
  </ItemGroup>
</Project>
