using Foundgine.Builders;
using Foundgine.Execution.Contracts;
using Foundgine.Metadata;
using Foundgine.Planning;
using Foundgine.Providers;
using Foundgine.Semantic;
using Foundgine.Semantic.Intent;
using Foundgine.Semantic.Resolution;
using Microsoft.Data.Sqlite;
using Xunit;
using ExecutionContext = Foundgine.Execution.Contracts.ExecutionContext;

namespace Foundgine.Tests;

/// <summary>
/// The bridge the architecture review flagged as the biggest gap after
/// Milestone 2: <c>Foundgine.Semantic</c>'s <see cref="EntityResolver"/>
/// and <c>Foundgine.Planning</c>'s <see cref="QueryPlanner"/> were "two
/// separate worlds" — a resolver that only ever produced a
/// <see cref="ResolvedReference"/> in isolation, and a planner that only
/// ever consumed a hand-built <see cref="QueryIntent"/>. Nothing connected
/// the two.
///
/// This test is that connection, proving the review's own target sentence
/// end to end against a real database with nothing faked:
///
/// <code>
/// "Find Ada's last five transactions."
///          │
///          ▼
///     ReadIntent                         (Foundgine.Semantic.Intent)
///          │
///          ▼
///     ReadPlanner + EntityResolver        (Foundgine.Semantic.Resolution)
///          │
///          ▼
///     ResolvedReadPlan
///          │
///          ▼  (this test's own translation step — the bridge itself)
///     QueryIntent (Filter/Sort/Page)      (Foundgine.Planning)
///          │
///          ▼
///     QueryPlanner -> QueryPlan -> SqlPlanCompiler -> ProviderPlan
///          │
///          ▼
///     SqlExecutionProvider -> real SQLite -> ExecutionRow
/// </code>
///
/// Per the review: don't teach <see cref="EntityResolver"/> English, and
/// don't fake WHERE/ORDER BY/LIMIT. Both hold here — the sentence itself
/// is never parsed by anything in this test; <see cref="ReadIntent"/> is
/// constructed by hand exactly the way an LLM or any other intent
/// extractor would hand it to Foundgine, and the WHERE/ORDER BY/LIMIT
/// clause below is real, generated by <c>Foundgine.Providers.SqlTextTranslator</c>
/// (Milestone 6/7, already proven independently by
/// <see cref="FilterSortPageEndToEndTests"/>), not simulated.
/// </summary>
public sealed class ReadIntentEndToEndTests : IAsyncLifetime
{
    private readonly string _connectionString =
        $"Data Source=file:{Guid.NewGuid():N};Mode=Memory;Cache=Shared";

    private SqliteConnection _keeper = null!;

    private static readonly EntityMetadata Customer = new(
        new EntityId(1),
        "Customer",
        new ColumnMetadata[]
        {
            new(new ColumnId(1), "Id"),
            new(new ColumnId(2), "Name"),
        });

    private static readonly EntityMetadata Account = new(
        new EntityId(2),
        "Account",
        new ColumnMetadata[]
        {
            new(new ColumnId(1), "Id"),
            new(new ColumnId(2), "CustomerId"),
            new(new ColumnId(3), "Balance"),
        });

    private static readonly EntityMetadata TransactionEntity = new(
        new EntityId(3),
        "Transaction",
        new ColumnMetadata[]
        {
            new(new ColumnId(1), "Id"),
            new(new ColumnId(2), "AccountId"),
            new(new ColumnId(3), "Amount"),
        });

    private static readonly JoinMetadata AccountToCustomer = new(
        new JoinCondition(
            new ColumnReference(Account, 2),
            new ColumnReference(Customer, 1)),
        JoinKind.Inner);

    private static readonly JoinMetadata AccountToTransaction = new(
        new JoinCondition(
            new ColumnReference(TransactionEntity, 2),
            new ColumnReference(Account, 1)),
        JoinKind.Inner);

    // Semantic-layer identities, kept deliberately independent of the
    // Foundgine.Metadata EntityId/ColumnId numbering above — nothing here
    // relies on the two numbering schemes lining up, only on both sides
    // agreeing on which EntityId means "Account" etc.
    private static readonly FieldId CustomerNameField = new(2);
    private static readonly RelationshipId CustomerAccounts = new(1);
    private static readonly RelationshipId AccountTransactions = new(2);

    private static SemanticModel BuildSemanticModel() =>
        new SemanticModelBuilder()
            .Entity(Customer.EntityId, "Customer", c => c
                .Identity(new FieldId(1), "Id")
                .Field(CustomerNameField, "Name", typeof(string))
                .Relationship(CustomerAccounts, "Accounts", Account.EntityId, RelationshipCardinality.Many)
                .Search(new SearchCapability([CustomerNameField], SearchStrategy.Fuzzy)))
            .Entity(Account.EntityId, "Account", a => a
                .Identity(new FieldId(1), "Id")
                .Field(new FieldId(3), "Balance", typeof(decimal))
                .Relationship(AccountTransactions, "Transactions", TransactionEntity.EntityId, RelationshipCardinality.Many))
            .Entity(TransactionEntity.EntityId, "Transaction", t => t
                .Identity(new FieldId(1), "Id")
                .Field(new FieldId(3), "Amount", typeof(decimal)))
            .Build();

    /// <summary>
    /// The real <see cref="ICandidateSource"/> for this test: parameterized
    /// SQL against the same database the final query runs against. Scoped
    /// down to exactly the two lookups this scenario needs (a Customer name
    /// search, and the two relationship walks), the same way this file's
    /// EntityMetadata/JoinMetadata are hand-written locally rather than
    /// shared with the Banking sample — matching every other test in this
    /// project, which builds its own metadata rather than importing the
    /// sample's. <c>Foundgine.Samples.Banking.Resolution.SqlCandidateSource</c>
    /// is the fully general version of this idea.
    /// </summary>
    private sealed class TestCandidateSource(string connectionString) : ICandidateSource
    {
        public IReadOnlyList<IdentityCandidate> FindByIdentity(EntityId entityType, string identityValue) =>
            throw new NotSupportedException(
                $"{nameof(TestCandidateSource)} only supports the lookups this scenario needs " +
                "(search + relationship traversal) — not identity lookup.");

        public IReadOnlyList<IdentityCandidate> FindByField(
            EntityId entityType, FieldId fieldId, string text, SearchStrategy strategy)
        {
            if (entityType != Customer.EntityId)
            {
                throw new NotSupportedException(
                    $"{nameof(TestCandidateSource)} only searches Customer, not entity " +
                    $"{entityType.Value}.");
            }

            using var connection = Open();
            using var command = connection.CreateCommand();
            command.CommandText = "SELECT Id, Name FROM Customer WHERE Name LIKE @pattern";
            command.Parameters.AddWithValue("@pattern", "%" + text + "%");

            return Read(command);
        }

        public IReadOnlyList<IdentityCandidate> FindByRelationship(
            RelationshipId relationshipId, string sourceIdentityValue)
        {
            using var connection = Open();
            using var command = connection.CreateCommand();

            if (relationshipId == CustomerAccounts)
                command.CommandText = "SELECT Id, Id FROM Account WHERE CustomerId = @id";
            else if (relationshipId == AccountTransactions)
                command.CommandText = "SELECT Id, Id FROM \"Transaction\" WHERE AccountId = @id";
            else
                throw new NotSupportedException($"Unknown relationship {relationshipId.Value}.");

            command.Parameters.AddWithValue("@id", sourceIdentityValue);

            return Read(command);
        }

        private SqliteConnection Open()
        {
            var connection = new SqliteConnection(connectionString);
            connection.Open();
            return connection;
        }

        private static IReadOnlyList<IdentityCandidate> Read(SqliteCommand command)
        {
            var results = new List<IdentityCandidate>();
            using var reader = command.ExecuteReader();

            while (reader.Read())
                results.Add(new IdentityCandidate(reader.GetValue(0).ToString()!, reader.GetValue(1).ToString()!));

            return results;
        }
    }

    public async Task InitializeAsync()
    {
        _keeper = new SqliteConnection(_connectionString);
        await _keeper.OpenAsync();

        var setup = _keeper.CreateCommand();
        setup.CommandText =
            """
            CREATE TABLE Customer (Id INTEGER PRIMARY KEY, Name TEXT NOT NULL);
            CREATE TABLE Account (Id INTEGER PRIMARY KEY, CustomerId INTEGER NOT NULL, Balance REAL NOT NULL);
            CREATE TABLE "Transaction" (Id INTEGER PRIMARY KEY, AccountId INTEGER NOT NULL, Amount REAL NOT NULL);

            INSERT INTO Customer (Id, Name) VALUES (1, 'Ada Lovelace');
            INSERT INTO Customer (Id, Name) VALUES (2, 'Grace Hopper');

            INSERT INTO Account (Id, CustomerId, Balance) VALUES (10, 1, 500.0);
            INSERT INTO Account (Id, CustomerId, Balance) VALUES (20, 2, 1000.0);

            -- Ada has 7 transactions, so "last five" actually exercises the
            -- LIMIT rather than trivially returning everything she has.
            INSERT INTO "Transaction" (Id, AccountId, Amount) VALUES (100, 10, -25.5);
            INSERT INTO "Transaction" (Id, AccountId, Amount) VALUES (101, 10, 60.0);
            INSERT INTO "Transaction" (Id, AccountId, Amount) VALUES (102, 10, -10.0);
            INSERT INTO "Transaction" (Id, AccountId, Amount) VALUES (103, 10, 15.0);
            INSERT INTO "Transaction" (Id, AccountId, Amount) VALUES (104, 10, -5.0);
            INSERT INTO "Transaction" (Id, AccountId, Amount) VALUES (105, 10, 200.0);
            INSERT INTO "Transaction" (Id, AccountId, Amount) VALUES (106, 10, -50.0);

            INSERT INTO "Transaction" (Id, AccountId, Amount) VALUES (200, 20, 10.0);
            INSERT INTO "Transaction" (Id, AccountId, Amount) VALUES (201, 20, 20.0);
            """;

        await setup.ExecuteNonQueryAsync();
    }

    public async Task DisposeAsync() =>
        await _keeper.DisposeAsync();

    private static MetadataRegistry Registry()
    {
        var registry = new MetadataRegistry();
        registry.Register(Customer);
        registry.Register(Account);
        registry.Register(TransactionEntity);
        return registry;
    }

    private static JoinGraph Joins()
    {
        var joinGraph = new JoinGraph();
        joinGraph.AddEdge(Customer.EntityId, Account.EntityId, AccountToCustomer);
        joinGraph.AddEdge(Account.EntityId, TransactionEntity.EntityId, AccountToTransaction);
        return joinGraph;
    }

    [Fact]
    public async Task FindAdasLastFiveTransactions_FromStructuredIntent_ThroughResolutionAndPlanning_ToRealDatabase()
    {
        // 1) Structured intent -- what an LLM or any other intent extractor
        //    would hand Foundgine for "Find Ada's last five transactions."
        //    Nothing in this test parses that sentence; per the review,
        //    that boundary is exactly the point.
        var readIntent = new ReadIntent(
            AnchorEntity: Customer.EntityId,
            AnchorPhrase: "Ada Lovelace",
            ThroughRelationships: ["Accounts"],
            TargetRelationship: "Transactions",
            OrderBy: new FieldId(1),
            Descending: true,
            Limit: 5);

        // 2) Structured intent -> resolved semantic query, via Milestone 2's
        //    EntityResolver against the *same* real database step 4 below
        //    executes against -- no fakes.
        var semanticModel = BuildSemanticModel();
        var candidates = new TestCandidateSource(_connectionString);
        var resolver = new EntityResolver(semanticModel, candidates);
        var readPlanner = new ReadPlanner(semanticModel, resolver);

        var readPlanResult = readPlanner.Plan(readIntent);
        Assert.True(readPlanResult.IsResolved, readPlanResult.UnresolvedReason);
        var readPlan = readPlanResult.Plan!;

        Assert.Equal(Customer.EntityId, readPlan.AnchorChain[0].EntityType);
        Assert.Equal("1", readPlan.AnchorChain[0].IdentityValue); // Customer#1 = Ada
        Assert.Equal(Account.EntityId, readPlan.AnchorChain[1].EntityType);
        Assert.Equal("10", readPlan.AnchorChain[1].IdentityValue); // her Account#10
        Assert.Equal(TransactionEntity.EntityId, readPlan.TargetEntity);

        // 3) ResolvedReadPlan -> QueryIntent: the bridge itself. The
        //    resolved anchor's literal identity becomes a WHERE-clause
        //    filter; the intent's ordering/limit pass straight through to
        //    Sort/Page. This is the connection the previous milestone was
        //    missing -- EntityResolver's output feeding QueryPlanner's
        //    input directly, with no hardcoded "Account.CustomerId" or
        //    "Transaction.Id" reasoning outside what both sides already
        //    expressed in Foundgine.Metadata terms.
        var anchor = readPlan.AnchorChain[^1];

        var queryIntent = QueryIntent.Linear(
            root: anchor.EntityType,
            path: [readPlan.TargetEntity],
            filter: new ComparisonFilter(
                new ColumnReference(Account, 1),
                ComparisonOperator.Equal,
                anchor.IdentityValue),
            sort: [new SortTerm(
                new ColumnReference(TransactionEntity, 1),
                readPlan.Descending ? SortDirection.Descending : SortDirection.Ascending)],
            page: new PageSpec(Limit: readPlan.Limit));

        // 4) QueryIntent -> QueryPlan -> ProviderPlan -> SQL -> real SQLite.
        //    The exact same pipeline BankingEndToEndTests and
        //    FilterSortPageEndToEndTests already prove independently --
        //    nothing here is special-cased for a resolved intent.
        var planner = new QueryPlanner(Registry(), Joins());
        var queryPlan = planner.Plan(queryIntent);
        var providerPlan = SqlPlanCompiler.Compile(queryPlan);
        var provider = new SqlExecutionProvider();

        var context = new ExecutionContext(
            Guid.NewGuid(),
            new Dictionary<string, object?> { ["ConnectionString"] = _connectionString });

        var rows = new List<ExecutionRow>();
        await foreach (var row in provider.ExecuteAsync(providerPlan, context))
            rows.Add(row);

        // 5) Result: exactly Ada's five most recent transactions, newest
        //    first -- proving the filter excluded Grace's account entirely
        //    (not just happened to rank below the limit) and the sort +
        //    limit both actually ran in SQL, not in this test.
        Assert.Equal(5, rows.Count);

        var transactionIds = rows
            .Select(r => (long)r.Single(TransactionEntity.EntityId)[0]!)
            .ToArray();

        Assert.Equal(new long[] { 106, 105, 104, 103, 102 }, transactionIds);

        Assert.All(rows, row =>
            Assert.Equal(10L, (long)row.Single(Account.EntityId)[0]!));
    }

    [Fact]
    public async Task FindAdasLastFiveTransactions_ProducesEvidence_AnsweringWhoWhatAndWhatCameBack()
    {
        // Same pipeline as the test above, but this time capturing evidence
        // at each stage instead of only asserting on the final rows -- the
        // review's own four questions: who did we resolve and why, what
        // plan did we generate, what provider executed it, what came back.
        var readIntent = new ReadIntent(
            AnchorEntity: Customer.EntityId,
            AnchorPhrase: "Ada Lovelace",
            ThroughRelationships: ["Accounts"],
            TargetRelationship: "Transactions",
            OrderBy: new FieldId(1),
            Descending: true,
            Limit: 5);

        var semanticModel = BuildSemanticModel();
        var resolver = new EntityResolver(semanticModel, new TestCandidateSource(_connectionString));
        var readPlanResult = new ReadPlanner(semanticModel, resolver).Plan(readIntent);

        Assert.True(readPlanResult.IsResolved, readPlanResult.UnresolvedReason);
        var readPlan = readPlanResult.Plan!;
        var anchor = readPlan.AnchorChain[^1];

        var queryIntent = QueryIntent.Linear(
            root: anchor.EntityType,
            path: [readPlan.TargetEntity],
            filter: new ComparisonFilter(
                new ColumnReference(Account, 1),
                ComparisonOperator.Equal,
                anchor.IdentityValue),
            sort: [new SortTerm(
                new ColumnReference(TransactionEntity, 1),
                readPlan.Descending ? SortDirection.Descending : SortDirection.Ascending)],
            page: new PageSpec(Limit: readPlan.Limit));

        var providerPlan = SqlPlanCompiler.Compile(new QueryPlanner(Registry(), Joins()).Plan(queryIntent));

        // Captured independently of SqlExecutionProvider.ExecuteAsync (which
        // compiles the same translation internally to actually run the
        // query) purely so this test can show the exact SQL as evidence --
        // SqlTextTranslator.Translate is a pure function of the plan, so
        // this is the same text the provider itself executes below.
        var translation = SqlTextTranslator.Translate(providerPlan);

        var provider = new SqlExecutionProvider();
        var context = new ExecutionContext(
            Guid.NewGuid(),
            new Dictionary<string, object?> { ["ConnectionString"] = _connectionString });

        var rows = new List<ExecutionRow>();
        await foreach (var row in provider.ExecuteAsync(providerPlan, context))
            rows.Add(row);

        var evidence = ReadEvidence.Build(
            readPlan, translation, provider.Kind, rows, TransactionEntity.EntityId);

        // Who did we resolve, and why -- the search that found Ada plus the
        // relationship walk to her account both show up.
        Assert.Contains(evidence.Resolution, e => e.Contains("Ada Lovelace"));
        Assert.Contains(evidence.Resolution, e => e.Contains("Accounts"));

        // What plan did we generate -- real SQL, not a description of SQL.
        Assert.Contains("SELECT", evidence.Plan);
        Assert.Contains("WHERE", evidence.Plan);
        Assert.Contains("ORDER BY", evidence.Plan);
        Assert.Contains("LIMIT", evidence.Plan);
        Assert.Contains("10", evidence.Plan); // the resolved account id, bound as a parameter

        // What provider executed it, and what came back.
        Assert.Contains("Sql", evidence.Execution);
        Assert.Equal(5, rows.Count);
        Assert.Equal(5, evidence.Result.Count);
    }
}
