using System.Text;
using System.Collections.Immutable;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Foundgine.Aot.Generator;

[Generator(LanguageNames.CSharp)]
public sealed class FoundgineMetadataGenerator : IIncrementalGenerator
{
    private const string EntityAttribute = "Foundgine.Aot.FoundgineEntityAttribute";
    private const string FieldAttribute = "Foundgine.Aot.FoundgineFieldAttribute";
    private const string RelationshipAttribute = "Foundgine.Aot.FoundgineRelationshipAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var entities = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                EntityAttribute,
                static (node, _) => node is ClassDeclarationSyntax,
                static (ctx, _) => (INamedTypeSymbol)ctx.TargetSymbol)
            .Collect();

        context.RegisterSourceOutput(entities, static (spc, symbols) =>
        {
            spc.AddSource("Foundgine.GeneratedMetadata.g.cs", Emit(symbols));
        });
    }

    private static string Emit(ImmutableArray<INamedTypeSymbol> symbols)
    {
        var ordered = symbols
            .OrderBy(x => x.ToDisplayString(), StringComparer.Ordinal)
            .ToArray();

        var entityIds = AllocateEntityIds(ordered);
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Linq;");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using Foundgine.Metadata;");
        sb.AppendLine("using Foundgine.Abstractions;");
        sb.AppendLine("using Foundgine.Aot;");
        sb.AppendLine("namespace Foundgine.Generated;");
        sb.AppendLine();
        sb.AppendLine("public static class GeneratedMetadata");
        sb.AppendLine("{");
        sb.AppendLine("    public static readonly MetadataRegistry Registry = Build();");
        sb.AppendLine();
        sb.AppendLine("    private static MetadataRegistry Build()");
        sb.AppendLine("    {");
        sb.AppendLine("        var registry = new MetadataRegistry();");

        foreach (var entity in ordered)
        {
            var entityId = entityIds[entity.ToDisplayString()];
            var entityName = GetEntityName(entity);
            var storageName = GetEntityStorageName(entity) ?? entityName;
            var properties = entity.GetMembers().OfType<IPropertySymbol>()
                .Where(p => p.DeclaredAccessibility == Accessibility.Public && !p.IsStatic)
                .ToArray();

            var scalar = properties.Where(p => p.GetAttributes().All(a => a.AttributeClass?.ToDisplayString() != RelationshipAttribute)).ToArray();
            var fieldIds = AllocateIds(scalar.Select(p => entity.ToDisplayString() + "." + p.Name).ToArray());
            var columnIds = fieldIds;

            sb.AppendLine("        registry.Register(new EntityMetadata(");
            sb.AppendLine($"            new EntityId({entityId}),");
            sb.AppendLine($"            \"{Escape(entityName)}\",");
            sb.AppendLine("            new ColumnMetadata[]");
            sb.AppendLine("            {");
            foreach (var p in scalar)
            {
                var field = GetAttribute(p, FieldAttribute);
                var colName = GetNamedString(field, "StorageName") ?? GetNamedString(field, "Name") ?? p.Name;
                var id = GetNamedUShort(field, "Id") ?? columnIds[entity.ToDisplayString() + "." + p.Name];
                sb.AppendLine($"                new ColumnMetadata(new ColumnId({id}), \"{Escape(colName)}\"),");
            }
            sb.AppendLine("            },");
            sb.AppendLine($"            StorageName: \"{Escape(storageName)}\",");
            var primaryKey = scalar.FirstOrDefault(p => GetNamedBool(GetAttribute(p, FieldAttribute), "IsPrimaryKey"));
            if (primaryKey is not null)
            {
                var pkField = GetAttribute(primaryKey, FieldAttribute);
                var pkId = GetNamedUShort(pkField, "Id") ?? columnIds[entity.ToDisplayString() + "." + primaryKey.Name];
                sb.AppendLine($"            PrimaryKey: new ColumnReference(new EntityId({entityId}), new ColumnId({pkId})),");
            }
            sb.AppendLine("            Fields: new FieldMetadata[]");
            sb.AppendLine("            {");
            foreach (var p in scalar)
            {
                var field = GetAttribute(p, FieldAttribute);
                var fieldName = GetNamedString(field, "Name") ?? p.Name;
                var fieldId = GetNamedUShort(field, "Id") ?? fieldIds[entity.ToDisplayString() + "." + p.Name];
                var colName = GetNamedString(field, "StorageName") ?? GetNamedString(field, "Name") ?? p.Name;
                var colId = GetNamedUShort(field, "Id") ?? columnIds[entity.ToDisplayString() + "." + p.Name];
                sb.AppendLine($"                new FieldMetadata(new FieldId({fieldId}), \"{Escape(fieldName)}\", typeof({p.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)}), new ColumnReference(new EntityId({entityId}), new ColumnId({colId}))),");
            }
            sb.AppendLine("            }));");
        }

        foreach (var entity in ordered)
        {
            var sourceId = entityIds[entity.ToDisplayString()];
            foreach (var p in entity.GetMembers().OfType<IPropertySymbol>())
            {
                var rel = GetAttribute(p, RelationshipAttribute);
                if (rel is null) continue;
                var target = GetTypeArgument(rel, 0);
                if (target is null) continue;
                var targetId = entityIds[target.ToDisplayString()];
                var relKey = entity.ToDisplayString() + "." + p.Name;
                var id = GetNamedUShort(rel, "Id") ?? AllocateIds(new[] { relKey })[relKey];
                var name = GetNamedString(rel, "Name") ?? p.Name;
                var fk = GetCtorString(rel, 1) ?? "Id";
                var pk = GetCtorString(rel, 2) ?? "Id";
                var sourceOwnsForeignKey = entity.GetMembers(fk).OfType<IPropertySymbol>().Any();
                var fkOwner = sourceOwnsForeignKey ? entity : target;
                var principalOwner = sourceOwnsForeignKey ? target : entity;
                var fkId = ResolveColumnId(fkOwner, fk, entityIds, fieldIds: null);
                var principalId = ResolveColumnId(principalOwner, pk, entityIds, fieldIds: null);

                // SourceKey/TargetKey always describe the key on each side of the
                // semantic relationship, regardless of which side physically owns
                // the foreign key.
                var sourceKeyEntity = sourceId;
                var sourceKeyColumn = sourceOwnsForeignKey ? fkId : principalId;
                var targetKeyEntity = targetId;
                var targetKeyColumn = sourceOwnsForeignKey ? principalId : fkId;
                sb.AppendLine($"        registry.Register(new RelationshipMetadata(new RelationshipId({id}), new EntityId({sourceId}), new EntityId({targetId}), \"{Escape(name)}\", new ColumnReference(new EntityId({sourceKeyEntity}), new ColumnId({sourceKeyColumn})), new ColumnReference(new EntityId({targetKeyEntity}), new ColumnId({targetKeyColumn}))));");
            }
        }

        sb.AppendLine("        return registry;");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("public sealed class GeneratedMetadataProvider : IMetadataProvider, IMetadataSource");
        sb.AppendLine("{");
        sb.AppendLine("    public IReadOnlyCollection<EntityMetadata> Entities => GeneratedMetadata.Registry.Entities.ToArray();");
        sb.AppendLine("    public IReadOnlyCollection<RelationshipMetadata> Relationships => GeneratedMetadata.Registry.Relationships.ToArray();");
        sb.AppendLine("    public EntityMetadata GetEntity(EntityId entityId) => GeneratedMetadata.Registry.GetEntity(entityId);");
        sb.AppendLine("    public RelationshipMetadata GetRelationship(RelationshipId relationshipId) => GeneratedMetadata.Registry.GetRelationship(relationshipId);");
        sb.AppendLine("}");
        return sb.ToString();
    }

    private static Dictionary<string, ushort> AllocateEntityIds(IReadOnlyList<INamedTypeSymbol> entities)
    {
        var result = new Dictionary<string, ushort>(StringComparer.Ordinal);
        var used = new HashSet<ushort>();
        foreach (var entity in entities.OrderBy(x => x.ToDisplayString(), StringComparer.Ordinal))
        {
            var explicitId = GetNamedUShort(GetAttribute(entity, EntityAttribute), "Id");
            if (explicitId.HasValue)
            {
                if (!used.Add(explicitId.Value))
                    throw new InvalidOperationException($"Duplicate Foundgine entity ID {explicitId.Value}.");
                result[entity.ToDisplayString()] = explicitId.Value;
            }
        }
        foreach (var entity in entities.OrderBy(x => x.ToDisplayString(), StringComparer.Ordinal))
        {
            if (result.ContainsKey(entity.ToDisplayString())) continue;
            var candidate = StableHash(entity.ToDisplayString());
            while (candidate == 0 || !used.Add(candidate))
                candidate = candidate == ushort.MaxValue ? (ushort)1 : (ushort)(candidate + 1);
            result[entity.ToDisplayString()] = candidate;
        }
        return result;
    }

    private static Dictionary<string, ushort> AllocateIds(IReadOnlyList<string> keys)
    {
        var used = new HashSet<ushort>();
        var result = new Dictionary<string, ushort>(StringComparer.Ordinal);
        foreach (var key in keys.OrderBy(x => x, StringComparer.Ordinal))
        {
            var candidate = StableHash(key);
            while (candidate == 0 || !used.Add(candidate))
                candidate = candidate == ushort.MaxValue ? (ushort)1 : (ushort)(candidate + 1);
            result[key] = candidate;
        }
        return result;
    }

    private static ushort StableHash(string value)
    {
        uint hash = 2166136261;
        foreach (var c in value)
        {
            hash ^= c;
            hash *= 16777619;
        }
        return (ushort)(hash ^ (hash >> 16));
    }

    private static AttributeData? GetAttribute(ISymbol symbol, string fullName) =>
        symbol.GetAttributes().FirstOrDefault(a => a.AttributeClass?.ToDisplayString() == fullName);

    private static string GetEntityName(INamedTypeSymbol type) =>
        GetNamedString(GetAttribute(type, EntityAttribute), "Name") ?? type.Name;

    private static string? GetEntityStorageName(INamedTypeSymbol type) =>
        GetNamedString(GetAttribute(type, EntityAttribute), "StorageName");

    private static string? GetNamedString(AttributeData? attribute, string name) =>
        attribute?.NamedArguments.FirstOrDefault(x => x.Key == name).Value.Value as string;

    private static ushort? GetNamedUShort(AttributeData? attribute, string name)
    {
        var value = attribute?.NamedArguments.FirstOrDefault(x => x.Key == name).Value.Value;
        return value is ushort u && u != 0 ? u : null;
    }

    private static bool GetNamedBool(AttributeData? attribute, string name) =>
        attribute?.NamedArguments.FirstOrDefault(x => x.Key == name).Value.Value is true;


    private static string? GetCtorString(AttributeData attribute, int index) =>
        index < attribute.ConstructorArguments.Length ? attribute.ConstructorArguments[index].Value as string : null;

    private static INamedTypeSymbol? GetTypeArgument(AttributeData attribute, int index) =>
        index < attribute.ConstructorArguments.Length ? attribute.ConstructorArguments[index].Value as INamedTypeSymbol : null;

    private static ushort ResolveColumnId(INamedTypeSymbol entity, string propertyName, Dictionary<string, ushort> _, Dictionary<string, ushort>? fieldIds)
    {
        var property = entity.GetMembers(propertyName).OfType<IPropertySymbol>().FirstOrDefault();
        if (property is null) return 0;
        var field = GetAttribute(property, FieldAttribute);
        var explicitId = GetNamedUShort(field, "Id");
        if (explicitId.HasValue) return explicitId.Value;
        return AllocateIds(new[] { entity.ToDisplayString() + "." + property.Name })[entity.ToDisplayString() + "." + property.Name];
    }

    private static string Escape(string value) => value.Replace("\\", "\\\\").Replace("\"", "\\\"");
}
