<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
      <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Npgsql" Version="9.0.4" />
    <ProjectReference Include="../../../src/Foundgine.Abstractions/Foundgine.Abstractions.csproj" />
    <ProjectReference Include="../../../src/Foundgine.Execution/Foundgine.Execution.csproj" />
    <ProjectReference Include="../../../src/Foundgine.Metadata/Foundgine.Metadata.csproj" />
    <ProjectReference Include="../../../src/Foundgine.Planning/Foundgine.Planning.csproj" />
    <ProjectReference Include="../../../src/Foundgine.Semantics/Foundgine.Semantics.csproj" />
    <ProjectReference Include="../../../src/Foundgine.Sql/Foundgine.Sql.csproj" />
    <ProjectReference Include="../../../src/Foundgine.GraphQL.HotChocolate/Foundgine.GraphQL.HotChocolate.csproj" />
    <ProjectReference Include="../../../src/Foundgine.GraphQL.HotChocolate.Mutations/Foundgine.GraphQL.HotChocolate.Mutations.csproj" />
  </ItemGroup>
</Project>
