using System.Linq.Expressions;
using System.Reflection;
using CoffeeBeanery.GraphQL.Core.Sql;

namespace CoffeeBeanery.GraphQL.Core.Mapping
{
    /// <summary>
    /// Declares that this model can appear as a nested field under a different
    /// parent model, even when there's no single EF entity navigation linking
    /// them (e.g. composite models like Product, which span Account/Contract/
    /// Transaction/CustomerBankingRelationship).
    ///
    /// Two ways an attachment gets here:
    ///   - Hand-written, via NodeMap.ChildAttachments.Add(...) inside BuildMap().
    ///     IsAutoGenerated = false. Always wins for its FieldName.
    ///   - Auto-generated, via ApplyGeneratedMappings (source generator output,
    ///     derived from ModelChildrenInference's property scan on the MODEL
    ///     type). IsAutoGenerated = true. Only added if no hand-written entry
    ///     already claims the same FieldName. The join column itself is
    ///     resolved later, at NodeBuilder build time, by convention -
    ///     ParentJoinColumn/ChildEntityType/ChildJoinColumn are left blank
    ///     for auto entries and filled in by NodeBuilder.ResolveAutoChildAttachments.
    /// </summary>
    public sealed class ChildAttachment
    {
        /// <summary>GraphQL field name on the parent, e.g. "product".</summary>
        public string FieldName { get; set; } = "";

        /// <summary>The child NodeMap's own Alias/ModelType.Name (e.g. "Product"). Always required.</summary>
        public string ToModelName { get; set; } = "";

        public bool IsCollection { get; set; } = true;

        public bool IsAutoGenerated { get; set; }

        // ---- Resolved at build time (auto entries) or supplied directly (hand-written) ----

        /// <summary>Entity that owns the join column on the parent side (defaults to the parent map's own EntityType if unset).</summary>
        public Type? ParentEntityType { get; set; }

        /// <summary>Column on the parent entity, e.g. "CustomerKey". Leave blank on auto entries; NodeBuilder fills it in.</summary>
        public string ParentJoinColumn { get; set; } = "";

        /// <summary>Which of the child model's composite entities actually carries the FK column.</summary>
        public Type? ChildEntityType { get; set; }

        /// <summary>Column on ChildEntityType matching ParentJoinColumn's value.</summary>
        public string ChildJoinColumn { get; set; } = "";
    }

    public sealed class NodeMap
    {
        public int Id { get; set; }

        public string Schema { get; set; } = "public";

        public bool IsRoot { get; set; }

        public bool IsModel { get; set; }

        public bool IsEntity { get; set; }

        public string Prefix { get; set; }

        public List<FieldMap> FieldMaps { get; } = new();

        public List<UpsertKey> UpsertKeys { get; private set; } = new();

        public string PrimaryKey { get; set; }

        public List<EntityKey> ModelToEntity { get; private set; } = new();

        public List<EntityKey> EntityChildrenRelated { get; set; } = new();

        public List<FieldMap> ExcludedFieldMappings { get; } = new();

        public List<ModelKey> ModelChildren { get; set; } = new();

        /// <summary>
        /// Cross-model attachment points - see ChildAttachment doc comment.
        /// Populated by hand-written BuildMap() code (wins) and/or by
        /// ApplyGeneratedMappings (auto, only fills unclaimed FieldNames).
        /// Consumed by NodeBuilder.ResolveAutoChildAttachments / BuildEdges
        /// to synthesize graph edges that EntityNavigationConvention could
        /// never discover, because the target model has no single backing
        /// EF entity to walk a navigation property against.
        /// </summary>
        public List<ChildAttachment> ChildAttachments { get; private set; } = new();

        public bool IsGraph { get; set; }

        public Type ModelType { get; set; }

        public Type EntityType { get; set; }

        public List<EntityKey> EntityChildren { get; set; } = new();

        public Dictionary<string, PropertyInfo> ModelProperties { get; set; }
            = new();

        public Dictionary<string, PropertyInfo> EntityProperties { get; set; }
            = new();

        public Func<object, object> CreateMapper { get; set; }

        public Action<object, object> UpdateMapper { get; set; }

        public string Alias { get; set; }

        public string ModelName { get; set; }

        public GraphMap? GraphMap { get; set; }

        public EntityKey AddModelToEntity<TModel, TEntity>(
            Expression<Func<TModel, object?>> fk,
            Expression<Func<TEntity, object?>> pk,
            Expression<Func<TModel, object?>>? alias = null,
            bool isPrimary = false)
        {
            var entityKey = new EntityKey
            {
                EntityType = typeof(TEntity),
                FromColumn = GetMemberName(fk),
                ToColumn = GetMemberName(pk),
                To = typeof(TEntity).Name,
                AliasProperty = alias != null
                    ? GetMemberName(alias)
                    : string.Empty
            };

            ModelToEntity.Add(entityKey);

            if (isPrimary || EntityType is null)
            {
                EntityType = typeof(TEntity);
                IsEntity = true;
            }

            return entityKey;
        }

        public EntityKey AddModelToEntityPath<TModel>(
            Expression<Func<TModel, object?>>? alias,
            params (Type EntityType, string Schema, string TableName, string FromColumn, string ToColumn)[] hops)
        {
            if (hops is null || hops.Length == 0)
                throw new ArgumentException("At least one hop is required.", nameof(hops));

            var finalHop = hops[^1];

            var entityKey = new EntityKey
            {
                EntityType = finalHop.EntityType,
                FromColumn = hops[0].FromColumn,
                ToColumn = finalHop.ToColumn,
                To = finalHop.EntityType.Name,
                AliasProperty = alias != null ? GetMemberName(alias) : string.Empty,
                Path = hops.Select(h => new JoinHop
                {
                    EntityType = h.EntityType,
                    Schema = h.Schema,
                    TableName = h.TableName,
                    FromColumn = h.FromColumn,
                    ToColumn = h.ToColumn
                }).ToList()
            };

            ModelToEntity.Add(entityKey);

            return entityKey;
        }

        /// <summary>
        /// Hand-written escape hatch for declaring that this model attaches
        /// under a different parent model as a nested field, when no single
        /// EF navigation exists to discover it automatically (e.g. composite
        /// models). Always wins over any auto-generated entry for the same
        /// FieldName.
        /// </summary>
        public ChildAttachment AddChildAttachment(
            string fieldName,
            string toModelName,
            Type? parentEntityType = null,
            string? parentJoinColumn = null,
            Type? childEntityType = null,
            string? childJoinColumn = null,
            bool isCollection = true)
        {
            var attachment = new ChildAttachment
            {
                FieldName = fieldName,
                ToModelName = toModelName,
                ParentEntityType = parentEntityType,
                ParentJoinColumn = parentJoinColumn ?? "",
                ChildEntityType = childEntityType,
                ChildJoinColumn = childJoinColumn ?? "",
                IsCollection = isCollection,
                IsAutoGenerated = false
            };

            ChildAttachments.Add(attachment);
            return attachment;
        }

        private static string GetMemberName(LambdaExpression expression)
        {
            Expression body = expression.Body;

            if (body is UnaryExpression unary &&
                unary.NodeType == ExpressionType.Convert)
            {
                body = unary.Operand;
            }

            if (body is MemberExpression member)
            {
                return member.Member.Name;
            }

            throw new ArgumentException(
                $"Expression '{expression}' does not reference a property.");
        }
    }
}