<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Npgsql"  />
    <PackageReference Include="ModelContextProtocol.AspNetCore"  />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Foundgine.Abstractions\Foundgine.Abstractions.csproj" />
    <ProjectReference Include="..\..\src\Foundgine.Aot\Foundgine.Aot.csproj" />
    <ProjectReference Include="..\..\src\Foundgine.Metadata\Foundgine.Metadata.csproj" />
    <ProjectReference Include="..\..\src\Foundgine.Planning\Foundgine.Planning.csproj" />
    <ProjectReference Include="..\..\src\Foundgine.Execution\Foundgine.Execution.csproj" />
    <ProjectReference Include="..\..\src\Foundgine.Sql\Foundgine.Sql.csproj" />
    <ProjectReference Include="..\..\src\Foundgine.Semantics\Foundgine.Semantics.csproj" />
    <ProjectReference Include="..\..\src\Foundgine.MCP\Foundgine.MCP.csproj" />

    <ProjectReference Include="..\..\src\Foundgine.Aot.Generator\Foundgine.Aot.Generator.csproj"
                      OutputItemType="Analyzer"
                      ReferenceOutputAssembly="false"
                      PrivateAssets="all" />
  </ItemGroup>

</Project>