<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <OutputType>Library</OutputType>
        <PlatformTarget>x64</PlatformTarget>
        <ImplicitUsings>enable</ImplicitUsings>
        <LangVersion>latest</LangVersion>
        <Nullable>enable</Nullable>
        <EnableDefaultCompileItems>true</EnableDefaultCompileItems>
    </PropertyGroup>
    
    <ItemGroup>
        <PackageReference Include="HotChocolate" Version="15.1.12" />
        <PackageReference Include="HotChocolate.AspNetCore" Version="15.1.12" />
        <PackageReference Include="HotChocolate.Data" Version="15.1.12" />
        <PackageReference Include="HotChocolate.Types" Version="15.1.12" />
        <PackageReference Include="HotChocolate.Types.Analyzers" Version="15.1.12" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Domain.Shared\Domain.Shared.csproj" />
        <ProjectReference Include="..\CoffeeBeanery.Runtime\CoffeeBeanery.Runtime.csproj" />
    </ItemGroup>

</Project>
