<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/Foundgine.Sql/Foundgine.Sql.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="xunit.assert"  />
    <PackageReference Include="xunit.extensibility.core"  />
  </ItemGroup>
</Project>
