using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Graphgine.SourceGenerators.Model;
using Graphgine.SourceGenerators.Passes;
using Microsoft.CodeAnalysis;

namespace Graphgine.SourceGenerators.Emit;

internal static class MutationMetadataEmitter
{
    internal sealed record GraphEdgeCteResolution(
        string NavigationAlias,

        string ForeignKeyColumn,
        ushort ForeignKeyColumnId,

        string OwningPrimaryKeyColumn,
        ushort OwningPrimaryKeyColumnId,

        string RelatedEntityTypeName,
        ushort RelatedStorageEntityId,

        string RelatedSurrogateIdColumn,
        ushort RelatedSurrogateIdColumnId,

        string RelatedNaturalKeyColumn,
        ushort RelatedNaturalKeyColumnId);


    public static string Emit(
    ImmutableArray<MappingClassInfo> allMappings,
    ImmutableHashSet<INamedTypeSymbol> rootEntityTypes,
    List<FluentEntityNavigationConvention.EntityForeignKeyGraph.Edge> entityGraph)
{
    var models =
        allMappings
            .Where(x => x.ModelType != null)
            .GroupBy(
                x => x.ModelType!.Name,
                StringComparer.OrdinalIgnoreCase)
            .Select(g => g.First())
            .OrderBy(x => x.ModelType!.Name)
            .ToList();


    foreach (var mapping in models)
    {
        if (mapping.CteUpdateMeta.Count > 0)
            continue;


        if (mapping.Graph != null)
        {
            var resolutions =
                BuildGraphEdgeCteResolutions(
                    mapping,
                    allMappings,
                    entityGraph);


            foreach (var resolution in resolutions)
            {
                mapping.CteUpdateMeta.Add(
                    new CteUpdateMetaInfo
                    {
                        NavigationAlias =
                            resolution.NavigationAlias,

                        ForeignKeyColumn =
                            resolution.ForeignKeyColumn,

                        ForeignKeyColumnId =
                            resolution.ForeignKeyColumnId,

                        OwningPrimaryKeyColumn =
                            resolution.OwningPrimaryKeyColumn,

                        OwningPrimaryKeyColumnId =
                            resolution.OwningPrimaryKeyColumnId,

                        RelatedEntityTypeName =
                            resolution.RelatedEntityTypeName,

                        RelatedStorageEntityId =
                            resolution.RelatedStorageEntityId,

                        RelatedSurrogateIdColumn =
                            resolution.RelatedSurrogateIdColumn,

                        RelatedSurrogateIdColumnId =
                            resolution.RelatedSurrogateIdColumnId,

                        RelatedNaturalKeyColumn =
                            resolution.RelatedNaturalKeyColumn,

                        RelatedNaturalKeyColumnId =
                            resolution.RelatedNaturalKeyColumnId
                    });
            }

            continue;
        }


        var navResult =
            EntityNavigationConvention.Resolve(
                mapping,
                allMappings,
                entityGraph,
                rootEntityTypes);


        MetadataEmitter.PopulateCteUpdateMeta(
            mapping,
            navResult,
            allMappings,
            entityGraph);
    }


    var sb =
        new StringBuilder();


    sb.AppendLine("#nullable enable");
    sb.AppendLine("// <auto-generated/>");
    sb.AppendLine();

    sb.AppendLine("using System;");
    sb.AppendLine("using System.Collections.Generic;");
    sb.AppendLine("using System.Collections.Immutable;");
    sb.AppendLine();

    sb.AppendLine(
        "namespace Graphgine.Execution;");

    sb.AppendLine();


    sb.AppendLine(
        "public static class MutationMetadataRegistry");

    sb.AppendLine("{");


    sb.AppendLine(
        "    private static readonly ImmutableDictionary<ushort, MutationEntityMetadata> _entities =");

    sb.AppendLine(
        "        ImmutableDictionary.CreateRange(new MutationEntityMetadata[]");

    sb.AppendLine("        {");


    for (var i = 0; i < models.Count; i++)
    {
        sb.AppendLine(
            $"            Create{models[i].ModelType!.Name}(){(i < models.Count - 1 ? "," : "")}");
    }


    sb.AppendLine(
        "        }.Select(x => new KeyValuePair<ushort, MutationEntityMetadata>(x.EntityId, x)));");


    sb.AppendLine();

    sb.AppendLine(
        "    public static int Count => _entities.Count;");


    sb.AppendLine();


    sb.AppendLine(
        "    public static MutationEntityMetadata Get(ushort entityId)");

    sb.AppendLine("    {");

    sb.AppendLine(
        "        if (!_entities.TryGetValue(entityId, out var metadata))");

    sb.AppendLine(
        "            throw new ArgumentOutOfRangeException(nameof(entityId));");

    sb.AppendLine();

    sb.AppendLine(
        "        return metadata;");

    sb.AppendLine("    }");


    sb.AppendLine();


    foreach (var model in models)
    {
        EmitFactory(
            sb,
            model,
            allMappings,
            entityGraph);

        sb.AppendLine();
    }


    sb.AppendLine("}");

    sb.AppendLine();

    EmitGeneratedMutationMetadataProvider(sb);

    return sb.ToString();
}


// ---------------------------------------------------------------
// GeneratedMutationMetadataProvider
// ---------------------------------------------------------------

private static void EmitGeneratedMutationMetadataProvider(StringBuilder sb)
{
    sb.AppendLine(
        "public sealed class GeneratedMutationMetadataProvider : global::Graphgine.Execution.IMutationMetadataProvider");

    sb.AppendLine("{");

    sb.AppendLine(
        "    public global::Graphgine.Execution.MutationFieldMetadata ResolveField(ushort entityId, ushort fieldId)");

    sb.AppendLine("    {");

    sb.AppendLine(
        "        var entity = MutationMetadataRegistry.Get(entityId);");

    sb.AppendLine();

    sb.AppendLine(
        "        if (!entity.TryResolveField(fieldId, out var mapping))");

    sb.AppendLine("        {");

    sb.AppendLine(
        "            throw new Exception($\"Field metadata missing.\\nEntity={entityId}\\nField={fieldId}\");");

    sb.AppendLine("        }");

    sb.AppendLine();

    sb.AppendLine(
        "        return mapping;");

    sb.AppendLine("    }");
    sb.AppendLine("}");
    sb.AppendLine();
}



    private static List<(string EntityName, string Schema)> GetStorageEntities(
        MappingClassInfo info)
    {
        return info.Definition.Entities
            .Where(e => e.EntityType != null)
            .Select(e =>
            {
                var name =
                    IdEmitter.StripEntitySuffix(
                        e.EntityType!.Name);

                return
                (
                    EntityName: name,
                    Schema:
                    e.Schema
                    ?? info.Schema
                    ?? "public"
                );
            })
            .ToList();
    }



    private static ushort ResolveColumnId(
        MappingClassInfo mapping,
        string column,
        ImmutableArray<MappingClassInfo> allMappings,
        List<FluentEntityNavigationConvention.EntityForeignKeyGraph.Edge> entityGraph)
    {
        foreach (var entity in mapping.Definition.Entities)
        {
            if (entity.EntityType == null)
                continue;


            var id =
                ColumnIdResolver.ResolveId(
                    entity.EntityType,
                    column,
                    allMappings,
                    entityGraph);


            if (id != ushort.MaxValue)
                return id;
        }


        return ushort.MaxValue;
    }
    
    public static List<GraphEdgeCteResolution>
BuildGraphEdgeCteResolutions(
    MappingClassInfo info,
    ImmutableArray<MappingClassInfo> allMappings,
    List<FluentEntityNavigationConvention.EntityForeignKeyGraph.Edge> entityGraph)
{
    var result =
        new List<GraphEdgeCteResolution>();


    if (info.Graph == null)
        return result;


    var navigationFields =
        info.FieldMaps
            .Where(x => x.IsNavigationKey)
            .ToList();


    if (navigationFields.Count < 2)
        return result;



    static string ExtractEntity(string? value)
    {
        if (string.IsNullOrWhiteSpace(value))
            return string.Empty;


        var parts =
            value.Split(
                new[]
                {
                    '.'
                },
                StringSplitOptions.RemoveEmptyEntries);


        return parts.Length > 1
            ? IdEmitter.StripEntitySuffix(parts[0])
            : string.Empty;
    }



    static string ExtractColumn(string? value)
    {
        if (string.IsNullOrWhiteSpace(value))
            return string.Empty;


        var parts =
            value.Split(
                new[]
                {
                    '.'
                },
                StringSplitOptions.RemoveEmptyEntries);


        return parts.Length > 1
            ? parts[1]
            : parts.LastOrDefault() ?? string.Empty;
    }



    static string ResolvePrimaryKeyColumn(
        MappingClassInfo mapping)
    {
        var declared =
            mapping.Definition.PrimaryKey
                .Select(x => x.ColumnKey)
                .FirstOrDefault(x =>
                    !string.IsNullOrWhiteSpace(x));


        if (!string.IsNullOrWhiteSpace(declared))
            return declared;


        return mapping.UpsertKeys
            .Select(x => x.Key)
            .FirstOrDefault(x =>
                !string.IsNullOrWhiteSpace(x))
            ?? string.Empty;
    }



    var endpoints =
        new[]
        {
            (
                Field: navigationFields[0],
                ForeignKey:
                    info.Graph.From.ForeignKeyColumn,
                // ---------------------------------------------------------
                // FIXED: NavigationAlias must be the bare alias (e.g.
                // "InnerCustomer"), not endpoint.Field.SourceName (e.g.
                // "InnerCustomerKey" -- the FieldMap's SourceName, which
                // ALREADY has "Key" appended per the mapping's Fields[]
                // declaration). Every consumer of GraphEdgeCteResolution.
                // NavigationAlias (MutationRuntimePlanner.EmitMutationDependencies
                // and EmitRowsGroupedByStorageEntity) does
                // `x.NavigationAlias + "Key"` itself when matching against
                // a field's FieldName -- so passing the already-suffixed
                // SourceName here produced "InnerCustomerKeyKey", which
                // never matches the real field name "InnerCustomerKey".
                // That mismatch made `spec` come back null every time,
                // silently dropping InnerCustomerKey/OuterCustomerKey from
                // BOTH the literal INSERT values (since they're marked
                // IsNavigationKey and the null-spec path falls through to
                // `continue`) AND from ever becoming a lookup-based JOIN
                // (since lookupGroup.Add is only reached when spec != null)
                // -- exactly why InnerCustomerId/OuterCustomerId never
                // appeared anywhere in the generated upsert CTE.
                //
                // info.Graph.From.Alias/To.Alias are already the correct
                // bare alias strings (set directly in the mapping's Graph
                // definition, e.g. Alias = nameof(CustomerCustomerEdge.
                // InnerCustomer)) -- use those instead of deriving anything
                // from the field's SourceName.
                // ---------------------------------------------------------
                NavigationAlias: info.Graph.From.Alias
            ),

            (
                Field: navigationFields[1],
                ForeignKey:
                    info.Graph.To.ForeignKeyColumn,
                NavigationAlias: info.Graph.To.Alias
            )
        };



    foreach (var endpoint in endpoints)
{
    var foreignKeyColumn =
        ExtractColumn(
            endpoint.ForeignKey);

    var endpointEntity =
        string.Equals(
            endpoint.NavigationAlias,
            info.Graph.From.Alias,
            StringComparison.OrdinalIgnoreCase)
                ? info.Graph.From.Label
                : info.Graph.To.Label;

    var relatedMapping =
        allMappings.FirstOrDefault(x =>
            !ReferenceEquals(x, info) &&
            x.Definition.Entities.Any(e =>
                e.IsPrimary &&
                e.EntityType != null &&
                string.Equals(
                    IdEmitter.StripEntitySuffix(
                        e.EntityType.Name),
                    endpointEntity,
                    StringComparison.OrdinalIgnoreCase)));

    if (relatedMapping == null)
        continue;

    var relatedEntityType =
        relatedMapping.Definition.Entities
            .Where(e => e.EntityType != null)
            .Select(e => e.EntityType!)
            .FirstOrDefault(e =>
                string.Equals(
                    IdEmitter.StripEntitySuffix(
                        e.Name),
                    endpointEntity,
                    StringComparison.OrdinalIgnoreCase));

    if (relatedEntityType == null)
        continue;

    var relatedEntity =
        IdEmitter.StripEntitySuffix(
            relatedEntityType.Name);

    var relatedNaturalKeyColumn =
        ResolvePrimaryKeyColumn(
            relatedMapping);

    var relatedSurrogateColumn =
        MetadataEmitter.GetPkPropertyName(
            relatedEntityType);

    var owningPrimaryKeyColumn =
        ResolvePrimaryKeyColumn(
            info);

    //
    // IMPORTANT:
    // Foreign key belongs to the related vertex entity.
    // NOT the graph edge entity.
    //
    var foreignKeyColumnId =
        ResolveColumnId(
            relatedMapping,
            foreignKeyColumn,
            allMappings,
            entityGraph);

    var owningPrimaryKeyColumnId =
        ResolveColumnId(
            info,
            owningPrimaryKeyColumn,
            allMappings,
            entityGraph);

    var relatedNaturalKeyColumnId =
        ResolveColumnId(
            relatedMapping,
            relatedNaturalKeyColumn,
            allMappings,
            entityGraph);

    var relatedSurrogateColumnId =
        ResolveColumnId(
            relatedMapping,
            relatedSurrogateColumn,
            allMappings,
            entityGraph);

    result.Add(
        new GraphEdgeCteResolution(
            NavigationAlias:
                endpoint.NavigationAlias,

            ForeignKeyColumn:
                foreignKeyColumn,

            ForeignKeyColumnId:
                foreignKeyColumnId,

            OwningPrimaryKeyColumn:
                owningPrimaryKeyColumn,

            OwningPrimaryKeyColumnId:
                owningPrimaryKeyColumnId,

            RelatedEntityTypeName:
                relatedEntity,

            RelatedStorageEntityId:
                ResolveStorageEntityId(
                    allMappings,
                    relatedEntityType),

            RelatedSurrogateIdColumn:
                relatedSurrogateColumn,

            RelatedSurrogateIdColumnId:
                relatedSurrogateColumnId,

            RelatedNaturalKeyColumn:
                relatedNaturalKeyColumn,

            RelatedNaturalKeyColumnId:
                relatedNaturalKeyColumnId));
}


    return result;
}
    
    private static string ResolveStorageEntityIdName(
    MappingClassInfo info,
    INamedTypeSymbol entityType,
    ImmutableArray<MappingClassInfo> allMappings)
{
    var entityName =
        IdEmitter.StripEntitySuffix(
            entityType.Name);


    //
    // 1. Direct entity match
    //
    foreach (var mapping in allMappings)
    {
        foreach (var entity in mapping.Definition.Entities)
        {
            if (entity.EntityType == null)
                continue;


            var candidate =
                IdEmitter.StripEntitySuffix(
                    entity.EntityType.Name);


            if (string.Equals(
                candidate,
                entityName,
                StringComparison.OrdinalIgnoreCase))
            {
                return candidate;
            }
        }
    }


    //
    // 2. Graph entity resolution
    //
    // Graph models may not equal storage entities.
    // Example:
    // CustomerCustomerEdge
    //        ->
    // CustomerCustomerRelationship
    //
    if (info.Graph != null)
    {
        foreach (var entity in info.Definition.Entities)
        {
            if (entity.EntityType == null)
                continue;


            var candidate =
                IdEmitter.StripEntitySuffix(
                    entity.EntityType.Name);


            if (candidate.EndsWith(
                    "Relationship",
                    StringComparison.OrdinalIgnoreCase))
            {
                return candidate;
            }
        }
    }


    //
    // 3. Remove Edge suffix fallback
    //
    var stripped = entityName;


    if (stripped.EndsWith(
            "Edge",
            StringComparison.OrdinalIgnoreCase))
    {
        stripped =
            stripped.Substring(
                0,
                stripped.Length - 4);
    }


    foreach (var mapping in allMappings)
    {
        foreach (var entity in mapping.Definition.Entities)
        {
            if (entity.EntityType == null)
                continue;


            var candidate =
                IdEmitter.StripEntitySuffix(
                    entity.EntityType.Name);


            if (candidate.StartsWith(
                    stripped,
                    StringComparison.OrdinalIgnoreCase))
            {
                return candidate;
            }
        }
    }


    //
    // 4. Relationship/graph fallback by shared prefix
    //
    foreach (var mapping in allMappings)
    {
        foreach (var entity in mapping.Definition.Entities)
        {
            if (entity.EntityType == null)
                continue;


            var candidate =
                IdEmitter.StripEntitySuffix(
                    entity.EntityType.Name);


            if (candidate.IndexOf(
                    stripped,
                    StringComparison.OrdinalIgnoreCase) >= 0)
            {
                return candidate;
            }
        }
    }


    throw new InvalidOperationException(
        $"Unable to resolve storage entity for '{entityName}'.");
}
    
    private static ushort ResolveStorageEntityId(
        ImmutableArray<MappingClassInfo> mappings,
        INamedTypeSymbol entityType)
    {
        var name =
            ResolveStorageEntityName(
                mappings,
                entityType);


        var entities =
            mappings
                .SelectMany(x => x.Definition.Entities)
                .Where(x => x.EntityType != null)
                .Select(x =>
                    IdEmitter.StripEntitySuffix(
                        x.EntityType!.Name))
                .Distinct(StringComparer.OrdinalIgnoreCase)
                .OrderBy(x => x, StringComparer.Ordinal)
                .ToList();


        var index =
            entities.FindIndex(x =>
                string.Equals(
                    x,
                    name,
                    StringComparison.OrdinalIgnoreCase));


        if (index < 0)
        {
            throw new InvalidOperationException(
                $"Storage entity '{name}' does not exist.");
        }


        return (ushort)index;
    }

    private static string ResolveStorageEntityName(
    ImmutableArray<MappingClassInfo> mappings,
    INamedTypeSymbol entityType)
{
    var entityName =
        IdEmitter.StripEntitySuffix(
            entityType.Name);


    //
    // Direct storage entity match.
    //
    foreach (var mapping in mappings)
    {
        foreach (var entity in mapping.Definition.Entities)
        {
            if (entity.EntityType == null)
                continue;


            var candidate =
                IdEmitter.StripEntitySuffix(
                    entity.EntityType.Name);


            if (string.Equals(
                candidate,
                entityName,
                StringComparison.OrdinalIgnoreCase))
            {
                return candidate;
            }
        }
    }


    //
    // Graph edge fallback.
    //
    // Example:
    // CustomerCustomerEdge
    //          |
    //          v
    // CustomerCustomerRelationship
    //
    if (entityName.EndsWith(
            "Edge",
            StringComparison.OrdinalIgnoreCase))
    {
        var baseName =
            entityName.Substring(
                0,
                entityName.Length - 4);


        foreach (var mapping in mappings)
        {
            foreach (var entity in mapping.Definition.Entities)
            {
                if (entity.EntityType == null)
                    continue;


                var candidate =
                    IdEmitter.StripEntitySuffix(
                        entity.EntityType.Name);


                if (candidate.StartsWith(
                        baseName,
                        StringComparison.OrdinalIgnoreCase))
                {
                    return candidate;
                }
            }
        }
    }


    //
    // Last-resort relationship matching.
    //
    foreach (var mapping in mappings)
    {
        foreach (var entity in mapping.Definition.Entities)
        {
            if (entity.EntityType == null)
                continue;


            var candidate =
                IdEmitter.StripEntitySuffix(
                    entity.EntityType.Name);


            if (candidate.IndexOf(
                    entityName,
                    StringComparison.OrdinalIgnoreCase) >= 0
                ||
                entityName.IndexOf(
                    candidate,
                    StringComparison.OrdinalIgnoreCase) >= 0)
            {
                return candidate;
            }
        }
    }


    throw new InvalidOperationException(
        $"Unable to resolve storage entity name for '{entityName}'.");
}

private static string ResolveRelatedSurrogateIdColumn(
    MappingClassInfo info,
    string relatedEntity)
{
    var entity =
        info.Definition.Entities
            .FirstOrDefault(e =>
                e.EntityType != null &&
                string.Equals(
                    IdEmitter.StripEntitySuffix(
                        e.EntityType.Name),
                    relatedEntity,
                    StringComparison.OrdinalIgnoreCase));


    if (entity == null)
    {
        throw new InvalidOperationException(
            $"Unable to resolve surrogate key for entity '{relatedEntity}'.");
    }



    var primaryKey =
        info.Definition.PrimaryKey
            .FirstOrDefault(pk =>
                pk.Entity != null &&
                string.Equals(
                    IdEmitter.StripEntitySuffix(
                        pk.Entity.Name),
                    relatedEntity,
                    StringComparison.OrdinalIgnoreCase));



    if (primaryKey == null ||
        string.IsNullOrWhiteSpace(primaryKey.ColumnKey))
    {
        throw new InvalidOperationException(
            $"Entity '{relatedEntity}' has no primary key metadata.");
    }



    return primaryKey.ColumnKey;
}

private static void EmitConflictColumnArray(
    StringBuilder sb,
    MappingClassInfo info,
    string modelName,
    IReadOnlyList<string> keys,
    ImmutableArray<MappingClassInfo> allMappings,
    List<FluentEntityNavigationConvention.EntityForeignKeyGraph.Edge> entityGraph)
{
    if (keys.Count == 0)
    {
        sb.AppendLine(
            "            ImmutableArray<ConflictColumn>.Empty,");

        return;
    }

    sb.AppendLine(
        "            ImmutableArray.Create(");

    for (var i = 0; i < keys.Count; i++)
    {
        var key = keys[i];

        var comma =
            i < keys.Count - 1
                ? ","
                : "";

        var columnId =
            ResolveColumnId(
                info,
                key,
                allMappings,
                entityGraph);

        sb.AppendLine(
            $"                new ConflictColumn(FieldId.{modelName}.{key}, {columnId}, \"{Escape(key)}\"){comma}");
    }

    sb.AppendLine(
        "            ),");
}

    private static void EmitFactory(
    StringBuilder sb,
    MappingClassInfo info,
    ImmutableArray<MappingClassInfo> allMappings,
    List<FluentEntityNavigationConvention.EntityForeignKeyGraph.Edge> entityGraph)
{
    var modelName =
        info.ModelType!.Name;


    var primaryEntity =
        info.Definition.Entities
            .FirstOrDefault(e => e.IsPrimary)
        ??
        info.Definition.Entities.FirstOrDefault();


    if (primaryEntity?.EntityType == null)
    {
        sb.AppendLine(
            $"    private static MutationEntityMetadata Create{modelName}()");

        sb.AppendLine(
            $"        => throw new InvalidOperationException(\"{modelName} has no primary entity.\");");

        return;
    }


    var storageEntityIdName =
        ResolveStorageEntityIdName(
            info,
            primaryEntity.EntityType,
            allMappings);



    var storageEntities =
        GetStorageEntities(info);



    var primaryStorage =
        storageEntities.FirstOrDefault(x =>
            string.Equals(
                x.EntityName,
                IdEmitter.StripEntitySuffix(primaryEntity.EntityType.Name),
                StringComparison.OrdinalIgnoreCase));


    if (primaryStorage == default)
    {
        primaryStorage =
            storageEntities.FirstOrDefault();
    }


    if (primaryStorage == default)
    {
        sb.AppendLine(
            $"    private static MutationEntityMetadata Create{modelName}()");

        sb.AppendLine(
            $"        => throw new InvalidOperationException(\"{modelName} has no storage entities.\");");

        return;
    }


    var schema =
        primaryStorage.Schema;



    var hasGraphMetadata =
        info.Graph != null &&
        info.Graph.From != null &&
        info.Graph.To != null;



    var kind =
        hasGraphMetadata
            ? "MutationKind.GraphEdge"
            : "MutationKind.Entity";



    var primaryColumns =
        info.Definition.PrimaryKey
            .Select(x => x.ColumnKey)
            .Where(x => !string.IsNullOrWhiteSpace(x))
            .ToList();



    var grouped =
        info.FieldMaps
            .Where(f =>
                !IsStorageOnlyField(info, f))
            .GroupBy(
                f => f.SourceName,
                StringComparer.Ordinal)
            .ToList();

    var allNavigationKeyFields =
        info.FieldMaps
            .Where(f => f.IsNavigationKey)
            .ToList();



    var fieldLines =
        new List<string>();



    foreach (var group in grouped)
    {
        var fieldIdName =
            GeneratedIdentifierHelper.Field(
                group.Key);



        var metadataLines =
            new List<string>();


        foreach (var target in group)
        {
            var storageEntityName =
                IdEmitter.StripEntitySuffix(
                    target.DestinationEntity);


            var columnName =
                target.DestinationName;



            if (target.IsNavigationKey &&
                hasGraphMetadata)
            {
                var index =
                    allNavigationKeyFields.IndexOf(target);

                var alias =
                    index == 0
                        ? info.Graph!.From.Alias
                        : info.Graph!.To.Alias;

                var owningEntityType =
                    info.Definition.Entities
                        .FirstOrDefault(e => e.IsPrimary && e.EntityType != null)
                        ?.EntityType;

                var relatedEntityTypeForFk =
                    info.Definition.Entities
                        .FirstOrDefault(e =>
                            e.EntityType != null &&
                            string.Equals(
                                IdEmitter.StripEntitySuffix(e.EntityType.Name),
                                storageEntityName,
                                StringComparison.OrdinalIgnoreCase))
                        ?.EntityType;

                var expectedFkColumn =
                    !string.IsNullOrWhiteSpace(alias)
                        ? alias + "Id"
                        : null;

                if (owningEntityType != null &&
                    relatedEntityTypeForFk != null &&
                    expectedFkColumn != null)
                {
                    var fkEdge =
                        entityGraph.FirstOrDefault(e =>
                            SymbolEqualityComparer.Default.Equals(
                                e.DependentEntity, owningEntityType) &&
                            SymbolEqualityComparer.Default.Equals(
                                e.PrincipalEntity, relatedEntityTypeForFk) &&
                            string.Equals(
                                e.DependentColumn,
                                expectedFkColumn,
                                StringComparison.OrdinalIgnoreCase));

                    if (fkEdge != null)
                    {
                        storageEntityName =
                            IdEmitter.StripEntitySuffix(owningEntityType.Name);

                        columnName =
                            fkEdge.DependentColumn;
                    }
                }
            }



            var columnId =
                ResolveMutationFieldColumnId(
                    info,
                    target,
                    storageEntityName,
                    columnName,
                    allMappings,
                    entityGraph);



            var isPrimary =
                info.Definition.PrimaryKey.Any(pk =>
                    string.Equals(
                        IdEmitter.StripEntitySuffix(
                            pk.Entity.Name),
                        storageEntityName,
                        StringComparison.OrdinalIgnoreCase)
                    &&
                    string.Equals(
                        pk.ColumnKey,
                        columnName,
                        StringComparison.OrdinalIgnoreCase));



            metadataLines.Add(
                $"new MutationFieldMetadata(" +
                $"FieldId.{modelName}.{fieldIdName}, " +
                $"EntityId.{modelName}, " +
                $"StorageEntityId.{storageEntityName}, " +
                $"{columnId}, " +
                $"{(isPrimary ? "true" : "false")}, " +
                $"{(target.IsNavigationKey ? "true" : "false")}, " +
                $"\"{Escape(group.Key)}\")");
        }



        fieldLines.Add(
            $"                [FieldId.{modelName}.{fieldIdName}] = " +
            $"ImmutableArray.Create({string.Join(", ", metadataLines)})");
    }



    sb.AppendLine(
        $"    private static MutationEntityMetadata Create{modelName}()");

    sb.AppendLine("    {");

    sb.AppendLine(
        "        return new MutationEntityMetadata(");



    sb.AppendLine(
        $"            EntityId.{modelName},");



    sb.AppendLine(
        $"            StorageEntityId.{storageEntityIdName},");



    sb.AppendLine(
        $"            \"{Escape(schema)}\",");



    sb.AppendLine(
        $"            \"{Escape(IdEmitter.StripEntitySuffix(primaryEntity.EntityType.Name))}\",");



    var isComposite =
        info.Definition.Entities.Count > 1;



    sb.AppendLine(
        isComposite
            ? "            false,"
            : "            true,");



    sb.AppendLine(
        $"            {kind},");



    EmitConflictColumnArray(
        sb,
        info,
        modelName,
        isComposite
            ? info.UpsertKeys.Select(x => x.Key).Distinct().ToList()
            : primaryColumns,
        allMappings,
        entityGraph);



    sb.AppendLine();



    sb.AppendLine(
        "            new Dictionary<ushort, ImmutableArray<MutationFieldMetadata>>");

    sb.AppendLine(
        "            {");



    if (fieldLines.Count > 0)
    {
        sb.AppendLine(
            string.Join(",\n", fieldLines));
    }



    sb.AppendLine(
        "            },");



    EmitStorageEntities(
        sb,
        info);



    if (hasGraphMetadata)
    {
        EmitGraphMetadata(
            sb,
            info,
            modelName);
    }



    sb.AppendLine(
        "        );");

    sb.AppendLine(
        "    }");
}

    private static void EmitGraphMetadata(
        StringBuilder sb,
        MappingClassInfo info,
        string modelName)
    {
        sb.AppendLine(",");



        var navigationFields =
            info.FieldMaps
                .Where(x => x.IsNavigationKey)
                .ToList();



        FieldInfo? fromField =
            navigationFields.Count > 0
                ? navigationFields[0]
                : null;



        FieldInfo? toField =
            navigationFields.Count > 1
                ? navigationFields[1]
                : null;



        sb.AppendLine(
            $"            graphName: \"{Escape(info.Graph!.GraphName)}\",");



        sb.AppendLine(
            $"            graphEdgeLabel: \"{Escape(info.Graph.EdgeLabel)}\",");



        sb.AppendLine(
            $"            graphFromVertex: \"{Escape(info.Graph.From.Label)}\",");



        sb.AppendLine(
            $"            graphToVertex: \"{Escape(info.Graph.To.Label)}\",");



        sb.AppendLine(
            $"            graphFromColumn: \"{Escape(info.Graph.From.GraphProperty)}\",");



        sb.AppendLine(
            $"            graphToColumn: \"{Escape(info.Graph.To.GraphProperty)}\",");



        sb.AppendLine(
            fromField != null
                ? $"            graphFromFieldId: FieldId.{modelName}.{GeneratedIdentifierHelper.Field(fromField.SourceName)},"
                : "            graphFromFieldId: null,");



        sb.AppendLine(
            toField != null
                ? $"            graphToFieldId: FieldId.{modelName}.{GeneratedIdentifierHelper.Field(toField.SourceName)}"
                : "            graphToFieldId: null");
    }

    private static ushort ResolveMutationFieldColumnId(
    MappingClassInfo info,
    FieldInfo field,
    string storageEntityName,
    string columnName,
    ImmutableArray<MappingClassInfo> allMappings,
    List<FluentEntityNavigationConvention.EntityForeignKeyGraph.Edge> entityGraph)
{
    //
    // Graph navigation:
    // Resolve against graph endpoint entity.
    //
    if (field.IsNavigationKey &&
        info.Graph != null)
    {
        var graphEntity =
            info.Definition.Entities
                .FirstOrDefault(e =>
                    e.EntityType != null &&
                    string.Equals(
                        IdEmitter.StripEntitySuffix(
                            e.EntityType.Name),
                        storageEntityName,
                        StringComparison.OrdinalIgnoreCase));


        if (graphEntity?.EntityType != null)
        {
            return ColumnIdResolver.Resolve(
                graphEntity.EntityType,
                columnName,
                allMappings,
                entityGraph);
        }


        //
        // Graph endpoint may belong to another mapping.
        //
        var externalMapping =
            allMappings.FirstOrDefault(x =>
                x.Definition.Entities.Any(e =>
                    e.EntityType != null &&
                    string.Equals(
                        IdEmitter.StripEntitySuffix(
                            e.EntityType.Name),
                        storageEntityName,
                        StringComparison.OrdinalIgnoreCase)));


        var externalEntity =
            externalMapping?
                .Definition.Entities
                .FirstOrDefault(e =>
                    e.EntityType != null &&
                    string.Equals(
                        IdEmitter.StripEntitySuffix(
                            e.EntityType.Name),
                        storageEntityName,
                        StringComparison.OrdinalIgnoreCase))
                ?.EntityType;


        if (externalEntity != null)
        {
            return ColumnIdResolver.Resolve(
                externalEntity,
                columnName,
                allMappings,
                entityGraph);
        }
    }


    //
    // Local entity resolution.
    //
    var localEntity =
        info.Definition.Entities
            .FirstOrDefault(e =>
                e.EntityType != null &&
                string.Equals(
                    IdEmitter.StripEntitySuffix(
                        e.EntityType.Name),
                    storageEntityName,
                    StringComparison.OrdinalIgnoreCase));


    if (localEntity?.EntityType != null)
    {
        return ColumnIdResolver.Resolve(
            localEntity.EntityType,
            columnName,
            allMappings,
            entityGraph);
    }



    //
    // Cross-model navigation:
    // Customer -> ContactPoint
    // Customer -> Product
    // etc.
    //
    var relatedEntity =
        allMappings
            .SelectMany(x => x.Definition.Entities)
            .FirstOrDefault(e =>
                e.EntityType != null &&
                string.Equals(
                    IdEmitter.StripEntitySuffix(
                        e.EntityType.Name),
                    storageEntityName,
                    StringComparison.OrdinalIgnoreCase));


    if (relatedEntity?.EntityType != null)
    {
        return ColumnIdResolver.Resolve(
            relatedEntity.EntityType,
            columnName,
            allMappings,
            entityGraph);
    }



    throw new InvalidOperationException(
        $"Unable to resolve mutation field column '{columnName}' " +
        $"on storage entity '{storageEntityName}' " +
        $"for field '{field.SourceName}'.");
}
    
    private static void EmitStorageEntities(
    StringBuilder sb,
    MappingClassInfo info)
{
    //
    // Argument #9 - CTE metadata
    //
    if (info.CteUpdateMeta.Count == 0)
    {
        sb.AppendLine(
            "            ImmutableArray<CteUpdateMetaInfo>.Empty,");
    }
    else
    {
        sb.AppendLine(
            "            ImmutableArray.Create(");


        for (var i = 0; i < info.CteUpdateMeta.Count; i++)
        {
            var meta =
                info.CteUpdateMeta[i];


            var comma =
                i < info.CteUpdateMeta.Count - 1
                    ? ","
                    : "";


            sb.AppendLine(
                "                new CteUpdateMetaInfo");

            sb.AppendLine(
                "                {");


            sb.AppendLine(
                $"                    NavigationAlias = \"{Escape(meta.NavigationAlias)}\",");


            sb.AppendLine(
                $"                    ForeignKeyColumn = \"{Escape(meta.ForeignKeyColumn)}\",");


            sb.AppendLine(
                $"                    ForeignKeyColumnId = {meta.ForeignKeyColumnId},");


            sb.AppendLine(
                $"                    OwningPrimaryKeyColumn = \"{Escape(meta.OwningPrimaryKeyColumn)}\",");


            sb.AppendLine(
                $"                    OwningPrimaryKeyColumnId = {meta.OwningPrimaryKeyColumnId},");


            sb.AppendLine(
                $"                    RelatedEntityTypeName = \"{Escape(meta.RelatedEntityTypeName)}\",");


            sb.AppendLine(
                $"                    RelatedStorageEntityId = {meta.RelatedStorageEntityId},");


            sb.AppendLine(
                $"                    RelatedSurrogateIdColumn = \"{Escape(meta.RelatedSurrogateIdColumn)}\",");


            sb.AppendLine(
                $"                    RelatedSurrogateIdColumnId = {meta.RelatedSurrogateIdColumnId},");


            sb.AppendLine(
                $"                    RelatedNaturalKeyColumn = \"{Escape(meta.RelatedNaturalKeyColumn)}\",");


            sb.AppendLine(
                $"                    RelatedNaturalKeyColumnId = {meta.RelatedNaturalKeyColumnId}");


            sb.AppendLine(
                $"                }}{comma}");
        }


        sb.AppendLine(
            "            ),");
    }
    
    var entities =
        info.Definition.Entities
            .Where(e => e.EntityType != null)
            .Select(e =>
            {
                return new
                {
                    Name =
                        IdEmitter.StripEntitySuffix(
                            e.EntityType!.Name),

                    Schema =
                        e.Schema
                        ?? info.Schema
                        ?? "public"
                };
            })
            .Distinct()
            .ToList();



    if (entities.Count == 0)
    {
        sb.AppendLine(
            "            ImmutableArray<MutationStorageEntityMetadata>.Empty");

        return;
    }



    sb.AppendLine(
        "            ImmutableArray.Create(");



    for (var i = 0; i < entities.Count; i++)
    {
        var comma =
            i < entities.Count - 1
                ? ","
                : "";


        sb.AppendLine(
            "                new MutationStorageEntityMetadata(");


        sb.AppendLine(
            $"                    StorageEntityId.{entities[i].Name},");


        sb.AppendLine(
            $"                    \"{Escape(entities[i].Schema)}\",");


        sb.AppendLine(
            $"                    \"{Escape(entities[i].Name)}\"){comma}");
    }



    sb.AppendLine(
        "            )");
}



    private static bool IsStorageOnlyField(
        MappingClassInfo info,
        FieldInfo field)
    {
        //
        // Navigation fields are required for graph endpoint resolution.
        //
        if (field.IsNavigationKey)
            return false;



        return info.Definition.PrimaryKey.Any(pk =>
            string.Equals(
                IdEmitter.StripEntitySuffix(pk.Entity.Name),
                IdEmitter.StripEntitySuffix(field.DestinationEntity),
                StringComparison.OrdinalIgnoreCase)
            &&
            string.Equals(
                pk.ColumnKey,
                field.DestinationName,
                StringComparison.OrdinalIgnoreCase));
    }




    private static string Escape(
        string value)
    {
        return value
            .Replace("\\", "\\\\")
            .Replace("\"", "\\\"");
    }
}