<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>Foundgine.InMemory</RootNamespace>
    <AssemblyName>Foundgine.InMemory</AssemblyName>
    <IsPackable>true</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Foundgine.Execution/Foundgine.Execution.csproj" />
    <ProjectReference Include="../Foundgine.Metadata/Foundgine.Metadata.csproj" />
    <ProjectReference Include="../Foundgine.Planning/Foundgine.Planning.csproj" />
    <ProjectReference Include="../Foundgine.Semantics/Foundgine.Semantics.csproj" />
  </ItemGroup>
</Project>
