using System.ComponentModel;
using System.Text.Json;
using Foundgine.Execution;
using Foundgine.Intent.Json;
using Foundgine.Semantics.Security.Execution;
using ModelContextProtocol.Server;
using ExecutionContext = Foundgine.Execution.ExecutionContext;

namespace Foundgine.MCP;

/// <summary>
/// MCP transport adapter for the Foundgine semantic application contract.
/// MCP arguments are translated into Foundgine inputs; MCP never owns domain
/// semantics, authorization, planning, or provider execution.
/// </summary>
[McpServerToolType]
public sealed class FoundgineMcpTools
{
    private static readonly JsonSerializerOptions JsonOptions = new(JsonSerializerDefaults.Web);

    private readonly IFoundgine _foundgine;
    private readonly JsonReadIntentAdapter _adapter;
    private readonly Func<ExecutionContext> _contextFactory;
    private readonly ISecurityExecutionContextProvider _securityContextProvider;

    /// <param name="foundgine">The Foundgine execution engine.</param>
    /// <param name="adapter">The JSON read-intent adapter. Defaults to a new instance.</param>
    /// <param name="contextFactory">Supplies execution context values per call. Defaults to an empty context.</param>
    /// <param name="securityContextProvider">
    /// Host-owned source of the caller's <see cref="SecurityExecutionContext"/>. Prefer this
    /// over <paramref name="securityContextFactory"/> for new hosts; both may not be supplied
    /// together.
    /// </param>
    /// <param name="securityContextFactory">
    /// Obsolete delegate form of <paramref name="securityContextProvider"/>, retained for
    /// existing hosts. Internally wrapped in a <see cref="DelegateSecurityExecutionContextProvider"/>.
    /// </param>
    public FoundgineMcpTools(
        IFoundgine foundgine,
        JsonReadIntentAdapter? adapter = null,
        Func<ExecutionContext>? contextFactory = null,
        ISecurityExecutionContextProvider? securityContextProvider = null,
        Func<SecurityExecutionContext?>? securityContextFactory = null)
    {
        _foundgine = foundgine ?? throw new ArgumentNullException(nameof(foundgine));
        _adapter = adapter ?? new JsonReadIntentAdapter();
        _contextFactory = contextFactory ?? (() => new ExecutionContext());

        if (securityContextProvider is not null && securityContextFactory is not null)
            throw new ArgumentException(
                $"Only one of {nameof(securityContextProvider)} or {nameof(securityContextFactory)} may be supplied.",
                nameof(securityContextFactory));

        _securityContextProvider = securityContextProvider
            ?? (securityContextFactory is not null
                ? new DelegateSecurityExecutionContextProvider(securityContextFactory)
                : new DelegateSecurityExecutionContextProvider(() => null));
    }

    /// <summary>
    /// Returns the canonical capability contract generated by Foundgine for the
    /// current caller. Discovery does not grant authorization.
    /// </summary>
    [McpServerTool(Name = "foundgine_capabilities")]
    [Description("Discover the Foundgine semantic capability contract available to the current caller. Discovery is descriptive; authorization is re-evaluated during execution.")]
    public string DescribeCapabilities()
    {
        var security = _securityContextProvider.RequireSecurityExecutionContext(
            "MCP", "capability discovery");

        return JsonSerializer.Serialize(
            _foundgine.DescribeCapabilityContract(security),
            JsonOptions);
    }

    /// <summary>
    /// Executes provider-neutral read intent through the Foundgine pipeline.
    /// Authentication, tenant and authorization context remain host-owned.
    /// </summary>
    [McpServerTool(Name = "foundgine_query")]
    [Description("Execute a provider-neutral Foundgine read intent as JSON. Use only entities, fields and relationships from foundgine_capabilities. Never supply tenant, identity, authorization predicates, SQL, provider or connection details.")]
    public async Task<string> ExecuteQueryAsync(
        [Description("JSON read intent containing rootEntity, selections, and optional filter/order/limit/offset/after. Do not include authentication, tenant or authorization context.")] string intentJson,
        CancellationToken cancellationToken = default)
    {
        if (string.IsNullOrWhiteSpace(intentJson))
            throw new ArgumentException("Intent JSON is required.", nameof(intentJson));

        var intent = _adapter.Parse(intentJson);
        var security = _securityContextProvider.RequireSecurityExecutionContext(
            "MCP", "execution");
        intent = intent with { Security = security };
        var result = await _foundgine.ExecuteAsync(
            intent,
            _contextFactory(),
            cancellationToken);

        return JsonSerializer.Serialize(new
        {
            rows = result.Rows.Select(row => row.Values).ToArray(),
            pageInfo = result.PageInfo,
            evidence = result.Evidence,
            receipt = result.Receipt
        }, JsonOptions);
    }
}
