<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>netstandard2.0</TargetFramework>
        <LangVersion>latest</LangVersion>
        <Nullable>enable</Nullable>

        <!-- Roslyn generator settings -->
        <IsRoslynComponent>true</IsRoslynComponent>
        <IncludeBuildOutput>false</IncludeBuildOutput>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>

        <!-- Debug generated output while developing -->
        <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
        <CompilerGeneratedFilesOutputPath>$(BaseIntermediateOutputPath)Generated</CompilerGeneratedFilesOutputPath>

        <EnforceExtendedAnalyzerRules>true</EnforceExtendedAnalyzerRules>

        <RootNamespace>CoffeeBeanery.GraphQL.Core.Mapping.Generators</RootNamespace>
    </PropertyGroup>


    <ItemGroup>
        <PackageReference Include="Microsoft.CodeAnalysis.CSharp"
                          Version="4.14.0"
                          PrivateAssets="all" />

        <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Workspaces"
                          Version="4.14.0"
                          PrivateAssets="all" />

        <PackageReference Include="Microsoft.CodeAnalysis.Common"
                          Version="4.14.0"
                          PrivateAssets="all" />

        <PackageReference Include="Microsoft.CodeAnalysis.Analyzers"
                          Version="3.11.0"
                          PrivateAssets="all" />
    </ItemGroup>


    <!-- Put generator assembly in analyzer folder when packed -->
    <ItemGroup>
        <None Include="$(OutputPath)$(AssemblyName).dll"
              Pack="true"
              PackagePath="analyzers/dotnet/cs"
              Visible="false" />
    </ItemGroup>


</Project>