using System;
using System.Linq;
using Microsoft.CodeAnalysis;
using CoffeeBeanery.GraphQL.Core.Mapping.Generators.Passes;

namespace CoffeeBeanery.GraphQL.Core.Mapping.Generators
{
    /// <summary>
    /// Runs in the entity-defining project itself (e.g. Database.Entity), where
    /// fluent EF configuration syntax is actually visible, and emits a SINGLE
    /// assembly-level [EntityForeignKeyGraph(...)] attribute carrying every
    /// derived FK edge as a delimited string - so MappingNodeGenerator (running
    /// separately in e.g. Domain.Shared) can rebuild the same edge list via
    /// ordinary compiled-metadata lookup, without either project needing to
    /// reference the other's source or duplicate any mapping logic by hand.
    ///
    /// Replaces the earlier per-class [EntityForeignKey] attribute approach:
    /// one assembly attribute instead of N per-class attributes removes the
    /// requirement that entity classes be declared 'partial', and lets the
    /// consuming side do a single lookup instead of walking every named type
    /// in the compilation looking for decorated classes.
    /// </summary>
    [Generator(LanguageNames.CSharp)]
    public sealed class EntityForeignKeyEmitterGenerator : IIncrementalGenerator
    {
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            context.RegisterPostInitializationOutput(static ctx =>
            {
                ctx.AddSource("EntityForeignKeyAttribute.g.cs", EntityForeignKeyAttributeSourceText.Value);
            });

            var derivedKeys = context.CompilationProvider
                .Select(static (compilation, ct) => FluentEntityNavigationConvention.CollectAll(compilation, ct));

            context.RegisterSourceOutput(derivedKeys, static (spc, keys) =>
            {
                try
                {
                    // Format: edges joined with ';', each edge is
                    // "{DependentTypeFullName}|{FkColumn}|{PrincipalTypeFullName}|{PkColumn}"
                    var edgeLines = keys.Select(k =>
                        $"{k.DeclaringEntityType.ToDisplayString()}|{k.RawForeignKeyColumn}|" +
                        $"{k.RelatedEntityType.ToDisplayString()}|{k.RawPrincipalKeyColumn}");

                    var serialized = string.Join(";", edgeLines);

                    // Escape for a C# verbatim string literal — only " needs doubling in @"...".
                    var escaped = serialized.Replace("\"", "\"\"");

                    var source =
                        $"[assembly: global::CoffeeBeanery.GraphQL.Core.Mapping.EntityForeignKeyGraph(@\"{escaped}\")]";

                    spc.AddSource("EntityForeignKeyGraph.g.cs", source);
                }
                catch (Exception ex)
                {
                    spc.ReportDiagnostic(Diagnostic.Create(
                        MappingDiagnostics.GeneratorCrashDescriptor,
                        Location.None,
                        ex.GetType().Name,
                        ex.Message,
                        ex.StackTrace?.Replace("\r\n", " ").Replace("\n", " ") ?? ""));

                    spc.AddSource("GeneratorCrash.g.cs", $@"
                    // <auto-generated/>
                    // GENERATOR CRASHED — see CBM000 diagnostic for details
                    #error CBM000: Source generator crashed: {ex.GetType().Name}: {ex.Message}
                    ");
                }
            });
        }
    }
}