using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using CoffeeBeanery.GraphQL.Core.Mapping.Generators;
using CoffeeBeanery.GraphQL.Core.Mapping.Generators.Emit;
using CoffeeBeanery.GraphQL.Core.Mapping.Generators.Model;
using CoffeeBeanery.GraphQL.Core.Mapping.Generators.Passes;
using Microsoft.CodeAnalysis;

internal static class MetadataEmitter
{
    public static string Emit(
        ImmutableArray<MappingClassInfo> allMappings,
        ImmutableHashSet<INamedTypeSymbol> rootEntityTypes,
        List<FluentEntityNavigationConvention.EntityForeignKeyGraph.Edge> entityGraph)
    {
        var models = allMappings
            .Where(m => m.IsModel)
            .GroupBy(m => m.ModelType.Name, System.StringComparer.OrdinalIgnoreCase)
            .Select(g => g.First())
            .OrderBy(m => m.ModelType.Name, System.StringComparer.Ordinal)
            .ToList();

        var navResults = models.ToDictionary(
            m => m.ModelType.Name,
            m => EntityNavigationConvention.Resolve(m, allMappings, entityGraph, rootEntityTypes),
            System.StringComparer.Ordinal);

        foreach (var m in models)
        {
            if (m.CteUpdateMeta.Count > 0)
                continue;

            var navResult = EntityNavigationConvention.Resolve(
                m,
                allMappings,
                entityGraph,
                rootEntityTypes);

            PopulateCteUpdateMeta(m, navResult);
        }

        var entityTypes = allMappings
            .SelectMany(m => m.Definition.Entities)
            .Where(x => x.EntityType is not null)
            .Select(x => x.EntityType!)
            .GroupBy(
                e => e.Name,
                StringComparer.Ordinal)
            .Select(g => g.First())
            .OrderBy(
                e => e.Name,
                StringComparer.Ordinal)
            .ToList();

        var entitySchemaLookup = allMappings
            .SelectMany(m => m.Definition.Entities
                .Where(x => x.EntityType != null)
                .Select(x => new
                {
                    Entity = x.EntityType!.Name,
                    Schema = m.Schema
                }))
            .Where(x => !string.IsNullOrEmpty(x.Schema))
            .GroupBy(
                x => x.Entity,
                StringComparer.Ordinal)
            .ToDictionary(
                g => g.Key,
                g => g.First().Schema,
                StringComparer.Ordinal);

        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System;");
        sb.AppendLine();

        sb.AppendLine("namespace CoffeeBeanery.GraphQL.Core.Runtime");
        sb.AppendLine("{");

        sb.AppendLine("    public static class EntityMeta");
        sb.AppendLine("    {");

        EmitModelNameArray(sb, models);
        EmitTableArray(sb, models);
        EmitSchemaArray(sb, models);
        EmitColumnNameArray(sb, models);
        EmitFieldNameArray(sb, models);
        EmitFieldToColumnArray(sb, models);
        EmitFieldMappingsArray(sb, models);
        EmitConflictColumnsArray(sb, models);
        EmitCteResolutionsArray(sb, models);

        EmitEntitySchemaArray(
            sb,
            entityTypes,
            entitySchemaLookup,
            models);

        EmitEntityTableArray(
            sb,
            entityTypes);

        EmitEntityColumnNameArray(
            sb,
            entityTypes,
            allMappings);

        sb.AppendLine("    }");

        EmitEnumConversions(sb, models);

        sb.AppendLine("}");
        sb.AppendLine();

        EmitModelIdConstants(sb, models);

        EmitGeneratedEntityMetaProvider(sb);

        EmitGeneratedPlannerRegistry(sb);

        return sb.ToString();
    }

    private static void EmitFieldToColumnArray(
        StringBuilder sb,
        List<MappingClassInfo> models)
    {
        sb.AppendLine(
            $"        public static readonly ushort[][] FieldToColumn = new ushort[{models.Count}][]");

        sb.AppendLine("        {");

        foreach (var m in models)
        {
            var mappings = PlannerEmitter.ComputeFieldMappingsEagerPublic(
                m,
                PlannerEmitter.IsCompositeInfo(m));

            if (mappings.Count == 0)
            {
                sb.AppendLine(
                    "            System.Array.Empty<ushort>(),");
                continue;
            }

            var ids = new List<ushort>();

            foreach (var fm in mappings)
            {
                var entity = m.Definition.Entities
                    .FirstOrDefault(e =>
                        e.EntityType != null &&
                        string.Equals(
                            e.EntityType.Name,
                            fm.EntityTypeName,
                            StringComparison.Ordinal));

                if (entity?.EntityType == null)
                {
                    ids.Add(ushort.MaxValue);
                    continue;
                }

                var columns = IdEmitter.GetScalarProperties(
                    entity.EntityType);
                
                var index = columns.FindIndex(c =>
                    string.Equals(
                        c.Name,
                        fm.ColumnName,
                        StringComparison.OrdinalIgnoreCase));

                ids.Add(
                    index < 0
                        ? ushort.MaxValue
                        : (ushort)index);
            }

            sb.AppendLine(
                $"            new ushort[] {{ {string.Join(", ", ids)} }},");
        }

        sb.AppendLine("        };");
        sb.AppendLine();
    }
    
    private static void EmitEnumConversions(
        StringBuilder sb,
        List<MappingClassInfo> models)
    {
        var enumFields = models
            .SelectMany(m => m.FieldMaps
                .Where(f => f.FromEnum != null && f.FromEnum.Count > 0)
                .Select(f => (Model: m, Field: f)))
            .ToList();

        sb.AppendLine("    public static class EnumConversions");
        sb.AppendLine("    {");

        sb.AppendLine(
            "        // Converts a model enum name string to its integer string value.");

        sb.AppendLine(
            "        // Returns null if the field has no enum conversion or the name is unknown.");

        sb.AppendLine(
            "        public static string? TryConvert(ushort storageEntityId, ushort columnId, string value)");

        sb.AppendLine("        {");

        sb.AppendLine(
            "            var normalizedValue = value.Trim().ToUpperInvariant();");
        sb.AppendLine("            switch (storageEntityId)");
        sb.AppendLine("            {");

        foreach (var group in enumFields.GroupBy(
                     x => x.Field.DestinationEntity,
                     StringComparer.Ordinal))
        {
            var entityName = group.Key;

            sb.AppendLine(
                $"                case StorageEntityId.{entityName}:");

            sb.AppendLine("                    switch (columnId)");
            sb.AppendLine("                    {");

            foreach (var (_, field) in group)
            {
                sb.AppendLine(
                    $"                        case (ushort)ColumnId.{entityName}.{field.DestinationName}:");

                sb.AppendLine("                            return normalizedValue switch");
                sb.AppendLine("                            {");

                foreach (var kvp in field.FromEnum!)
                {
                    sb.AppendLine(
                        $"                                \"{kvp.Key.Trim().ToUpperInvariant()}\" => \"{kvp.Value}\",");
                }

                sb.AppendLine(
                    "                                _ => null");

                sb.AppendLine("                            };");
            }

            sb.AppendLine("                    }");
            sb.AppendLine("                    break;");
        }

        sb.AppendLine("            }");

        sb.AppendLine("            return null;");
        sb.AppendLine("        }");

        sb.AppendLine("    }");
        sb.AppendLine();
    }


    private static ushort ResolveStorageEntityId(
        List<MappingClassInfo> models,
        object destinationEntity)
    {
        if (destinationEntity is ushort id)
            return id;

        var name = destinationEntity.ToString();

        var entities = models
            .SelectMany(m => m.Definition.Entities)
            .Where(x => x.EntityType != null)
            .Select(x => x.EntityType!)
            .GroupBy(
                x => x.Name,
                StringComparer.Ordinal)
            .Select(g => g.First())
            .OrderBy(
                x => x.Name,
                StringComparer.Ordinal)
            .ToList();

        var index = entities.FindIndex(e => string.Equals(
            e.Name,
            name,
            StringComparison.Ordinal));

        if (index < 0)
        {
            throw new InvalidOperationException(
                $"Cannot resolve storage entity id for '{name}'");
        }

        return (ushort)index;
    }

    private static void EmitFieldMappingsArray( StringBuilder sb, List<MappingClassInfo> models) { sb.AppendLine( $" public static readonly global::CoffeeBeanery.GraphQL.Core.Runtime.FieldMapSpec[][] FieldMappings = " + $"new global::CoffeeBeanery.GraphQL.Core.Runtime.FieldMapSpec[{models.Count}][]"); sb.AppendLine( " {"); foreach (var m in models) { var mappings = PlannerEmitter.ComputeFieldMappingsEagerPublic( m, PlannerEmitter.IsCompositeInfo(m)); if (mappings.Count == 0) { sb.AppendLine( " System.Array.Empty<global::CoffeeBeanery.GraphQL.Core.Runtime.FieldMapSpec>(),"); continue; } sb.AppendLine( " new global::CoffeeBeanery.GraphQL.Core.Runtime.FieldMapSpec[]"); sb.AppendLine( " {"); foreach (var fm in mappings) { sb.AppendLine( " new global::CoffeeBeanery.GraphQL.Core.Runtime.FieldMapSpec("); sb.AppendLine( $" \"{fm.FieldName}\","); sb.AppendLine( $" StorageEntityId.{fm.EntityTypeName},"); sb.AppendLine( $" \"{fm.ColumnName}\","); sb.AppendLine( " \"\","); sb.AppendLine( " \"\""); sb.AppendLine( " ),"); } sb.AppendLine( " },"); } sb.AppendLine( " };"); sb.AppendLine(); }

    private static void PopulateCteUpdateMeta(
    MappingClassInfo info,
    NavigationResolutionResult navResult)
{
    var primaryEntry = info.Definition.Entities
        .FirstOrDefault(k => k.IsPrimary && k.EntityType != null);

    if (primaryEntry == null)
        return;

    if (string.IsNullOrWhiteSpace(primaryEntry.ToColumn))
        return;
    
    foreach (var nav in navResult.Navigations)
    {
        if (nav.RelatedEntityType == null)
            continue;


        if (string.IsNullOrWhiteSpace(nav.ForeignKeyProperty))
            continue;


        var naturalKeyInfo = info.Definition.Entities .FirstOrDefault(k => k.EntityType != null && k.AliasProperty != null && ( string.Equals( k.AliasProperty, nav.NavigationName, StringComparison.OrdinalIgnoreCase) || string.Equals( k.EntityType.Name, nav.RelatedEntityType.Name, StringComparison.OrdinalIgnoreCase) ) && !string.IsNullOrWhiteSpace(k.ToColumn)); if (naturalKeyInfo == null) { continue; }



        if (info.CteUpdateMeta.Any(c =>
                string.Equals(
                    c.NavigationAlias,
                    nav.NavigationName,
                    StringComparison.OrdinalIgnoreCase)))
        {
            continue;
        }



        info.CteUpdateMeta.Add(
            new CteUpdateMetaInfo
            {
                NavigationAlias =
                    nav.NavigationName,


                ForeignKeyColumn =
                    nav.ForeignKeyProperty,


                OwningPrimaryKeyColumn =
                    primaryEntry.ToColumn!,


                RelatedEntityTypeName =
                    nav.RelatedEntityType.Name,


                RelatedSurrogateIdColumn =
                    GetPkPropertyName(nav.RelatedEntityType),


                RelatedNaturalKeyColumn =
                naturalKeyInfo.ToColumn!

            });
    }
    
    // FIX: ForeignKeyColumn/RelatedNaturalKeyColumn were previously taken
    // directly from link.ToColumn/link.FromColumn (the ModelKey/EntityKey
    // pair used for reading the model's own scalar back out of the related
    // entity's natural key — e.g. InnerCustomerKey/CustomerKey). That pair
    // describes a completely different mapping than what the SQL writer
    // needs here:
    //   - ForeignKeyColumn must be the actual FK column on THIS (owning)
    //     entity that points at the related row (e.g. InnerCustomerId /
    //     OuterCustomerId on CustomerCustomerRelationship) — not the
    //     related entity's natural key column name.
    //   - RelatedNaturalKeyColumn must be the natural key column on the
    //     RELATED entity (e.g. CustomerKey on Customer) — not the parent
    //     model's own scalar name (e.g. InnerCustomerKey), which doesn't
    //     exist as a column on the related table at all.
    // The {AliasProperty}Id convention mirrors the same convention already
    // used for ordinary secondary-link joins in PlannerEmitter's
    // EmitBuildQuery (fkColumn = alias + "Id"), so this stays consistent
    // with how FK columns are derived elsewhere in the generator rather
    // than introducing a new naming rule.
    foreach (var link in info.Definition.Entities.Where(k => 
                 !k.IsPrimary &&
                 k.EntityType != null &&
                 !string.IsNullOrWhiteSpace(k.AliasProperty) &&
                 !string.IsNullOrWhiteSpace(k.FromColumn) &&
                 !string.IsNullOrWhiteSpace(k.ToColumn)))
    {
        if (info.CteUpdateMeta.Any(c =>
                string.Equals(
                    c.NavigationAlias,
                    link.AliasProperty,
                    StringComparison.OrdinalIgnoreCase)))
        {
            continue;
        }

        info.CteUpdateMeta.Add(
            new CteUpdateMetaInfo
            {
                NavigationAlias = link.AliasProperty!,

                ForeignKeyColumn = link.AliasProperty! + "Id",

                OwningPrimaryKeyColumn = primaryEntry.ToColumn!,

                RelatedEntityTypeName = link.EntityType.Name,

                RelatedSurrogateIdColumn =
                    GetPkPropertyName(link.EntityType),

                RelatedNaturalKeyColumn =
                    link.ToColumn!
            });
    }
}
    
    private static string GetPkPropertyName(
        INamedTypeSymbol entityType)
    {
        var pk = IdEmitter.GetScalarProperties(entityType)
            .FirstOrDefault(p =>
                string.Equals(
                    p.Name,
                    "Id",
                    StringComparison.OrdinalIgnoreCase));

        if (pk != null)
            return pk.Name;


        var first = IdEmitter.GetScalarProperties(entityType)
            .FirstOrDefault();

        if (first != null)
            return first.Name;


        throw new InvalidOperationException(
            $"Cannot find primary key property for entity '{entityType.Name}'.");
    }

private static void EmitModelIdConstants(
        StringBuilder sb,
        List<MappingClassInfo> models)
    {
        sb.AppendLine(
            "        public static class ModelId");

        sb.AppendLine("        {");

        for (int i = 0; i < models.Count; i++)
        {
            sb.AppendLine(
                $"            public const ushort {models[i].ModelType.Name} = {i};");
        }

        sb.AppendLine();

        sb.AppendLine(
            $"            public const ushort Count = {models.Count};");

        sb.AppendLine("        }");

        sb.AppendLine();
    }


    // private static void EmitStorageEntityIdConstants(
    //     StringBuilder sb,
    //     List<Microsoft.CodeAnalysis.INamedTypeSymbol> entityTypes)
    // {
    //     sb.AppendLine(
    //         "namespace CoffeeBeanery.GraphQL.Core.Runtime");
    //
    //     sb.AppendLine("{");
    //
    //     sb.AppendLine(
    //         "    public static class StorageEntityId");
    //
    //     sb.AppendLine("    {");
    //
    //     for (int i = 0; i < entityTypes.Count; i++)
    //     {
    //         sb.AppendLine(
    //             $"        public const ushort {entityTypes[i].Name} = {i};");
    //     }
    //
    //     sb.AppendLine();
    //
    //     sb.AppendLine(
    //         $"        public const ushort Count = {entityTypes.Count};");
    //
    //     sb.AppendLine("    }");
    //
    //     sb.AppendLine("}");
    //
    //     sb.AppendLine();
    // }


// ---------------------------------------------------------------
// Model-keyed arrays
// ---------------------------------------------------------------

    private static void EmitSchemaArray(
        StringBuilder sb,
        List<MappingClassInfo> models)
    {
        sb.AppendLine(
            $"        public static readonly string[] Schema = new string[{models.Count}]");

        sb.AppendLine("        {");

        foreach (var m in models)
        {
            sb.AppendLine(
                $"            \"{m.Schema ?? ""}\",");
        }

        sb.AppendLine("        };");

        sb.AppendLine();
    }


    private static void EmitModelNameArray(
        StringBuilder sb,
        List<MappingClassInfo> models)
    {
        sb.AppendLine(
            $"        public static readonly string[][] ModelName = new string[{models.Count}][]");

        sb.AppendLine("        {");

        foreach (var m in models)
        {
            var names = new List<string>
            {
                m.ModelType.Name
            };

            names.AddRange(
                m.CteUpdateMeta
                    .Select(x => x.NavigationAlias)
                    .Distinct());

            sb.AppendLine(
                $"            new string[] {{ {string.Join(", ", names.Select(x => $"\"{x}\""))} }},");
        }

        sb.AppendLine("        };");

        sb.AppendLine();
    }


    private static string ToCamel(string name)
    {
        if (string.IsNullOrEmpty(name))
            return name;

        return char.ToLowerInvariant(name[0])
               + name.Substring(1);
    }

    private static void EmitTableArray(
        StringBuilder sb,
        List<MappingClassInfo> models)
    {
        sb.AppendLine(
            $"        public static readonly string[][] Table = new string[{models.Count}][]");

        sb.AppendLine("        {");

        foreach (var m in models)
        {
            string dbTable;

            if (IsComposite(m))
            {
                var primaryEntity =
                    m.Definition.Entities.FirstOrDefault(k => k.IsPrimary)
                    ?? throw new InvalidOperationException(
                        $"Composite model '{m.ModelType.Name}' has no entry marked isPrimary: true.");

                dbTable =
                    primaryEntity.EntityType?.Name
                    ?? throw new InvalidOperationException(
                        $"Composite model '{m.ModelType.Name}' has no resolved primary EntityType.");
            }
            else
            {
                dbTable =
                    m.EntityType?.Name
                    ?? throw new InvalidOperationException(
                        $"Simple model '{m.ModelType.Name}' has no EntityType.");
            }

            var navAliases = m.CteUpdateMeta
                .Select(c => c.NavigationAlias)
                .Distinct()
                .ToList();

            if (navAliases.Count == 0)
            {
                sb.AppendLine(
                    $"            new string[] {{ \"{dbTable}\" }},");
            }
            else
            {
                sb.AppendLine(
                    $"            new string[] {{ \"{dbTable}\", {string.Join(", ", navAliases.Select(a => $"\"{a}\""))} }},");
            }
        }

        sb.AppendLine("        };");
        sb.AppendLine();
    }


    private static void EmitColumnNameArray(
        StringBuilder sb,
        List<MappingClassInfo> models)
    {
        sb.AppendLine(
            $"        public static readonly string[][] ColumnName = new string[{models.Count}][]");

        sb.AppendLine("        {");

        foreach (var m in models)
        {
            INamedTypeSymbol typeForColumns;

            if (IsComposite(m))
            {
                var primaryEntity =
                    m.Definition.Entities.FirstOrDefault(k => k.IsPrimary);

                typeForColumns =
                    primaryEntity?.EntityType
                    ?? throw new InvalidOperationException(
                        $"Composite model '{m.ModelType.Name}' has no primary EntityType.");
            }
            else
            {
                typeForColumns =
                    m.EntityType
                    ?? throw new InvalidOperationException(
                        $"Simple model '{m.ModelType.Name}' has no EntityType.");
            }

            var cols =
                IdEmitter.GetScalarProperties(
                    typeForColumns);

            sb.AppendLine(
                $"            new string[{cols.Count}]");

            sb.AppendLine("            {");

            foreach (var c in cols)
            {
                sb.AppendLine(
                    $"                \"{c.Name}\",");
            }

            sb.AppendLine("            },");
        }

        sb.AppendLine("        };");
        sb.AppendLine();
    }


    private static bool IsComposite(
        MappingClassInfo info)
    {
        return info.Definition.Entities
            .Where(x => x.EntityType != null)
            .Select(x => x.EntityType!.Name)
            .Distinct(StringComparer.Ordinal)
            .Count() > 1;
    }


    private static void EmitFieldNameArray(
        StringBuilder sb,
        List<MappingClassInfo> models)
    {
        sb.AppendLine(
            $"        public static readonly string[][] FieldName = new string[{models.Count}][]");

        sb.AppendLine("        {");

        foreach (var m in models)
        {
            var fields =
                IdEmitter.GetScalarProperties(
                        m.ModelType)
                    .Select(p => ToCamel(p.Name))
                    .ToList();

            sb.AppendLine(
                $"            new string[] {{ {string.Join(", ", fields.Select(x => $"\"{x}\""))} }},");
        }

        sb.AppendLine("        };");
        sb.AppendLine();
    }

private static void EmitConflictColumnsArray(
    StringBuilder sb,
    List<MappingClassInfo> models)
{
    sb.AppendLine(
        $"        public static readonly string[][] ConflictColumns = new string[{models.Count}][]");

    sb.AppendLine(
        "        {");


    foreach (var m in models)
    {
        var keys = m.UpsertKeys
            .Where(k => !string.IsNullOrWhiteSpace(k.Key))
            .Select(k => k.Key)
            .Distinct(StringComparer.OrdinalIgnoreCase)
            .ToList();



        if (keys.Count == 0)
        {
            keys = m.Definition.Entities
                .Where(k =>
                    k.IsPrimary &&
                    !string.IsNullOrWhiteSpace(k.ToColumn))
                .Select(k => k.ToColumn!)
                .Distinct(StringComparer.OrdinalIgnoreCase)
                .ToList();
        }



        if (keys.Count == 0 && PlannerEmitter.IsCompositeInfo(m))
        {
            keys = PlannerEmitter
                .ComputeFieldMappingsEagerPublic(
                    m,
                    composite: true)
                .Where(f =>
                    m.Definition.Entities.Any(e =>
                        e.IsPrimary &&
                        string.Equals(
                            e.EntityType?.Name,
                            f.EntityTypeName,
                            StringComparison.Ordinal) &&
                        string.Equals(
                            e.ToColumn,
                            f.ColumnName,
                            StringComparison.OrdinalIgnoreCase)))
                .Select(f => f.ColumnName)
                .Distinct(StringComparer.OrdinalIgnoreCase)
                .ToList();
        }



        if (keys.Count == 0)
        {
            sb.AppendLine(
                "            System.Array.Empty<string>(),");
        }
        else
        {
            sb.AppendLine(
                $"            new string[] {{ {string.Join(", ", keys.Select(k => $"\"{k}\""))} }},");
        }
    }


    sb.AppendLine(
        "        };");

    sb.AppendLine();
}

private static void EmitCteResolutionsArray(
    StringBuilder sb,
    List<MappingClassInfo> models)
{
    sb.AppendLine(
        $"        public static readonly global::CoffeeBeanery.GraphQL.Core.Runtime.CteResolutionSpec[][] CteResolutions = new global::CoffeeBeanery.GraphQL.Core.Runtime.CteResolutionSpec[{models.Count}][]");

    sb.AppendLine(
        "        {");


    foreach (var m in models)
    {
        if (m.CteUpdateMeta.Count == 0)
        {
            sb.AppendLine(
                "            System.Array.Empty<global::CoffeeBeanery.GraphQL.Core.Runtime.CteResolutionSpec>(),");

            continue;
        }


        var primaryEntity =
            m.Definition.Entities
                .FirstOrDefault(e => e.IsPrimary)
                ?.EntityType;


        var entityColumns =
            primaryEntity == null
                ? new Dictionary<string, ushort>(
                    StringComparer.OrdinalIgnoreCase)
                :
                IdEmitter.GetScalarProperties(primaryEntity)
                    .Select((c, i) =>
                        new
                        {
                            Name = c.Name,
                            Index = (ushort)i
                        })
                    .ToDictionary(
                        x => x.Name,
                        x => x.Index,
                        StringComparer.OrdinalIgnoreCase);



        sb.AppendLine(
            "            new global::CoffeeBeanery.GraphQL.Core.Runtime.CteResolutionSpec[]");

        sb.AppendLine(
            "            {");


        foreach (var cte in m.CteUpdateMeta)
        {
            entityColumns.TryGetValue(
                cte.OwningPrimaryKeyColumn,
                out var pkColumnId);



            var tableAlias =
                cte.NavigationAlias +
                cte.RelatedEntityTypeName;



            sb.AppendLine(
                "                new global::CoffeeBeanery.GraphQL.Core.Runtime.CteResolutionSpec(");


            sb.AppendLine(
                $"                    \"{cte.NavigationAlias}\",");


            sb.AppendLine(
                $"                    \"{cte.ForeignKeyColumn}\",");


            sb.AppendLine(
                $"                    \"{cte.OwningPrimaryKeyColumn}\",");


            sb.AppendLine(
                $"                    {pkColumnId},");


            sb.AppendLine(
                $"                    \"{tableAlias}\",");


            sb.AppendLine(
                $"                    \"{cte.RelatedSurrogateIdColumn}\",");


            sb.AppendLine(
                $"                    \"{cte.RelatedNaturalKeyColumn}\"");


            sb.AppendLine(
                "                ),");
        }


        sb.AppendLine(
            "            },");
    }


    sb.AppendLine(
        "        };");

    sb.AppendLine();
}

// ---------------------------------------------------------------
// Storage-entity-keyed arrays
// ---------------------------------------------------------------

    private static void EmitEntitySchemaArray(
        StringBuilder sb,
        List<INamedTypeSymbol> entityTypes,
        Dictionary<string, string> entitySchemaLookup,
        List<MappingClassInfo> models)
    {
        sb.AppendLine(
            "        /// <summary>Indexed by StorageEntityId.*</summary>");

        sb.AppendLine(
            $"        public static readonly string[] EntitySchema = new string[{entityTypes.Count}]");

        sb.AppendLine("        {");

        foreach (var entity in entityTypes)
        {
            var schema = "";

            if (entitySchemaLookup.TryGetValue(
                    entity.Name,
                    out var found))
            {
                schema = found;
            }

            sb.AppendLine(
                $"            \"{schema}\",");
        }

        sb.AppendLine("        };");
        sb.AppendLine();
    }


    private static void EmitEntityTableArray(
        StringBuilder sb,
        List<INamedTypeSymbol> entityTypes)
    {
        sb.AppendLine(
            "        /// <summary>Indexed by StorageEntityId.*</summary>");

        sb.AppendLine(
            $"        public static readonly string[] EntityTable = new string[{entityTypes.Count}]");

        sb.AppendLine("        {");

        foreach (var e in entityTypes)
        {
            sb.AppendLine(
                $"            \"{e.Name}\",");
        }

        sb.AppendLine("        };");
        sb.AppendLine();
    }


    private static void EmitEntityColumnNameArray(
        StringBuilder sb,
        List<INamedTypeSymbol> entityTypes,
        ImmutableArray<MappingClassInfo> allMappings)   // add this parameter
    {
        sb.AppendLine("        /// <summary>Indexed by StorageEntityId.* then ColumnId.{EntityName}.*</summary>");
        sb.AppendLine($"        public static readonly string[][] EntityColumnName = new string[{entityTypes.Count}][]");
        sb.AppendLine("        {");

        foreach (var e in entityTypes)
        {
            var cols = IdEmitter.GetOrderedColumnNames(e.Name, allMappings);  // was: IdEmitter.GetScalarProperties(e)

            sb.AppendLine($"            new string[{cols.Count}]");
            sb.AppendLine("            {");
            foreach (var c in cols)
                sb.AppendLine($"                \"{c}\",");
            sb.AppendLine("            },");
        }

        sb.AppendLine("        };");
        sb.AppendLine();
    }


// ---------------------------------------------------------------
// GeneratedEntityMetaProvider
// ---------------------------------------------------------------

    private static void EmitGeneratedEntityMetaProvider(
        StringBuilder sb)
    {
        sb.AppendLine(
            "namespace CoffeeBeanery.GraphQL.Core.Runtime");

        sb.AppendLine("{");

        sb.AppendLine(
            "    public sealed class GeneratedEntityMetaProvider : global::CoffeeBeanery.GraphQL.Core.Runtime.IEntityMetaProvider");

        sb.AppendLine("    {");

        sb.AppendLine(
            "        public int Count => EntityMeta.Table.Length;");

        sb.AppendLine(
            "        public string[][] ModelName => EntityMeta.ModelName;");

        sb.AppendLine(
            "        public string[][] Table => EntityMeta.Table;");

        sb.AppendLine(
            "        public string[] Schema => EntityMeta.Schema;");

        sb.AppendLine(
            "        public FieldMapSpec[][] FieldMappings => EntityMeta.FieldMappings;");

        sb.AppendLine(
            "        public string[][] ColumnName => EntityMeta.ColumnName;");

        sb.AppendLine(
            "        public string[][] FieldName => EntityMeta.FieldName;");

        sb.AppendLine(
            "        public ushort[][] FieldToColumn => EntityMeta.FieldToColumn;");

        sb.AppendLine(
            "        public string[][] ConflictColumns => EntityMeta.ConflictColumns;");

        sb.AppendLine(
            "        public CteResolutionSpec[][] CteResolutions => EntityMeta.CteResolutions;");

        sb.AppendLine(
            "        public int StorageEntityCount => EntityMeta.EntityTable.Length;");

        sb.AppendLine(
            "        public string[] EntitySchema => EntityMeta.EntitySchema;");

        sb.AppendLine(
            "        public string[] EntityTable => EntityMeta.EntityTable;");

        sb.AppendLine(
            "        public string[][] EntityColumnName => EntityMeta.EntityColumnName;");

        sb.AppendLine();

        sb.AppendLine(
            "        public bool TryGetEntityId(string modelName, out ushort entityId)");

        sb.AppendLine("        {");

        sb.AppendLine(
            "            for (ushort i = 0; i < EntityMeta.ModelName.Length; i++)");

        sb.AppendLine("            {");

        sb.AppendLine(
            "                if (global::System.StringComparer.OrdinalIgnoreCase.Equals(EntityMeta.ModelName[i][0], modelName))");

        sb.AppendLine("                {");

        sb.AppendLine(
            "                    entityId = i;");

        sb.AppendLine(
            "                    return true;");

        sb.AppendLine("                }");

        sb.AppendLine("            }");

        sb.AppendLine(
            "            entityId = 0;");

        sb.AppendLine(
            "            return false;");

        sb.AppendLine("        }");

        sb.AppendLine("    }");

        sb.AppendLine("}");

        sb.AppendLine();
    }


// ---------------------------------------------------------------
// GeneratedPlannerRegistry
// ---------------------------------------------------------------

    private static void EmitGeneratedPlannerRegistry(StringBuilder sb)
    {
        sb.AppendLine("namespace CoffeeBeanery.GraphQL.Core.Runtime");
        sb.AppendLine("{");
        sb.AppendLine("    public sealed class GeneratedPlannerRegistry : global::CoffeeBeanery.GraphQL.Core.Runtime.IPlannerRegistry");
        sb.AppendLine("    {");
        sb.AppendLine("        public void Build(ushort entityId, in global::CoffeeBeanery.GraphQL.Core.Runtime.SelectionIR selection, ref global::CoffeeBeanery.GraphQL.Core.Runtime.QueryPlanBuilder builder)");
        sb.AppendLine("            => GeneratedPlanners.PlannerRegistry.Build(entityId, selection, ref builder);");
        sb.AppendLine();
        sb.AppendLine("        public void BuildMutation(ushort entityId, in global::CoffeeBeanery.GraphQL.Core.Runtime.MutationIR mutation, ref global::CoffeeBeanery.GraphQL.Core.Runtime.MutationPlanBuilder builder)");
        sb.AppendLine("            => global::CoffeeBeanery.GraphQL.Core.Runtime.MutationRuntimePlanner.Build(entityId, mutation, ref builder);");
        sb.AppendLine();
        sb.AppendLine("        public bool IsValidEntity(ushort entityId)");
        sb.AppendLine("            => GeneratedPlanners.PlannerRegistry.IsValidEntity(entityId);");
        sb.AppendLine();
        sb.AppendLine("        public string GetEntityName(ushort entityId)");
        sb.AppendLine("            => GeneratedPlanners.PlannerRegistry.GetEntityName(entityId);");
        sb.AppendLine("    }");
        sb.AppendLine("}");
    }
}