using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using CoffeeBeanery.GraphQL.Core.Mapping.Generators;
using CoffeeBeanery.GraphQL.Core.Mapping.Generators.Emit;
using CoffeeBeanery.GraphQL.Core.Mapping.Generators.Model;
using CoffeeBeanery.GraphQL.Core.Mapping.Generators.Passes;
using Microsoft.CodeAnalysis;

internal static class MetadataEmitter
{
    public static string Emit(
        ImmutableArray<MappingClassInfo> allMappings,
        ImmutableHashSet<INamedTypeSymbol> rootEntityTypes,
        List<FluentEntityNavigationConvention.EntityForeignKeyGraph.Edge> entityGraph)
    {
        var models = allMappings
            .Where(m => m.IsModel)
            .GroupBy(m => m.ModelType.Name, System.StringComparer.OrdinalIgnoreCase)
            .Select(g => g.First())
            .Distinct()
            .OrderBy(m => m.ModelType.Name, System.StringComparer.Ordinal)
            .ToList();

        foreach (var m in models)
        {
            if (m.CteUpdateMeta.Count > 0)
                continue;

            var navResult = EntityNavigationConvention.Resolve(
                m,
                allMappings,
                entityGraph,
                rootEntityTypes);

            PopulateCteUpdateMeta(m, navResult);
        }

        var entityTypes = new List<INamedTypeSymbol>();

        foreach (var entity in models
                     .SelectMany(m => m.Definition.Entities)
                     .Select(e => e.EntityType)
                     .Where(e => e != null))
        {
            if (!entityTypes.Any(x =>
                    SymbolEqualityComparer.Default.Equals(x, entity)))
            {
                entityTypes.Add(entity!);
            }
        }

        var entitySchemaLookup =
            new Dictionary<INamedTypeSymbol,string>(
                SymbolEqualityComparer.Default);

        foreach (var mapping in models)
        {
            foreach (var entity in mapping.Definition.Entities)
            {
                if (entity.EntityType == null)
                    continue;


                // Ignore composite model schema
                if (mapping.Definition.Entities.Count > 1)
                    continue;


                if (string.IsNullOrWhiteSpace(mapping.Schema))
                    continue;


                entitySchemaLookup[entity.EntityType] =
                    mapping.Schema;
            }
        }

        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System;");
        sb.AppendLine();

        sb.AppendLine("namespace CoffeeBeanery.GraphQL.Core.Runtime");
        sb.AppendLine("{");

        sb.AppendLine("    public static class EntityMeta");
        sb.AppendLine("    {");
        
        EmitModelNameArray(sb, models);
        EmitSchemaArray(sb, models);
        EmitColumnNameArray(sb, models);
        EmitFieldNameArray(sb, models);
        EmitFieldToColumnArray(sb, models);
        EmitFieldMappingsArray(sb, models);
        EmitConflictColumnsArray(sb, entityTypes, allMappings);
        EmitCteResolutionsArray(sb, models);

        var storageEntities =
            GetStorageEntities(
                entityTypes,
                allMappings);

        EmitTableArray(sb, models);
        
        EmitEntityTableArray(
            sb,
            storageEntities);

        EmitEntitySchemaArray(
            sb,
            storageEntities);

        EmitEntityColumnNameArray(
            sb,
            entityTypes,
            allMappings);

        sb.AppendLine("    }");

        EmitEnumConversions(sb, models);

        sb.AppendLine("}");
        sb.AppendLine();

        EmitModelIdConstants(sb, models);

        EmitGeneratedEntityMetaProvider(sb);

        EmitGeneratedPlannerRegistry(sb);

        return sb.ToString();
    }

    private static void EmitFieldToColumnArray(
    StringBuilder sb,
    List<MappingClassInfo> models)
{
    sb.AppendLine(
        $"        public static readonly ushort[][] FieldToColumn = new ushort[{models.Count}][]");

    sb.AppendLine("        {");

    foreach (var m in models)
    {
        var mappings =
            PlannerEmitter.ComputeFieldMappingsEagerPublic(
                m,
                PlannerEmitter.IsCompositeInfo(m))
            .ToList();

        if (mappings.Count == 0)
        {
            sb.AppendLine(
                "            System.Array.Empty<ushort>(),");
            continue;
        }

        var ids = new List<ushort>();

        foreach (var fm in mappings)
        {
            var entity =
                m.Definition.Entities
                    .FirstOrDefault(e =>
                        e.EntityType != null &&
                        string.Equals(
                            e.EntityType.Name,
                            fm.EntityTypeName,
                            StringComparison.Ordinal));


            if (entity?.EntityType == null)
            {
                ids.Add(ushort.MaxValue);
                continue;
            }


            var columns =
                IdEmitter.GetScalarProperties(
                    entity.EntityType);


            var index =
                columns.FindIndex(c =>
                    string.Equals(
                        c.Name,
                        fm.ColumnName,
                        StringComparison.OrdinalIgnoreCase));


            if (index >= 0)
            {
                ids.Add((ushort)index);
                continue;
            }
            
            //
            // Primary key / natural key support
            //
            var pk =
                m.Definition.PrimaryKey
                    .FirstOrDefault(p =>
                        SymbolEqualityComparer.Default.Equals(
                            p.Entity,
                            entity.EntityType) &&
                        string.Equals(
                            p.ColumnKey,
                            fm.ColumnName,
                            StringComparison.OrdinalIgnoreCase));


            if (pk != null)
            {
                var pkIndex =
                    columns.FindIndex(c =>
                        string.Equals(
                            c.Name,
                            pk.ColumnKey,
                            StringComparison.OrdinalIgnoreCase));


                ids.Add(
                    pkIndex >= 0
                        ? (ushort)pkIndex
                        : ushort.MaxValue);

                continue;
            }


            ids.Add(ushort.MaxValue);
        }


        sb.AppendLine(
            $"            new ushort[] {{ {string.Join(", ", ids)} }},");
    }


    sb.AppendLine("        };");
    sb.AppendLine();
}
    
    private static List<(string EntityName, string Schema)> GetStorageEntities(
        List<INamedTypeSymbol> entityTypes,
        ImmutableArray<MappingClassInfo> allMappings)
    {
        var result = new List<(string EntityName, string Schema)>();

        foreach (var entityType in entityTypes)
        {
            var entityName = entityType.Name;

            if (entityName.EndsWith(
                    "Entity",
                    StringComparison.Ordinal))
            {
                entityName = entityName.Substring(
                    0,
                    entityName.Length - "Entity".Length);
            }


            var schema = "public";


            var mapping =
                allMappings
                    .Where(m =>
                        m.Definition.Entities.Any(e =>
                            e.EntityType != null &&
                            SymbolEqualityComparer.Default.Equals(
                                e.EntityType,
                                entityType)))
                    .OrderByDescending(m =>
                        m.Definition.Entities.Any(e =>
                            e.EntityType != null &&
                            e.IsPrimary &&
                            SymbolEqualityComparer.Default.Equals(
                                e.EntityType,
                                entityType)))
                    .FirstOrDefault();


            if (mapping != null)
            {
                var entityMapping =
                    mapping.Definition.Entities.FirstOrDefault(e =>
                        e.EntityType != null &&
                        SymbolEqualityComparer.Default.Equals(
                            e.EntityType,
                            entityType));


                schema = new[]
                    {
                        entityMapping?.Schema,
                        mapping.Schema,
                        mapping.Definition.Schema,
                        "public"
                    }
                    .First(s => !string.IsNullOrWhiteSpace(s));
            }


            result.Add((
                EntityName: entityName,
                Schema: schema));
        }


        return result;
    }
    
    private static void EmitEnumConversions(
    StringBuilder sb,
    List<MappingClassInfo> models)
{
    var enumFields = models
        .SelectMany(m => m.FieldMaps
            .Where(f => f.ModelEnumType != null &&
                        f.EntityEnumType != null)
            .Select(f => (Model: m, Field: f)))
        .ToList();

    sb.AppendLine("    public static class EnumConversions");
    sb.AppendLine("    {");

    sb.AppendLine("        public static string? TryConvert(ushort storageEntityId, ushort columnId, string value)");
    sb.AppendLine("        {");
    sb.AppendLine("            var normalizedValue = value.Trim();");
    sb.AppendLine("            switch (storageEntityId)");
    sb.AppendLine("            {");

    foreach (var group in enumFields.GroupBy(
                 x => x.Field.DestinationEntity,
                 StringComparer.Ordinal))
    {
        var entityName = IdEmitter.StripEntitySuffix(group.Key);

        sb.AppendLine($"                case StorageEntityId.{entityName}:");
        sb.AppendLine("                    switch (columnId)");
        sb.AppendLine("                    {");

        foreach (var item in group)
        {
            var field = item.Field;

            var entityType =
                item.Model.Definition.Entities
                    .FirstOrDefault(e =>
                        string.Equals(
                            IdEmitter.StripEntitySuffix(
                                e.EntityType?.Name ?? ""),
                            entityName,
                            StringComparison.OrdinalIgnoreCase))
                    ?.EntityType;

            var columnExpression =
                entityType != null
                    ? ColumnIdResolver.Resolve(
                        entityType,
                        field.DestinationName)
                    : ColumnIdResolver.Resolve(
                        entityName,
                        field.DestinationName);

            sb.AppendLine($"                        case (ushort){columnExpression}:");
            sb.AppendLine("                            return normalizedValue switch");
            sb.AppendLine("                            {");

            var modelMembers =
                field.ModelEnumType!
                    .GetMembers()
                    .OfType<IFieldSymbol>()
                    .Where(f => f.IsConst && f.HasConstantValue)
                    .ToDictionary(
                        x => x.Name,
                        x => Convert.ToInt32(x.ConstantValue),
                        StringComparer.Ordinal);

            var entityMembers =
                field.EntityEnumType!
                    .GetMembers()
                    .OfType<IFieldSymbol>()
                    .Where(f => f.IsConst && f.HasConstantValue)
                    .ToDictionary(
                        x => x.Name,
                        x => Convert.ToInt32(x.ConstantValue),
                        StringComparer.Ordinal);

            foreach (var pair in modelMembers)
            {
                var modelName = pair.Key;
                var modelValue = pair.Value;

                if (field.EnumIgnored.Contains(modelName))
                    continue;

                var destinationName =
                    field.EnumOverrides.TryGetValue(
                        modelName,
                        out var overrideName)
                        ? overrideName
                        : modelName;

                if (!entityMembers.TryGetValue(
                        destinationName,
                        out var entityValue))
                {
                    throw new InvalidOperationException(
                        $"Enum mapping '{field.ModelEnumType.Name}.{modelName}' -> '{field.EntityEnumType.Name}.{destinationName}' does not exist.");
                }

                sb.AppendLine(
                    $"                                \"{modelValue}\" => \"{entityValue}\",");
            }

            sb.AppendLine("                                _ => null");
            sb.AppendLine("                            };");
        }

        sb.AppendLine("                    }");
        sb.AppendLine("                    break;");
    }

    sb.AppendLine("            }");

    sb.AppendLine("            return null;");
    sb.AppendLine("        }");

    sb.AppendLine("    }");
    sb.AppendLine();
}

    private static List<(string[] Tables, string[] Schemas)> GetModelStorageMappings(
        ImmutableArray<MappingClassInfo> models)
    {
        var result =
            new List<(string[] Tables, string[] Schemas)>();

        foreach (var model in models)
        {
            var tables = new List<string>();
            var schemas = new List<string>();

            foreach (var entity in model.Definition.Entities)
            {
                if (entity.EntityType == null)
                    continue;

                var name = entity.EntityType.Name;

                const string suffix = "Entity";

                if (name.EndsWith(
                        suffix,
                        StringComparison.Ordinal))
                {
                    name = name.Substring(
                        0,
                        name.Length - suffix.Length);
                }

                tables.Add(name);

                schemas.Add(
                    entity.Schema
                    ?? model.Schema
                    ?? model.Definition.Schema
                    ?? "public");
            }

            result.Add((
                Tables: tables.ToArray(),
                Schemas: schemas.ToArray()));
        }

        return result;
    }

    private static ushort ResolveStorageEntityId(
        List<MappingClassInfo> models,
        object destinationEntity)
    {
        if (destinationEntity is ushort id)
            return id;

        var name = destinationEntity.ToString();

        var entities = models
            .SelectMany(m => m.Definition.Entities)
            .Where(x => x.EntityType != null)
            .Select(x => x.EntityType!)
            .GroupBy(
                x => x.Name,
                StringComparer.Ordinal)
            .Select(g => g.First())
            .OrderBy(
                x => x.Name,
                StringComparer.Ordinal)
            .ToList();

        var index = entities.FindIndex(e => string.Equals(
            e.Name,
            name,
            StringComparison.Ordinal));

        if (index < 0)
        {
            throw new InvalidOperationException(
                $"Cannot resolve storage entity id for '{name}'");
        }

        return (ushort)index;
    }

    private static void EmitFieldMappingsArray( StringBuilder sb, List<MappingClassInfo> models) { sb.AppendLine( $" public static readonly global::CoffeeBeanery.GraphQL.Core.Runtime.FieldMapSpec[][] FieldMappings = " + $"new global::CoffeeBeanery.GraphQL.Core.Runtime.FieldMapSpec[{models.Count}][]"); sb.AppendLine( " {"); foreach (var m in models) { var mappings = PlannerEmitter.ComputeFieldMappingsEagerPublic( m, PlannerEmitter.IsCompositeInfo(m)); if (mappings.Count == 0) { sb.AppendLine( " System.Array.Empty<global::CoffeeBeanery.GraphQL.Core.Runtime.FieldMapSpec>(),"); continue; } sb.AppendLine( " new global::CoffeeBeanery.GraphQL.Core.Runtime.FieldMapSpec[]"); sb.AppendLine( " {"); foreach (var fm in mappings) { sb.AppendLine( " new global::CoffeeBeanery.GraphQL.Core.Runtime.FieldMapSpec("); sb.AppendLine( $" \"{fm.FieldName}\","); sb.AppendLine( $" StorageEntityId.{fm.EntityTypeName},"); sb.AppendLine( $" \"{fm.ColumnName}\","); sb.AppendLine( " \"\","); sb.AppendLine( " \"\""); sb.AppendLine( " ),"); } sb.AppendLine( " },"); } sb.AppendLine( " };"); sb.AppendLine(); }

    private static void PopulateCteUpdateMeta(
    MappingClassInfo info,
    NavigationResolutionResult navResult)
{
    var primaryEntry = info.Definition.Entities
        .FirstOrDefault(k => k.IsPrimary && k.EntityType != null);

    if (primaryEntry == null)
        return;

    if (string.IsNullOrWhiteSpace(primaryEntry.ToColumn))
        return;
    
    foreach (var nav in navResult.Navigations)
    {
        if (nav.RelatedEntityType == null)
            continue;


        if (string.IsNullOrWhiteSpace(nav.ForeignKeyProperty))
            continue;


        var naturalKeyInfo = info.Definition.Entities .FirstOrDefault(k => k.EntityType != null && k.AliasProperty != null && ( string.Equals( k.AliasProperty, nav.NavigationName, StringComparison.OrdinalIgnoreCase) || string.Equals( k.EntityType.Name, nav.RelatedEntityType.Name, StringComparison.OrdinalIgnoreCase) ) && !string.IsNullOrWhiteSpace(k.ToColumn)); if (naturalKeyInfo == null) { continue; }



        if (info.CteUpdateMeta.Any(c =>
                string.Equals(
                    c.NavigationAlias,
                    nav.NavigationName,
                    StringComparison.OrdinalIgnoreCase)))
        {
            continue;
        }



        info.CteUpdateMeta.Add(
            new CteUpdateMetaInfo
            {
                NavigationAlias =
                    nav.NavigationName,


                ForeignKeyColumn =
                    nav.ForeignKeyProperty,


                OwningPrimaryKeyColumn =
                    primaryEntry.ToColumn!,


                RelatedEntityTypeName =
                    nav.RelatedEntityType.Name,


                RelatedSurrogateIdColumn =
                    GetPkPropertyName(nav.RelatedEntityType),


                RelatedNaturalKeyColumn =
                naturalKeyInfo.ToColumn!

            });
    }
    
    // FIX: ForeignKeyColumn/RelatedNaturalKeyColumn were previously taken
    // directly from link.ToColumn/link.FromColumn (the ModelKey/EntityKey
    // pair used for reading the model's own scalar back out of the related
    // entity's natural key — e.g. InnerCustomerKey/CustomerKey). That pair
    // describes a completely different mapping than what the SQL writer
    // needs here:
    //   - ForeignKeyColumn must be the actual FK column on THIS (owning)
    //     entity that points at the related row (e.g. InnerCustomerId /
    //     OuterCustomerId on CustomerCustomerRelationship) — not the
    //     related entity's natural key column name.
    //   - RelatedNaturalKeyColumn must be the natural key column on the
    //     RELATED entity (e.g. CustomerKey on Customer) — not the parent
    //     model's own scalar name (e.g. InnerCustomerKey), which doesn't
    //     exist as a column on the related table at all.
    // The {AliasProperty}Id convention mirrors the same convention already
    // used for ordinary secondary-link joins in PlannerEmitter's
    // EmitBuildQuery (fkColumn = alias + "Id"), so this stays consistent
    // with how FK columns are derived elsewhere in the generator rather
    // than introducing a new naming rule.
    foreach (var link in info.Definition.Entities.Where(k => 
                 !k.IsPrimary &&
                 k.EntityType != null &&
                 !string.IsNullOrWhiteSpace(k.AliasProperty) &&
                 !string.IsNullOrWhiteSpace(k.FromColumn) &&
                 !string.IsNullOrWhiteSpace(k.ToColumn)))
    {
        if (info.CteUpdateMeta.Any(c =>
                string.Equals(
                    c.NavigationAlias,
                    link.AliasProperty,
                    StringComparison.OrdinalIgnoreCase)))
        {
            continue;
        }

        info.CteUpdateMeta.Add(
            new CteUpdateMetaInfo
            {
                NavigationAlias = link.AliasProperty!,

                ForeignKeyColumn = link.AliasProperty! + "Id",

                OwningPrimaryKeyColumn = primaryEntry.ToColumn!,

                RelatedEntityTypeName = link.EntityType.Name,

                RelatedSurrogateIdColumn =
                    GetPkPropertyName(link.EntityType),

                RelatedNaturalKeyColumn =
                    link.ToColumn!
            });
    }
}
    
    private static string GetPkPropertyName(
        INamedTypeSymbol entityType)
    {
        var pk = IdEmitter.GetScalarProperties(entityType)
            .FirstOrDefault(p =>
                string.Equals(
                    p.Name,
                    "Id",
                    StringComparison.OrdinalIgnoreCase));

        if (pk != null)
            return pk.Name;


        var first = IdEmitter.GetScalarProperties(entityType)
            .FirstOrDefault();

        if (first != null)
            return first.Name;


        throw new InvalidOperationException(
            $"Cannot find primary key property for entity '{entityType.Name}'.");
    }

private static void EmitModelIdConstants(
        StringBuilder sb,
        List<MappingClassInfo> models)
    {
        sb.AppendLine(
            "        public static class ModelId");

        sb.AppendLine("        {");

        for (int i = 0; i < models.Count; i++)
        {
            sb.AppendLine(
                $"            public const ushort {models[i].ModelType.Name} = {i};");
        }

        sb.AppendLine();

        sb.AppendLine(
            $"            public const ushort Count = {models.Count};");

        sb.AppendLine("        }");

        sb.AppendLine();
    }


    private static void EmitSchemaArray(
    StringBuilder sb,
    List<MappingClassInfo> models)
{
    sb.AppendLine(
        $"        public static readonly string[][] Schema = new string[{models.Count}][]");

    sb.AppendLine("        {");

    foreach (var model in models)
    {
        var schemas =
            model.Definition.Entities
                .Where(e => e.EntityType != null)
                .Select(e =>
                {
                    var entityName = e.EntityType.Name;

                    if (entityName.EndsWith(
                            "Entity",
                            StringComparison.Ordinal))
                    {
                        entityName = entityName.Substring(
                            0,
                            entityName.Length - "Entity".Length);
                    }

                    return FindSchemaByEntityName(
                        entityName,
                        models);
                })
                .Select(x => $"\"{Escape(x ?? string.Empty)}\"")
                .ToList();

        sb.AppendLine(
            $"            new string[] {{ {string.Join(", ", schemas)} }},");
    }

    sb.AppendLine("        };");

    sb.AppendLine();
}

private static string? FindSchemaByEntityName(
    string entityName,
    List<MappingClassInfo> models)
{
    foreach (var model in models)
    {
        foreach (var entity in model.Definition.Entities)
        {
            if (entity.EntityType == null)
            {
                continue;
            }

            var name = entity.EntityType.Name;

            if (name.EndsWith(
                    "Entity",
                    StringComparison.Ordinal))
            {
                name = name.Substring(
                    0,
                    name.Length - "Entity".Length);
            }

            if (!string.Equals(
                    name,
                    entityName,
                    StringComparison.Ordinal))
            {
                continue;
            }

            if (!string.IsNullOrWhiteSpace(model.Definition.Schema))
            {
                return model.Definition.Schema;
            }

            if (!string.IsNullOrWhiteSpace(model.Schema))
            {
                return model.Schema;
            }
        }
    }

    return null;
}

    private static string Escape(string value)
    {
        return value.Replace("\\", "\\\\")
            .Replace("\"", "\\\"");
    }

    private static void EmitModelNameArray(
        StringBuilder sb,
        List<MappingClassInfo> models)
    {
        sb.AppendLine(
            $"        public static readonly string[][] ModelName = new string[{models.Count}][]");

        sb.AppendLine("        {");

        foreach (var m in models)
        {
            var names = new List<string>
            {
                m.ModelType.Name
            };

            names.AddRange(
                m.CteUpdateMeta
                    .Select(x => x.NavigationAlias)
                    .Distinct());

            sb.AppendLine(
                $"            new string[] {{ {string.Join(", ", names.Select(x => $"\"{x}\""))} }},");
        }

        sb.AppendLine("        };");

        sb.AppendLine();
    }


    private static string ToCamel(string name)
    {
        if (string.IsNullOrEmpty(name))
            return name;

        return char.ToLowerInvariant(name[0])
               + name.Substring(1);
    }

    private static void EmitTableArray(
        StringBuilder sb,
        List<MappingClassInfo> models)
    {
        sb.AppendLine(
            $"        public static readonly string[][] Table = new string[{models.Count}][]");

        sb.AppendLine("        {");

        foreach (var model in models)
        {
            var tables =
                model.Definition.Entities
                    .Where(e => e.EntityType != null)
                    .Select(e =>
                    {
                        var name = e.EntityType!.Name;

                        if (name.EndsWith(
                                "Entity",
                                StringComparison.Ordinal))
                        {
                            name =
                                name.Substring(
                                    0,
                                    name.Length - "Entity".Length);
                        }

                        return name;
                    })
                    .ToList();

            sb.AppendLine(
                $"            new string[] {{ {string.Join(", ", tables.Select(x => $"\"{Escape(x)}\""))} }},");
        }

        sb.AppendLine("        };");
        sb.AppendLine();
    }


    private static void EmitColumnNameArray(
        StringBuilder sb,
        List<MappingClassInfo> models)
    {
        sb.AppendLine(
            $"        public static readonly string[][] ColumnName = new string[{models.Count}][]");

        sb.AppendLine("        {");

        foreach (var m in models)
        {
            INamedTypeSymbol typeForColumns;

            if (IsComposite(m))
            {
                var primaryEntity =
                    m.Definition.Entities.FirstOrDefault(k => k.IsPrimary);

                typeForColumns =
                    primaryEntity?.EntityType
                    ?? throw new InvalidOperationException(
                        $"Composite model '{m.ModelType.Name}' has no primary EntityType.");
            }
            else
            {
                typeForColumns =
                    m.EntityType
                    ?? throw new InvalidOperationException(
                        $"Simple model '{m.ModelType.Name}' has no EntityType.");
            }

            var cols =
                IdEmitter.GetScalarProperties(
                    typeForColumns);

            sb.AppendLine(
                $"            new string[{cols.Count}]");

            sb.AppendLine("            {");

            foreach (var c in cols)
            {
                sb.AppendLine(
                    $"                \"{c.Name}\",");
            }

            sb.AppendLine("            },");
        }

        sb.AppendLine("        };");
        sb.AppendLine();
    }


    private static bool IsComposite(
        MappingClassInfo info)
    {
        return info.Definition.Entities
            .Where(x => x.EntityType != null)
            .Select(x => x.EntityType!.Name)
            .Distinct(StringComparer.Ordinal)
            .Count() > 1;
    }


    private static void EmitFieldNameArray(
        StringBuilder sb,
        List<MappingClassInfo> models)
    {
        sb.AppendLine(
            $"        public static readonly string[][] FieldName = new string[{models.Count}][]");

        sb.AppendLine("        {");


        foreach (var m in models)
        {
            var mappings =
                PlannerEmitter.ComputeFieldMappingsEagerPublic(
                        m,
                        PlannerEmitter.IsCompositeInfo(m))
                    .ToList();


            if (mappings.Count == 0)
            {
                sb.AppendLine(
                    "            System.Array.Empty<string>(),");
                continue;
            }


            sb.AppendLine(
                "            new string[]");

            sb.AppendLine(
                "            {");


            foreach (var mapping in mappings)
            {
                // This is the same name used by FieldMappings.
                sb.AppendLine(
                    $"                \"{ToCamel(mapping.FieldName)}\",");
            }


            sb.AppendLine(
                "            },");
        }


        sb.AppendLine("        };");
        sb.AppendLine();
    }
    
private static void EmitConflictColumnsArray(
    StringBuilder sb,
    List<INamedTypeSymbol> entityTypes,
    ImmutableArray<MappingClassInfo> allMappings)
{
    sb.AppendLine(
        $"        public static readonly string[][] EntityConflictColumns = new string[{entityTypes.Count}][]");

    sb.AppendLine("        {");


    foreach (var entityType in entityTypes)
    {
        var keys = new List<string>();


        //
        // Find the mapping that owns this storage entity
        //
        var mappings =
            allMappings
                .Where(m =>
                    m.Definition.Entities.Any(e =>
                        e.EntityType != null &&
                        SymbolEqualityComparer.Default.Equals(
                            e.EntityType,
                            entityType)))
                .ToList();


        //
        // Find explicit upsert keys belonging to this entity
        //
        foreach (var mapping in mappings)
        {
            foreach (var upsertKey in mapping.UpsertKeys)
            {
                if (string.IsNullOrWhiteSpace(upsertKey.Key))
                    continue;


                var scalar =
                    IdEmitter.GetScalarProperties(entityType)
                        .FirstOrDefault(p =>
                            string.Equals(
                                p.Name,
                                upsertKey.Key,
                                StringComparison.OrdinalIgnoreCase));


                if (scalar != null)
                {
                    keys.Add(scalar.Name);
                }
            }
        }


        keys =
            keys
                .Distinct(StringComparer.OrdinalIgnoreCase)
                .ToList();



        //
        // Fallback: entity primary key/natural key
        //
        if (keys.Count == 0)
        {
            foreach (var mapping in mappings)
            {
                var entity =
                    mapping.Definition.Entities
                        .FirstOrDefault(e =>
                            e.IsPrimary &&
                            e.EntityType != null &&
                            SymbolEqualityComparer.Default.Equals(
                                e.EntityType,
                                entityType));


                if (entity != null &&
                    !string.IsNullOrWhiteSpace(entity.ToColumn))
                {
                    keys.Add(entity.ToColumn!);
                    break;
                }
            }
        }



        //
        // Final fallback:
        // Convention: *Key column
        //
        if (keys.Count == 0)
        {
            var scalar =
                IdEmitter.GetScalarProperties(entityType)
                    .FirstOrDefault(p =>
                        p.Name.EndsWith(
                            "Key",
                            StringComparison.OrdinalIgnoreCase));


            if (scalar != null)
            {
                keys.Add(scalar.Name);
            }
        }



        keys =
            keys
                .Distinct(StringComparer.OrdinalIgnoreCase)
                .ToList();



        if (keys.Count == 0)
        {
            sb.AppendLine(
                "            System.Array.Empty<string>(),");
        }
        else
        {
            sb.AppendLine(
                $"            new string[] {{ {string.Join(", ", keys.Select(k => $"\"{k}\""))} }},");
        }
    }


    sb.AppendLine("        };");
    sb.AppendLine();
}

private static void EmitCteResolutionsArray(
    StringBuilder sb,
    List<MappingClassInfo> models)
{
    sb.AppendLine(
        $"        public static readonly global::CoffeeBeanery.GraphQL.Core.Runtime.CteResolutionSpec[][] CteResolutions = new global::CoffeeBeanery.GraphQL.Core.Runtime.CteResolutionSpec[{models.Count}][]");

    sb.AppendLine(
        "        {");


    foreach (var m in models)
    {
        if (m.CteUpdateMeta.Count == 0)
        {
            sb.AppendLine(
                "            System.Array.Empty<global::CoffeeBeanery.GraphQL.Core.Runtime.CteResolutionSpec>(),");

            continue;
        }


        var primaryEntity =
            m.Definition.Entities
                .FirstOrDefault(e => e.IsPrimary)
                ?.EntityType;


        var entityColumns =
            primaryEntity == null
                ? new Dictionary<string, ushort>(
                    StringComparer.OrdinalIgnoreCase)
                :
                IdEmitter.GetScalarProperties(primaryEntity)
                    .Select((c, i) =>
                        new
                        {
                            Name = c.Name,
                            Index = (ushort)i
                        })
                    .ToDictionary(
                        x => x.Name,
                        x => x.Index,
                        StringComparer.OrdinalIgnoreCase);



        sb.AppendLine(
            "            new global::CoffeeBeanery.GraphQL.Core.Runtime.CteResolutionSpec[]");

        sb.AppendLine(
            "            {");


        foreach (var cte in m.CteUpdateMeta)
        {
            entityColumns.TryGetValue(
                cte.OwningPrimaryKeyColumn,
                out var pkColumnId);



            var tableAlias =
                cte.NavigationAlias +
                cte.RelatedEntityTypeName;



            sb.AppendLine(
                "                new global::CoffeeBeanery.GraphQL.Core.Runtime.CteResolutionSpec(");


            sb.AppendLine(
                $"                    \"{cte.NavigationAlias}\",");


            sb.AppendLine(
                $"                    \"{cte.ForeignKeyColumn}\",");


            sb.AppendLine(
                $"                    \"{cte.OwningPrimaryKeyColumn}\",");


            sb.AppendLine(
                $"                    {pkColumnId},");


            sb.AppendLine(
                $"                    \"{tableAlias}\",");


            sb.AppendLine(
                $"                    \"{cte.RelatedSurrogateIdColumn}\",");


            sb.AppendLine(
                $"                    \"{cte.RelatedNaturalKeyColumn}\"");


            sb.AppendLine(
                "                ),");
        }


        sb.AppendLine(
            "            },");
    }


    sb.AppendLine(
        "        };");

    sb.AppendLine();
}

// ---------------------------------------------------------------
// Storage-entity-keyed arrays
// ---------------------------------------------------------------

    private static void EmitEntitySchemaArray(
        StringBuilder sb,
        List<(string EntityName, string Schema)> entities)
    {
        sb.AppendLine(
            "        public static readonly string[] EntitySchema = new string[" +
            entities.Count +
            "]");

        sb.AppendLine("        {");

        foreach (var entity in entities)
        {
            sb.AppendLine(
                $"            \"{Escape(entity.Schema)}\",");
        }

        sb.AppendLine("        };");
        sb.AppendLine();
    }
    
    private static void EmitEntityTableArray(
        StringBuilder sb,
        List<(string EntityName, string Schema)> entities)
    {
        sb.AppendLine(
            $"        public static readonly string[] EntityTable = new string[{entities.Count}]");

        sb.AppendLine("        {");

        foreach (var entity in entities)
        {
            sb.AppendLine(
                $"            \"{Escape(entity.EntityName)}\",");
        }

        sb.AppendLine("        };");
        sb.AppendLine();
    }

    // private static void EmitEntityTableArray(
    //     StringBuilder sb,
    //     List<INamedTypeSymbol> entityTypes)
    // {
    //     sb.AppendLine(
    //         "        /// <summary>Indexed by StorageEntityId.*</summary>");
    //
    //     sb.AppendLine(
    //         $"        public static readonly string[] EntityTable = new string[{entityTypes.Count}]");
    //
    //     sb.AppendLine("        {");
    //
    //     foreach (var e in entityTypes)
    //     {
    //         sb.AppendLine(
    //             $"            \"{e.Name}\",");
    //     }
    //
    //     sb.AppendLine("        };");
    //     sb.AppendLine();
    // }


    private static void EmitEntityColumnNameArray(
        StringBuilder sb,
        List<INamedTypeSymbol> entityTypes,
        ImmutableArray<MappingClassInfo> allMappings)
    {
        sb.AppendLine(
            "        /// <summary>Indexed by StorageEntityId.* then ColumnId.{EntityName}.*</summary>");

        sb.AppendLine(
            $"        public static readonly string[][] EntityColumnName = new string[{entityTypes.Count}][]");

        sb.AppendLine("        {");

        foreach (var entity in entityTypes)
        {
            var entityName =
                IdEmitter.StripEntitySuffix(entity.Name);

            // IMPORTANT: must use the exact same ordering as ColumnId.* constants
            // (IdEmitter.EmitColumnIds). Both now call GetFullColumnOrder so the
            // numeric ColumnId values and this runtime name array can never
            // disagree again — previously this method inserted the PK column
            // independently while EmitColumnIds did not, causing every column
            // reference for entities whose PK wasn't already a mapped field to
            // resolve one index off from its actual physical column.
            var columns =
                IdEmitter.GetFullColumnOrder(
                        entityName,
                        allMappings,
                        entity)
                    .ToList();

            sb.AppendLine(
                $"            new string[{columns.Count}]");

            sb.AppendLine("            {");

            foreach (var column in columns)
            {
                sb.AppendLine(
                    $"                \"{column}\",");
            }

            sb.AppendLine("            },");
        }

        sb.AppendLine("        };");
        sb.AppendLine();
    }


// ---------------------------------------------------------------
// GeneratedEntityMetaProvider
// ---------------------------------------------------------------

    private static void EmitGeneratedEntityMetaProvider(
        StringBuilder sb)
    {
        sb.AppendLine(
            "namespace CoffeeBeanery.GraphQL.Core.Runtime");

        sb.AppendLine("{");

        sb.AppendLine(
            "    public sealed class " +
            "GeneratedEntityMetaProvider : global::CoffeeBeanery.GraphQL.Core.Runtime.IEntityMetaProvider");

        sb.AppendLine("    {");

        sb.AppendLine(
            "        public int Count => EntityMeta.Table.Length;");

        sb.AppendLine(
            "        public string[][] ModelName => EntityMeta.ModelName;");

        sb.AppendLine(
            "        public string[][] Table => EntityMeta.Table;");

        sb.AppendLine(
            "        public string[][] Schema => EntityMeta.Schema;");

        sb.AppendLine(
            "        public FieldMapSpec[][] FieldMappings => EntityMeta.FieldMappings;");

        sb.AppendLine(
            "        public string[][] ColumnName => EntityMeta.ColumnName;");

        sb.AppendLine(
            "        public string[][] FieldName => EntityMeta.FieldName;");

        sb.AppendLine(
            "        public ushort[][] FieldToColumn => EntityMeta.FieldToColumn;");

        sb.AppendLine(
            "        public string[][] EntityConflictColumns => EntityMeta.EntityConflictColumns;");;

        sb.AppendLine(
            "        public CteResolutionSpec[][] CteResolutions => EntityMeta.CteResolutions;");

        sb.AppendLine(
            "        public int StorageEntityCount => EntityMeta.EntityTable.Length;");

        sb.AppendLine(
            "        public string[] EntitySchema => EntityMeta.EntitySchema;");

        sb.AppendLine(
            "        public string[] EntityTable => EntityMeta.EntityTable;");

        sb.AppendLine(
            "        public string[][] EntityColumnName => EntityMeta.EntityColumnName;");

        sb.AppendLine();

        sb.AppendLine(
            "        public bool TryGetEntityId(string modelName, out ushort entityId)");

        sb.AppendLine("        {");

        sb.AppendLine(
            "            for (ushort i = 0; i < EntityMeta.ModelName.Length; i++)");

        sb.AppendLine("            {");

        sb.AppendLine(
            "                if (global::System.StringComparer.OrdinalIgnoreCase.Equals(EntityMeta.ModelName[i][0], modelName))");

        sb.AppendLine("                {");

        sb.AppendLine(
            "                    entityId = i;");

        sb.AppendLine(
            "                    return true;");

        sb.AppendLine("                }");

        sb.AppendLine("            }");

        sb.AppendLine(
            "            entityId = 0;");

        sb.AppendLine(
            "            return false;");

        sb.AppendLine("        }");

        sb.AppendLine("    }");

        sb.AppendLine("}");

        sb.AppendLine();
    }


// ---------------------------------------------------------------
// GeneratedPlannerRegistry
// ---------------------------------------------------------------

    private static void EmitGeneratedPlannerRegistry(StringBuilder sb)
    {
        sb.AppendLine("namespace CoffeeBeanery.GraphQL.Core.Runtime");
        sb.AppendLine("{");
        sb.AppendLine("    public sealed class GeneratedPlannerRegistry : global::CoffeeBeanery.GraphQL.Core.Runtime.IPlannerRegistry");
        sb.AppendLine("    {");

        sb.AppendLine(
            "        public void Build(ushort entityId, in global::CoffeeBeanery.GraphQL.Core.Runtime.SelectionIR selection, ref global::CoffeeBeanery.GraphQL.Core.Runtime.QueryPlanBuilder builder, bool isRoot)");

        sb.AppendLine(
            "            => GeneratedPlanners.PlannerRegistry.Build(entityId, selection, ref builder, isRoot);");

        sb.AppendLine();

        sb.AppendLine(
            "        public void BuildMutation(ushort entityId, in global::CoffeeBeanery.GraphQL.Core.Runtime.MutationIR mutation, ref global::CoffeeBeanery.GraphQL.Core.Runtime.MutationPlanBuilder builder)");

        sb.AppendLine(
            "            => global::CoffeeBeanery.GraphQL.Core.Runtime.MutationRuntimePlanner.Build(entityId, mutation, ref builder);");

        sb.AppendLine();

        sb.AppendLine(
            "        public bool IsValidEntity(ushort entityId)");

        sb.AppendLine(
            "            => GeneratedPlanners.PlannerRegistry.IsValidEntity(entityId);");

        sb.AppendLine();

        sb.AppendLine(
            "        public string GetEntityName(ushort entityId)");

        sb.AppendLine(
            "            => GeneratedPlanners.PlannerRegistry.GetEntityName(entityId);");

        sb.AppendLine("    }");
        sb.AppendLine("}");
    }
}