using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using CoffeeBeanery.GraphQL.Core.Mapping.Generators.Model;
using CoffeeBeanery.GraphQL.Core.Mapping.Generators.Passes;

namespace CoffeeBeanery.GraphQL.Core.Mapping.Generators.Emit
{
    /// <summary>
    /// Emits AdapterTables.g.cs — the static lookup tables consumed by
    /// HotChocolateAdapter to convert GraphQL field name strings into
    /// integer EntityId/FieldId constants.
    ///
    /// This is the ONLY generated file that still contains strings at
    /// runtime. After the adapter runs, no strings appear in the pipeline.
    ///
    /// Emits:
    ///   AdapterTables.Build() → AdapterLookup
    ///     Populated from two sources:
    ///     1. Scalar fields: ModelType properties → FieldId constants
    ///     2. Navigation children: EntityNavigationConvention results + 
    ///        CompositeChildAttachment links → childEntityId constants
    /// </summary>
    internal static class AdapterEmitter
    {
        public static string Emit(
            ImmutableArray<MappingClassInfo> allMappings,
            ImmutableHashSet<INamedTypeSymbol> rootEntityTypes,
            List<FluentEntityNavigationConvention.EntityForeignKeyGraph.Edge> entityGraph)
        {
            var models = allMappings
                .Where(m => m.IsModel)
                .OrderBy(m => m.ModelType.Name, System.StringComparer.Ordinal)
                .ToList();

            var navResults = models.ToDictionary(
                m => m.ModelType.Name,
                m => EntityNavigationConvention.Resolve(m, allMappings, entityGraph, rootEntityTypes),
                System.StringComparer.Ordinal);

            // Build a name → EntityId map for resolving child entity names.
            var entityIdByName = models
                .Select((m, i) => (Name: m.ModelType.Name, Id: (ushort)i))
                .ToDictionary(x => x.Name, x => x.Id, System.StringComparer.Ordinal);

            var sb = new StringBuilder();
            sb.AppendLine("#nullable enable");
            sb.AppendLine("// <auto-generated/>");
            
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine("using CoffeeBeanery.GraphQL.Core.Runtime;");
            sb.AppendLine();
            sb.AppendLine("namespace CoffeeBeanery.GraphQL.Core.Runtime");
            sb.AppendLine("{");
            sb.AppendLine("    /// <summary>");
            sb.AppendLine("    /// Static lookup tables for HotChocolateAdapter.");
            sb.AppendLine("    /// Strings only appear here — everywhere else in the pipeline uses integer IDs.");
            sb.AppendLine("    /// </summary>");
            sb.AppendLine("    public static class AdapterTables");
            sb.AppendLine("    {");

            EmitBuildMethod(sb, models, navResults, entityIdByName, allMappings);

            sb.AppendLine("    }");
            sb.AppendLine("}");

            return sb.ToString();
        }

        private static void EmitBuildMethod(
            StringBuilder sb,
            List<MappingClassInfo> models,
            Dictionary<string, NavigationResolutionResult?> navResults,
            Dictionary<string, ushort> entityIdByName,
            ImmutableArray<MappingClassInfo> allMappings)
        {
            sb.AppendLine("        /// <summary>");
            sb.AppendLine("        /// Builds a fully-populated AdapterLookup from generated constants.");
            sb.AppendLine("        /// Call once at startup and inject the result as a singleton.");
            sb.AppendLine("        /// </summary>");
            sb.AppendLine("        public static AdapterLookup Build()");
            sb.AppendLine("        {");
            sb.AppendLine("            var childEntityIds = new Dictionary<ushort, Dictionary<string, ushort>>();");
            sb.AppendLine("            var fieldIds = new Dictionary<ushort, Dictionary<string, ushort>>();");
            sb.AppendLine();

            foreach (var model in models)
            {
                if (!entityIdByName.TryGetValue(model.ModelType.Name, out var entityId))
                    continue;

                var navResult = navResults.TryGetValue(model.ModelType.Name, out var r) ? r : null;

                EmitScalarFieldLinks(sb, model, entityId);
                EmitChildEntityLinks(sb, model, entityId, navResult, entityIdByName, allMappings);
            }

            sb.AppendLine("            return new AdapterLookup(childEntityIds, fieldIds);");
            sb.AppendLine("        }");
        }

        private static void EmitScalarFieldLinks(
            StringBuilder sb,
            MappingClassInfo model,
            ushort entityId)
        {
            var fields = IdEmitter.GetResolvedFieldNames(model);
            if (fields.Count == 0)
                return;

            sb.AppendLine($"            // {model.ModelType.Name} scalar fields");
            sb.AppendLine("            {");
            sb.AppendLine("                var m = new Dictionary<string, ushort>(StringComparer.OrdinalIgnoreCase);");

            foreach (var field in fields)
            {
                var camel = ToCamelCase(field);
                sb.AppendLine(
                    $"                m[\"{camel}\"] = FieldId.{model.ModelType!.Name}.{field};");
            }

            sb.AppendLine($"                fieldIds[EntityId.{model.ModelType!.Name}] = m;");
            sb.AppendLine("            }");
            sb.AppendLine();
        }

        private static void EmitChildEntityLinks(
            StringBuilder sb,
            MappingClassInfo model,
            ushort entityId,
            NavigationResolutionResult? navResult,
            Dictionary<string, ushort> entityIdByName,
            ImmutableArray<MappingClassInfo> allMappings)
        {
            var links = new List<(string FieldName, string ChildModelName)>();

            // 1. Navigation children from EntityNavigationConvention.
            if (navResult is not null)
            {
                foreach (var nav in navResult.Navigations)
                {
                    var childMapping = allMappings.FirstOrDefault(m =>
                        SymbolEqualityComparer.Default.Equals(m.EntityType, nav.RelatedEntityType));

                    if (childMapping is null) continue;

                    var fieldName = ToCamelCase(nav.NavigationName);
                    links.Add((fieldName, childMapping.ModelType.Name));
                }
            }

            foreach (var link in model.Definition.Entities)
            {
                if (string.IsNullOrWhiteSpace(link.AliasProperty))
                    continue;


                var childMapping =
                    allMappings.FirstOrDefault(m =>
                        m.Definition.Entities.Any(x =>
                            x.IsPrimary &&
                            SymbolEqualityComparer.Default.Equals(x.EntityType, link.EntityType)));


                if (childMapping is null)
                    continue;


                var fieldName =
                    ToCamelCase(link.AliasProperty);


                if (links.Any(l =>
                        string.Equals(
                            l.FieldName,
                            fieldName,
                            System.StringComparison.OrdinalIgnoreCase)
                        &&
                        string.Equals(
                            l.ChildModelName,
                            childMapping.ModelType.Name,
                            System.StringComparison.Ordinal)))
                {
                    continue;
                }


                links.Add(
                    (
                        fieldName,
                        childMapping.ModelType.Name
                    ));
            }

            // 3. CompositeChildAttachment links (e.g. Customer.product → Product).
            var parentKeyName = model.EntityType?.Name + "Key";
            if (model.EntityType is not null)
            {
                var parentHasKey = model.EntityType.GetMembers().OfType<IPropertySymbol>()
                    .Any(p => p.Name == parentKeyName);

                if (parentHasKey)
                {
                    var modelProps = model.ModelType.GetMembers().OfType<IPropertySymbol>()
                        .Where(p => p.GetMethod is not null && !p.IsStatic);

                    foreach (var prop in modelProps)
                    {
                        var elementType = UnwrapCollection(prop.Type);
                        var unwrapped = UnwrapNullable(elementType);

                        if (unwrapped is not INamedTypeSymbol related) continue;

                        if (related.TypeKind == TypeKind.Enum) continue;
                        if (related.SpecialType != SpecialType.None) continue;

                        if (SymbolEqualityComparer.Default.Equals(related, model.ModelType)) continue;
                        if (related.Name == "Wrapper") continue;

                        var childMapping = allMappings.FirstOrDefault(m =>
                            SymbolEqualityComparer.Default.Equals(m.ModelType, related));

                        if (childMapping?.EntityType is null) continue;

                        var fieldName = ToCamelCase(prop.Name);

                        if (links.Any(l =>
                                string.Equals(l.FieldName, fieldName, StringComparison.OrdinalIgnoreCase) &&
                                string.Equals(l.ChildModelName, childMapping.ModelType.Name, StringComparison.Ordinal)))
                            continue;

                        links.Add((fieldName, childMapping.ModelType.Name));
                    }
                }
            }

            if (links.Count == 0) return;

            sb.AppendLine($"            // {model.ModelType.Name} child entity links");
            sb.AppendLine($"            {{");
            sb.AppendLine($"                var m = new Dictionary<string, ushort>(StringComparer.OrdinalIgnoreCase);");

            foreach (var (fieldName, childModelName) in links)
            {
                if (!entityIdByName.ContainsKey(childModelName)) continue;
                sb.AppendLine($"                m[\"{fieldName}\"] = EntityId.{childModelName};");
            }

            sb.AppendLine($"                childEntityIds[EntityId.{model.ModelType.Name}] = m;");
            sb.AppendLine($"            }}");
            sb.AppendLine();
        }

        private static string ToCamelCase(string name) =>
            string.IsNullOrEmpty(name) ? name :
            char.ToLowerInvariant(name[0]) + name.Substring(1);

        public static ITypeSymbol UnwrapCollection(ITypeSymbol type)
        {
            if (type is INamedTypeSymbol { IsGenericType: true } named &&
                named.TypeArguments.Length == 1 &&
                named.Name is "List" or "IEnumerable" or "ICollection" or "IList")
                return named.TypeArguments[0];
            return type;
        }

        internal static ITypeSymbol UnwrapNullable(ITypeSymbol type) =>
            type is INamedTypeSymbol { OriginalDefinition.SpecialType: SpecialType.System_Nullable_T } n
                ? n.TypeArguments[0]
                : type;
    }
}