using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using CoffeeBeanery.GraphQL.Core.Mapping.Generators.Model;
using CoffeeBeanery.GraphQL.Core.Mapping.Generators.Passes;
using Microsoft.CodeAnalysis;

namespace CoffeeBeanery.GraphQL.Core.Mapping.Generators.Emit
{
    /// <summary>
    /// Emits AdapterTables.g.cs — the static child-link table the
    /// HotChocolateAdapter uses to map GraphQL field names to child EntityIds.
    ///
    /// Field links (fieldName → FieldId) are already fully derivable at
    /// runtime from EntityMeta.FieldName[], so this emitter only needs to
    /// produce the child entity links, which require cross-mapping knowledge
    /// the runtime does not have.
    ///
    /// Output:
    ///
    ///   public static class AdapterTables
    ///   {
    ///       // (parentEntityId, graphqlFieldName) → childEntityId
    ///       // Used by AdapterLookup.BuildFromGeneratedMetadata at startup.
    ///       public static readonly (ushort Parent, string Field, ushort Child)[]
    ///           ChildLinks = { ... };
    ///   }
    /// </summary>
    internal static class AdapterTablesEmitter
    {
        public static string Emit(
            ImmutableArray<MappingClassInfo> allMappings,
            ImmutableHashSet<INamedTypeSymbol> rootEntityTypes,
            ImmutableDictionary<(INamedTypeSymbol, string), string> fluentInverseNav)
        {
            var models = allMappings
                .Where(m => m.IsModel)
                .OrderBy(m => m.ModelType.Name, System.StringComparer.Ordinal)
                .ToList();

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("#nullable enable");
            sb.AppendLine("");
            sb.AppendLine("namespace CoffeeBeanery.GraphQL.Core.Runtime");
            sb.AppendLine("{");
            sb.AppendLine("    /// <summary>");
            sb.AppendLine("    /// Generated child-entity link table for HotChocolateAdapter.");
            sb.AppendLine("    /// Maps (parentEntityId, graphqlFieldName) → childEntityId.");
            sb.AppendLine("    /// Field links are derived at runtime from EntityMeta.FieldName.");
            sb.AppendLine("    /// </summary>");
            sb.AppendLine("    public static class AdapterTables");
            sb.AppendLine("    {");
            sb.AppendLine("        public static readonly (string Parent, string Field, string Child)[] ChildLinks =");
            sb.AppendLine("        {");

            var emittedLinks = new HashSet<(string ParentModel, string Field)>();

            foreach (var parentModel in models)
            {
                if (parentModel.EntityType is null) continue;

                var navResult = EntityNavigationConvention.ResolveQuietly(
                    parentModel, rootEntityTypes, fluentInverseNav);

                // Navigation children (from EF entity relationships).
                foreach (var nav in navResult.Navigations)
                {
                    var childMapping = allMappings.FirstOrDefault(m =>
                        SymbolEqualityComparer.Default.Equals(m.EntityType, nav.RelatedEntityType));

                    if (childMapping is null) continue;

                    var fieldName = ToCamelCase(nav.NavigationName);
                    var key = (parentModel.ModelType.Name, fieldName);
                    if (!emittedLinks.Add(key)) continue;

                    sb.AppendLine(
                        $"            ( \"{parentModel.ModelType.Name}\", " +
                        $"\"{fieldName}\", " +
                        $"\"{childMapping.ModelType.Name}\" ),");
                }

                // Cross-model composite children (ChildAttachments convention).
                var parentKeyName = parentModel.EntityType.Name + "Key";
                var parentHasKey = parentModel.EntityType.GetMembers()
                    .OfType<IPropertySymbol>()
                    .Any(p => p.Name == parentKeyName);

                if (!parentHasKey) continue;

                var modelProps = parentModel.ModelType.GetMembers()
                    .OfType<IPropertySymbol>()
                    .Where(p => p.GetMethod is not null && !p.IsStatic);

                foreach (var prop in modelProps)
                {
                    var elementType = UnwrapCollection(prop.Type);
                    var unwrapped   = UnwrapNullable(elementType);

                    if (unwrapped is not INamedTypeSymbol related) continue;
                    if (IdEmitter.IsScalarProperty(related)) continue;
                    if (SymbolEqualityComparer.Default.Equals(related, parentModel.ModelType)) continue;
                    if (related.Name == "Wrapper") continue;

                    var childMapping = allMappings.FirstOrDefault(m =>
                        SymbolEqualityComparer.Default.Equals(m.ModelType, related));

                    if (childMapping?.EntityType is null) continue;

                    // Confirm the child actually has the FK back to the parent.
                    var childCarriesFk = childMapping.ModelToEntity.Any(link =>
                        link.EntityType.GetMembers().OfType<IPropertySymbol>()
                            .Any(p => p.Name == parentKeyName));

                    if (!childCarriesFk) continue;

                    var fieldName = ToCamelCase(prop.Name);
                    var key = (parentModel.ModelType.Name, fieldName);
                    if (!emittedLinks.Add(key)) continue;

                    sb.AppendLine(
                        $"            ( EntityId.{parentModel.ModelType.Name}, " +
                        $"\"{fieldName}\", " +
                        $"EntityId.{childMapping.ModelType.Name} ),");
                }
            }

            sb.AppendLine("        };");
            sb.AppendLine("    }");
            sb.AppendLine("}");
            return sb.ToString();
        }

        private static ITypeSymbol UnwrapCollection(ITypeSymbol type)
        {
            if (type is INamedTypeSymbol { IsGenericType: true } named &&
                named.TypeArguments.Length == 1 &&
                named.Name is "List" or "IEnumerable" or "ICollection" or "IList")
                return named.TypeArguments[0];

            return type;
        }

        private static ITypeSymbol UnwrapNullable(ITypeSymbol type) =>
            type is INamedTypeSymbol { OriginalDefinition.SpecialType: SpecialType.System_Nullable_T } n
                ? n.TypeArguments[0]
                : type;

        private static string ToCamelCase(string name) =>
            string.IsNullOrEmpty(name) ? name :
            char.ToLowerInvariant(name[0]) + name.Substring(1);
    }
}