using System;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using CoffeeBeanery.GraphQL.Core.Mapping.Generators.Model;

namespace CoffeeBeanery.GraphQL.Core.Mapping.Generators.Emit;

internal static class ColumnNameResolverEmitter
{
    public static string Emit(
        ImmutableArray<MappingClassInfo> mappings)
    {
        var sb = new StringBuilder();

        sb.AppendLine("#nullable enable");
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("using System;");
        sb.AppendLine("using CoffeeBeanery.GraphQL.Core.Runtime;");
        sb.AppendLine();

        sb.AppendLine("namespace CoffeeBeanery.GraphQL.Core.Runtime");
        sb.AppendLine("{");

        sb.AppendLine("public static class ColumnNameResolver");
        sb.AppendLine("{");

        sb.AppendLine("    public static string Resolve(\n    ushort storageEntityId,\n    ushort columnId)");
        sb.AppendLine("    {");

        sb.AppendLine("        return (storageEntityId, columnId) switch");
        sb.AppendLine("        {");
        foreach (var entity in mappings
                     .SelectMany(x => x.Definition.Entities)
                     .Where(x => x.EntityType != null)
                     .Select(x => x.EntityType!.Name)
                     .Distinct()
                     .OrderBy(x => x))
        {
            var columns =
                mappings
                    .SelectMany(x => x.FieldMaps)
                    .Where(x =>
                        string.Equals(
                            x.DestinationEntity,
                            entity,
                            StringComparison.OrdinalIgnoreCase))
                    .Select(x => x.DestinationName)
                    .Distinct()
                    .OrderBy(x => x);

            foreach (var column in columns)
            {
                sb.AppendLine(
                    $"            (StorageEntityId.{entity}, ColumnId.{entity}.{column}) => \"{column}\",");
            }
        }
        sb.AppendLine(
            "            _ => throw new ArgumentException(\n    $\"Unknown StorageEntityId {storageEntityId}, ColumnId {columnId}\")");

        sb.AppendLine("        };");
        sb.AppendLine("    }");

        sb.AppendLine("}");

        sb.AppendLine("}");

        return sb.ToString();
    }
}