using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using CoffeeBeanery.GraphQL.Core.Mapping.Generators.Passes;

namespace CoffeeBeanery.GraphQL.Core.Mapping.Generators.Emit
{
    internal static class EntityForeignKeyAttributeEmitter
    {
        public static SourceText Emit(
            INamedTypeSymbol declaringEntityType,
            System.Collections.Generic.IReadOnlyList<FluentForeignKeyAttributeConvention.DerivedForeignKey> keys)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("#nullable enable");
            sb.AppendLine();
            sb.AppendLine($"namespace {declaringEntityType.ContainingNamespace.ToDisplayString()}");
            sb.AppendLine("{");

            foreach (var key in keys)
            {
                var navArg = key.IsAmbiguous
                    ? $", navigationName: \"{key.NavigationName}\""
                    : string.Empty;

                var relatedTypeNonNullable = key.RelatedEntityType.WithNullableAnnotation(NullableAnnotation.NotAnnotated);

                sb.AppendLine(
                    $"    [global::CoffeeBeanery.GraphQL.Core.Mapping.EntityForeignKey(" +
                    $"typeof(global::{relatedTypeNonNullable.ToDisplayString()}), " +
                    $"\"{key.ForeignKeyProperty}\", " +
                    $"\"{key.PrincipalKeyProperty}\"" +
                    $"{navArg})]");
            }

            sb.AppendLine($"    public partial class {declaringEntityType.Name}");
            sb.AppendLine("    {");
            sb.AppendLine("    }");
            sb.AppendLine("}");

            return SourceText.From(sb.ToString(), System.Text.Encoding.UTF8);
        }
    }
}