using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using CoffeeBeanery.GraphQL.Core.Mapping.Generators.Model;
using Microsoft.CodeAnalysis;

namespace CoffeeBeanery.GraphQL.Core.Mapping.Generators.Emit;

internal static class IdEmitter
{
    public static string Emit(
        ImmutableArray<MappingClassInfo> mappings)
    {
        var sb = new StringBuilder();

        sb.AppendLine("#nullable enable");
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine();

        sb.AppendLine("namespace CoffeeBeanery.GraphQL.Core.Runtime");
        sb.AppendLine("{");

        EmitEntityIds(sb, mappings);
        EmitStorageEntityIds(sb, mappings);
        EmitFieldIds(sb, mappings);
        EmitColumnIds(sb, mappings);

        sb.AppendLine("}");

        return sb.ToString();
    }

    public static string StripEntitySuffix(string entityTypeName)
    {
        const string suffix = "Entity";

        return entityTypeName.EndsWith(suffix, StringComparison.Ordinal)
            ? entityTypeName.Substring(0, entityTypeName.Length - suffix.Length)
            : entityTypeName;
    }

    private static void EmitEntityIds(
        StringBuilder sb,
        ImmutableArray<MappingClassInfo> mappings)
    {
        var entities =
            mappings
                .Where(x => x.ModelType != null)
                .Select(x => x.ModelType!.Name)
                .Distinct(StringComparer.OrdinalIgnoreCase)
                .OrderBy(x => x)
                .ToList();

        sb.AppendLine();
        sb.AppendLine("public static class EntityId");
        sb.AppendLine("{");

        ushort id = 0;

        foreach (var entity in entities)
        {
            sb.AppendLine($"    public const ushort {entity} = {id};");
            id++;
        }

        sb.AppendLine("}");
    }

    internal static IReadOnlyList<IPropertySymbol> GetScalarProperties(
        INamedTypeSymbol type)
    {
        return type
            .GetMembers()
            .OfType<IPropertySymbol>()
            .Where(IsScalarProperty)
            .ToList();
    }

    internal static bool IsScalarProperty(IPropertySymbol property)
    {
        if (property.IsStatic) return false;
        if (property.DeclaredAccessibility != Accessibility.Public) return false;

        var type = property.Type;

        if (type.TypeKind == TypeKind.Enum)
            return true;
        
        var namedType = type as INamedTypeSymbol;
        var underlying = namedType?.OriginalDefinition.SpecialType == SpecialType.System_Nullable_T
            ? namedType.TypeArguments[0]
            : type;

        if (underlying.ToDisplayString() == "System.Guid")
            return true;

        return type.SpecialType switch
        {
            SpecialType.System_String => true,
            SpecialType.System_Int32 => true,
            SpecialType.System_Int64 => true,
            SpecialType.System_Double => true,
            SpecialType.System_Decimal => true,
            SpecialType.System_Boolean => true,
            SpecialType.System_DateTime => true,
            _ => false
        };
    }
    
    internal static List<string> GetOrderedColumnNames(
        string entityName,
        ImmutableArray<MappingClassInfo> mappings)
    {
        return mappings
            .SelectMany(m => m.FieldMaps)
            .Where(f => string.Equals(f.DestinationEntity, entityName, StringComparison.OrdinalIgnoreCase))
            .Select(f => f.DestinationName)
            .Distinct(StringComparer.OrdinalIgnoreCase)
            .OrderBy(n => n, StringComparer.OrdinalIgnoreCase)
            .ToList();
    }

    internal static bool IsScalarProperty(
        INamedTypeSymbol type)
    {
        return GetScalarProperties(type).Count > 0;
    }

    private static void EmitStorageEntityIds(
        StringBuilder sb,
        ImmutableArray<MappingClassInfo> mappings)
    {
        var entities =
            mappings
                .SelectMany(x => x.Definition.Entities)
                .Where(x => x.EntityType != null)
                .Select(x => StripEntitySuffix(x.EntityType!.Name))
                .Distinct(StringComparer.OrdinalIgnoreCase)
                .OrderBy(x => x)
                .ToList();

        sb.AppendLine();
        sb.AppendLine("public static class StorageEntityId");
        sb.AppendLine("{");

        ushort id = 0;

        foreach (var entity in entities)
        {
            sb.AppendLine($"    public const ushort {entity} = {id};");
            id++;
        }

        sb.AppendLine("}");
    }

    private static void EmitFieldIds(
        StringBuilder sb,
        ImmutableArray<MappingClassInfo> mappings)
    {
        sb.AppendLine();
        sb.AppendLine("public static class FieldId");
        sb.AppendLine("{");

        foreach (var mapping in mappings
                     .Where(x => x.ModelType != null)
                     .OrderBy(x => x.ModelType!.Name))
        {
            var modelName = mapping.ModelType!.Name;

            sb.AppendLine($"    public static class {modelName}");
            sb.AppendLine("    {");

            ushort id = 0;

            foreach (var fieldName in GetResolvedFieldNames(mapping))
            {
                sb.AppendLine($"        public const ushort {fieldName} = {id};");
                id++;
            }

            sb.AppendLine("    }");
        }

        sb.AppendLine("}");
    }
    
    internal static IReadOnlyList<string> GetResolvedFieldNames(
        MappingClassInfo mapping)
    {
        var fields = new HashSet<string>(StringComparer.Ordinal);

        // Convention-discovered scalar properties
        foreach (var prop in GetScalarProperties(mapping.ModelType!))
        {
            fields.Add(prop.Name);
        }

        // Explicit/custom mapping fields
        foreach (var field in mapping.FieldMaps)
        {
            var name = FieldIdNameHelper.GetName(field);

            if (!string.IsNullOrWhiteSpace(name))
                fields.Add(name);
        }

        return fields
            .OrderBy(x => x, StringComparer.Ordinal)
            .ToList();
    }

    private static void EmitColumnIds(
        StringBuilder sb,
        ImmutableArray<MappingClassInfo> mappings)
    {
        sb.AppendLine();
        sb.AppendLine("public static class ColumnId");
        sb.AppendLine("{");

        var distinctEntities =
            mappings
                .SelectMany(m => m.Definition.Entities)
                .Where(e => e.EntityType != null)
                .Select(e => e.EntityType!)
                .Distinct(SymbolEqualityComparer.Default)
                .Cast<INamedTypeSymbol>()
                .OrderBy(e => e.Name)
                .ToList();

        var columnsByEntity =
            mappings
                .SelectMany(m => m.FieldMaps)
                .GroupBy(f => f.DestinationEntity)
                .ToDictionary(
                    g => g.Key,
                    g => g
                        .Select(f => f.DestinationName)
                        .Distinct(StringComparer.OrdinalIgnoreCase)
                        .OrderBy(n => n)
                        .ToList());

        foreach (var entityType in distinctEntities)
        {
            var entityName = entityType.Name;

            sb.AppendLine($"    public static class {entityName}");
            sb.AppendLine("    {");

            ushort id = 0;

            if (columnsByEntity.TryGetValue(entityName, out var columns))
            {
                foreach (var column in columns)
                {
                    sb.AppendLine($"        public const ushort {column} = {id};");
                    id++;
                }
            }

            sb.AppendLine("    }");
        }

        sb.AppendLine("}");
    }
}