using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using CoffeeBeanery.GraphQL.Core.Mapping.Generators.Model;
using CoffeeBeanery.GraphQL.Core.Mapping.Generators.Passes;
using Microsoft.CodeAnalysis;

namespace CoffeeBeanery.GraphQL.Core.Mapping.Generators.Emit;

internal static class IdEmitter
{
    public static string Emit(
        ImmutableArray<MappingClassInfo> mappings,
        List<FluentEntityNavigationConvention.EntityForeignKeyGraph.Edge> entityGraph)
    {
        var sb = new StringBuilder();

        sb.AppendLine("#nullable enable");
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine();

        sb.AppendLine("namespace CoffeeBeanery.GraphQL.Core.Runtime");
        sb.AppendLine("{");

        EmitEntityIds(sb, mappings);
        EmitStorageEntityIds(sb, mappings);
        EmitFieldIds(sb, mappings);
        EmitColumnIds(sb, mappings, entityGraph);

        sb.AppendLine("}");

        return sb.ToString();
    }
    
    internal static ushort GetFieldId(
        MappingClassInfo mapping,
        string fieldName)
    {
        var fields =
            GetResolvedFieldNames(mapping);

        for (ushort i = 0; i < fields.Count; i++)
        {
            if (string.Equals(
                    fields[(int)i],
                    fieldName,
                    StringComparison.OrdinalIgnoreCase))
            {
                return i;
            }
        }

        throw new InvalidOperationException(
            $"Unable to resolve FieldId for '{fieldName}' on '{mapping.ModelType?.Name}'.");
    }
    
    internal static ushort GetColumnId(
        ImmutableArray<MappingClassInfo> mappings,
        INamedTypeSymbol entityType,
        List<FluentEntityNavigationConvention.EntityForeignKeyGraph.Edge> entityGraph,
        string columnName)
    {
        var columns =
            GetFullColumnOrder(
                StripEntitySuffix(entityType.Name),
                mappings,
                entityType,
                entityGraph);

        for (ushort i = 0; i < columns.Count; i++)
        {
            if (string.Equals(
                    columns[(int)i],
                    columnName,
                    StringComparison.OrdinalIgnoreCase))
            {
                return i;
            }
        }

        throw new InvalidOperationException(
            $"Unable to resolve ColumnId for '{columnName}' on '{entityType.Name}'.");
    }

    public static string StripEntitySuffix(string entityTypeName)
    {
        const string suffix = "Entity";

        return entityTypeName.EndsWith(
            suffix,
            StringComparison.Ordinal)
            ? entityTypeName.Substring(
                0,
                entityTypeName.Length - suffix.Length)
            : entityTypeName;
    }

    private static void EmitEntityIds(
        StringBuilder sb,
        ImmutableArray<MappingClassInfo> mappings)
    {
        var entities =
            mappings
                .Where(x => x.ModelType != null)
                .Select(x => x.ModelType!.Name)
                .Distinct(StringComparer.Ordinal)
                .OrderBy(x => x, StringComparer.Ordinal)
                .ToList();

        sb.AppendLine();
        sb.AppendLine("public static class EntityId");
        sb.AppendLine("{");

        for (ushort id = 0; id < entities.Count; id++)
        {
            sb.AppendLine(
                $"    public const ushort {entities[id]} = {id};");
        }

        sb.AppendLine("}");
    }

    internal static IReadOnlyList<IPropertySymbol> GetScalarProperties(
        INamedTypeSymbol type)
    {
        return type
            .GetMembers()
            .OfType<IPropertySymbol>()
            .Where(IsScalarProperty)
            .ToList();
    }

    internal static bool IsScalarProperty(IPropertySymbol property)
    {
        if (property.IsStatic)
            return false;

        if (property.DeclaredAccessibility != Accessibility.Public)
            return false;

        var type = property.Type;

        var namedType = type as INamedTypeSymbol;

        var underlying =
            namedType?.OriginalDefinition.SpecialType == SpecialType.System_Nullable_T
                ? namedType.TypeArguments[0]
                : type;

        if (underlying.TypeKind == TypeKind.Enum)
            return true;

        if (underlying.ToDisplayString() == "System.Guid")
            return true;

        return underlying.SpecialType switch
        {
            SpecialType.System_String => true,
            SpecialType.System_Int32 => true,
            SpecialType.System_Int64 => true,
            SpecialType.System_Double => true,
            SpecialType.System_Decimal => true,
            SpecialType.System_Boolean => true,
            SpecialType.System_DateTime => true,
            _ => false
        };
    }

    /// <summary>
    /// Returns the primary-key scalar properties for an entity — typically
    /// just the surrogate "Id" property. Used both when computing ColumnId
    /// constants and when computing the runtime EntityColumnName array, so
    /// both MUST call GetFullColumnOrder (below) rather than duplicating
    /// this insertion logic independently.
    /// </summary>
    internal static List<IPropertySymbol> GetPrimaryKeyProperties(
        INamedTypeSymbol type)
    {
        var idProp = GetScalarProperties(type)
            .FirstOrDefault(p =>
                string.Equals(p.Name, "Id", StringComparison.Ordinal));

        return idProp != null
            ? new List<IPropertySymbol> { idProp }
            : new List<IPropertySymbol>();
    }

    internal static List<string> GetOrderedColumnNames(
        string entityName,
        ImmutableArray<MappingClassInfo> mappings)
    {
        return mappings
            .SelectMany(m => m.FieldMaps)
            .Where(f => string.Equals(f.DestinationEntity, entityName, StringComparison.OrdinalIgnoreCase))
            .Select(f => f.DestinationName)
            .Distinct(StringComparer.OrdinalIgnoreCase)
            .OrderBy(n => n, StringComparer.OrdinalIgnoreCase)
            .ToList();
    }

    /// <summary>
    /// Single source of truth for an entity's full column ordering:
    /// 1. FieldMaps-derived scalar columns (alphabetical)
    /// 2. Primary key column, inserted at index 0 if not already present
    /// 3. FK columns this entity owns as the DEPENDENT side of any edge in
    ///    entityGraph, appended if not already present — these are pure
    ///    relational plumbing columns (e.g. Transaction.AccountId,
    ///    Contract.CustomerBankingRelationshipId) that are never surfaced
    ///    as a GraphQL-facing scalar field, but ARE needed as real ColumnId
    ///    constants once join emission references them directly (e.g. for
    ///    composite-entity internal join chains).
    ///
    /// EmitColumnIds (numeric ColumnId.* constants) and
    /// EmitEntityColumnNameArray (the runtime string[] indexed by those
    /// constants) MUST both call this same method — computing the ordering
    /// independently in each place is exactly what caused ColumnId
    /// constants to disagree with the runtime name array previously.
    /// </summary>
    internal static List<string> GetFullColumnOrder(
        string entityName,
        ImmutableArray<MappingClassInfo> mappings,
        INamedTypeSymbol? entityType,
        List<FluentEntityNavigationConvention.EntityForeignKeyGraph.Edge>? entityGraph = null)
    {
        var columns = GetOrderedColumnNames(entityName, mappings);

        if (entityType != null)
        {
            var primaryKeys = GetPrimaryKeyProperties(entityType)
                .Select(x => x.Name)
                .ToList();

            foreach (var pk in primaryKeys)
            {
                if (!columns.Contains(pk, StringComparer.Ordinal))
                {
                    columns.Insert(0, pk);
                }
            }

            if (entityGraph != null)
            {
                var fkColumns = entityGraph
                    .Where(e => SymbolEqualityComparer.Default.Equals(e.DependentEntity, entityType))
                    .Select(e => e.DependentColumn)
                    .Distinct(StringComparer.Ordinal);

                foreach (var fkCol in fkColumns)
                {
                    if (!columns.Contains(fkCol, StringComparer.Ordinal))
                    {
                        columns.Add(fkCol);
                    }
                }
            }
        }

        return columns;
    }

    internal static bool IsScalarProperty(
        INamedTypeSymbol type)
    {
        return GetScalarProperties(type).Count > 0;
    }

    private static void EmitStorageEntityIds(
        StringBuilder sb,
        ImmutableArray<MappingClassInfo> mappings)
    {
        var entities =
            mappings
                .SelectMany(x => x.Definition.Entities)
                .Where(x => x.EntityType != null)
                .Select(x => StripEntitySuffix(x.EntityType!.Name))
                .Distinct(StringComparer.Ordinal)
                .OrderBy(x => x, StringComparer.Ordinal)
                .ToList();

        sb.AppendLine();
        sb.AppendLine("public static class StorageEntityId");
        sb.AppendLine("{");

        for (ushort id = 0; id < entities.Count; id++)
        {
            sb.AppendLine(
                $"    public const ushort {entities[id]} = {id};");
        }

        sb.AppendLine("}");
    }

    private static void EmitFieldIds(
        StringBuilder sb,
        ImmutableArray<MappingClassInfo> mappings)
    {
        sb.AppendLine();
        sb.AppendLine("public static class FieldId");
        sb.AppendLine("{");

        foreach (var mapping in mappings
                     .Where(x => x.ModelType != null)
                     .OrderBy(x => x.ModelType!.Name))
        {
            var modelName = mapping.ModelType!.Name;

            sb.AppendLine($"    public static class {modelName}");
            sb.AppendLine("    {");

            ushort id = 0;

            foreach (var fieldName in GetResolvedFieldNames(mapping))
            {
                sb.AppendLine($"        public const ushort {fieldName} = {id};");
                id++;
            }

            sb.AppendLine("    }");
        }

        sb.AppendLine("}");
    }

    internal static IReadOnlyList<string> GetResolvedFieldNames(
        MappingClassInfo mapping)
    {
        var fields = new HashSet<string>(StringComparer.Ordinal);

        foreach (var prop in GetScalarProperties(mapping.ModelType!))
        {
            fields.Add(prop.Name);
        }

        foreach (var field in mapping.FieldMaps)
        {
            var name = FieldIdNameHelper.GetName(field);

            if (!string.IsNullOrWhiteSpace(name))
                fields.Add(name);
        }

        return fields
            .OrderBy(x => x, StringComparer.Ordinal)
            .ToList();
    }

    private static void EmitColumnIds(
        StringBuilder sb,
        ImmutableArray<MappingClassInfo> mappings,
        List<FluentEntityNavigationConvention.EntityForeignKeyGraph.Edge> entityGraph)
    {
        sb.AppendLine();
        sb.AppendLine("public static class ColumnId");
        sb.AppendLine("{");

        var distinctEntities =
            mappings
                .SelectMany(m => m.Definition.Entities)
                .Where(e => e.EntityType != null)
                .Select(e => e.EntityType!)
                .Distinct(SymbolEqualityComparer.Default)
                .Cast<INamedTypeSymbol>()
                .OrderBy(e => e.Name)
                .ToList();

        foreach (var entityType in distinctEntities)
        {
            var strippedName = StripEntitySuffix(entityType.Name);

            var columns =
                GetFullColumnOrder(
                    strippedName,
                    mappings,
                    entityType,
                    entityGraph);

            sb.AppendLine($"    public static class {strippedName}");
            sb.AppendLine("    {");

            for (ushort id = 0; id < columns.Count; id++)
            {
                sb.AppendLine($"        public const ushort {columns[(int)id]} = {id};");
            }

            sb.AppendLine("    }");
        }

        sb.AppendLine("}");
    }
}