using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using CoffeeBeanery.GraphQL.Core.Mapping.Generators.Model;
using CoffeeBeanery.GraphQL.Core.Mapping.Generators.Passes;

namespace CoffeeBeanery.GraphQL.Core.Mapping.Generators.Emit
{
    internal static class MaterializerEmitter
    {
        private const string Sentinel = "ushort.MaxValue";

        public static string Emit(
            ImmutableArray<MappingClassInfo> allMappings,
            ImmutableHashSet<INamedTypeSymbol> rootEntityTypes,
            ImmutableDictionary<(INamedTypeSymbol, string), string> fluentInverseNav)
        {
            var models = allMappings
                .Where(m => m.IsModel)
                .OrderBy(m => m.ModelType.Name, System.StringComparer.Ordinal)
                .ToList();

            var entities = allMappings
                .SelectMany(m => m.Definition.Entities)
                .Select(k => k.EntityType)
                .Where(t => t is not null)
                .GroupBy(t => t!.Name, System.StringComparer.Ordinal)
                .Select(g => g.First()!)
                .OrderBy(t => t.Name, System.StringComparer.Ordinal)
                .ToList();

            var navResults = models.ToDictionary(
                m => m.ModelType.Name,
                m => EntityNavigationConvention.Resolve(m, rootEntityTypes, fluentInverseNav),
                System.StringComparer.Ordinal);

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("#nullable enable");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine("using System.Data;");
            sb.AppendLine("using System.Linq;");
            sb.AppendLine("using Domain.Model;");
            sb.AppendLine("using CoffeeBeanery.GraphQL.Core.Runtime;");
            sb.AppendLine();
            sb.AppendLine("namespace CoffeeBeanery.GraphQL.Core.Runtime");
            sb.AppendLine("{");

            sb.AppendLine("    public static class MaterializerRegistry");
            sb.AppendLine("    {");
            sb.AppendLine("        public static object? Materialize(ushort storageEntityId, IDataRecord record, ushort[] map)");
            sb.AppendLine("        {");
            sb.AppendLine("            switch (storageEntityId)");
            sb.AppendLine("            {");
            foreach (var entity in entities)
                sb.AppendLine($"                case StorageEntityId.{entity.Name}: return {entity.Name}Materializer.Materialize(record, map);");
            sb.AppendLine("                default: return null;");
            sb.AppendLine("            }");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine();

            sb.AppendLine("    public static class ResultBuilderRegistry");
            sb.AppendLine("    {");
            sb.AppendLine("        public static List<T> Build<T>(ushort entityId, RowLayout layout, List<object?[]> rows) where T : class");
            sb.AppendLine("        {");
            sb.AppendLine("            switch (entityId)");
            sb.AppendLine("            {");
            foreach (var model in models)
                sb.AppendLine($"                case EntityId.{model.ModelType.Name}: return (List<T>)(object){model.ModelType.Name}ResultBuilder.Build(layout, rows);");
            sb.AppendLine("                default: throw new global::System.InvalidOperationException($\"No result builder registered for entity {entityId}.\");");
            sb.AppendLine("            }");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine();

            foreach (var entity in entities)
                EmitEntityMaterializer(sb, entity);

            foreach (var model in models)
                EmitModelMapper(sb, model);

            foreach (var model in models)
            {
                var navResult = navResults.TryGetValue(model.ModelType.Name, out var r) ? r : null;
                EmitResultBuilder(sb, model, allMappings, models, navResult);
            }

            sb.AppendLine("}");
            return sb.ToString();
        }

        // ---------------------------------------------------------------
        // Entity materializer — map-based ordinal lookup
        // ---------------------------------------------------------------

        private static void EmitEntityMaterializer(StringBuilder sb, INamedTypeSymbol entityType)
        {
            var scalarProps = IdEmitter.GetScalarProperties(entityType);

            var pkProp = scalarProps.FirstOrDefault(p =>
                string.Equals(p.Name, "Id", System.StringComparison.Ordinal))
                ?? (scalarProps.Count > 0 ? scalarProps[0] : null);

            sb.AppendLine($"    public static class {entityType.Name}Materializer");
            sb.AppendLine("    {");
            sb.AppendLine($"        // map is indexed by ColumnId.{entityType.Name}.* constants.");
            sb.AppendLine($"        // Entries equal to ushort.MaxValue mean the column was not projected.");
            sb.AppendLine($"        public static Database.Entity.{entityType.Name}? Materialize(IDataRecord record, ushort[] map)");
            sb.AppendLine("        {");

            if (pkProp is not null)
            {
                sb.AppendLine($"            var pkOrdinal = map[ColumnId.{entityType.Name}.{pkProp.Name}];");
                sb.AppendLine($"            if (pkOrdinal == {Sentinel} || record.IsDBNull(pkOrdinal)) return null;");
                sb.AppendLine();
            }

            sb.AppendLine($"            var entity = new Database.Entity.{entityType.Name}();");

            foreach (var prop in scalarProps)
            {
                var ordinal = $"_o_{prop.Name}";
                sb.AppendLine($"            var {ordinal} = map[ColumnId.{entityType.Name}.{prop.Name}];");

                var type = prop.Type;
                var nullableType = type as INamedTypeSymbol;
                var underlying = nullableType?.OriginalDefinition.SpecialType == SpecialType.System_Nullable_T
                    ? nullableType.TypeArguments[0]
                    : type;

                if (underlying.TypeKind == TypeKind.Enum)
                {
                    // Nullable or non-nullable enum
                    var enumTypeName = underlying.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)
                                                 .Replace("global::", "");

                    if (underlying.Equals(type, SymbolEqualityComparer.Default))
                    {
                        // Non-nullable enum
                        sb.AppendLine(
                            $"            entity.{prop.Name} = {ordinal} == {Sentinel} ? default({enumTypeName}) : ({enumTypeName})record.GetInt32({ordinal});");
                    }
                    else
                    {
                        // Nullable enum
                        sb.AppendLine(
                            $"            entity.{prop.Name} = {ordinal} == {Sentinel} ? null : record.IsDBNull({ordinal}) ? null : ({enumTypeName})record.GetInt32({ordinal});");
                    }
                }
                else
                {
                    var accessExpr = BuildMapAccessor(prop, ordinal);
                    sb.AppendLine($"            entity.{prop.Name} = {accessExpr};");
                }
            }

            sb.AppendLine("            return entity;");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine();
        }

        private static string BuildMapAccessor(IPropertySymbol prop, string ordinalExpr)
        {
            var type = prop.Type;
            var isNullable = type.NullableAnnotation == NullableAnnotation.Annotated
                              || type.OriginalDefinition.SpecialType == SpecialType.System_Nullable_T;

            var defaultLiteral = isNullable ? "null" : $"default({type.ToDisplayString()})";

            var getter = type switch
            {
                { SpecialType: SpecialType.System_String }   => $"record.GetString({ordinalExpr})",
                { SpecialType: SpecialType.System_Int32 }    => $"record.GetInt32({ordinalExpr})",
                { SpecialType: SpecialType.System_Boolean }  => $"record.GetBoolean({ordinalExpr})",
                { SpecialType: SpecialType.System_DateTime } => $"record.GetDateTime({ordinalExpr})",
                { Name: "Guid" }                              => $"record.GetGuid({ordinalExpr})",
                { TypeKind: TypeKind.Enum }                   => $"({type.Name})record.GetInt32({ordinalExpr})",
                _ => $"({type.ToDisplayString()})record.GetValue({ordinalExpr})"
            };

            var readExpr = isNullable
                ? $"record.IsDBNull({ordinalExpr}) ? {defaultLiteral} : {getter}"
                : getter;

            return $"{ordinalExpr} == {Sentinel} ? {defaultLiteral} : {readExpr}";
        }

        // ---------------------------------------------------------------
        // Entity -> Model mapper
        // ---------------------------------------------------------------

        private static void EmitModelMapper(StringBuilder sb, MappingClassInfo model)
        {
            if (PlannerEmitter.IsCompositeInfo(model)) return;

            var entityType = model.EntityType
                ?? model.Definition.Entities.FirstOrDefault(k => k.IsPrimary)?.EntityType;
            if (entityType is null) return;

            var fields = PlannerEmitter.ComputeFieldMappingsEagerPublic(model, composite: false)
                .Where(f => string.Equals(f.EntityTypeName, entityType.Name, System.StringComparison.Ordinal))
                .ToList();

            sb.AppendLine($"    public static class {model.ModelType.Name}ModelMapper");
            sb.AppendLine("    {");
            sb.AppendLine($"        public static {model.ModelType.Name} FromEntity(Database.Entity.{entityType.Name} entity)");
            sb.AppendLine("        {");
            sb.AppendLine($"            var model = new {model.ModelType.Name}();");

            foreach (var fm in fields)
                sb.AppendLine($"            {BuildFieldAssignment(fm, model.ModelType, entityType, "entity", "model")}");

            sb.AppendLine("            return model;");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine();
        }

        // ---------------------------------------------------------------
        // Tree-assembly result builder
        // ---------------------------------------------------------------

        private static void EmitResultBuilder(
            StringBuilder sb,
            MappingClassInfo info,
            ImmutableArray<MappingClassInfo> allMappings,
            List<MappingClassInfo> models,
            NavigationResolutionResult? navResult)
        {
            var composite = PlannerEmitter.IsCompositeInfo(info);

            var primaryLink       = info.Definition.Entities.FirstOrDefault(k => k.IsPrimary);
            var primaryEntityName = primaryLink?.EntityType?.Name ?? info.EntityType?.Name;
            if (primaryEntityName is null) return;

            var primaryEntityType = primaryLink?.EntityType ?? info.EntityType;

            var childLinks = PlannerEmitter.ComputeChildLinks(info, allMappings, navResult).ToList();

            // Carry EntityType (INamedTypeSymbol) through the tuple so the
            // flatten-field path below can call BuildFieldAssignment without
            // needing a separate lookup dictionary.
            var fkNavAliases = info.Definition.Entities
                .Where(k => !k.IsPrimary && !string.IsNullOrWhiteSpace(k.AliasProperty))
                .Select(k =>
                {
                    var entityName   = k.EntityType!.Name;
                    var entitySymbol = k.EntityType!;
                    var relatedModel = allMappings.FirstOrDefault(m =>
                        m.IsModel &&
                        !PlannerEmitter.IsCompositeInfo(m) &&
                        string.Equals(m.EntityType?.Name, entityName, System.StringComparison.Ordinal));
                    return (
                        Alias:       k.AliasProperty!,
                        EntityName:  entityName,
                        EntityType:  entitySymbol,          // INamedTypeSymbol — for BuildFieldAssignment
                        ModelName:   relatedModel?.ModelType.Name ?? entityName);
                })
                .ToList();

            sb.AppendLine($"    public static class {info.ModelType.Name}ResultBuilder");
            sb.AppendLine("    {");
            sb.AppendLine($"        public static List<{info.ModelType.Name}> Build(RowLayout layout, List<object?[]> rows)");
            sb.AppendLine("        {");
            sb.AppendLine($"            var rootIdx = layout.IndexOf(\"{info.ModelType.Name}\");");
            sb.AppendLine("            if (rootIdx < 0) return new();");
            sb.AppendLine();
            sb.AppendLine("            var order    = new List<int>();");
            sb.AppendLine($"            var byRootId = new Dictionary<int, {info.ModelType.Name}>();");
            sb.AppendLine();

            foreach (var (alias, _, _, _) in fkNavAliases)
                sb.AppendLine($"            var {ToCamel(alias)}Idx = layout.IndexOf(\"{alias}\");");

            foreach (var link in childLinks)
                sb.AppendLine($"            var {ToCamel(link.NavigationName)}Idx = layout.IndexOf(\"{link.NavigationName}\");");

            sb.AppendLine();
            sb.AppendLine("            foreach (var row in rows)");
            sb.AppendLine("            {");
            sb.AppendLine($"                var rootEntity = (Database.Entity.{primaryEntityName}?)row[rootIdx];");
            sb.AppendLine("                if (rootEntity is null) continue;");
            sb.AppendLine();
            sb.AppendLine("                if (!byRootId.TryGetValue(rootEntity.Id, out var model))");
            sb.AppendLine("                {");
            sb.AppendLine($"                    model = new {info.ModelType.Name}();");

            var primaryFields = PlannerEmitter.ComputeFieldMappingsEagerPublic(info, composite: true)
                .Where(f => string.Equals(f.EntityTypeName, primaryEntityName, System.StringComparison.Ordinal))
                .ToList();

            foreach (var fm in primaryFields)
                sb.AppendLine($"                    {BuildFieldAssignment(fm, info.ModelType, primaryEntityType, "rootEntity", "model")}");

            sb.AppendLine("                    byRootId[rootEntity.Id] = model;");
            sb.AppendLine("                    order.Add(rootEntity.Id);");
            sb.AppendLine("                }");
            sb.AppendLine();

            foreach (var (alias, entityName, entityType, modelName) in fkNavAliases)
            {
                var camel = ToCamel(alias);

                sb.AppendLine($"                if ({camel}Idx >= 0 && model.{alias} is null)");
                sb.AppendLine("                {");
                sb.AppendLine($"                    var {camel} = (Database.Entity.{entityName}?)row[{camel}Idx];");
                sb.AppendLine($"                    if ({camel} is not null) model.{alias} = {modelName}ModelMapper.FromEntity({camel});");

                // Flatten-field path: scalars declared in Definition.Fields whose
                // EntityTypeName matches this FK-alias entity (e.g. InnerCustomerKey
                // ← InnerCustomer.CustomerKey). These live on the composite model
                // directly rather than through the nested object, so they are NOT
                // handled by primaryFields (wrong entity) or ModelMapper (wrong model).
                var flattenFields = PlannerEmitter.ComputeFieldMappingsEagerPublic(info, composite: true)
                    .Where(f => string.Equals(f.EntityTypeName, entityName,
                        System.StringComparison.Ordinal))
                    .ToList();

                foreach (var fm in flattenFields)
                    sb.AppendLine($"                    if ({camel} is not null) {BuildFieldAssignment(fm, info.ModelType, entityType, camel, "model")}");

                sb.AppendLine("                }");
                sb.AppendLine();
            }

            foreach (var link in childLinks)
            {
                var camel = ToCamel(link.NavigationName);
                if (link.IsCollection)
                {
                    sb.AppendLine($"                if ({camel}Idx >= 0)");
                    sb.AppendLine("                {");
                    sb.AppendLine($"                    var {camel} = (Database.Entity.{link.ChildEntityName}?)row[{camel}Idx];");
                    sb.AppendLine($"                    if ({camel} is not null)");
                    sb.AppendLine("                    {");
                    sb.AppendLine($"                        model.{link.NavigationName} ??= new();");
                    sb.AppendLine($"                        if (!model.{link.NavigationName}.Any(x => x.Id == {camel}.Id))");
                    sb.AppendLine($"                            model.{link.NavigationName}.Add({link.ChildModelName}ModelMapper.FromEntity({camel}));");
                    sb.AppendLine("                    }");
                    sb.AppendLine("                }");
                }
                else
                {
                    sb.AppendLine($"                if ({camel}Idx >= 0 && model.{link.NavigationName} is null)");
                    sb.AppendLine("                {");
                    sb.AppendLine($"                    var {camel} = (Database.Entity.{link.ChildEntityName}?)row[{camel}Idx];");
                    sb.AppendLine($"                    if ({camel} is not null) model.{link.NavigationName} = {link.ChildModelName}ModelMapper.FromEntity({camel});");
                    sb.AppendLine("                }");
                }
                sb.AppendLine();
            }

            sb.AppendLine("            }");
            sb.AppendLine();
            sb.AppendLine("            return order.Select(id => byRootId[id]).ToList();");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine();
        }

        // ---------------------------------------------------------------
        // Field assignment helpers
        // ---------------------------------------------------------------

        private static string BuildFieldAssignment(
            (string FieldName, string EntityTypeName, string ColumnName) fm,
            INamedTypeSymbol modelType,
            INamedTypeSymbol? entityType,
            string sourceVar,
            string targetVar)
        {
            var modelProp  = modelType.GetMembers().OfType<IPropertySymbol>()
                .FirstOrDefault(p => p.Name == fm.FieldName);
            var entityProp = entityType?.GetMembers().OfType<IPropertySymbol>()
                .FirstOrDefault(p => p.Name == fm.ColumnName);

            var sourceExpr = $"{sourceVar}.{fm.ColumnName}";
            if (modelProp is not null && entityProp is not null)
                sourceExpr = ConvertExpression(modelProp.Type, entityProp.Type, sourceExpr);

            return $"{targetVar}.{fm.FieldName} = {sourceExpr};";
        }

        private static string ConvertExpression(ITypeSymbol modelType, ITypeSymbol entityType, string expr)
        {
            var modelUnwrapped  = UnwrapNullable(modelType);
            var entityUnwrapped = UnwrapNullable(entityType);

            var entityIsNullable = !SymbolEqualityComparer.Default.Equals(entityType, entityUnwrapped);
            var modelIsNullable  = !SymbolEqualityComparer.Default.Equals(modelType, modelUnwrapped);
            var sameUnderlying   = SymbolEqualityComparer.Default.Equals(modelUnwrapped, entityUnwrapped);

            if (!sameUnderlying)
            {
                if (modelUnwrapped.TypeKind == TypeKind.Enum && entityUnwrapped.TypeKind == TypeKind.Enum)
                    return $"({modelType.ToDisplayString()}){expr}";

                if (modelUnwrapped.SpecialType == SpecialType.System_String && entityUnwrapped.Name == "Guid")
                    return entityIsNullable ? $"{expr}?.ToString()" : $"{expr}.ToString()";

                if (modelUnwrapped.Name == "Guid" && entityUnwrapped.SpecialType == SpecialType.System_String)
                {
                    return modelIsNullable
                        ? $"(string.IsNullOrEmpty({expr}) ? ({modelType.ToDisplayString()})null : global::System.Guid.Parse({expr}))"
                        : $"global::System.Guid.Parse({expr})";
                }

                return expr;
            }

            if (entityIsNullable && !modelIsNullable && modelUnwrapped.IsValueType)
                return $"{expr}.GetValueOrDefault()";

            return expr;
        }

        private static ITypeSymbol UnwrapNullable(ITypeSymbol type) =>
            type is INamedTypeSymbol { OriginalDefinition.SpecialType: SpecialType.System_Nullable_T } n
                ? n.TypeArguments[0]
                : type;

        private static string ToCamel(string name) =>
            string.IsNullOrEmpty(name) ? name : char.ToLowerInvariant(name[0]) + name.Substring(1);
    }
}