using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using CoffeeBeanery.GraphQL.Core.Mapping.Generators.Model;
using CoffeeBeanery.GraphQL.Core.Mapping.Generators.Passes;

namespace CoffeeBeanery.GraphQL.Core.Mapping.Generators.Emit
{
    internal static class MaterializerEmitter
    {
        // Sentinel value placed in the column map for columns that were not
        // projected by the current query. ushort.MaxValue (65535) is safe
        // because no real query will ever have 65535 result columns.
        private const string Sentinel = "ushort.MaxValue";

        public static string Emit(
            ImmutableArray<MappingClassInfo> allMappings,
            ImmutableHashSet<INamedTypeSymbol> rootEntityTypes,
            ImmutableDictionary<(INamedTypeSymbol, string), string> fluentInverseNav)
        {
            var models = allMappings
                .Where(m => m.IsModel)
                .OrderBy(m => m.ModelType.Name, System.StringComparer.Ordinal)
                .ToList();

            // NOTE: previously filtered on `m.IsEntity && m.EntityType is not null`,
            // which assumed a separate entity-side MappingClassInfo registration.
            // Under the current IMappingDefinition/Definition architecture there is
            // no such thing - every discovered MappingClassInfo is a model, and
            // IsEntity is never set to true by MappingClassParser. Filtering on it
            // silently produced an empty `entities` list (no compile error - the
            // MaterializerRegistry switch just had no cases and always fell through
            // to `return null`), which breaks every query at runtime with no build
            // failure to signal it. Instead, derive the distinct set of storage
            // entity types directly from every model's ModelToEntity links, which
            // is where entity types are actually declared now.
            var entities = allMappings
                .SelectMany(m => m.ModelToEntity)
                .Select(k => k.EntityType)
                .Where(t => t is not null)
                .GroupBy(t => t!.Name, System.StringComparer.Ordinal)
                .Select(g => g.First()!)
                .OrderBy(t => t.Name, System.StringComparer.Ordinal)
                .ToList();

            var navResults = models.ToDictionary(
                m => m.ModelType.Name,
                m => EntityNavigationConvention.Resolve(m, rootEntityTypes, fluentInverseNav),
                System.StringComparer.Ordinal);

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("#nullable enable");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine("using System.Data;");
            sb.AppendLine("using System.Linq;");
            sb.AppendLine("using Domain.Model;");
            sb.AppendLine("using CoffeeBeanery.GraphQL.Core.Runtime;");
            sb.AppendLine();
            sb.AppendLine("namespace CoffeeBeanery.GraphQL.Core.Runtime");
            sb.AppendLine("{");

            // ---------------------------------------------------------------
            // MaterializerRegistry
            // Signature changed: accepts ushort[] map instead of int ordinalStart.
            // The map is built by QueryPlan.BuildColumnMap(storageEntityId, columnCount)
            // and contains the result-set ordinal for each ColumnId constant,
            // or ushort.MaxValue (Sentinel) for columns that were not projected.
            // ---------------------------------------------------------------
            sb.AppendLine("    public static class MaterializerRegistry");
            sb.AppendLine("    {");
            sb.AppendLine("        public static object? Materialize(ushort storageEntityId, IDataRecord record, ushort[] map)");
            sb.AppendLine("        {");
            sb.AppendLine("            switch (storageEntityId)");
            sb.AppendLine("            {");
            foreach (var entity in entities)
                sb.AppendLine($"                case StorageEntityId.{entity.Name}: return {entity.Name}Materializer.Materialize(record, map);");
            sb.AppendLine("                default: return null;");
            sb.AppendLine("            }");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine();

            // ---------------------------------------------------------------
            // ResultBuilderRegistry — unchanged
            // ---------------------------------------------------------------
            sb.AppendLine("    public static class ResultBuilderRegistry");
            sb.AppendLine("    {");
            sb.AppendLine("        public static List<T> Build<T>(ushort entityId, RowLayout layout, List<object?[]> rows) where T : class");
            sb.AppendLine("        {");
            sb.AppendLine("            switch (entityId)");
            sb.AppendLine("            {");
            foreach (var model in models)
                sb.AppendLine($"                case EntityId.{model.ModelType.Name}: return (List<T>)(object){model.ModelType.Name}ResultBuilder.Build(layout, rows);");
            sb.AppendLine("                default: throw new global::System.InvalidOperationException($\"No result builder registered for entity {entityId}.\");");
            sb.AppendLine("            }");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine();

            foreach (var entity in entities)
                EmitEntityMaterializer(sb, entity);

            foreach (var model in models)
                EmitModelMapper(sb, model);

            foreach (var model in models)
            {
                var navResult = navResults.TryGetValue(model.ModelType.Name, out var r) ? r : null;
                EmitResultBuilder(sb, model, allMappings, models, navResult);
            }

            sb.AppendLine("}");
            return sb.ToString();
        }

        // ---------------------------------------------------------------
        // Column-reading materializer
        //
        // Old contract:  Materialize(IDataRecord record, int ordinalStart)
        //                reads record[ordinalStart + i] for each property i.
        //                BROKEN when query projects only a subset of columns.
        //
        // New contract:  Materialize(IDataRecord record, ushort[] map)
        //                map is indexed by ColumnId.{Entity}.{Prop} constant.
        //                map[colId] == ushort.MaxValue  → column not projected,
        //                                                 use default/null.
        //                map[colId] == N                → read record[N].
        //
        // The map is built once per entity per query execution by
        // QueryPlan.BuildColumnMap(storageEntityId, ColumnId.{Entity}.Count).
        // ---------------------------------------------------------------

        // Takes the storage entity's INamedTypeSymbol directly rather than a
        // MappingClassInfo — there is no separate entity-side MappingClassInfo
        // under the current architecture, and this method never needed anything
        // but the entity type itself.
        private static void EmitEntityMaterializer(StringBuilder sb, INamedTypeSymbol entityType)
        {
            var scalarProps = IdEmitter.GetScalarProperties(entityType);

            // Identify the PK column — used for NULL check on outer-joined rows.
            // Convention: prefer "Id" if present, otherwise first column.
            var pkProp = scalarProps.FirstOrDefault(p =>
                string.Equals(p.Name, "Id", System.StringComparison.Ordinal))
                ?? (scalarProps.Count > 0 ? scalarProps[0] : null);

            sb.AppendLine($"    public static class {entityType.Name}Materializer");
            sb.AppendLine("    {");
            sb.AppendLine($"        // map is indexed by ColumnId.{entityType.Name}.* constants.");
            sb.AppendLine($"        // Entries equal to ushort.MaxValue mean the column was not projected.");
            sb.AppendLine($"        public static Database.Entity.{entityType.Name}? Materialize(IDataRecord record, ushort[] map)");
            sb.AppendLine("        {");

            if (pkProp is not null)
            {
                // If the PK column was not projected or is NULL, this row belongs
                // to a LEFT JOIN that produced no match — return null.
                sb.AppendLine($"            var pkOrdinal = map[ColumnId.{entityType.Name}.{pkProp.Name}];");
                sb.AppendLine($"            if (pkOrdinal == {Sentinel} || record.IsDBNull(pkOrdinal)) return null;");
                sb.AppendLine();
            }

            sb.AppendLine($"            var entity = new Database.Entity.{entityType.Name}();");

            foreach (var prop in scalarProps)
            {
                var colIdExpr = $"ColumnId.{entityType.Name}.{prop.Name}";
                // Emit one local per property — evaluated exactly once
                sb.AppendLine($"            var _o_{prop.Name} = map[{colIdExpr}];");
                var accessExpr = BuildMapAccessor(prop, $"_o_{prop.Name}");
                sb.AppendLine($"            entity.{prop.Name} = {accessExpr};");
            }

            sb.AppendLine("            return entity;");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine();
        }

        /// <summary>
        /// Builds the read expression for one property when the result ordinal
        /// is held in <paramref name="ordinalExpr"/> (a map lookup).
        /// Emits: map[colId] == Sentinel ? default(T) : record.GetXxx(map[colId])
        /// For nullable types the sentinel branch returns null.
        /// </summary>
        private static string BuildMapAccessor(IPropertySymbol prop, string ordinalExpr)
        {
            var type = prop.Type;
            var isNullable = type.NullableAnnotation == NullableAnnotation.Annotated
                              || type.OriginalDefinition.SpecialType == SpecialType.System_Nullable_T;

            // We need to avoid evaluating ordinalExpr twice (it's a map indexer).
            // The generated code uses a helper method on the reader side instead —
            // emit a checked read that tests the sentinel inline.
            var defaultLiteral = isNullable ? "null" : $"default({type.ToDisplayString()})";

            var getter = type switch
            {
                { SpecialType: SpecialType.System_String }   => $"record.GetString({ordinalExpr})",
                { SpecialType: SpecialType.System_Int32 }    => $"record.GetInt32({ordinalExpr})",
                { SpecialType: SpecialType.System_Boolean }  => $"record.GetBoolean({ordinalExpr})",
                { SpecialType: SpecialType.System_DateTime } => $"record.GetDateTime({ordinalExpr})",
                { Name: "Guid" }                              => $"record.GetGuid({ordinalExpr})",
                { TypeKind: TypeKind.Enum }                   => $"({type.Name})record.GetInt32({ordinalExpr})",
                _ => $"({type.ToDisplayString()})record.GetValue({ordinalExpr})"
            };

            // Nullable types also need a DBNull guard even when the column was projected.
            var readExpr = isNullable
                ? $"record.IsDBNull({ordinalExpr}) ? {defaultLiteral} : {getter}"
                : getter;

            // Sentinel guard wraps everything: if column wasn't projected, skip.
            return $"{ordinalExpr} == {Sentinel} ? {defaultLiteral} : {readExpr}";
        }

        // ---------------------------------------------------------------
        // Entity -> Model mapper
        // ---------------------------------------------------------------

        private static void EmitModelMapper(StringBuilder sb, MappingClassInfo model)
        {
            if (PlannerEmitter.IsCompositeInfo(model)) return;

            // Fall back to deriving from ModelToEntity directly rather than only
            // trusting info.EntityType — keeps this resilient even if the parser's
            // EntityType derivation step is skipped or ordered differently.
            var entityType = model.EntityType
                ?? model.ModelToEntity.FirstOrDefault(k => k.IsPrimary)?.EntityType;
            if (entityType is null) return;

            var fields = PlannerEmitter.ComputeFieldMappingsEagerPublic(model, composite: false)
                .Where(f => string.Equals(f.EntityTypeName, entityType.Name, System.StringComparison.Ordinal))
                .ToList();

            sb.AppendLine($"    public static class {model.ModelType.Name}ModelMapper");
            sb.AppendLine("    {");
            sb.AppendLine($"        public static {model.ModelType.Name} FromEntity(Database.Entity.{entityType.Name} entity)");
            sb.AppendLine("        {");
            sb.AppendLine($"            var model = new {model.ModelType.Name}();");

            foreach (var fm in fields)
                sb.AppendLine($"            {BuildFieldAssignment(fm, model.ModelType, entityType, "entity", "model")}");

            sb.AppendLine("            return model;");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine();
        }

        // ---------------------------------------------------------------
        // Tree-assembly result builder
        // ---------------------------------------------------------------

        private static void EmitResultBuilder(
            StringBuilder sb,
            MappingClassInfo info,
            ImmutableArray<MappingClassInfo> allMappings,
            List<MappingClassInfo> models,
            NavigationResolutionResult? navResult)
        {
            var composite = PlannerEmitter.IsCompositeInfo(info);

            var primaryLink       = info.ModelToEntity.FirstOrDefault(k => k.IsPrimary);
            var primaryEntityName = primaryLink?.EntityType?.Name ?? info.EntityType?.Name;
            if (primaryEntityName is null) return;

            // Previously re-resolved primaryEntityType by searching allMappings for a
            // *separate* MappingClassInfo whose own EntityType matched by name — that
            // assumed an entity-side registration distinct from the model-side one,
            // which does not exist under the current IMappingDefinition architecture.
            // allMappings only ever contains model mappings now, so that lookup always
            // returned null, silently skipping the enum/Guid conversion logic in
            // ConvertExpression and producing unconverted (type-mismatched) assignments.
            // The correct entity type is already sitting on primaryLink itself.
            var primaryEntityType = primaryLink?.EntityType ?? info.EntityType;

            var childLinks = PlannerEmitter.ComputeChildLinks(info, allMappings, navResult).ToList();

            var fkNavAliases = info.ModelToEntity
                .Where(k => !k.IsPrimary && !string.IsNullOrWhiteSpace(k.AliasProperty))
                .Select(k =>
                {
                    var entityName  = k.EntityType!.Name;
                    var relatedModel = allMappings.FirstOrDefault(m =>
                        m.IsModel &&
                        !PlannerEmitter.IsCompositeInfo(m) &&
                        string.Equals(m.EntityType?.Name, entityName, System.StringComparison.Ordinal));
                    return (
                        Alias:     k.AliasProperty!,
                        EntityName: entityName,
                        ModelName: relatedModel?.ModelType.Name ?? entityName);
                })
                .ToList();

            sb.AppendLine($"    public static class {info.ModelType.Name}ResultBuilder");
            sb.AppendLine("    {");
            sb.AppendLine($"        public static List<{info.ModelType.Name}> Build(RowLayout layout, List<object?[]> rows)");
            sb.AppendLine("        {");
            sb.AppendLine($"            var rootIdx = layout.IndexOf(\"{info.ModelType.Name}\");");
            sb.AppendLine("            if (rootIdx < 0) return new();");
            sb.AppendLine();
            sb.AppendLine("            var order    = new List<int>();");
            sb.AppendLine($"            var byRootId = new Dictionary<int, {info.ModelType.Name}>();");
            sb.AppendLine();

            foreach (var (alias, _, _) in fkNavAliases)
                sb.AppendLine($"            var {ToCamel(alias)}Idx = layout.IndexOf(\"{alias}\");");

            foreach (var link in childLinks)
                sb.AppendLine($"            var {ToCamel(link.NavigationName)}Idx = layout.IndexOf(\"{link.NavigationName}\");");

            sb.AppendLine();
            sb.AppendLine("            foreach (var row in rows)");
            sb.AppendLine("            {");
            sb.AppendLine($"                var rootEntity = (Database.Entity.{primaryEntityName}?)row[rootIdx];");
            sb.AppendLine("                if (rootEntity is null) continue;");
            sb.AppendLine();
            sb.AppendLine("                if (!byRootId.TryGetValue(rootEntity.Id, out var model))");
            sb.AppendLine("                {");
            sb.AppendLine($"                    model = new {info.ModelType.Name}();");

            var primaryFields = PlannerEmitter.ComputeFieldMappingsEagerPublic(info, composite: true)
                .Where(f => string.Equals(f.EntityTypeName, primaryEntityName, System.StringComparison.Ordinal))
                .ToList();

            foreach (var fm in primaryFields)
                sb.AppendLine($"                    {BuildFieldAssignment(fm, info.ModelType, primaryEntityType, "rootEntity", "model")}");

            sb.AppendLine("                    byRootId[rootEntity.Id] = model;");
            sb.AppendLine("                    order.Add(rootEntity.Id);");
            sb.AppendLine("                }");
            sb.AppendLine();

            foreach (var (alias, entityName, modelName) in fkNavAliases)
            {
                var camel = ToCamel(alias);
                sb.AppendLine($"                if ({camel}Idx >= 0 && model.{alias} is null)");
                sb.AppendLine("                {");
                sb.AppendLine($"                    var {camel} = (Database.Entity.{entityName}?)row[{camel}Idx];");
                sb.AppendLine($"                    if ({camel} is not null) model.{alias} = {modelName}ModelMapper.FromEntity({camel});");
                sb.AppendLine("                }");
                sb.AppendLine();
            }

            foreach (var link in childLinks)
            {
                var camel = ToCamel(link.NavigationName);
                if (link.IsCollection)
                {
                    sb.AppendLine($"                if ({camel}Idx >= 0)");
                    sb.AppendLine("                {");
                    sb.AppendLine($"                    var {camel} = (Database.Entity.{link.ChildEntityName}?)row[{camel}Idx];");
                    sb.AppendLine($"                    if ({camel} is not null)");
                    sb.AppendLine("                    {");
                    sb.AppendLine($"                        model.{link.NavigationName} ??= new();");
                    sb.AppendLine($"                        if (!model.{link.NavigationName}.Any(x => x.Id == {camel}.Id))");
                    sb.AppendLine($"                            model.{link.NavigationName}.Add({link.ChildModelName}ModelMapper.FromEntity({camel}));");
                    sb.AppendLine("                    }");
                    sb.AppendLine("                }");
                }
                else
                {
                    sb.AppendLine($"                if ({camel}Idx >= 0 && model.{link.NavigationName} is null)");
                    sb.AppendLine("                {");
                    sb.AppendLine($"                    var {camel} = (Database.Entity.{link.ChildEntityName}?)row[{camel}Idx];");
                    sb.AppendLine($"                    if ({camel} is not null) model.{link.NavigationName} = {link.ChildModelName}ModelMapper.FromEntity({camel});");
                    sb.AppendLine("                }");
                }
                sb.AppendLine();
            }

            sb.AppendLine("            }");
            sb.AppendLine();
            sb.AppendLine("            return order.Select(id => byRootId[id]).ToList();");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine();
        }

        // ---------------------------------------------------------------
        // Field assignment helpers — unchanged from original
        // ---------------------------------------------------------------

        private static string BuildFieldAssignment(
            (string FieldName, string EntityTypeName, string ColumnName) fm,
            INamedTypeSymbol modelType,
            INamedTypeSymbol? entityType,
            string sourceVar,
            string targetVar)
        {
            var modelProp  = modelType.GetMembers().OfType<IPropertySymbol>()
                .FirstOrDefault(p => p.Name == fm.FieldName);
            var entityProp = entityType?.GetMembers().OfType<IPropertySymbol>()
                .FirstOrDefault(p => p.Name == fm.ColumnName);

            var sourceExpr = $"{sourceVar}.{fm.ColumnName}";
            if (modelProp is not null && entityProp is not null)
                sourceExpr = ConvertExpression(modelProp.Type, entityProp.Type, sourceExpr);

            return $"{targetVar}.{fm.FieldName} = {sourceExpr};";
        }

        private static string ConvertExpression(ITypeSymbol modelType, ITypeSymbol entityType, string expr)
        {
            var modelUnwrapped  = UnwrapNullable(modelType);
            var entityUnwrapped = UnwrapNullable(entityType);

            var entityIsNullable = !SymbolEqualityComparer.Default.Equals(entityType, entityUnwrapped);
            var modelIsNullable  = !SymbolEqualityComparer.Default.Equals(modelType, modelUnwrapped);
            var sameUnderlying   = SymbolEqualityComparer.Default.Equals(modelUnwrapped, entityUnwrapped);

            if (!sameUnderlying)
            {
                if (modelUnwrapped.TypeKind == TypeKind.Enum && entityUnwrapped.TypeKind == TypeKind.Enum)
                    return $"({modelType.ToDisplayString()}){expr}";

                if (modelUnwrapped.SpecialType == SpecialType.System_String && entityUnwrapped.Name == "Guid")
                    return entityIsNullable ? $"{expr}?.ToString()" : $"{expr}.ToString()";

                if (modelUnwrapped.Name == "Guid" && entityUnwrapped.SpecialType == SpecialType.System_String)
                {
                    return modelIsNullable
                        ? $"(string.IsNullOrEmpty({expr}) ? ({modelType.ToDisplayString()})null : global::System.Guid.Parse({expr}))"
                        : $"global::System.Guid.Parse({expr})";
                }

                return expr;
            }

            if (entityIsNullable && !modelIsNullable && modelUnwrapped.IsValueType)
                return $"{expr}.GetValueOrDefault()";

            return expr;
        }

        private static ITypeSymbol UnwrapNullable(ITypeSymbol type) =>
            type is INamedTypeSymbol { OriginalDefinition.SpecialType: SpecialType.System_Nullable_T } n
                ? n.TypeArguments[0]
                : type;

        private static string ToCamel(string name) =>
            string.IsNullOrEmpty(name) ? name : char.ToLowerInvariant(name[0]) + name.Substring(1);
    }
}