using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using CoffeeBeanery.GraphQL.Core.Mapping.Generators.Model;
using Microsoft.CodeAnalysis;

namespace CoffeeBeanery.GraphQL.Core.Mapping.Generators.Emit;

internal static class MaterializerEmitter
{
    public static string Emit(ImmutableArray<MappingClassInfo> mappings)
    {
        var sb = new StringBuilder();

        sb.AppendLine("#nullable enable");
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Immutable;");
        sb.AppendLine("using CoffeeBeanery.GraphQL.Core.Runtime;");
        sb.AppendLine("using Domain.Model;");
        sb.AppendLine();
        sb.AppendLine("namespace CoffeeBeanery.GraphQL.Core.Runtime;");
        sb.AppendLine();

        var models =
            mappings
                .Where(x => x.ModelType != null)
                .OrderBy(x => x.ModelType!.Name)
                .ToList();

        foreach (var info in models)
        {
            EmitMaterializer(sb, info);
            sb.AppendLine();

            EmitDematerializer(sb, info);
            sb.AppendLine();
        }

        EmitRegistries(sb, models);

        return sb.ToString();
    }


    private static void EmitMaterializer(
        StringBuilder sb,
        MappingClassInfo info)
    {
        var model = info.ModelType!.Name;

        sb.AppendLine($"public static class {model}Materializer");
        sb.AppendLine("{");

        sb.AppendLine(
            $"    public static {model} Materialize(in MutationIR node, MutationEntityMetadata metadata)");

        sb.AppendLine("    {");
        sb.AppendLine($"        var model = new {model}();");
        sb.AppendLine();

        sb.AppendLine("        foreach (var value in node.Values)");
        sb.AppendLine("        {");
        sb.AppendLine("            switch (value.FieldId)");
        sb.AppendLine("            {");

        foreach (var group in RelevantFieldsGrouped(info))
        {
            var representative = group.First();

            sb.AppendLine(
                $"                case FieldId.{model}.{FieldIdNameHelper.GetName(representative)}:");

            sb.AppendLine("                {");

            sb.AppendLine(
                $"                    model.{representative.SourceName} = {ConvertFromRaw(representative)};");

            sb.AppendLine("                    break;");
            sb.AppendLine("                }");
        }

        sb.AppendLine("            }");
        sb.AppendLine("        }");

        sb.AppendLine();
        sb.AppendLine("        return model;");
        sb.AppendLine("    }");
        sb.AppendLine("}");
    }


    private static void EmitDematerializer(StringBuilder sb, MappingClassInfo info)
    {
        var model = info.ModelType!.Name;

        sb.AppendLine($"public static class {model}Dematerializer");
        sb.AppendLine("{");
        sb.AppendLine($"    public static ImmutableArray<FieldValue> Dematerialize({model} model, MutationEntityMetadata metadata)");
        sb.AppendLine("    {");
        sb.AppendLine("        var builder = ImmutableArray.CreateBuilder<FieldValue>();");
        sb.AppendLine();

        var counter = 0;

        foreach (var group in RelevantFieldsGrouped(info))
        {
            var representative = group.First();

            var variable = $"rawValue{counter++}";

            sb.AppendLine($"        var {variable} = {ConvertToRaw(representative)};");
            sb.AppendLine();

            foreach (var field in group)
            {
                sb.AppendLine("        builder.Add(new FieldValue(");
                sb.AppendLine(
                    $"            FieldId.{model}.{FieldIdNameHelper.GetName(field)},");
                sb.AppendLine(
                    $"            ColumnId.{field.DestinationEntity}.{field.DestinationName},");
                sb.AppendLine(
                    $"            {variable} ?? string.Empty));");
                sb.AppendLine();
            }
        }

        sb.AppendLine("        return builder.ToImmutable();");
        sb.AppendLine("    }");
        sb.AppendLine("}");

    }


    private static bool IsNullableValueType(ITypeSymbol? type)
    {
        return type is INamedTypeSymbol named &&
               named.OriginalDefinition.SpecialType ==
               SpecialType.System_Nullable_T;
    }


    private static void EmitRegistries(
        StringBuilder sb,
        List<MappingClassInfo> models)
    {
        sb.AppendLine("public static class MutationMaterializerRegistry");
        sb.AppendLine("{");

        sb.AppendLine(
            "    public static object Materialize(ushort entityId, in MutationIR node, MutationEntityMetadata metadata)");

        sb.AppendLine("    {");
        sb.AppendLine("        switch (entityId)");
        sb.AppendLine("        {");

        foreach (var info in models)
        {
            var model = info.ModelType!.Name;

            sb.AppendLine($"            case EntityId.{model}:");
            sb.AppendLine(
                $"                return {model}Materializer.Materialize(node, metadata);");
        }

        sb.AppendLine("            default:");
        sb.AppendLine(
            "                throw new ArgumentException($\"Unknown entity runtime ID: {entityId}\");");

        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        sb.AppendLine();


        sb.AppendLine("public static class MutationDematerializerRegistry");
        sb.AppendLine("{");

        sb.AppendLine(
            "    public static ImmutableArray<FieldValue> Dematerialize(ushort entityId, object model, MutationEntityMetadata metadata)");

        sb.AppendLine("    {");
        sb.AppendLine("        switch (entityId)");
        sb.AppendLine("        {");

        foreach (var info in models)
        {
            var model = info.ModelType!.Name;

            sb.AppendLine($"            case EntityId.{model}:");

            sb.AppendLine(
                $"                return {model}Dematerializer.Dematerialize(({model})model, metadata);");
        }

        sb.AppendLine("            default:");

        sb.AppendLine(
            "                throw new ArgumentException($\"Unknown entity runtime ID: {entityId}\");");

        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");
    }


    private static IEnumerable<List<FieldInfo>> RelevantFieldsGrouped(
        MappingClassInfo info)
    {
        var fields =
            info.FieldMaps
                .Where(field =>
                    !(info.Graph != null &&
                    (
                        string.Equals(
                            field.SourceName,
                            info.Graph.From?.KeyColumn,
                            StringComparison.OrdinalIgnoreCase)

                        ||

                        string.Equals(
                            field.SourceName,
                            info.Graph.To?.KeyColumn,
                            StringComparison.OrdinalIgnoreCase)
                    )))
                .ToList();


        return fields
            .GroupBy(
                f => f.SourceName,
                StringComparer.Ordinal)
            .Select(g => g.ToList());
    }


    private static string ConvertFromRaw(FieldInfo field)
{
    var propertyType = field.PropertyType;

    if (propertyType == null)
        return "value.RawValue";

    var isNullable =
        propertyType is INamedTypeSymbol nullable &&
        nullable.OriginalDefinition.SpecialType ==
        SpecialType.System_Nullable_T;

    var underlying =
        isNullable
            ? ((INamedTypeSymbol)propertyType).TypeArguments[0]
            : propertyType;


    // enums
    if (underlying.TypeKind == TypeKind.Enum)
    {
        var enumName =
            underlying.ToDisplayString(
                SymbolDisplayFormat.FullyQualifiedFormat);

        return isNullable
            ? $"string.IsNullOrEmpty(value.RawValue) ? null : Enum.Parse<{enumName}>(value.RawValue, true)"
            : $"Enum.Parse<{enumName}>(value.RawValue!, true)";
    }


    // string
    if (underlying.SpecialType == SpecialType.System_String)
    {
        return "value.RawValue";
    }


    // Guid
    if (underlying.ToDisplayString() == "System.Guid")
    {
        return isNullable
            ? "Guid.TryParse(value.RawValue, out var guid) ? guid : null"
            : "Guid.Parse(value.RawValue!)";
    }


    // primitives
    switch (underlying.SpecialType)
    {
        case SpecialType.System_Int32:
            return isNullable
                ? "int.TryParse(value.RawValue, out var i) ? i : null"
                : "int.Parse(value.RawValue!)";


        case SpecialType.System_Int64:
            return isNullable
                ? "long.TryParse(value.RawValue, out var l) ? l : null"
                : "long.Parse(value.RawValue!)";


        case SpecialType.System_Decimal:
            return isNullable
                ? "decimal.TryParse(value.RawValue, out var d) ? d : null"
                : "decimal.Parse(value.RawValue!)";


        case SpecialType.System_Boolean:
            return isNullable
                ? "bool.TryParse(value.RawValue, out var b) ? b : null"
                : "bool.Parse(value.RawValue!)";


        case SpecialType.System_Double:
            return isNullable
                ? "double.TryParse(value.RawValue, out var dbl) ? dbl : null"
                : "double.Parse(value.RawValue!)";
    }


    // fallback for unknown structs/classes
    return $"({propertyType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)})value.RawValue";
}


    private static string ConvertToRaw(FieldInfo field)
    {
        var type = field.PropertyType;

        if (type == null)
            return $"model.{field.SourceName}?.ToString()";


        if (type.IsReferenceType ||
            IsNullableValueType(type))
        {
            return $"model.{field.SourceName}?.ToString()";
        }


        return $"model.{field.SourceName}.ToString()";
    }
}