using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using CoffeeBeanery.GraphQL.Core.Mapping.Generators.Emit;
using CoffeeBeanery.GraphQL.Core.Mapping.Generators.Model;
using CoffeeBeanery.GraphQL.Core.Mapping.Generators.Passes;
using Microsoft.CodeAnalysis;

internal static class MetadataEmitter
{
    public static string Emit(
        ImmutableArray<MappingClassInfo> allMappings,
        ImmutableHashSet<INamedTypeSymbol> rootEntityTypes,
        ImmutableDictionary<(INamedTypeSymbol, string), string> fluentInverseNav)
    {
        var models = allMappings
            .Where(m => m.IsModel)
            .OrderBy(m => m.ModelType.Name)
            .ToList();

        // Populate CteUpdateMeta before any emit — required for Table, ColumnName, CteResolutions
        foreach (var m in models)
        {
            if (m.CteUpdateMeta.Count > 0) continue;

            var navResult = EntityNavigationConvention.ResolveQuietly(
                m, rootEntityTypes, fluentInverseNav);

            PopulateCteUpdateMeta(m, navResult);
        }

        // All unique storage entity types — same logic as IdEmitter
        var entityTypes = allMappings
            .SelectMany(m =>
            {
                var types = new List<Microsoft.CodeAnalysis.INamedTypeSymbol>();
                if (m.EntityType is not null) types.Add(m.EntityType);
                foreach (var link in m.ModelToEntity)
                    if (link.EntityType is not null) types.Add(link.EntityType);
                return types;
            })
            .GroupBy(e => e.Name, System.StringComparer.Ordinal)
            .Select(g => g.First())
            .OrderBy(e => e.Name, System.StringComparer.Ordinal)
            .ToList();

        // Build a schema lookup: entityTypeName → schema
        // Derived from mappings that have a matching EntityType
        var entitySchemaLookup = allMappings
            .Where(m => m.EntityType is not null && !string.IsNullOrEmpty(m.Schema))
            .GroupBy(m => m.EntityType!.Name, System.StringComparer.Ordinal)
            .ToDictionary(g => g.Key, g => g.First().Schema, System.StringComparer.Ordinal);

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System;");
        sb.AppendLine();
        sb.AppendLine("namespace CoffeeBeanery.GraphQL.Core.Runtime");
        sb.AppendLine("{");
        sb.AppendLine("    public static class EntityMeta");
        sb.AppendLine("    {");

        EmitModelNameArray(sb, models);
        EmitTableArray(sb, models);
        EmitSchemaArray(sb, models);
        EmitColumnNameArray(sb, models);
        EmitFieldNameArray(sb, models);
        EmitConflictColumnsArray(sb, models);
        EmitCteResolutionsArray(sb, models);
        EmitEntitySchemaArray(sb, entityTypes, entitySchemaLookup, models);
        EmitEntityTableArray(sb, entityTypes);
        EmitEntityColumnNameArray(sb, entityTypes);

        sb.AppendLine("    }");
        sb.AppendLine("}");
        sb.AppendLine();

        EmitStorageEntityIdConstants(sb, entityTypes);
        EmitGeneratedEntityMetaProvider(sb);
        EmitGeneratedPlannerRegistry(sb);

        return sb.ToString();
    }
    
    private static void PopulateCteUpdateMeta(
        MappingClassInfo info,
        NavigationResolutionResult navResult)
    {
        var fkNavs = navResult.Navigations
            .Where(n => !n.IsCollection && !string.IsNullOrWhiteSpace(n.ForeignKeyProperty))
            .ToList();

        if (fkNavs.Count == 0) return;

        var primaryEntry = info.ModelToEntity.FirstOrDefault(k => k.IsPrimary);
        if (primaryEntry is null || string.IsNullOrWhiteSpace(primaryEntry.ToColumn)) return;

        var aliasToNaturalKey = info.ModelToEntity
            .Where(k => k.AliasProperty != null && !string.IsNullOrWhiteSpace(k.ToColumn))
            .ToDictionary(k => k.AliasProperty!, k => k);

        foreach (var nav in fkNavs)
        {
            if (!aliasToNaturalKey.TryGetValue(nav.NavigationName, out var naturalKeyInfo))
                continue;

            if (info.CteUpdateMeta.Any(c => c.NavigationAlias == nav.NavigationName))
                continue;

            info.CteUpdateMeta.Add(new CteUpdateMetaInfo
            {
                NavigationAlias          = nav.NavigationName,
                ForeignKeyColumn         = nav.ForeignKeyProperty,
                OwningPrimaryKeyColumn   = primaryEntry.ToColumn!,
                RelatedEntityTypeName    = nav.RelatedEntityType.Name,
                RelatedSurrogateIdColumn = nav.PrincipalKeyProperty,
                RelatedNaturalKeyColumn  = naturalKeyInfo.ToColumn!
            });
        }
    }
    
    private static void EmitStorageEntityIdConstants(
        StringBuilder sb,
        List<Microsoft.CodeAnalysis.INamedTypeSymbol> entityTypes)
    {
        sb.AppendLine("namespace CoffeeBeanery.GraphQL.Core.Runtime");
        sb.AppendLine("{");
        sb.AppendLine("    public static class StorageEntityId");
        sb.AppendLine("    {");

        for (int i = 0; i < entityTypes.Count; i++)
        {
            sb.AppendLine(
                $"        public const ushort {entityTypes[i].Name} = {i};");
        }

        sb.AppendLine();
        sb.AppendLine($"        public const ushort Count = {entityTypes.Count};");

        sb.AppendLine("    }");
        sb.AppendLine("}");
        sb.AppendLine();
    }

    // ---------------------------------------------------------------
    // Model-keyed arrays
    // ---------------------------------------------------------------

    private static void EmitSchemaArray(StringBuilder sb, List<MappingClassInfo> models)
    {
        sb.AppendLine($"        public static readonly string[] Schema = new string[{models.Count}]");
        sb.AppendLine("        {");
        foreach (var m in models)
            sb.AppendLine($"            \"{m.Schema ?? ""}\",");
        sb.AppendLine("        };");
        sb.AppendLine();
    }

    private static void EmitModelNameArray(StringBuilder sb, List<MappingClassInfo> models)
    {
        sb.AppendLine($"        public static readonly string[][] ModelName = new string[{models.Count}][]");
        sb.AppendLine("        {");

        foreach (var m in models)
        {
            var navAliases = m.CteUpdateMeta
                .Select(c => c.NavigationAlias)
                .Distinct()
                .ToList();

            if (navAliases.Count == 0)
                sb.AppendLine($"            new string[] {{ \"{m.ModelType.Name}\" }},");
            else
                sb.AppendLine($"            new string[] {{ \"{m.ModelType.Name}\", {string.Join(", ", navAliases.Select(a => $"\"{a}\""))} }},");
        }

        sb.AppendLine("        };");
        sb.AppendLine();
    }

    private static void EmitTableArray(StringBuilder sb, List<MappingClassInfo> models)
    {
        sb.AppendLine($"        public static readonly string[][] Table = new string[{models.Count}][]");
        sb.AppendLine("        {");

        foreach (var m in models)
        {
            string dbTable;
            if (IsComposite(m))
            {
                var primaryEntity = m.ModelToEntity.FirstOrDefault(k => k.IsPrimary);
                dbTable = primaryEntity?.EntityType.Name ?? m.ModelType.Name;
            }
            else
            {
                dbTable = m.EntityType?.Name ?? m.ModelType.Name;
            }

            var navAliases = m.CteUpdateMeta
                .Select(c => c.NavigationAlias)
                .Distinct()
                .ToList();

            if (navAliases.Count == 0)
                sb.AppendLine($"            new string[] {{ \"{dbTable}\" }},");
            else
                sb.AppendLine($"            new string[] {{ \"{dbTable}\", {string.Join(", ", navAliases.Select(a => $"\"{a}\""))} }},");
        }

        sb.AppendLine("        };");
        sb.AppendLine();
    }

    private static void EmitColumnNameArray(StringBuilder sb, List<MappingClassInfo> models)
    {
        sb.AppendLine($"        public static readonly string[][] ColumnName = new string[{models.Count}][]");
        sb.AppendLine("        {");

        foreach (var m in models)
        {
            INamedTypeSymbol typeForColumns;

            if (IsComposite(m))
            {
                var primaryEntity = m.ModelToEntity.FirstOrDefault(k => k.IsPrimary);
                typeForColumns = primaryEntity?.EntityType ?? m.ModelType;
            }
            else
            {
                typeForColumns = m.EntityType ?? m.ModelType;
            }

            var cols = IdEmitter.GetScalarProperties(typeForColumns);
            sb.AppendLine($"            new string[{cols.Count}]");
            sb.AppendLine("            {");
            foreach (var c in cols)
                sb.AppendLine($"                \"{c.Name}\",");
            sb.AppendLine("            },");
        }

        sb.AppendLine("        };");
        sb.AppendLine();
    }

    private static bool IsComposite(MappingClassInfo info) =>
        info.ModelToEntity
            .Select(k => k.EntityType.Name)
            .Distinct(System.StringComparer.Ordinal)
            .Count() > 1;

    private static void EmitFieldNameArray(StringBuilder sb, List<MappingClassInfo> models)
    {
        sb.AppendLine($"        public static readonly string[][] FieldName = new string[{models.Count}][]");
        sb.AppendLine("        {");
        foreach (var m in models)
        {
            var cols = IdEmitter.GetScalarProperties(m.ModelType);
            sb.AppendLine($"            new string[{cols.Count}]");
            sb.AppendLine("            {");
            foreach (var c in cols)
            {
                var camel = char.ToLowerInvariant(c.Name[0]) + c.Name.Substring(1);
                sb.AppendLine($"                \"{camel}\",");
            }
            sb.AppendLine("            },");
        }
        sb.AppendLine("        };");
        sb.AppendLine();
    }

    private static void EmitConflictColumnsArray(StringBuilder sb, List<MappingClassInfo> models)
    {
        sb.AppendLine($"        public static readonly string[][] ConflictColumns = new string[{models.Count}][]");
        sb.AppendLine("        {");
        foreach (var m in models)
        {
            var keys = m.UpsertKeys
                .Where(k => !string.IsNullOrWhiteSpace(k.Key))
                .Select(k => k.Key)
                .Distinct(System.StringComparer.OrdinalIgnoreCase)
                .ToList();

            if (keys.Count == 0)
            {
                keys = m.ModelToEntity
                    .Where(k => k.IsPrimary && !string.IsNullOrWhiteSpace(k.ToColumn))
                    .Select(k => k.ToColumn!)
                    .Distinct(System.StringComparer.OrdinalIgnoreCase)
                    .ToList();
            }

            if (keys.Count == 0)
                sb.AppendLine("            System.Array.Empty<string>(),");
            else
                sb.AppendLine($"            new string[] {{ {string.Join(", ", keys.Select(p => $"\"{p}\""))} }},");
        }
        sb.AppendLine("        };");
        sb.AppendLine();
    }

    private static void EmitCteResolutionsArray(StringBuilder sb, List<MappingClassInfo> models)
    {
        sb.AppendLine($"        public static readonly global::CoffeeBeanery.GraphQL.Core.Runtime.CteResolutionSpec[][] CteResolutions = new global::CoffeeBeanery.GraphQL.Core.Runtime.CteResolutionSpec[{models.Count}][]");
        sb.AppendLine("        {");
        foreach (var m in models)
        {
            if (m.CteUpdateMeta.Count == 0)
            {
                sb.AppendLine("            System.Array.Empty<global::CoffeeBeanery.GraphQL.Core.Runtime.CteResolutionSpec>(),");
                continue;
            }

            var entityCols = IdEmitter.GetScalarProperties(m.EntityType ?? m.ModelType)
                .Select((c, i) => (c.Name, Index: (ushort)i))
                .ToDictionary(x => x.Name, x => x.Index, System.StringComparer.OrdinalIgnoreCase);

            sb.AppendLine("            new global::CoffeeBeanery.GraphQL.Core.Runtime.CteResolutionSpec[]");
            sb.AppendLine("            {");
            foreach (var cte in m.CteUpdateMeta)
            {
                entityCols.TryGetValue(cte.OwningPrimaryKeyColumn, out var pkFieldId);
                var tableAlias = cte.NavigationAlias + cte.RelatedEntityTypeName;
                sb.AppendLine("                new global::CoffeeBeanery.GraphQL.Core.Runtime.CteResolutionSpec(");
                sb.AppendLine($"                    \"{cte.NavigationAlias}\",");
                sb.AppendLine($"                    \"{cte.ForeignKeyColumn}\",");
                sb.AppendLine($"                    \"{cte.OwningPrimaryKeyColumn}\",");
                sb.AppendLine($"                    {pkFieldId},");
                sb.AppendLine($"                    \"{tableAlias}\",");
                sb.AppendLine($"                    \"{cte.RelatedSurrogateIdColumn}\",");
                sb.AppendLine($"                    \"{cte.RelatedNaturalKeyColumn}\"");
                sb.AppendLine("                ),");
            }
            sb.AppendLine("            },");
        }
        sb.AppendLine("        };");
        sb.AppendLine();
    }

    // ---------------------------------------------------------------
    // Storage-entity-keyed arrays (indexed by StorageEntityId.*)
    // ---------------------------------------------------------------

    private static void EmitEntitySchemaArray(
        StringBuilder sb,
        List<Microsoft.CodeAnalysis.INamedTypeSymbol> entityTypes,
        Dictionary<string, string> entitySchemaLookup,
        List<MappingClassInfo> models)
    {
        sb.AppendLine($"        /// <summary>Indexed by StorageEntityId.*</summary>");
        sb.AppendLine($"        public static readonly string[] EntitySchema = new string[{entityTypes.Count}]");
        sb.AppendLine("        {");
        foreach (var e in entityTypes)
        {
            // Look up schema from mappings that reference this entity
            var schema = entitySchemaLookup.TryGetValue(e.Name, out var s) ? s : "";

            // Also check if any model's ModelToEntity links reference this entity with a schema
            if (string.IsNullOrEmpty(schema))
            {
                foreach (var m in models)
                {
                    var link = m.ModelToEntity.FirstOrDefault(l =>
                        string.Equals(l.EntityType?.Name, e.Name, System.StringComparison.Ordinal));
                    if (link is not null && !string.IsNullOrEmpty(m.Schema))
                    {
                        schema = m.Schema;
                        break;
                    }
                }
            }

            sb.AppendLine($"            \"{schema}\",");
        }
        sb.AppendLine("        };");
        sb.AppendLine();
    }

    private static void EmitEntityTableArray(
        StringBuilder sb,
        List<Microsoft.CodeAnalysis.INamedTypeSymbol> entityTypes)
    {
        sb.AppendLine($"        /// <summary>Indexed by StorageEntityId.*</summary>");
        sb.AppendLine($"        public static readonly string[] EntityTable = new string[{entityTypes.Count}]");
        sb.AppendLine("        {");
        foreach (var e in entityTypes)
            sb.AppendLine($"            \"{e.Name}\",");
        sb.AppendLine("        };");
        sb.AppendLine();
    }

    private static void EmitEntityColumnNameArray(
        StringBuilder sb,
        List<Microsoft.CodeAnalysis.INamedTypeSymbol> entityTypes)
    {
        sb.AppendLine($"        /// <summary>Indexed by StorageEntityId.* then ColumnId.{{EntityName}}.*</summary>");
        sb.AppendLine($"        public static readonly string[][] EntityColumnName = new string[{entityTypes.Count}][]");
        sb.AppendLine("        {");
        foreach (var e in entityTypes)
        {
            var cols = IdEmitter.GetScalarProperties(e);
            sb.AppendLine($"            new string[{cols.Count}]");
            sb.AppendLine("            {");
            foreach (var c in cols)
                sb.AppendLine($"                \"{c.Name}\",");
            sb.AppendLine("            },");
        }
        sb.AppendLine("        };");
        sb.AppendLine();
    }

    // ---------------------------------------------------------------
    // GeneratedEntityMetaProvider
    // ---------------------------------------------------------------

    private static void EmitGeneratedEntityMetaProvider(StringBuilder sb)
    {
        sb.AppendLine("namespace CoffeeBeanery.GraphQL.Core.Runtime");
        sb.AppendLine("{");
        sb.AppendLine("    public sealed class GeneratedEntityMetaProvider : global::CoffeeBeanery.GraphQL.Core.Runtime.IEntityMetaProvider");
        sb.AppendLine("    {");
        sb.AppendLine("        public int Count               => EntityMeta.Table.Length;");
        sb.AppendLine("        public string[][] ModelName    => EntityMeta.ModelName;");
        sb.AppendLine("        public string[][] Table        => EntityMeta.Table;");
        sb.AppendLine("        public string[] Schema         => EntityMeta.Schema;");
        sb.AppendLine("        public string[][] ColumnName   => EntityMeta.ColumnName;");
        sb.AppendLine("        public string[][] FieldName    => EntityMeta.FieldName;");
        sb.AppendLine("        public string[][] ConflictColumns   => EntityMeta.ConflictColumns;");
        sb.AppendLine("        public CteResolutionSpec[][] CteResolutions => EntityMeta.CteResolutions;");
        sb.AppendLine("        public int StorageEntityCount          => EntityMeta.EntityTable.Length;");
        sb.AppendLine("        public string[] EntitySchema           => EntityMeta.EntitySchema;");
        sb.AppendLine("        public string[] EntityTable            => EntityMeta.EntityTable;");
        sb.AppendLine("        public string[][] EntityColumnName     => EntityMeta.EntityColumnName;");
        sb.AppendLine();
        sb.AppendLine("        public bool TryGetEntityId(string modelName, out ushort entityId)");
        sb.AppendLine("        {");
        sb.AppendLine("            for (ushort i = 0; i < EntityMeta.Table.Length; i++)");
        sb.AppendLine("            {");
        sb.AppendLine("                if (global::System.StringComparer.OrdinalIgnoreCase.Equals(EntityMeta.Table[i][0], modelName))");
        sb.AppendLine("                {");
        sb.AppendLine("                    entityId = i;");
        sb.AppendLine("                    return true;");
        sb.AppendLine("                }");
        sb.AppendLine("            }");
        sb.AppendLine("            entityId = 0;");
        sb.AppendLine("            return false;");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        sb.AppendLine();
    }

    // ---------------------------------------------------------------
    // GeneratedPlannerRegistry
    // ---------------------------------------------------------------

    private static void EmitGeneratedPlannerRegistry(StringBuilder sb)
    {
        sb.AppendLine("namespace CoffeeBeanery.GraphQL.Core.Runtime");
        sb.AppendLine("{");
        sb.AppendLine("    public sealed class GeneratedPlannerRegistry : global::CoffeeBeanery.GraphQL.Core.Runtime.IPlannerRegistry");
        sb.AppendLine("    {");
        sb.AppendLine("        public void Build(");
        sb.AppendLine("            ushort entityId,");
        sb.AppendLine("            in global::CoffeeBeanery.GraphQL.Core.Runtime.SelectionIR selection,");
        sb.AppendLine("            ref global::CoffeeBeanery.GraphQL.Core.Runtime.QueryPlanBuilder builder)");
        sb.AppendLine("            => PlannerRegistry.Build(entityId, selection, ref builder);");
        sb.AppendLine();
        sb.AppendLine("        public void BuildMutation(");
        sb.AppendLine("            ushort entityId,");
        sb.AppendLine("            in global::CoffeeBeanery.GraphQL.Core.Runtime.MutationIR mutation,");
        sb.AppendLine("            ref global::CoffeeBeanery.GraphQL.Core.Runtime.MutationPlanBuilder builder)");
        sb.AppendLine("            => PlannerRegistry.BuildMutation(entityId, mutation, ref builder);");
        sb.AppendLine();
        sb.AppendLine("        public bool IsValidEntity(ushort entityId)");
        sb.AppendLine("            => PlannerRegistry.IsValidEntity(entityId);");
        sb.AppendLine();
        sb.AppendLine("        public string GetEntityName(ushort entityId)");
        sb.AppendLine("            => PlannerRegistry.GetEntityName(entityId);");
        sb.AppendLine("    }");
        sb.AppendLine("}");
    }
}