using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using CoffeeBeanery.GraphQL.Core.Mapping.Generators.Model;
using CoffeeBeanery.GraphQL.Core.Mapping.Generators.Passes;
using Microsoft.CodeAnalysis;

namespace CoffeeBeanery.GraphQL.Core.Mapping.Generators.Emit;

internal static class MutationMetadataEmitter
{
    private sealed record GraphEdgeCteResolution(
        string NavigationAlias,
        string ForeignKeyColumn,
        string OwningPrimaryKeyColumn,
        string RelatedEntityTypeName,
        string RelatedSurrogateIdColumn,
        string RelatedNaturalKeyColumn);
    
    public static string Emit(
    ImmutableArray<MappingClassInfo> allMappings,
    ImmutableHashSet<INamedTypeSymbol> rootEntityTypes,
    List<FluentEntityNavigationConvention.EntityForeignKeyGraph.Edge> entityGraph)
{
    var models =
        allMappings
            .Where(x => x.ModelType != null)
            .OrderBy(x => x.ModelType!.Name)
            .ToList();


    foreach (var m in models)
    {
        if (m.CteUpdateMeta.Count > 0)
            continue;


        if (m.Graph != null)
        {
            var resolutions =
                BuildGraphEdgeCteResolutions(m);


            foreach (var resolution in resolutions)
            {
                m.CteUpdateMeta.Add(
                    new CteUpdateMetaInfo
                    {
                        NavigationAlias =
                            resolution.NavigationAlias,

                        ForeignKeyColumn =
                            resolution.ForeignKeyColumn,

                        OwningPrimaryKeyColumn =
                            resolution.OwningPrimaryKeyColumn,

                        RelatedEntityTypeName =
                            resolution.RelatedEntityTypeName,

                        RelatedSurrogateIdColumn =
                            resolution.RelatedSurrogateIdColumn,

                        RelatedNaturalKeyColumn =
                            resolution.RelatedNaturalKeyColumn
                    });
            }


            continue;
        }


        var navResult =
            EntityNavigationConvention.Resolve(
                m,
                allMappings,
                entityGraph,
                rootEntityTypes);


        MetadataEmitter.PopulateCteUpdateMeta(
            m,
            navResult);
    }


    var sb =
        new StringBuilder();


    sb.AppendLine("#nullable enable");
    sb.AppendLine("// <auto-generated/>");
    sb.AppendLine();

    sb.AppendLine("using System;");
    sb.AppendLine("using System.Collections.Generic;");
    sb.AppendLine("using System.Collections.Immutable;");
    sb.AppendLine();

    sb.AppendLine(
        "namespace CoffeeBeanery.GraphQL.Core.Runtime;");

    sb.AppendLine();


    sb.AppendLine(
        "public static class MutationMetadataRegistry");

    sb.AppendLine("{");


    sb.AppendLine(
        "    private static readonly ImmutableDictionary<ushort, MutationEntityMetadata> _entities =");

    sb.AppendLine(
        "        ImmutableDictionary.CreateRange(new MutationEntityMetadata[]");

    sb.AppendLine("        {");


    for (var i = 0; i < models.Count; i++)
    {
        sb.AppendLine(
            $"            Create{models[i].ModelType!.Name}(){(i < models.Count - 1 ? "," : "")}");
    }


    sb.AppendLine(
        "        }.Select(x => new KeyValuePair<ushort, MutationEntityMetadata>(x.EntityId, x)));");


    sb.AppendLine();


    sb.AppendLine(
        "    public static int Count => _entities.Count;");


    sb.AppendLine();


    sb.AppendLine(
        "    public static MutationEntityMetadata Get(ushort entityId)");

    sb.AppendLine("    {");


    sb.AppendLine(
        "        if (!_entities.TryGetValue(entityId, out var metadata))");

    sb.AppendLine(
        "            throw new ArgumentOutOfRangeException(nameof(entityId));");


    sb.AppendLine();


    sb.AppendLine(
        "        return metadata;");


    sb.AppendLine("    }");


    sb.AppendLine();


    foreach (var model in models)
    {
        EmitFactory(
            sb,
            model);

        sb.AppendLine();
    }


    sb.AppendLine("}");


    return sb.ToString();
}
    
        private static List<(string EntityName, string Schema)> GetStorageEntities(
        MappingClassInfo info)
    {
        return info.Definition.Entities
            .Where(e => e.EntityType != null)
            .Select(e =>
            {
                var name =
                    IdEmitter.StripEntitySuffix(
                        e.EntityType!.Name);

                return (
                    EntityName: name,
                    Schema:
                        e.Schema
                        ?? info.Schema
                        ?? "public"
                );
            })
            .ToList();
    }
        
public static List<(
    string NavigationAlias,
    string ForeignKeyColumn,
    string RelatedEntityTypeName,
    string RelatedSurrogateIdColumn,
    string RelatedNaturalKeyColumn,
    string OwningPrimaryKeyColumn)>
BuildGraphEdgeCteResolutions(
    MappingClassInfo info)
{
    var result =
        new List<(
            string NavigationAlias,
            string ForeignKeyColumn,
            string RelatedEntityTypeName,
            string RelatedSurrogateIdColumn,
            string RelatedNaturalKeyColumn,
            string OwningPrimaryKeyColumn)>();


    if (info.Graph == null)
        return result;


    var navigationFields =
        info.FieldMaps
            .Where(x => x.IsNavigationKey)
            .ToList();


    if (navigationFields.Count < 2)
        return result;


    static string ExtractEntity(string value)
    {
        var parts =
            value.Split(
                '.',
                StringSplitOptions.RemoveEmptyEntries);

        return parts.Length > 1
            ? IdEmitter.StripEntitySuffix(parts[0])
            : string.Empty;
    }


    static string ExtractColumn(string value)
    {
        var parts =
            value.Split(
                '.',
                StringSplitOptions.RemoveEmptyEntries);

        return parts.Length > 1
            ? parts[1]
            : parts.Length == 1
                ? parts[0]
                : "Id";
    }


    //
    // IMPORTANT:
    // Alias comes from the navigation metadata.
    // Do NOT infer it from "Key".
    //
    var fromField = navigationFields[0];
    var toField = navigationFields[1];


    var fromEntity =
        ExtractEntity(
            info.Graph.From.ForeignKeyColumn);


    var toEntity =
        ExtractEntity(
            info.Graph.To.ForeignKeyColumn);


    result.Add(
        (
            NavigationAlias:
                fromField.SourceName,

            ForeignKeyColumn:
                ExtractColumn(
                    info.Graph.From.ForeignKeyColumn),

            RelatedEntityTypeName:
                fromEntity,

            RelatedSurrogateIdColumn:
                "Id",

            RelatedNaturalKeyColumn:
                info.Graph.From.GraphProperty,

            OwningPrimaryKeyColumn:
                info.Graph.EdgeProperty
                    ?? string.Empty
        ));


    result.Add(
        (
            NavigationAlias:
                toField.SourceName,

            ForeignKeyColumn:
                ExtractColumn(
                    info.Graph.To.ForeignKeyColumn),

            RelatedEntityTypeName:
                toEntity,

            RelatedSurrogateIdColumn:
                "Id",

            RelatedNaturalKeyColumn:
                info.Graph.To.GraphProperty,

            OwningPrimaryKeyColumn:
                info.Graph.EdgeProperty
                    ?? string.Empty
        ));


    return result;
}

    private static void EmitFactory(
    StringBuilder sb,
    MappingClassInfo info)
{
    var modelName = info.ModelType!.Name;

    var primaryEntity =
        info.Definition.Entities
            .FirstOrDefault(e => e.IsPrimary)
        ?? info.Definition.Entities.FirstOrDefault();

    if (primaryEntity?.EntityType == null)
    {
        sb.AppendLine(
            $"    private static MutationEntityMetadata Create{modelName}()");

        sb.AppendLine(
            $"        => throw new InvalidOperationException(\"{modelName} has no primary entity.\");");

        return;
    }


    var storageEntities =
        GetStorageEntities(info);


    var tableName =
        IdEmitter.StripEntitySuffix(
            primaryEntity.EntityType.Name);


    var primaryStorage =
        storageEntities.FirstOrDefault(x =>
            string.Equals(
                x.EntityName,
                tableName,
                StringComparison.OrdinalIgnoreCase));


    if (primaryStorage == default)
    {
        primaryStorage =
            storageEntities.FirstOrDefault();

        if (primaryStorage == default)
        {
            sb.AppendLine(
                $"    private static MutationEntityMetadata Create{modelName}()");

            sb.AppendLine(
                $"        => throw new InvalidOperationException(\"{modelName} has no storage entities.\");");

            return;
        }
    }


    var schema =
        primaryStorage.Schema;


    var hasGraphMetadata =
        info.Graph != null &&
        info.Graph.From != null &&
        info.Graph.To != null;


    var kind =
        hasGraphMetadata
            ? "MutationKind.GraphEdge"
            : "MutationKind.Entity";


    var primaryColumns =
        info.Definition.PrimaryKey
            .Select(pk => pk.ColumnKey)
            .Where(c => !string.IsNullOrWhiteSpace(c))
            .ToList();


    var grouped =
        info.FieldMaps
            .Where(f =>
                !IsStorageOnlyField(info, f) &&
                (
                    !IsPrimaryKeyColumn(info, f)
                    || f.IsNavigationKey
                ))
            .GroupBy(
                f => f.SourceName,
                StringComparer.Ordinal)
            .ToList();


    var lines =
        new List<string>();


    foreach (var group in grouped)
    {
        var fieldIdName =
            GeneratedIdentifierHelper.Field(group.Key);


        var targetLines =
            group.Select(target =>
            {
                var storageEntityName =
                    IdEmitter.StripEntitySuffix(
                        target.DestinationEntity);


                var columnName =
                    target.DestinationName;


                //
                // Graph navigation keys are not physical columns.
                // Resolve their storage information from graph metadata.
                //
                if (target.IsNavigationKey && hasGraphMetadata)
                {
                    var navigationTargets =
                        group
                            .Where(x => x.IsNavigationKey)
                            .ToList();


                    var navigationIndex =
                        navigationTargets.IndexOf(target);


                    var foreignKeyColumn =
                        navigationIndex == 0
                            ? info.Graph!.From!.ForeignKeyColumn
                            : info.Graph!.To!.ForeignKeyColumn;


                    var parts =
                        foreignKeyColumn.Split(
                            new[] { '.' },
                            StringSplitOptions.RemoveEmptyEntries);


                    if (parts.Length == 2)
                    {
                        storageEntityName =
                            IdEmitter.StripEntitySuffix(parts[0]);

                        columnName =
                            parts[1];
                    }
                    else
                    {
                        storageEntityName =
                            IdEmitter.StripEntitySuffix(
                                primaryEntity.EntityType.Name);

                        columnName =
                            foreignKeyColumn;
                    }
                }


                var isPrimaryKey =
                    info.Definition.PrimaryKey.Any(pk =>
                        pk.Entity != null &&
                        string.Equals(
                            IdEmitter.StripEntitySuffix(pk.Entity.Name),
                            storageEntityName,
                            StringComparison.OrdinalIgnoreCase)
                        &&
                        string.Equals(
                            pk.ColumnKey,
                            columnName,
                            StringComparison.OrdinalIgnoreCase));


                string columnExpression;


                //
                // IMPORTANT:
                // Navigation fields do not have ColumnId entries.
                // They are resolved through graph metadata.
                //
                if (target.IsNavigationKey && hasGraphMetadata)
                {
                    columnExpression = "0";
                }
                else
                {
                    columnExpression =
                        ColumnIdResolver.Resolve(
                            storageEntityName,
                            columnName);
                }
                
                return
                    $"new MutationFieldMetadata(" +
                    $"FieldId.{modelName}.{fieldIdName}, " +
                    $"EntityId.{modelName}, " +
                    $"StorageEntityId.{storageEntityName}, " +
                    $"{columnExpression}, " +
                    $"{(isPrimaryKey ? "true" : "false")}, " +
                    $"{(target.IsNavigationKey ? "true" : "false")}, " +
                    $"\"{Escape(group.Key)}\")";

            })
            .ToList();


        lines.Add(
            $"                [FieldId.{modelName}.{fieldIdName}] = " +
            $"ImmutableArray.Create({string.Join(", ", targetLines)})");
    }


    sb.AppendLine(
        $"    private static MutationEntityMetadata Create{modelName}()");

    sb.AppendLine("    {");

    sb.AppendLine(
        "        return new MutationEntityMetadata(");


    sb.AppendLine(
        $"            EntityId.{modelName},");

    sb.AppendLine(
        $"            StorageEntityId.{tableName},");

    sb.AppendLine(
        $"            \"{Escape(schema)}\",");

    sb.AppendLine(
        $"            \"{Escape(tableName)}\",");


    var isComposite =
        info.Definition.Entities.Count(e => e.EntityType != null) > 1;


    if (isComposite)
    {
        sb.AppendLine("            false,");
        sb.AppendLine($"            {kind},");


        var upsertColumns =
            info.UpsertKeys
                .Select(x =>
                {
                    var field =
                        info.FieldMaps.FirstOrDefault(f =>
                            string.Equals(
                                f.SourceName,
                                x.Key,
                                StringComparison.Ordinal));

                    return field?.DestinationName ?? x.Key;
                })
                .Where(x => !string.IsNullOrWhiteSpace(x))
                .Distinct(StringComparer.OrdinalIgnoreCase)
                .ToList();


        if (upsertColumns.Count == 0)
        {
            sb.AppendLine(
                "            ImmutableArray<string>.Empty,");
        }
        else
        {
            sb.AppendLine(
                "            ImmutableArray.Create<string>(" +
                string.Join(", ",
                    upsertColumns.Select(x =>
                        $"\"{Escape(x)}\"")) +
                "),");
        }
    }
    else
    {
        sb.AppendLine("            true,");
        sb.AppendLine($"            {kind},");


        if (primaryColumns.Count == 0)
        {
            sb.AppendLine(
                "            ImmutableArray<string>.Empty,");
        }
        else
        {
            sb.AppendLine(
                "            ImmutableArray.Create<string>(" +
                string.Join(", ",
                    primaryColumns.Select(c =>
                        $"\"{Escape(c)}\"")) +
                "),");
        }
    }


    sb.AppendLine();

    sb.AppendLine(
        "            new Dictionary<ushort, ImmutableArray<MutationFieldMetadata>>");

    sb.AppendLine("            {");


    if (lines.Count > 0)
    {
        sb.AppendLine(
            string.Join(",\n", lines));
    }


    sb.AppendLine(
        "            },");


    EmitStorageEntities(
        sb,
        info);


       if (hasGraphMetadata)
{
    sb.AppendLine(",");

    var fromParts =
        info.Graph!
            .From!
            .ForeignKeyColumn
            .Split(
                new[] { '.' },
                StringSplitOptions.RemoveEmptyEntries);

    var toParts =
        info.Graph!
            .To!
            .ForeignKeyColumn
            .Split(
                new[] { '.' },
                StringSplitOptions.RemoveEmptyEntries);


    var fromEntity =
        fromParts.Length > 1
            ? IdEmitter.StripEntitySuffix(fromParts[0])
            : null;

    var fromColumn =
        fromParts.Length > 1
            ? fromParts[1]
            : fromParts.LastOrDefault();


    var toEntity =
        toParts.Length > 1
            ? IdEmitter.StripEntitySuffix(toParts[0])
            : null;

    var toColumn =
        toParts.Length > 1
            ? toParts[1]
            : toParts.LastOrDefault();


    var navigationFields =
        info.FieldMaps
            .Where(f => f.IsNavigationKey)
            .ToList();


    FieldInfo? fromField = null;
    FieldInfo? toField = null;


    foreach (var field in navigationFields)
    {
        var destinationEntity =
            IdEmitter.StripEntitySuffix(
                field.DestinationEntity);


        if (fromField == null &&
            string.Equals(
                destinationEntity,
                fromEntity,
                StringComparison.OrdinalIgnoreCase) &&
            string.Equals(
                field.DestinationName,
                fromColumn,
                StringComparison.OrdinalIgnoreCase))
        {
            fromField = field;
            continue;
        }


        if (toField == null &&
            string.Equals(
                destinationEntity,
                toEntity,
                StringComparison.OrdinalIgnoreCase) &&
            string.Equals(
                field.DestinationName,
                toColumn,
                StringComparison.OrdinalIgnoreCase))
        {
            toField = field;
        }
    }
    
    fromField ??=
        navigationFields.FirstOrDefault(f =>
            string.Equals(
                f.DestinationName,
                fromColumn,
                StringComparison.OrdinalIgnoreCase));


    toField ??=
        navigationFields.FirstOrDefault(f =>
            f != fromField &&
            string.Equals(
                f.DestinationName,
                toColumn,
                StringComparison.OrdinalIgnoreCase));
    
    if (fromField == null &&
        navigationFields.Count > 0)
    {
        fromField = navigationFields[0];
    }


    if (toField == null &&
        navigationFields.Count > 1)
    {
        toField = navigationFields[1];
    }


    sb.AppendLine(
        $"            graphName: \"{Escape(info.Graph.GraphName)}\",");

    sb.AppendLine(
        $"            graphEdgeLabel: \"{Escape(info.Graph.EdgeLabel)}\",");

    sb.AppendLine(
        $"            graphFromVertex: \"{Escape(info.Graph.From.Label)}\",");

    sb.AppendLine(
        $"            graphToVertex: \"{Escape(info.Graph.To.Label)}\",");

    sb.AppendLine(
        $"            graphFromColumn: \"{Escape(info.Graph.From.GraphProperty)}\",");

    sb.AppendLine(
        $"            graphToColumn: \"{Escape(info.Graph.To.GraphProperty)}\",");


    sb.AppendLine(
        fromField != null
            ? $"            graphFromFieldId: FieldId.{modelName}.{GeneratedIdentifierHelper.Field(fromField.SourceName)},"
            : "            graphFromFieldId: null,");


    sb.AppendLine(
        toField != null
            ? $"            graphToFieldId: FieldId.{modelName}.{GeneratedIdentifierHelper.Field(toField.SourceName)}"
            : "            graphToFieldId: null");
}


    sb.AppendLine(
        "        );");

    sb.AppendLine(
        "    }");
}

    private static bool IsPrimaryKeyColumn(
        MappingClassInfo info,
        FieldInfo field)
    {
        return info.Definition.PrimaryKey.Any(pk =>
            string.Equals(
                IdEmitter.StripEntitySuffix(pk.Entity.Name),
                IdEmitter.StripEntitySuffix(field.DestinationEntity),
                StringComparison.OrdinalIgnoreCase)
            &&
            string.Equals(
                pk.ColumnKey,
                field.DestinationName,
                StringComparison.OrdinalIgnoreCase));
    }



    private static void EmitStorageEntities(
    StringBuilder sb,
    MappingClassInfo info)
{
    //
    // Argument #9 - CTE metadata
    //
    if (info.CteUpdateMeta.Count == 0)
    {
        sb.AppendLine(
            "            ImmutableArray<CteUpdateMetaInfo>.Empty,");
    }
    else
    {
        sb.AppendLine(
            "            ImmutableArray.Create(");

        for (var i = 0; i < info.CteUpdateMeta.Count; i++)
        {
            var meta = info.CteUpdateMeta[i];

            var comma =
                i < info.CteUpdateMeta.Count - 1
                    ? ","
                    : "";

            sb.AppendLine(
                "                new CteUpdateMetaInfo");

            sb.AppendLine(
                "                {");

            sb.AppendLine(
                $"                    NavigationAlias = \"{Escape(meta.NavigationAlias)}\",");

            sb.AppendLine(
                $"                    ForeignKeyColumn = \"{Escape(meta.ForeignKeyColumn)}\",");

            sb.AppendLine(
                $"                    OwningPrimaryKeyColumn = \"{Escape(meta.OwningPrimaryKeyColumn)}\",");

            sb.AppendLine(
                $"                    RelatedEntityTypeName = \"{Escape(meta.RelatedEntityTypeName)}\",");

            sb.AppendLine(
                $"                    RelatedSurrogateIdColumn = \"{Escape(meta.RelatedSurrogateIdColumn)}\",");

            sb.AppendLine(
                $"                    RelatedNaturalKeyColumn = \"{Escape(meta.RelatedNaturalKeyColumn)}\"");

            sb.AppendLine(
                $"                }}{comma}");
        }

        sb.AppendLine(
            "            ),");
    }

    //
    // Argument #10 - Storage entities
    //
    var entities =
        info.Definition.Entities
            .Where(e => e.EntityType != null)
            .Select(e =>
            {
                var name =
                    IdEmitter.StripEntitySuffix(
                        e.EntityType!.Name);

                return new
                {
                    Name = name,
                    Schema =
                        e.Schema
                        ?? info.Schema
                        ?? "public"
                };
            })
            .ToList();

    if (entities.Count == 0)
    {
        sb.AppendLine(
            "            ImmutableArray<MutationStorageEntityMetadata>.Empty");
        return;
    }

    sb.AppendLine(
        "            ImmutableArray.Create(");

    for (var i = 0; i < entities.Count; i++)
    {
        var comma =
            i < entities.Count - 1
                ? ","
                : "";

        sb.AppendLine(
            "                new MutationStorageEntityMetadata(");

        sb.AppendLine(
            $"                    StorageEntityId.{entities[i].Name},");

        sb.AppendLine(
            $"                    \"{Escape(entities[i].Schema)}\",");

        sb.AppendLine(
            $"                    \"{Escape(entities[i].Name)}\"){comma}");
    }

    sb.AppendLine(
        "            )");
}
    
    private static bool IsStorageOnlyField(
        MappingClassInfo info,
        FieldInfo field)
    {
        //
        // Primary keys are represented through identity/upsert metadata.
        //
        // However navigation keys are NOT storage-only because graph
        // relationships need them to resolve the edge endpoints.
        //
        if (field.IsNavigationKey)
            return false;


        return info.Definition.PrimaryKey.Any(pk =>
            string.Equals(
                IdEmitter.StripEntitySuffix(pk.Entity.Name),
                IdEmitter.StripEntitySuffix(field.DestinationEntity),
                StringComparison.OrdinalIgnoreCase)
            &&
            string.Equals(
                pk.ColumnKey,
                field.DestinationName,
                StringComparison.OrdinalIgnoreCase));
    }



    private static string Escape(
        string value)
    {
        return value
            .Replace("\\", "\\\\")
            .Replace("\"", "\\\"");
    }
}