using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using CoffeeBeanery.GraphQL.Core.Mapping.Generators.Model;

namespace CoffeeBeanery.GraphQL.Core.Mapping.Generators.Emit
{
    internal static class NodeTreeEmitter
    {
        public static string EmitRegisterOverride(
            MappingClassInfo info,
            NavigationResolutionResult navResult)
        {
            var sb = new StringBuilder();

            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("#nullable enable");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine("using CoffeeBeanery.GraphQL.Core.Mapping;");
            sb.AppendLine("using CoffeeBeanery.GraphQL.Core.Sql;");
            sb.AppendLine();

            if (!string.IsNullOrWhiteSpace(info.Namespace))
            {
                sb.AppendLine($"namespace {info.Namespace}");
                sb.AppendLine("{");
            }

            sb.AppendLine($"public partial class {info.ClassName}");
            sb.AppendLine("{");

            sb.AppendLine(
                "    protected override void ApplyGeneratedMappings(global::CoffeeBeanery.GraphQL.Core.Mapping.NodeMap map)");

            sb.AppendLine("    {");

            sb.AppendLine("        var alias = map.Alias;");
            sb.AppendLine("        var modelName = map.ModelName;");
            sb.AppendLine();

            EmitModelToEntityKeys(sb, info);
            EmitEntityChildren(sb, info, navResult);
            EmitChildAttachments(sb, info);
            EmitFieldMapsList(sb, info);
            EmitCteUpdateMeta(sb, info, navResult);

            sb.AppendLine("    }");
            sb.AppendLine("}");

            if (!string.IsNullOrWhiteSpace(info.Namespace))
                sb.AppendLine("}");

            return sb.ToString();
        }


        private static void EmitCteUpdateMeta(
            StringBuilder sb,
            MappingClassInfo info,
            NavigationResolutionResult navResult)
        {
            var fkNavs = navResult.Navigations
                .Where(n =>
                    !n.IsCollection &&
                    !string.IsNullOrWhiteSpace(n.ForeignKeyProperty))
                .ToList();

            if (fkNavs.Count == 0)
                return;

            var primaryEntry =
                info.ModelToEntity.FirstOrDefault(k => k.IsPrimary);

            if (primaryEntry is null ||
                string.IsNullOrWhiteSpace(primaryEntry.ToColumn))
                return;

            var aliasToNaturalKey =
                info.ModelToEntity
                    .Where(k =>
                        k.AliasProperty != null &&
                        !string.IsNullOrWhiteSpace(k.ToColumn))
                    .ToDictionary(
                        k => k.AliasProperty!,
                        k => k);

            foreach (var nav in fkNavs)
            {
                if (!aliasToNaturalKey.TryGetValue(
                        nav.NavigationName,
                        out var naturalKeyInfo))
                    continue;

                if (!info.CteUpdateMeta.Any(e =>
                        string.Equals(
                            e.NavigationAlias,
                            nav.NavigationName,
                            StringComparison.OrdinalIgnoreCase)))
                {
                    info.CteUpdateMeta.Add(
                        new CteUpdateMetaInfo
                        {
                            NavigationAlias = nav.NavigationName,
                            ForeignKeyColumn = nav.ForeignKeyProperty,
                            OwningPrimaryKeyColumn = primaryEntry.ToColumn!,
                            RelatedEntityTypeName =
                                nav.RelatedEntityType.Name,
                            RelatedSurrogateIdColumn =
                                nav.PrincipalKeyProperty,
                            RelatedNaturalKeyColumn =
                                naturalKeyInfo.ToColumn!
                        });
                }
            }
        }


        private static void EmitModelToEntityKeys(
            StringBuilder sb,
            MappingClassInfo info)
        {
            sb.AppendLine(
                "        var existingModelToEntity = new HashSet<(string,string)>();");

            sb.AppendLine(
                "        foreach (var k in map.ModelToEntity) existingModelToEntity.Add((k.EntityType.Name, k.AliasProperty ?? \"\"));");

            sb.AppendLine();

            foreach (var key in info.ModelToEntity)
            {
                var aliasExpr =
                    !string.IsNullOrWhiteSpace(key.AliasProperty)
                        ? $"\"{key.AliasProperty}\""
                        : AliasFor(
                            info,
                            key.EntityType.Name,
                            targetIsRoot: false);

                sb.AppendLine(
                    $"        if (!existingModelToEntity.Contains((\"{key.EntityType.Name}\", {StringOrNull(key.AliasProperty)} ?? \"\")))");

                sb.AppendLine("        {");
                sb.AppendLine(
                    "            map.ModelToEntity.Add(new EntityKey");

                sb.AppendLine("            {");

                sb.AppendLine(
                    $"                From = \"{info.ModelType.Name}\",");

                sb.AppendLine(
                    "                AliasFrom = alias,");

                sb.AppendLine(
                    $"                FromColumn = \"{key.FromColumn}\",");

                sb.AppendLine(
                    $"                To = \"{key.To}\",");

                sb.AppendLine(
                    $"                AliasTo = {aliasExpr},");

                sb.AppendLine(
                    $"                ToColumn = \"{key.ToColumn}\",");

                sb.AppendLine(
                    $"                EntityType = typeof({Fqn(key.EntityType)}),");

                sb.AppendLine(
                    $"                AliasProperty = {StringOrNull(key.AliasProperty)}");

                sb.AppendLine("            });");
                sb.AppendLine("        }");
            }

            sb.AppendLine();
        }
                private static void EmitEntityChildren(
            StringBuilder sb,
            MappingClassInfo info,
            NavigationResolutionResult navResult)
        {
            if (!info.IsEntity)
                return;

            sb.AppendLine(
                "        var existingEntityChildren = new HashSet<string>();");

            sb.AppendLine(
                "        foreach (var c in map.EntityChildren) existingEntityChildren.Add(c.AliasTo);");

            sb.AppendLine(
                "        foreach (var c in map.EntityChildrenRelated) existingEntityChildren.Add(c.AliasTo);");

            sb.AppendLine();

            foreach (var nav in navResult.Navigations)
            {
                var targetList =
                    nav.IsCollection
                        ? "map.EntityChildren"
                        : "map.EntityChildrenRelated";

                var aliasExpr =
                    AliasFor(
                        info,
                        nav.NavigationName,
                        nav.TargetIsRoot);

                sb.AppendLine(
                    $"        if (!existingEntityChildren.Contains({aliasExpr}))");

                sb.AppendLine("        {");

                sb.AppendLine(
                    $"            {targetList}.Add(new EntityKey");

                sb.AppendLine("            {");

                sb.AppendLine(
                    $"                From = \"{info.ModelType.Name}\",");

                sb.AppendLine(
                    "                AliasFrom = alias,");

                sb.AppendLine(
                    $"                FromColumn = \"{nav.ForeignKeyProperty}\",");

                sb.AppendLine(
                    $"                To = \"{nav.RelatedEntityType.Name}\",");

                sb.AppendLine(
                    $"                AliasTo = {aliasExpr},");

                sb.AppendLine(
                    $"                ToColumn = \"{nav.PrincipalKeyProperty}\",");

                sb.AppendLine(
                    $"                EntityType = typeof({Fqn(nav.RelatedEntityType)})");

                sb.AppendLine("            });");
                sb.AppendLine("        }");
            }

            sb.AppendLine();
        }


        private static void EmitChildAttachments(
            StringBuilder sb,
            MappingClassInfo info)
        {
            if (info.AutoChildAttachments.Count == 0)
                return;

            sb.AppendLine(
                "        var existingChildAttachmentFields = new HashSet<string>();");

            sb.AppendLine(
                "        foreach (var c in map.ChildAttachments) existingChildAttachmentFields.Add(c.FieldName);");

            sb.AppendLine();

            foreach (var att in info.AutoChildAttachments)
            {
                sb.AppendLine(
                    $"        if (!existingChildAttachmentFields.Contains(\"{att.FieldName}\"))");

                sb.AppendLine("        {");

                sb.AppendLine(
                    "            map.ChildAttachments.Add(new ChildAttachment");

                sb.AppendLine("            {");

                sb.AppendLine(
                    $"                FieldName = \"{att.FieldName}\",");

                sb.AppendLine(
                    $"                ToModelName = \"{att.ToModelName}\",");

                sb.AppendLine(
                    $"                ParentEntityType = typeof({Fqn(att.ParentEntityType)}),");

                sb.AppendLine(
                    $"                ParentJoinColumn = \"{att.ParentJoinColumn}\",");

                sb.AppendLine(
                    $"                ChildEntityType = typeof({Fqn(att.ChildEntityType)}),");

                sb.AppendLine(
                    $"                ChildJoinColumn = \"{att.ChildJoinColumn}\",");

                sb.AppendLine(
                    "                IsCollection = true,");

                sb.AppendLine(
                    "                IsAutoGenerated = true");

                sb.AppendLine("            });");
                sb.AppendLine("        }");
            }

            sb.AppendLine();
        }


        private static void EmitFieldMapsList(
            StringBuilder sb,
            MappingClassInfo info)
        {
            sb.AppendLine(
                "        var existingFieldMaps = new HashSet<string>();");

            sb.AppendLine(
                "        foreach (var f in map.FieldMaps) existingFieldMaps.Add($\"{f.SourceName}|{f.DestinationEntity}\");");

            sb.AppendLine();

            sb.AppendLine(
                "        var fieldMaps = new List<FieldMap>();");

            foreach (var fm in info.FieldMaps)
            {
                var dedupKey =
                    $"{fm.SourceName}|{fm.DestinationEntity}";

                sb.AppendLine(
                    $"        if (!existingFieldMaps.Contains(\"{dedupKey}\"))");

                sb.AppendLine("        {");

                sb.AppendLine(
                    "            var fm = new FieldMap");

                sb.AppendLine("            {");

                sb.AppendLine(
                    $"                SourceModel = \"{info.ModelType.Name}\",");

                sb.AppendLine(
                    $"                SourceName = \"{fm.SourceName}\",");

                sb.AppendLine(
                    $"                DestinationEntity = \"{fm.DestinationEntity}\",");

                sb.AppendLine(
                    $"                DestinationName = \"{fm.DestinationName}\",");

                sb.AppendLine(
                    $"                SourceAlias = {StringOrAlias(info, fm.SourceAlias)},");

                sb.AppendLine(
                    $"                DestinationAlias = {StringOrAlias(info, fm.DestinationAlias)},");

                sb.AppendLine(
                    $"                FromEnum = {EmitDict(fm.FromEnum)},");

                sb.AppendLine(
                    $"                ToEnum = {EmitDict(fm.ToEnum)}");

                sb.AppendLine("            };");

                sb.AppendLine(
                    "            map.FieldMaps.Add(fm);");

                sb.AppendLine(
                    "            fieldMaps.Add(fm);");

                sb.AppendLine("        }");
            }

            sb.AppendLine();
        }


        private static string AliasFor(
            MappingClassInfo info,
            string seed,
            bool targetIsRoot)
        {
            if (targetIsRoot)
                return $"\"{seed}\"";

            return string.IsNullOrWhiteSpace(info.Prefix)
                ? $"\"{seed}\""
                : $"\"{info.Prefix}{seed}\"";
        }


        private static string StringOrAlias(
            MappingClassInfo info,
            string? value)
        {
            if (string.IsNullOrWhiteSpace(value))
                return "null";

            if (value == "{alias}" ||
                value == info.Alias)
                return "alias";

            return $"\"{value}\"";
        }


        private static string StringOrNull(string? value)
            => value is null
                ? "null"
                : $"\"{value}\"";


        private static string EmitDict(
            Dictionary<string, int>? dict)
        {
            if (dict is null || dict.Count == 0)
                return "null";

            return "new Dictionary<string,int> { " +
                   string.Join(
                       ", ",
                       dict.Select(kv =>
                           $"[\"{kv.Key}\"] = {kv.Value}")) +
                   " }";
        }


        private static string Fqn(
            Microsoft.CodeAnalysis.INamedTypeSymbol symbol)
            => symbol.ToDisplayString(
                    Microsoft.CodeAnalysis.SymbolDisplayFormat
                        .FullyQualifiedFormat)
                .TrimStart(':');
    }
}