using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using CoffeeBeanery.GraphQL.Core.Mapping.Generators.Model;
using CoffeeBeanery.GraphQL.Core.Mapping.Generators.Passes;
using Microsoft.CodeAnalysis;

namespace CoffeeBeanery.GraphQL.Core.Mapping.Generators.Emit;

internal static class PlannerEmitter
{
    public static string Emit(
        ImmutableArray<MappingClassInfo> mappings,
        ImmutableHashSet<INamedTypeSymbol> rootEntityTypes,
        List<FluentEntityNavigationConvention.EntityForeignKeyGraph.Edge> entityGraph)
    {
        var sb = new StringBuilder();

        sb.AppendLine("#nullable enable");
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Collections.Immutable;");
        sb.AppendLine();
        sb.AppendLine("using CoffeeBeanery.GraphQL.Core.Runtime;");
        sb.AppendLine();
        sb.AppendLine("namespace CoffeeBeanery.GraphQL.Core.Runtime;");
        sb.AppendLine();

        sb.AppendLine("public static partial class GeneratedPlanners");
        sb.AppendLine("{");
        sb.AppendLine();

        var models =
            mappings
                .Where(x => x.ModelType != null)
                .GroupBy(
                    x => x.ModelType!.Name,
                    StringComparer.OrdinalIgnoreCase)
                .Select(g => g.First())
                .OrderBy(x => x.ModelType!.Name)
                .ToList();

        foreach (var mapping in models)
        {
            EmitPlanner(
                sb,
                mapping,
                mappings,
                rootEntityTypes,
                entityGraph);

            sb.AppendLine();
        }

        EmitRegistry(sb, models);

        sb.AppendLine("}");

        return sb.ToString();
    }


    private static void EmitCompositeStorageJoins(
    StringBuilder sb,
    MappingClassInfo info,
    ImmutableArray<MappingClassInfo> allMappings,
    List<FluentEntityNavigationConvention.EntityForeignKeyGraph.Edge> entityGraph)
{
    var emitted = new HashSet<string>(
        StringComparer.OrdinalIgnoreCase);

    var index = 0;

    // Tracks the SQL alias each entity type is reachable under, as this
    // chain is built up hop by hop. The chain's own root entity (the
    // first join's parent) is reached via node.OutputAlias — the actual
    // runtime alias this Build() invocation is running under, whether
    // it's the query root or a nested attached child. Every subsequent
    // hop's parent alias must be looked up here rather than re-emitting
    // the model/entity name as a literal, since a hardcoded name is only
    // coincidentally correct when this node happens to be the root.
    var aliasByEntity =
        new Dictionary<INamedTypeSymbol, string>(
            SymbolEqualityComparer.Default);

    foreach (var join in info.CompositeStorageJoinInfo)
    {
        var parentExists =
            allMappings.Any(x =>
                x.Definition.Entities.Any(e =>
                    e.EntityType != null &&
                    SymbolEqualityComparer.Default.Equals(
                        e.EntityType,
                        join.ParentEntityType)));

        var childExists =
            allMappings.Any(x =>
                x.Definition.Entities.Any(e =>
                    e.EntityType != null &&
                    SymbolEqualityComparer.Default.Equals(
                        e.EntityType,
                        join.ChildEntityType)));

        if (!parentExists || !childExists)
            continue;


        var key =
            $"{join.ParentEntityType.Name}->{join.ChildEntityType.Name}";


        if (!emitted.Add(key))
            continue;


        var edge =
            FindEdge(
                join.ParentEntityType,
                join.ChildEntityType,
                entityGraph);


        if (edge == null)
        {
            throw new InvalidOperationException(
                $"Missing FK edge between {join.ParentEntityType.Name} and {join.ChildEntityType.Name}");
        }


        string parentColumn;
        string childColumn;


        if (SymbolEqualityComparer.Default.Equals(
                edge.PrincipalEntity,
                join.ParentEntityType))
        {
            parentColumn = edge.PrincipalColumn;
            childColumn = edge.DependentColumn;
        }
        else
        {
            parentColumn = edge.DependentColumn;
            childColumn = edge.PrincipalColumn;
        }


        var parentStorage =
            IdEmitter.StripEntitySuffix(
                join.ParentEntityType.Name);


        var childStorage =
            IdEmitter.StripEntitySuffix(
                join.ChildEntityType.Name);


        var childAlias =
            $"{info.ModelType!.Name}_{childStorage}_{index}";


        // The parent side's alias: if this is the first hop in the chain
        // (the composite model's own primary/anchor entity), use
        // node.OutputAlias — the real runtime alias for this Build()
        // invocation. Otherwise use whatever alias an earlier hop already
        // established for this same parent entity.
        string parentAliasExpr;

        if (aliasByEntity.TryGetValue(join.ParentEntityType, out var knownParentAlias))
        {
            parentAliasExpr = $"\"{knownParentAlias}\"";
        }
        else
        {
            parentAliasExpr = "node.OutputAlias";
        }

        aliasByEntity[join.ChildEntityType] = childAlias;


        sb.AppendLine(
            "            builder.AddJoin(");

        if (parentAliasExpr == "node.OutputAlias")
        {
            sb.AppendLine(
                "                node.OutputAlias,");
        }
        else
        {
            sb.AppendLine(
                $"                {parentAliasExpr},");
        }

        sb.AppendLine(
            $"                \"{childAlias}\",");


        sb.AppendLine(
            $"                EntityId.{ResolveRuntimeEntityId(join.ParentEntityType, allMappings)},");

        sb.AppendLine(
            $"                StorageEntityId.{parentStorage},");

        sb.AppendLine(
            $"                {ColumnIdResolver.Resolve(join.ParentEntityType, parentColumn)},");


        sb.AppendLine(
            $"                EntityId.{ResolveRuntimeEntityId(join.ChildEntityType, allMappings)},");

        sb.AppendLine(
            $"                StorageEntityId.{childStorage},");

        sb.AppendLine(
            $"                {ColumnIdResolver.Resolve(join.ChildEntityType, childColumn)},");


        sb.AppendLine(
            "                JoinKind.Left);");


        sb.AppendLine();

        index++;
    }
}


private static void EmitCompositeChildAttachmentJoins(
    StringBuilder sb,
    MappingClassInfo info,
    ImmutableArray<MappingClassInfo> allMappings,
    List<FluentEntityNavigationConvention.EntityForeignKeyGraph.Edge> entityGraph)
{
    sb.AppendLine(
        "            foreach (var attachChild in node.Children)");

    sb.AppendLine(
        "            {");

    var index = 0;

    foreach (var attachment in info.AutoChildAttachments)
    {
        var parentEntityName =
            IdEmitter.StripEntitySuffix(
                attachment.ParentEntityType.Name);

        var childEntityName =
            IdEmitter.StripEntitySuffix(
                attachment.ChildEntityType.Name);

        var edge =
            FindEdge(
                attachment.ParentEntityType,
                attachment.ChildEntityType,
                entityGraph);

        if (edge == null)
        {
            continue;
        }

        string parentColumn;
        string childColumn;

        if (SymbolEqualityComparer.Default.Equals(
                edge.PrincipalEntity,
                attachment.ParentEntityType))
        {
            parentColumn = edge.PrincipalColumn;
            childColumn = edge.DependentColumn;
        }
        else
        {
            parentColumn = edge.DependentColumn;
            childColumn = edge.PrincipalColumn;
        }

        var attachmentAlias =
            $"{attachment.ToModelName}_{childEntityName}_{index}";

        sb.AppendLine(
            $"                if (string.Equals(attachChild.OutputAlias, \"{attachment.FieldName}\", System.StringComparison.OrdinalIgnoreCase))");

        sb.AppendLine(
            "                {");

        sb.AppendLine(
            "                    builder.AddJoin(");

        // FIX: the parent side of this attachment is THIS node itself —
        // its real runtime alias is node.OutputAlias, never a hardcoded
        // literal of the model/entity name. Hardcoding was only
        // coincidentally correct when this node happened to be the query
        // root; when reached as a nested child (e.g. Customer attached
        // under CustomerCustomerEdge as "InnerCustomer"), the real alias
        // differs from the model name entirely.
        sb.AppendLine(
            "                        node.OutputAlias,");

        sb.AppendLine(
            $"                        \"{attachmentAlias}\",");

        sb.AppendLine(
            $"                        EntityId.{ResolveRuntimeEntityId(attachment.ParentEntityType, allMappings)},");

        sb.AppendLine(
            $"                        StorageEntityId.{parentEntityName},");

        sb.AppendLine(
            $"                        {ColumnIdResolver.Resolve(attachment.ParentEntityType, parentColumn)},");

        sb.AppendLine(
            $"                        EntityId.{ResolveRuntimeEntityId(attachment.ChildEntityType, allMappings)},");

        sb.AppendLine(
            $"                        StorageEntityId.{childEntityName},");

        sb.AppendLine(
            $"                        {ColumnIdResolver.Resolve(attachment.ChildEntityType, childColumn)},");

        sb.AppendLine(
            "                        JoinKind.Left);");

        var childMapping =
            allMappings.FirstOrDefault(m =>
                m.ModelType != null &&
                string.Equals(
                    m.ModelType.Name,
                    attachment.ToModelName,
                    StringComparison.Ordinal));

        if (childMapping != null && childMapping.IsComposite)
        {
            var compositeTypes =
                childMapping.Definition.Entities
                    .Select(e => e.EntityType)
                    .Where(t => t != null)
                    .Cast<INamedTypeSymbol>()
                    .ToList();

            var chain =
                CompositeChildAttachmentConvention
                    .ComputeCompositeJoinChain(
                        attachment.ChildEntityType,
                        compositeTypes,
                        entityGraph);

            // Track the alias each hop's parent entity is reachable
            // under. The chain's own first entity (attachment.ChildEntityType)
            // was just established above as `attachmentAlias`.
            var aliasByEntity =
                new Dictionary<INamedTypeSymbol, string>(
                    SymbolEqualityComparer.Default)
                {
                    [attachment.ChildEntityType] = attachmentAlias
                };

            var hopIndex = 0;

            foreach (var hop in chain)
            {
                var hopEdge =
                    FindEdge(
                        hop.ParentEntityType,
                        hop.ChildEntityType,
                        entityGraph);

                if (hopEdge == null)
                {
                    continue;
                }

                string hopParentColumn;
                string hopChildColumn;

                if (SymbolEqualityComparer.Default.Equals(
                        hopEdge.PrincipalEntity,
                        hop.ParentEntityType))
                {
                    hopParentColumn = hopEdge.PrincipalColumn;
                    hopChildColumn = hopEdge.DependentColumn;
                }
                else
                {
                    hopParentColumn = hopEdge.DependentColumn;
                    hopChildColumn = hopEdge.PrincipalColumn;
                }

                var hopParentName =
                    IdEmitter.StripEntitySuffix(
                        hop.ParentEntityType.Name);

                var hopChildName =
                    IdEmitter.StripEntitySuffix(
                        hop.ChildEntityType.Name);

                var hopAlias =
                    $"{attachmentAlias}_{hopChildName}_{hopIndex}";

                // Look up the parent's actual established alias rather
                // than emitting a hardcoded entity-name literal.
                var hopParentAlias =
                    aliasByEntity.TryGetValue(hop.ParentEntityType, out var known)
                        ? known
                        : hopParentName; // fallback, shouldn't normally hit

                aliasByEntity[hop.ChildEntityType] = hopAlias;

                sb.AppendLine(
                    "                    builder.AddJoin(");

                sb.AppendLine(
                    $"                        \"{hopParentAlias}\",");

                sb.AppendLine(
                    $"                        \"{hopAlias}\",");

                sb.AppendLine(
                    $"                        EntityId.{ResolveRuntimeEntityId(hop.ParentEntityType, allMappings)},");

                sb.AppendLine(
                    $"                        StorageEntityId.{hopParentName},");

                sb.AppendLine(
                    $"                        {ColumnIdResolver.Resolve(hop.ParentEntityType, hopParentColumn)},");

                sb.AppendLine(
                    $"                        EntityId.{ResolveRuntimeEntityId(hop.ChildEntityType, allMappings)},");

                sb.AppendLine(
                    $"                        StorageEntityId.{hopChildName},");

                sb.AppendLine(
                    $"                        {ColumnIdResolver.Resolve(hop.ChildEntityType, hopChildColumn)},");

                sb.AppendLine(
                    "                        JoinKind.Left);");

                hopIndex++;
            }
        }

        sb.AppendLine(
            "                }");

        index++;
    }

    sb.AppendLine(
        "            }");

    sb.AppendLine();
}

    private static FluentEntityNavigationConvention.EntityForeignKeyGraph.Edge? FindEdge(
        INamedTypeSymbol entityA,
        INamedTypeSymbol entityB,
        List<FluentEntityNavigationConvention.EntityForeignKeyGraph.Edge> entityGraph)
    {
        foreach (var edge in entityGraph)
        {
            if (SymbolEqualityComparer.Default.Equals(edge.PrincipalEntity, entityA) &&
                SymbolEqualityComparer.Default.Equals(edge.DependentEntity, entityB))
            {
                return edge;
            }

            if (SymbolEqualityComparer.Default.Equals(edge.PrincipalEntity, entityB) &&
                SymbolEqualityComparer.Default.Equals(edge.DependentEntity, entityA))
            {
                return edge;
            }
        }

        return null;
    }

    private static void EmitPlanner(
        StringBuilder sb,
        MappingClassInfo info,
        ImmutableArray<MappingClassInfo> allMappings,
        ImmutableHashSet<INamedTypeSymbol> rootEntityTypes,
        List<FluentEntityNavigationConvention.EntityForeignKeyGraph.Edge> entityGraph)
    {
        if (info.ModelType == null)
            return;

        var name = info.ModelType.Name;

        sb.AppendLine(
            $"    public static class {name}Planner");

        sb.AppendLine(
            "    {");

        EmitBuild(
            sb,
            info,
            allMappings,
            rootEntityTypes,
            entityGraph);

        sb.AppendLine(
            "    }");
    }


    private static void EmitBuild(
        StringBuilder sb,
        MappingClassInfo info,
        ImmutableArray<MappingClassInfo> allMappings,
        ImmutableHashSet<INamedTypeSymbol> rootEntityTypes,
        List<FluentEntityNavigationConvention.EntityForeignKeyGraph.Edge> entityGraph)
    {
        sb.AppendLine(
            "        public static void Build(in SelectionIR node, ref QueryPlanBuilder builder, bool isRoot)");

        sb.AppendLine(
            "        {");


        sb.AppendLine(
            "            if (isRoot)");
        sb.AppendLine(
            "            {");

        sb.AppendLine(
            "                builder.BeginCompositeChain(EntityId." + info.ModelType!.Name + ", \"" + info.ModelType.Name + "\");");
        
        if (info.CompositeStorageJoinInfo.Count > 0)
        {
            EmitCompositeStorageJoins(sb, info, allMappings, entityGraph);
        }

        sb.AppendLine(
            "            }");


        EmitScalarSelection(sb, info);


        EmitChildSelection(
            sb,
            info,
            allMappings,
            rootEntityTypes,
            entityGraph);


        sb.AppendLine(
            "        }");
    }
    
        private static void EmitChildSelection(
        StringBuilder sb,
        MappingClassInfo info,
        ImmutableArray<MappingClassInfo> allMappings,
        ImmutableHashSet<INamedTypeSymbol> rootEntityTypes,
        List<FluentEntityNavigationConvention.EntityForeignKeyGraph.Edge> entityGraph)
    {
        var navResult =
            EntityNavigationConvention.Resolve(
                info,
                allMappings,
                entityGraph,
                rootEntityTypes);


        var hasNavigations =
            navResult != null &&
            navResult.Navigations.Count > 0;


        var hasAutoAttachments =
            info.AutoChildAttachments.Count > 0;


        var hasGraph =
            info.Graph != null &&
            !string.IsNullOrWhiteSpace(
                info.Graph.GraphName);


        if (!hasNavigations &&
            !hasAutoAttachments &&
            !hasGraph)
        {
            return;
        }


        sb.AppendLine();


        if (hasAutoAttachments)
        {
            EmitCompositeChildAttachmentJoins(
                sb,
                info,
                allMappings,
                entityGraph);
        }


        if (hasGraph)
        {
            EmitGraphVertexResultJoins(
                sb,
                info,
                allMappings);
        }


        sb.AppendLine(
            "            foreach (var child in node.Children)");

        sb.AppendLine(
            "            {");

        sb.AppendLine(
            "                PlannerRegistry.Build(child.EntityId, child, ref builder, isRoot: false);");

        sb.AppendLine(
            "            }");
    }
        

    private static string ResolveRuntimeEntityId(
        INamedTypeSymbol type,
        ImmutableArray<MappingClassInfo> mappings)
    {
        foreach (var mapping in mappings)
        {
            foreach (var entity in mapping.Definition.Entities)
            {
                if (entity.EntityType == null)
                    continue;


                if (SymbolEqualityComparer.Default.Equals(
                        entity.EntityType,
                        type))
                {
                    return IdEmitter.StripEntitySuffix(
                        entity.EntityType.Name);
                }
            }
        }


        throw new InvalidOperationException(
            $"No EntityId mapping found for '{type.Name}'.");
    }

   private static void EmitGraphVertexResultJoins(
    StringBuilder sb,
    MappingClassInfo info,
    ImmutableArray<MappingClassInfo> allMappings)
{
    var g = info.Graph!;

    var graphAlias =
        $"{info.ModelType!.Name}_{g.EdgeLabel}_graph";


    sb.AppendLine(
        "            builder.AddGraphJoin(");

    sb.AppendLine(
        $"                EntityId.{info.ModelType.Name},");

    sb.AppendLine(
        $"                StorageEntityId.{IdEmitter.StripEntitySuffix(info.EntityType!.Name)},");

    sb.AppendLine(
        $"                \"{g.GraphName}\",");

    sb.AppendLine(
        $"                \"{g.EdgeLabel}\",");

    sb.AppendLine(
        $"                \"{g.EdgeKey}\",");

    sb.AppendLine(
        $"                \"{g.From.Label}\",");

    sb.AppendLine(
        $"                \"{g.From.GraphProperty}\",");

    sb.AppendLine(
        $"                \"{g.From.Alias ?? g.From.Label}\",");

    sb.AppendLine(
        $"                \"{g.FromJoinColumn}\",");

    sb.AppendLine(
        $"                \"{g.To.Label}\",");

    sb.AppendLine(
        $"                \"{g.To.GraphProperty}\",");

    sb.AppendLine(
        $"                \"{g.To.Alias ?? g.To.Label}\",");

    sb.AppendLine(
        $"                \"{g.ToJoinColumn}\",");

    sb.AppendLine(
        $"                \"{graphAlias}\");");


    foreach (var (vertex, isFrom) in new[]
             {
                 (g.From, true),
                 (g.To, false)
             })
    {
        var alias =
            vertex.Alias ?? vertex.Label;


        var relatedModel =
            allMappings.FirstOrDefault(m =>
                m.IsModel &&
                string.Equals(
                    m.EntityType?.Name,
                    vertex.Label,
                    StringComparison.Ordinal));


        if (relatedModel?.EntityType == null ||
            relatedModel.ModelType == null)
        {
            continue;
        }


        var joinColumn =
            isFrom
                ? g.FromJoinColumn
                : g.ToJoinColumn;


        var storageEntityName =
            IdEmitter.StripEntitySuffix(
                relatedModel.EntityType.Name);


        var graphColumnAlias =
            alias + joinColumn;


        var columnExpression =
            ColumnIdResolver.Resolve(
                relatedModel.EntityType,
                joinColumn);


        sb.AppendLine(
            "            foreach (var gc in node.Children)");

        sb.AppendLine(
            "            {");


        sb.AppendLine(
            $"                if (string.Equals(gc.OutputAlias, \"{alias}\", System.StringComparison.OrdinalIgnoreCase))");

        sb.AppendLine(
            "                {");


        sb.AppendLine(
            "                    builder.AddGraphResultJoin(");

        sb.AppendLine(
            $"                        \"{graphAlias}\",");

        sb.AppendLine(
            $"                        \"{graphColumnAlias}\",");

        sb.AppendLine(
            $"                        EntityId.{relatedModel.ModelType.Name},");

        sb.AppendLine(
            $"                        StorageEntityId.{storageEntityName},");

        sb.AppendLine(
            $"                        {columnExpression},");

        sb.AppendLine(
            "                        JoinKind.Left,");

        sb.AppendLine(
            "                        gc.OutputAlias);");


        sb.AppendLine(
            "                }");

        sb.AppendLine(
            "            }");
    }
}
    


    internal static bool IsCompositeInfo(
        MappingClassInfo info)
        => info.IsComposite;


    internal static List<(
    string FieldName,
    string EntityTypeName,
    string ColumnName,
    string StorageEntityName)>
    ComputeFieldMappingsEagerPublic(
        MappingClassInfo info,
        bool composite)
    => ComputeFieldMappingsEager(info, composite);


private static List<(
    string FieldName,
    string EntityTypeName,
    string ColumnName,
    string StorageEntityName)>
ComputeFieldMappingsEager(
    MappingClassInfo info,
    bool composite)
{
    var fields =
        new List<(
            string FieldName,
            string EntityTypeName,
            string ColumnName,
            string StorageEntityName)>();


    foreach (var field in info.FieldMaps)
    {
        if (field.IsNavigationKey)
            continue;


        var entityTypeName =
            string.IsNullOrWhiteSpace(field.DestinationEntity)
                ? info.EntityType?.Name ?? info.ModelType!.Name
                : field.DestinationEntity;


        // Resolve the actual entity symbol.
        var entitySymbol =
            info.Definition.Entities
                .FirstOrDefault(e =>
                    e.EntityType != null &&
                    string.Equals(
                        IdEmitter.StripEntitySuffix(
                            e.EntityType.Name),
                        IdEmitter.StripEntitySuffix(
                            entityTypeName),
                        StringComparison.OrdinalIgnoreCase))
                ?.EntityType;


        if (entitySymbol == null)
        {
            throw new InvalidOperationException(
                $"No entity mapping found for '{entityTypeName}' while processing field '{field.SourceName}' on model '{info.ModelType?.Name}'.");
        }


        var storageEntityName =
            IdEmitter.StripEntitySuffix(
                entitySymbol.Name);


        fields.Add(
            (
                field.SourceName,
                entitySymbol.Name,
                field.DestinationName,
                storageEntityName));
    }


    var primaryEntityName =
        info.EntityType?.Name ??
        info.ModelType!.Name;


    var resolved =
        new List<(
            string FieldName,
            string EntityTypeName,
            string ColumnName,
            string StorageEntityName)>();


    foreach (var group in fields.GroupBy(
                 f => f.FieldName,
                 StringComparer.Ordinal))
    {
        if (group.Count() == 1)
        {
            resolved.Add(group.Single());
            continue;
        }


        var primaryMatches =
            group
                .Where(f =>
                    string.Equals(
                        IdEmitter.StripEntitySuffix(
                            f.EntityTypeName),
                        IdEmitter.StripEntitySuffix(
                            primaryEntityName),
                        StringComparison.OrdinalIgnoreCase))
                .ToList();


        if (primaryMatches.Count == 1)
        {
            resolved.Add(primaryMatches[0]);
            continue;
        }


        if (primaryMatches.Count > 1)
        {
            throw new InvalidOperationException(
                $"Model '{info.ModelType?.Name}' has multiple field maps for '{group.Key}' from primary entity.");
        }


        throw new InvalidOperationException(
            $"Model '{info.ModelType?.Name}' has ambiguous field mappings for '{group.Key}'.");
    }


    return resolved;
}


    private static void EmitScalarSelection(
    StringBuilder sb,
    MappingClassInfo info)
{
    var fields =
        ComputeFieldMappingsEagerPublic(
            info,
            info.IsComposite);


    if (fields.Count == 0)
        return;


    sb.AppendLine();
    sb.AppendLine(
        "            foreach (var scalar in node.Scalars)");
    sb.AppendLine(
        "            {");

    sb.AppendLine(
        "                switch (scalar.FieldId)");
    sb.AppendLine(
        "                {");


    foreach (var group in fields.GroupBy(
                 x => x.FieldName,
                 StringComparer.Ordinal))
    {
        sb.AppendLine(
            $"                    case FieldId.{info.ModelType!.Name}.{group.Key}:");

        sb.AppendLine(
            "                    {");


        foreach (var field in group)
        {
            var entity =
                info.Definition.Entities
                    .FirstOrDefault(e =>
                        e.EntityType != null &&
                        string.Equals(
                            IdEmitter.StripEntitySuffix(e.EntityType.Name),
                            IdEmitter.StripEntitySuffix(field.EntityTypeName),
                            StringComparison.OrdinalIgnoreCase))
                    ?.EntityType;


            if (entity == null)
            {
                throw new InvalidOperationException(
                    $"Cannot resolve entity '{field.EntityTypeName}' for '{field.FieldName}'.");
            }


            var storageName =
                IdEmitter.StripEntitySuffix(entity.Name);


            var column =
                ColumnIdResolver.Resolve(
                    entity,
                    field.ColumnName);


            sb.AppendLine(
                "                        builder.AddColumn(");


            // ALWAYS the model runtime entity
            sb.AppendLine(
                $"                            EntityId.{IdEmitter.StripEntitySuffix(info.ModelType.Name)},");


            sb.AppendLine(
                $"                            StorageEntityId.{storageName},");


            sb.AppendLine(
                $"                            {column},");


            sb.AppendLine(
                "                            node.OutputAlias,");


            sb.AppendLine(
                "                            scalar.OutputAlias);");
        }


        sb.AppendLine(
            "                        break;");

        sb.AppendLine(
            "                    }");
    }


    sb.AppendLine(
        "                }");

    sb.AppendLine(
        "            }");
}


    private static void EmitRegistry(
        StringBuilder sb,
        List<MappingClassInfo> models)
    {
        sb.AppendLine(
            "public static class PlannerRegistry");

        sb.AppendLine(
            "{");


        sb.AppendLine(
            $"    public const ushort PlannerCount = {models.Count};");


        sb.AppendLine();


        EmitRegistryQuery(sb, models);

        EmitRegistryHelpers(sb, models);


        sb.AppendLine(
            "}");
    }


    private static void EmitRegistryQuery(
        StringBuilder sb,
        List<MappingClassInfo> models)
    {
        sb.AppendLine(
            "    public static void Build(");

        sb.AppendLine(
            "        ushort entityId,");

        sb.AppendLine(
            "        in SelectionIR selection,");

        sb.AppendLine(
            "        ref QueryPlanBuilder builder,");

        sb.AppendLine(
            "        bool isRoot)");

        sb.AppendLine(
            "    {");


        sb.AppendLine(
            "        switch (entityId)");

        sb.AppendLine(
            "        {");


        foreach (var model in models)
        {
            if (model.ModelType == null)
                continue;

            sb.AppendLine(
                $"            case EntityId.{model.ModelType.Name}:");

            sb.AppendLine(
                $"                {model.ModelType.Name}Planner.Build(selection, ref builder, isRoot);");

            sb.AppendLine(
                "                return;");
        }


        sb.AppendLine(
            "            default:");

        sb.AppendLine(
            "                ThrowUnknownEntity(entityId);");


        sb.AppendLine(
            "                return;");


        sb.AppendLine(
            "        }");


        sb.AppendLine(
            "    }");
    }


    private static void EmitRegistryHelpers(
        StringBuilder sb,
        List<MappingClassInfo> models)
    {
        sb.AppendLine();

        sb.AppendLine(
            "    public static bool IsValidEntity(ushort entityId)");

        sb.AppendLine(
            "        => entityId < (ushort)PlannerCount;");

        sb.AppendLine();


        sb.AppendLine(
            "    public static string GetEntityName(ushort entityId)");

        sb.AppendLine(
            "    {");

        sb.AppendLine(
            "        switch (entityId)");

        sb.AppendLine(
            "        {");


        foreach (var model in models)
        {
            if (model.ModelType == null)
                continue;


            var name =
                model.ModelType.Name;


            sb.AppendLine(
                $"            case EntityId.{name}:");


            sb.AppendLine(
                $"                return \"{name}\";");
        }


        sb.AppendLine(
            "            default:");

        sb.AppendLine(
            "                ThrowUnknownEntity(entityId);");

        sb.AppendLine(
            "                return string.Empty;");

        sb.AppendLine(
            "        }");

        sb.AppendLine(
            "    }");


        sb.AppendLine();


        sb.AppendLine(
            "    private static void ThrowUnknownEntity(ushort entityId)");

        sb.AppendLine(
            "        => throw new ArgumentException($\"Unknown entity runtime ID: {entityId}\");");
    }


    internal static List<ChildLinkInfo> ComputeChildLinks(
        MappingClassInfo parent,
        ImmutableArray<MappingClassInfo> mappings,
        Dictionary<string, NavigationResolutionResult?> navResults,
        List<FluentEntityNavigationConvention.EntityForeignKeyGraph.Edge> entityGraph)
    {
        var result =
            new List<ChildLinkInfo>();


        if (parent.ModelType == null)
            return result;


        if (!navResults.TryGetValue(
                parent.ModelType.Name,
                out var nav) ||
            nav == null)
        {
            return result;
        }


        foreach (var navigation in nav.Navigations)
        {
            var child =
                mappings.FirstOrDefault(x =>
                    x.ModelType != null &&
                    string.Equals(
                        x.ModelType.Name,
                        navigation.TargetModel.Name,
                        StringComparison.Ordinal));


            if (child == null)
                continue;


            var entity =
                child.EntityType ??
                child.Definition.Entities
                    .FirstOrDefault(x => x.IsPrimary)
                    ?.EntityType;


            if (entity == null)
                continue;


            var property =
                parent.ModelType
                    .GetMembers()
                    .OfType<IPropertySymbol>()
                    .FirstOrDefault(p =>
                        string.Equals(
                            p.Name,
                            navigation.NavigationName,
                            StringComparison.Ordinal));


            var isCollection =
                property?.Type is INamedTypeSymbol named &&
                named.IsGenericType;


            result.Add(
                new ChildLinkInfo(
                    navigation.NavigationName,
                    child.ModelType.Name,
                    entity.Name,
                    isCollection));
        }


        return result
            .Distinct()
            .ToList();
    }


    internal sealed record ChildLinkInfo(
        string NavigationName,
        string ChildModelName,
        string ChildEntityName,
        bool IsCollection);
}