using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using CoffeeBeanery.GraphQL.Core.Mapping.Generators.Model;
using CoffeeBeanery.GraphQL.Core.Mapping.Generators.Passes;

namespace CoffeeBeanery.GraphQL.Core.Mapping.Generators.Emit
{
    internal static class PlannerEmitter
    {
        private static readonly ImmutableHashSet<INamedTypeSymbol> EmptyEntityTypes =
            ImmutableHashSet.Create<INamedTypeSymbol>(SymbolEqualityComparer.Default);

        public static string Emit(
            ImmutableArray<MappingClassInfo> allMappings,
            ImmutableHashSet<INamedTypeSymbol> rootEntityTypes,
            ImmutableDictionary<(INamedTypeSymbol, string), string> fluentInverseNav)
        {
            var models = allMappings
                .Where(m => m.IsModel)
                .OrderBy(m => m.ModelType.Name, System.StringComparer.Ordinal)
                .ToList();

            var navResults = models.ToDictionary(
                m => m.ModelType.Name,
                m => EntityNavigationConvention.ResolveQuietly(m, rootEntityTypes, fluentInverseNav),
                System.StringComparer.Ordinal);

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("#nullable enable");
            sb.AppendLine("using System.Collections.Immutable;");
            sb.AppendLine("using CoffeeBeanery.GraphQL.Core.Runtime;");
            sb.AppendLine();
            sb.AppendLine("namespace CoffeeBeanery.GraphQL.Core.Runtime");
            sb.AppendLine("{");

            foreach (var model in models)
            {
                var navResult = navResults.TryGetValue(model.ModelType.Name, out var r) ? r : null;
                EmitPlanner(sb, model, allMappings, navResult);
            }

            EmitRegistry(sb, models);

            sb.AppendLine("}");
            return sb.ToString();
        }

        // ---------------------------------------------------------------
        // Per-model planner
        // ---------------------------------------------------------------

        private static void EmitPlanner(
            StringBuilder sb,
            MappingClassInfo info,
            ImmutableArray<MappingClassInfo> allMappings,
            NavigationResolutionResult? navResult)
        {
            sb.AppendLine($"    public static class {info.ModelType.Name}Planner");
            sb.AppendLine("    {");

            EmitBuildQuery(sb, info, allMappings, navResult);
            EmitBuildMutation(sb, info, allMappings, navResult);

            sb.AppendLine("    }");
            sb.AppendLine();
        }

        private static bool IsComposite(MappingClassInfo info) =>
            info.ModelToEntity
                .Select(k => k.EntityType.Name)
                .Distinct(System.StringComparer.Ordinal)
                .Count() > 1;

        // ---------------------------------------------------------------
        // Build (query)
        // ---------------------------------------------------------------

        private static void EmitBuildQuery(
            StringBuilder sb,
            MappingClassInfo info,
            ImmutableArray<MappingClassInfo> allMappings,
            NavigationResolutionResult? navResult)
        {
            sb.AppendLine("        public static void Build(in SelectionIR node, ref QueryPlanBuilder builder)");
            sb.AppendLine("        {");

            var fieldMappings = ComputeFieldMappings(info).ToList();
            var childLinks    = ComputeChildLinks(info, allMappings, navResult).ToList();

            if (IsComposite(info))
            {
                EmitCompositeQuery(sb, info, allMappings, fieldMappings, childLinks);
                return;
            }

            EmitSimpleQuery(sb, info, fieldMappings, childLinks);
        }

        private static void EmitSimpleQuery(
            StringBuilder sb,
            MappingClassInfo info,
            List<FieldMapping> fieldMappings,
            List<ChildLink> childLinks)
        {
            if (fieldMappings.Count > 0)
            {
                sb.AppendLine("            foreach (var scalar in node.Scalars)");
                sb.AppendLine("            {");
                sb.AppendLine("                switch (scalar.FieldId)");
                sb.AppendLine("                {");

                foreach (var fm in fieldMappings)
                {
                    sb.AppendLine($"                    case FieldId.{info.ModelType.Name}.{fm.FieldName}:");
                    sb.AppendLine($"                        builder.AddColumn(");
                    sb.AppendLine($"                            EntityId.{info.EntityType.Name},");
                    sb.AppendLine($"                            StorageEntityId.{fm.EntityTypeName},");
                    sb.AppendLine($"                            ColumnId.{fm.EntityTypeName}.{fm.ColumnName},");
                    sb.AppendLine($"                            node.OutputAlias,");
                    sb.AppendLine($"                            scalar.OutputAlias);");
                    sb.AppendLine("                        break;");
                }

                sb.AppendLine("                }");
                sb.AppendLine("            }");
            }

            EmitQueryChildLinks(sb, info.ModelType.Name, childLinks, composite: false);

            sb.AppendLine("        }");
            sb.AppendLine();
        }

        private static void EmitCompositeQuery(
            StringBuilder sb,
            MappingClassInfo info,
            ImmutableArray<MappingClassInfo> allMappings,
            List<FieldMapping> fieldMappings,
            List<ChildLink> childLinks)
        {
            if (fieldMappings.Count > 0)
            {
                sb.AppendLine("            foreach (var scalar in node.Scalars)");
                sb.AppendLine("            {");
                sb.AppendLine("                switch (scalar.FieldId)");
                sb.AppendLine("                {");

                foreach (var fm in fieldMappings)
                {
                    var entityIdName = ResolveEntityIdName(fm.EntityTypeName, allMappings);
                    sb.AppendLine($"                    case FieldId.{info.ModelType.Name}.{fm.FieldName}:");
                    sb.AppendLine($"                        builder.AddColumn(");
                    sb.AppendLine($"                            EntityId.{entityIdName},");
                    sb.AppendLine($"                            StorageEntityId.{fm.EntityTypeName},");
                    sb.AppendLine($"                            ColumnId.{fm.EntityTypeName}.{fm.ColumnName},");
                    sb.AppendLine($"                            node.OutputAlias,");
                    sb.AppendLine($"                            scalar.OutputAlias);");
                    sb.AppendLine("                        break;");
                }

                sb.AppendLine("                }");
                sb.AppendLine("            }");
            }

            EmitQueryChildLinks(sb, info.ModelType.Name, childLinks, composite: true);

            sb.AppendLine("        }");
            sb.AppendLine();
        }

        private static void EmitQueryChildLinks(
            StringBuilder sb,
            string modelTypeName,
            List<ChildLink> childLinks,
            bool composite)
        {
            if (childLinks.Count == 0)
                return;

            sb.AppendLine();
            sb.AppendLine("            foreach (var child in node.Children)");
            sb.AppendLine("            {");
            sb.AppendLine("                switch (child.EntityId)");
            sb.AppendLine("                {");

            foreach (var group in childLinks.GroupBy(l => l.ChildModelName, System.StringComparer.Ordinal))
            {
                sb.AppendLine($"                    case EntityId.{group.Key}:");
                var links = group.ToList();

                if (links.Count == 1)
                {
                    EmitAddJoin(sb, modelTypeName, links[0], indent: 24);
                }
                else
                {
                    for (var i = 0; i < links.Count; i++)
                    {
                        var l  = links[i];
                        var kw = i == 0 ? "if" : "else if";
                        sb.AppendLine($"                        {kw} (child.OutputAlias == \"{l.NavigationName}\")");
                        sb.AppendLine($"                        {{");
                        EmitAddJoin(sb, modelTypeName, l, indent: 28);
                        sb.AppendLine($"                        }}");
                    }
                }

                sb.AppendLine($"                        {group.Key}Planner.Build(child, ref builder);");
                sb.AppendLine("                        break;");
            }

            sb.AppendLine("                }");
            sb.AppendLine("            }");
        }

        private static void EmitAddJoin(
            StringBuilder sb,
            string modelTypeName,
            ChildLink l,
            int indent)
        {
            var pad = new string(' ', indent);
            sb.AppendLine($"{pad}builder.AddJoin(");
            sb.AppendLine($"{pad}    EntityId.{modelTypeName},");
            sb.AppendLine($"{pad}    StorageEntityId.{l.ParentEntityName},");
            sb.AppendLine($"{pad}    EntityId.{l.ChildModelName},");
            sb.AppendLine($"{pad}    StorageEntityId.{l.ChildEntityName},");
            sb.AppendLine($"{pad}    ColumnId.{l.ParentEntityName}.{l.ParentJoinColumn},");
            sb.AppendLine($"{pad}    ColumnId.{l.ChildEntityName}.{l.ChildJoinColumn},");
            sb.AppendLine($"{pad}    JoinKind.Left,");
            sb.AppendLine($"{pad}    child.OutputAlias);");
        }

        // ---------------------------------------------------------------
        // BuildMutation
        // ---------------------------------------------------------------

        private static void EmitBuildMutation(
            StringBuilder sb,
            MappingClassInfo info,
            ImmutableArray<MappingClassInfo> allMappings,
            NavigationResolutionResult? navResult)
        {
            sb.AppendLine("        public static void BuildMutation(in MutationIR node, ref MutationPlanBuilder builder)");
            sb.AppendLine("        {");

            if (IsComposite(info))
            {
                EmitCompositeMutation(sb, info, allMappings);
            }
            else
            {
                EmitSimpleMutation(
                    sb,
                    info,
                    ComputeChildLinks(info, allMappings, navResult).ToList());
            }

            sb.AppendLine("        }");
        }

        private static void EmitCompositeMutation(
            StringBuilder sb,
            MappingClassInfo info,
            ImmutableArray<MappingClassInfo> allMappings)
        {
            var primaryEntity = info.ModelToEntity
                .FirstOrDefault(x => x.IsPrimary);

            if (primaryEntity is null)
            {
                sb.AppendLine(
                    "            // Composite mapping has no primary entity.");
                return;
            }

            var primaryStorageEntity = primaryEntity.EntityType.Name;

            var fieldMappings = ComputeFieldMappings(info)
                .Where(x => x.EntityTypeName == primaryStorageEntity)
                .ToList();


            // ------------------------------------------------------------
            // 1. Build related child entities first
            // ------------------------------------------------------------

            sb.AppendLine("            foreach (var child in node.Children)");
            sb.AppendLine("            {");
            sb.AppendLine("                switch (child.EntityId)");
            sb.AppendLine("                {");


            foreach (var child in info.ModelToEntity
                         .Where(x => !x.IsPrimary)
                         .Select(x => x.EntityType)
                         .Distinct(SymbolEqualityComparer.Default)
                         .OrderBy(x => x.Name))
            {
                sb.AppendLine(
                    $"                    case EntityId.{child.Name}:");

                sb.AppendLine(
                    $"                        {child.Name}Planner.BuildMutation(child, ref builder);");

                sb.AppendLine("                        break;");
            }


            sb.AppendLine("                }");
            sb.AppendLine("            }");

            sb.AppendLine();


            // ------------------------------------------------------------
            // 2. Build primary entity values only
            // ------------------------------------------------------------

            sb.AppendLine(
                "            var entityValues = ImmutableArray.CreateBuilder<FieldValue>(node.Values.Length);");

            sb.AppendLine();

            sb.AppendLine("            foreach (var v in node.Values)");
            sb.AppendLine("            {");
            sb.AppendLine("                switch (v.FieldId)");
            sb.AppendLine("                {");


            foreach (var fm in fieldMappings)
            {
                sb.AppendLine(
                    $"                    case FieldId.{info.ModelType.Name}.{fm.FieldName}:");

                sb.AppendLine(
                    "                        entityValues.Add(new FieldValue(");

                sb.AppendLine(
                    $"                            ColumnId.{fm.EntityTypeName}.{fm.ColumnName},");

                sb.AppendLine(
                    "                            v.RawValue));");

                sb.AppendLine("                        break;");
            }


            sb.AppendLine("                }");
            sb.AppendLine("            }");

            sb.AppendLine();


            // ------------------------------------------------------------
            // 3. Resolve foreign key relationships
            // ------------------------------------------------------------

            sb.AppendLine(
                "            var cteChildren = ImmutableArray.CreateBuilder<MutationCteNode>();");


            foreach (var relation in info.ModelToEntity
                         .Where(x => !x.IsPrimary &&
                                     !string.IsNullOrWhiteSpace(x.AliasProperty)))
            {
                var relatedEntity = relation.EntityType.Name;

                sb.AppendLine();

                sb.AppendLine(
                    "            foreach (var child in node.Children)");

                sb.AppendLine("            {");

                sb.AppendLine(
                    $"                if (child.OutputAlias == \"{relation.AliasProperty}\")");

                sb.AppendLine("                {");

                sb.AppendLine(
                    "                    string? key = null;");

                sb.AppendLine();

                sb.AppendLine(
                    "                    foreach (var v in child.Values)");

                sb.AppendLine("                    {");

                sb.AppendLine(
                    $"                        if (v.FieldId == FieldId.{relatedEntity}.{relation.ToColumn})");

                sb.AppendLine("                        {");

                sb.AppendLine(
                    "                            key = v.RawValue;");

                sb.AppendLine(
                    "                            break;");

                sb.AppendLine("                        }");

                sb.AppendLine("                    }");

                sb.AppendLine();


                sb.AppendLine(
                    "                    if (key != null)");

                sb.AppendLine("                    {");

                sb.AppendLine(
                    "                        cteChildren.Add(new MutationCteNode(");

                sb.AppendLine(
                    $"                            EntityId.{relatedEntity},");

                sb.AppendLine(
                    $"                            StorageEntityId.{relatedEntity},");

                sb.AppendLine(
                    $"                            \"{relation.AliasProperty}\",");

                sb.AppendLine(
                    $"                            ImmutableArray.Create(new FieldValue(ColumnId.{relatedEntity}.{relation.ToColumn}, key)),");

                sb.AppendLine(
                    "                            ImmutableArray<MutationCteNode>.Empty));");

                sb.AppendLine("                    }");

                sb.AppendLine("                }");

                sb.AppendLine("            }");
            }


            sb.AppendLine();


            // ------------------------------------------------------------
            // 4. Add root CTE node using real storage entity
            // ------------------------------------------------------------

            sb.AppendLine(
                "            builder.AddCteRoot(new MutationCteNode(");

            sb.AppendLine(
                $"                EntityId.{info.ModelType.Name},");

            sb.AppendLine(
                $"                StorageEntityId.{primaryStorageEntity},");

            sb.AppendLine(
                "                node.OutputAlias,");

            sb.AppendLine(
                "                entityValues.ToImmutable(),");

            sb.AppendLine(
                "                cteChildren.ToImmutable()));");
        }

        private static void EmitSimpleMutation(
            StringBuilder sb,
            MappingClassInfo info,
            List<ChildLink> childLinks)
        {
            var primaryEntity = info.ModelToEntity
                .FirstOrDefault(x => x.IsPrimary);

            if (primaryEntity is null)
            {
                sb.AppendLine(
                    "            // No primary storage entity defined.");
                return;
            }

            var storageEntityName = primaryEntity.EntityType.Name;

            var fieldMappings = ComputeFieldMappings(info).ToList();


            sb.AppendLine(
                "            var values = ImmutableArray.CreateBuilder<FieldValue>(node.Values.Length);");

            sb.AppendLine();

            sb.AppendLine("            foreach (var v in node.Values)");
            sb.AppendLine("            {");
            sb.AppendLine("                switch (v.FieldId)");
            sb.AppendLine("                {");

            foreach (var fm in fieldMappings)
            {
                sb.AppendLine(
                    $"                    case FieldId.{info.ModelType.Name}.{fm.FieldName}:");

                sb.AppendLine(
                    "                        values.Add(new FieldValue(");

                sb.AppendLine(
                    $"                            ColumnId.{fm.EntityTypeName}.{fm.ColumnName},");

                sb.AppendLine(
                    "                            v.RawValue));");

                sb.AppendLine("                        break;");
            }

            sb.AppendLine("                }");
            sb.AppendLine("            }");

            sb.AppendLine();

            sb.AppendLine("            builder.AddRow(");
            sb.AppendLine($"                EntityId.{info.ModelType.Name},");
            sb.AppendLine($"                StorageEntityId.{storageEntityName},");
            sb.AppendLine("                node.OutputAlias,");
            sb.AppendLine("                values.ToImmutable());");


            if (childLinks.Count == 0)
                return;


            sb.AppendLine();

            sb.AppendLine("            foreach (var child in node.Children)");
            sb.AppendLine("            {");
            sb.AppendLine("                switch (child.EntityId)");
            sb.AppendLine("                {");


            foreach (var group in childLinks
                         .GroupBy(x => x.ChildModelName)
                         .OrderBy(x => x.Key))
            {
                sb.AppendLine(
                    $"                    case EntityId.{group.Key}:");

                sb.AppendLine(
                    $"                        {group.Key}Planner.BuildMutation(child, ref builder);");

                sb.AppendLine("                        break;");
            }


            sb.AppendLine("                }");
            sb.AppendLine("            }");
        }

        // ---------------------------------------------------------------
        // Registry
        // ---------------------------------------------------------------

        private static void EmitRegistry(StringBuilder sb, List<MappingClassInfo> models)
        {
            sb.AppendLine("    /// <summary>");
            sb.AppendLine("    /// Single entry point for plan building. Called exactly once — at the");
            sb.AppendLine("    /// root entity resolved by the adapter. All subsequent dispatch is");
            sb.AppendLine("    /// direct planner-to-planner, never back through this registry.");
            sb.AppendLine("    /// </summary>");
            sb.AppendLine("    public static class PlannerRegistry");
            sb.AppendLine("    {");
            sb.AppendLine($"        public const ushort PlannerCount = {models.Count};");
            sb.AppendLine();

            sb.AppendLine("        public static void Build(");
            sb.AppendLine("            ushort entityId,");
            sb.AppendLine("            in SelectionIR selection,");
            sb.AppendLine("            ref QueryPlanBuilder builder)");
            sb.AppendLine("        {");
            sb.AppendLine("            switch (entityId)");
            sb.AppendLine("            {");

            foreach (var m in models)
            {
                sb.AppendLine($"                case EntityId.{m.ModelType.Name}:");
                sb.AppendLine($"                    {m.ModelType.Name}Planner.Build(selection, ref builder);");
                sb.AppendLine("                    return;");
            }

            sb.AppendLine("                default:");
            sb.AppendLine("                    ThrowUnknownEntity(entityId);");
            sb.AppendLine("                    return;");
            sb.AppendLine("            }");
            sb.AppendLine("        }");
            sb.AppendLine();

            sb.AppendLine("        public static void BuildMutation(");
            sb.AppendLine("            ushort entityId,");
            sb.AppendLine("            in MutationIR mutation,");
            sb.AppendLine("            ref MutationPlanBuilder builder)");
            sb.AppendLine("        {");
            sb.AppendLine("            switch (entityId)");
            sb.AppendLine("            {");

            foreach (var m in models)
            {
                sb.AppendLine($"                case EntityId.{m.ModelType.Name}:");
                sb.AppendLine($"                    {m.ModelType.Name}Planner.BuildMutation(mutation, ref builder);");
                sb.AppendLine("                    return;");
            }

            sb.AppendLine("                default:");
            sb.AppendLine("                    ThrowUnknownEntity(entityId);");
            sb.AppendLine("                    return;");
            sb.AppendLine("            }");
            sb.AppendLine("        }");
            sb.AppendLine();

            sb.AppendLine("        public static bool IsValidEntity(ushort entityId) =>");
            sb.AppendLine("            entityId < PlannerCount;");
            sb.AppendLine();

            sb.AppendLine("        public static string GetEntityName(ushort entityId) => entityId switch");
            sb.AppendLine("        {");
            foreach (var m in models)
                sb.AppendLine($"            EntityId.{m.ModelType.Name} => \"{m.ModelType.Name}\",");
            sb.AppendLine("            _ => $\"<unknown:{entityId}>\",");
            sb.AppendLine("        };");
            sb.AppendLine();

            sb.AppendLine("        private static void ThrowUnknownEntity(ushort entityId) =>");
            sb.AppendLine("            throw new global::System.InvalidOperationException(");
            sb.AppendLine("                $\"No planner registered for entity {entityId} " +
                          "({GetEntityName(entityId)}). Did you forget to add a mapping class?\");");
            sb.AppendLine("    }");
        }

        // ---------------------------------------------------------------
        // Field mapping helpers
        // ---------------------------------------------------------------

        private sealed record FieldMapping(
            string FieldName,
            string EntityTypeName,
            string ColumnName);

        private static IEnumerable<FieldMapping> ComputeFieldMappings(MappingClassInfo info)
        {
            if (info.EntityType is null && !IsComposite(info)) yield break;

            var manualByField = info.FieldMaps
                .Where(f => !f.IsGenerated)
                .GroupBy(f => f.SourceName, System.StringComparer.OrdinalIgnoreCase)
                .ToDictionary(g => g.Key, g => g.First(),
                    System.StringComparer.OrdinalIgnoreCase);

            var fkColumns = IsComposite(info)
                ? new HashSet<string>(System.StringComparer.OrdinalIgnoreCase)
                : new HashSet<string>(
                    info.ModelToEntity
                        .Where(k => !SymbolEqualityComparer.Default.Equals(k.EntityType, info.EntityType))
                        .Select(k => k.FromColumn ?? string.Empty),
                    System.StringComparer.OrdinalIgnoreCase);

            var entityPropsByEntity = info.ModelToEntity
                .GroupBy(k => k.EntityType.Name, System.StringComparer.Ordinal)
                .ToDictionary(
                    g => g.Key,
                    g => g.First().EntityType.GetMembers()
                        .OfType<IPropertySymbol>()
                        .Where(p => p.GetMethod is not null && !p.IsStatic)
                        .ToDictionary(p => p.Name, System.StringComparer.OrdinalIgnoreCase),
                    System.StringComparer.Ordinal);

            foreach (var modelProp in IdEmitter.GetScalarProperties(info.ModelType))
            {
                if (fkColumns.Contains(modelProp.Name)) continue;

                if (manualByField.TryGetValue(modelProp.Name, out var manual))
                {
                    yield return new FieldMapping(
                        FieldName: modelProp.Name,
                        EntityTypeName: manual.DestinationEntity ?? info.EntityType?.Name ?? string.Empty,
                        ColumnName: manual.DestinationName ?? modelProp.Name);
                    continue;
                }

                foreach (var kvp in entityPropsByEntity
                             .OrderByDescending(x =>
                                 x.Key == info.EntityType?.Name))
                {
                    if (kvp.Value.TryGetValue(modelProp.Name, out var entityProp) &&
                        IdEmitter.IsScalarProperty(entityProp.Type))
                    {
                        yield return new FieldMapping(
                            FieldName: modelProp.Name,
                            EntityTypeName: kvp.Key,
                            ColumnName: entityProp.Name);
                        break;
                    }
                }
            }
        }

        // ---------------------------------------------------------------
        // Child link helpers
        // ---------------------------------------------------------------

        private sealed record ChildLink(
            string NavigationName,
            string ChildModelName,
            string ParentEntityName,
            string ParentJoinColumn,
            string ChildEntityName,
            string ChildJoinColumn,
            bool IsCollection);

        private static IEnumerable<ChildLink> ComputeChildLinks(
            MappingClassInfo info,
            ImmutableArray<MappingClassInfo> allMappings,
            NavigationResolutionResult? navResult)
        {
            if (info.EntityType is null) yield break;

            var seen = new HashSet<string>(System.StringComparer.OrdinalIgnoreCase);

            if (navResult is not null)
            {
                foreach (var nav in navResult.Navigations)
                {
                    var childMapping = allMappings.FirstOrDefault(m =>
                        SymbolEqualityComparer.Default.Equals(m.EntityType, nav.RelatedEntityType));

                    if (childMapping is null) continue;

                    var childModelName = childMapping.ModelType.Name;
                    var key = $"{childModelName}|{nav.NavigationName}";
                    if (!seen.Add(key)) continue;

                    yield return new ChildLink(
                        NavigationName: nav.NavigationName,
                        ChildModelName: childModelName,
                        ParentEntityName: info.EntityType.Name,
                        ParentJoinColumn: nav.ForeignKeyProperty,
                        ChildEntityName: nav.RelatedEntityType.Name,
                        ChildJoinColumn: nav.PrincipalKeyProperty,
                        IsCollection: nav.IsCollection);
                }
            }

            var parentKeyName = info.EntityType.Name + "Key";
            var parentHasKey  = info.EntityType.GetMembers().OfType<IPropertySymbol>()
                .Any(p => p.Name == parentKeyName);

            if (!parentHasKey) yield break;

            var modelProps = info.ModelType.GetMembers().OfType<IPropertySymbol>()
                .Where(p => p.GetMethod is not null && !p.IsStatic);

            foreach (var prop in modelProps)
            {
                var elementType = UnwrapCollection(prop.Type);
                var unwrapped   = UnwrapNullable(elementType);

                if (unwrapped is not INamedTypeSymbol related) continue;
                if (IdEmitter.IsScalarProperty(related)) continue;
                if (SymbolEqualityComparer.Default.Equals(related, info.ModelType)) continue;
                if (related.Name == "Wrapper") continue;

                var childMapping = allMappings.FirstOrDefault(m =>
                    SymbolEqualityComparer.Default.Equals(m.ModelType, related));

                if (childMapping?.EntityType is null) continue;

                var key = $"{childMapping.ModelType.Name}|{prop.Name}";
                if (!seen.Add(key)) continue;

                INamedTypeSymbol? childEntityType = null;
                foreach (var link in childMapping.ModelToEntity)
                {
                    var hasFk = link.EntityType.GetMembers().OfType<IPropertySymbol>()
                        .Any(p => p.Name == parentKeyName);
                    if (hasFk) { childEntityType = link.EntityType; break; }
                }

                if (childEntityType is null) continue;

                yield return new ChildLink(
                    NavigationName: prop.Name,
                    ChildModelName: childMapping.ModelType.Name,
                    ParentEntityName: info.EntityType.Name,
                    ParentJoinColumn: parentKeyName,
                    ChildEntityName: childEntityType.Name,
                    ChildJoinColumn: parentKeyName,
                    IsCollection: IsCollectionType(prop.Type));
            }
        }

        // ---------------------------------------------------------------
        // Resolution helpers
        // ---------------------------------------------------------------

        /// <summary>
        /// Resolves the EntityId constant name for a given entity type name.
        /// EntityId constants use model names — this finds which model owns the entity type
        /// via its ModelToEntity links, handling composite models where EntityType is null.
        /// </summary>
        private static string ResolveEntityIdName(
            string entityTypeName,
            ImmutableArray<MappingClassInfo> allMappings)
        {
            var owningModel = allMappings.FirstOrDefault(m =>
                m.ModelToEntity.Any(link =>
                    string.Equals(link.EntityType.Name,
                        entityTypeName,
                        System.StringComparison.Ordinal)));

            return owningModel?.ModelType.Name ?? entityTypeName;
        }

        // ---------------------------------------------------------------
        // Type helpers
        // ---------------------------------------------------------------

        private static ITypeSymbol UnwrapCollection(ITypeSymbol type)
        {
            if (type is INamedTypeSymbol { IsGenericType: true } named &&
                named.TypeArguments.Length == 1 &&
                named.Name is "List" or "IEnumerable" or "ICollection" or "IList")
                return named.TypeArguments[0];
            return type;
        }

        private static bool IsCollectionType(ITypeSymbol type) =>
            type is INamedTypeSymbol { IsGenericType: true } named &&
            named.TypeArguments.Length == 1 &&
            named.Name is "List" or "IEnumerable" or "ICollection" or "IList";

        private static ITypeSymbol UnwrapNullable(ITypeSymbol type) =>
            type is INamedTypeSymbol { OriginalDefinition.SpecialType: SpecialType.System_Nullable_T } n
                ? n.TypeArguments[0]
                : type;
    }
}