using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using CoffeeBeanery.GraphQL.Core.Mapping.Generators.Model;
using CoffeeBeanery.GraphQL.Core.Mapping.Generators.Passes;

namespace CoffeeBeanery.GraphQL.Core.Mapping.Generators.Emit
{
    internal static class PlannerEmitter
    {
        public static string Emit(
            ImmutableArray<MappingClassInfo> allMappings,
            ImmutableHashSet<INamedTypeSymbol> rootEntityTypes,
            ImmutableDictionary<(INamedTypeSymbol, string), string> fluentInverseNav)
        {
            var models = allMappings
                .Where(m => m.IsModel)
                .OrderBy(m => m.ModelType.Name, System.StringComparer.Ordinal)
                .ToList();

            var navResults = models.ToDictionary(
                m => m.ModelType.Name,
                m => EntityNavigationConvention.Resolve(m, rootEntityTypes, fluentInverseNav),
                System.StringComparer.Ordinal);

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("#nullable enable");
            sb.AppendLine("using System.Collections.Immutable;");
            sb.AppendLine("using CoffeeBeanery.GraphQL.Core.Runtime;");
            sb.AppendLine();
            sb.AppendLine("namespace CoffeeBeanery.GraphQL.Core.Runtime");
            sb.AppendLine("{");

            foreach (var model in models)
            {
                var navResult = navResults.TryGetValue(model.ModelType.Name, out var r) ? r : null;
                EmitPlanner(sb, model, allMappings, models, navResult);
            }

            EmitRegistry(sb, models);

            sb.AppendLine("}");
            return sb.ToString();
        }

        // ---------------------------------------------------------------
        // Per-model planner class
        // ---------------------------------------------------------------

        private static void EmitPlanner(
            StringBuilder sb,
            MappingClassInfo info,
            ImmutableArray<MappingClassInfo> allMappings,
            List<MappingClassInfo> models,
            NavigationResolutionResult? navResult)
        {
            sb.AppendLine($"    public static class {info.ModelType.Name}Planner");
            sb.AppendLine("    {");

            var composite = IsCompositeInfo(info);

            EmitBuildQuery(sb, info, allMappings, navResult, composite);
            EmitBuildMutation(sb, info, allMappings, models, navResult, composite);

            sb.AppendLine("    }");
            sb.AppendLine();
        }

        // ---------------------------------------------------------------
        // IsComposite
        // ---------------------------------------------------------------

        internal static bool IsCompositeInfo(MappingClassInfo info)
        {
            string? firstName = null;
            foreach (var k in info.ModelToEntity)
            {
                var name = k.EntityType?.Name;
                if (name is null) continue;
                if (firstName is null) firstName = name;
                else if (!string.Equals(firstName, name, System.StringComparison.Ordinal)) return true;
            }
            return false;
        }

        // ---------------------------------------------------------------
        // Build (SELECT)
        // ---------------------------------------------------------------

        private static void EmitBuildQuery(
            StringBuilder sb,
            MappingClassInfo info,
            ImmutableArray<MappingClassInfo> allMappings,
            NavigationResolutionResult? navResult,
            bool composite)
        {
            sb.AppendLine("        public static void Build(in SelectionIR node, ref QueryPlanBuilder builder)");
            sb.AppendLine("        {");

            if (composite)
            {
                var primaryLink = info.ModelToEntity.FirstOrDefault(k => k.IsPrimary);
                var primaryEntityType = primaryLink?.EntityType
                    ?? throw new InvalidOperationException(
                        $"Composite model {info.ModelType.Name} has no primary storage entity.");

                // ---- Place 1: primary entity columns → AddRootColumn ----
                foreach (var prop in IdEmitter.GetScalarProperties(primaryEntityType))
                {
                    sb.AppendLine($"            builder.AddRootColumn(");
                    sb.AppendLine($"                EntityId.{info.ModelType.Name},");
                    sb.AppendLine($"                StorageEntityId.{primaryEntityType.Name},");
                    sb.AppendLine($"                ColumnId.{primaryEntityType.Name}.{prop.Name},");
                    sb.AppendLine($"                node.OutputAlias, \"{ToCamel(prop.Name)}\");");
                }
                sb.AppendLine();

                // ---- FK-alias secondary joins (InnerCustomer / OuterCustomer etc.) ----
                foreach (var link in info.ModelToEntity.Where(k =>
                    !k.IsPrimary && k.EntityType != null && k.AliasProperty != null))
                {
                    var relatedEntityType = link.EntityType!;
                    var alias             = link.AliasProperty!;
                    var fkColumn          = alias + "Id";

                    var relatedModel = allMappings.FirstOrDefault(m =>
                        m.IsModel &&
                        string.Equals(m.EntityType?.Name, relatedEntityType.Name,
                            System.StringComparison.Ordinal));
                    if (relatedModel is null) continue;

                    sb.AppendLine($"            builder.AddJoin(");
                    sb.AppendLine($"                EntityId.{info.ModelType.Name},");
                    sb.AppendLine($"                StorageEntityId.{primaryEntityType.Name},");
                    sb.AppendLine($"                EntityId.{relatedModel.ModelType.Name},");
                    sb.AppendLine($"                StorageEntityId.{relatedEntityType.Name},");
                    sb.AppendLine($"                ColumnId.{primaryEntityType.Name}.{fkColumn},");
                    sb.AppendLine($"                ColumnId.{relatedEntityType.Name}.Id,");
                    sb.AppendLine($"                JoinKind.Left, \"{alias}\");");
                    sb.AppendLine();

                    // ---- Place 2: join segment columns → AddColumn ----
                    // One column per entity property, aliased to the MODEL field name.
                    // FieldMaps.DestinationName = entity column (FullName)
                    // FieldMaps.SourceName      = model field  (FullNaming)
                    // No dictionary needed — look up rename directly per column.
                    foreach (var prop in IdEmitter.GetScalarProperties(relatedEntityType))
                    {
                        var modelFieldName = relatedModel.FieldMaps
                            .FirstOrDefault(f =>
                                !f.IsGenerated &&
                                string.Equals(f.DestinationName, prop.Name,
                                    System.StringComparison.OrdinalIgnoreCase))
                            ?.SourceName
                            ?? prop.Name;   // no rename declared — model field same name as entity column

                        sb.AppendLine($"            builder.AddColumn(");
                        sb.AppendLine($"                EntityId.{relatedModel.ModelType.Name},");
                        sb.AppendLine($"                StorageEntityId.{relatedEntityType.Name},");
                        sb.AppendLine($"                ColumnId.{relatedEntityType.Name}.{prop.Name},");
                        sb.AppendLine($"                \"{alias}\", \"{ToCamel(modelFieldName)}\");");
                    }
                    sb.AppendLine();
                }

                // Navigation-based child links, excluding composite children.
                var childLinks = ComputeChildLinks(info, allMappings, navResult)
                    .Where(l =>
                    {
                        var childInfo = allMappings.FirstOrDefault(m =>
                            string.Equals(m.ModelType.Name, l.ChildModelName,
                                System.StringComparison.Ordinal));
                        return childInfo != null && !IsCompositeInfo(childInfo);
                    })
                    .ToList();

                EmitChildJoinDispatch(sb, info, childLinks);
            }
            else
            {
                // ---- Simple (single-entity) path ----
                // Projects only client-requested fields; materializer map handles ordinals.
                var fieldMappings = ComputeFieldMappingsEager(info, composite: false);

                if (fieldMappings.Count > 0)
                {
                    sb.AppendLine("            foreach (var scalar in node.Scalars)");
                    sb.AppendLine("            {");
                    sb.AppendLine("                switch (scalar.FieldId)");
                    sb.AppendLine("                {");

                    foreach (var fm in fieldMappings)
                    {
                        sb.AppendLine($"                    case FieldId.{info.ModelType.Name}.{fm.FieldName}:");
                        sb.AppendLine($"                        builder.AddRootColumn(");
                        sb.AppendLine($"                            EntityId.{info.ModelType.Name},");
                        sb.AppendLine($"                            StorageEntityId.{fm.EntityTypeName},");
                        sb.AppendLine($"                            ColumnId.{fm.EntityTypeName}.{fm.ColumnName},");
                        sb.AppendLine($"                            node.OutputAlias, scalar.OutputAlias);");
                        sb.AppendLine("                        break;");
                    }

                    sb.AppendLine("                }");
                    sb.AppendLine("            }");
                    sb.AppendLine();
                }

                var childLinks = ComputeChildLinks(info, allMappings, navResult)
                    .Where(l =>
                    {
                        var childInfo = allMappings.FirstOrDefault(m =>
                            string.Equals(m.ModelType.Name, l.ChildModelName,
                                System.StringComparison.Ordinal));
                        return childInfo != null && !IsCompositeInfo(childInfo);
                    })
                    .ToList();

                EmitChildJoinDispatch(sb, info, childLinks);
            }

            sb.AppendLine("        }");
            sb.AppendLine();
        }

        private static void EmitChildJoinDispatch(
            StringBuilder sb,
            MappingClassInfo info,
            List<ChildLink> childLinks)
        {
            if (childLinks.Count == 0) return;

            sb.AppendLine("            foreach (var child in node.Children)");
            sb.AppendLine("            {");
            sb.AppendLine("                switch (child.EntityId)");
            sb.AppendLine("                {");

            foreach (var group in childLinks.GroupBy(l => l.ChildModelName, System.StringComparer.Ordinal))
            {
                sb.AppendLine($"                    case EntityId.{group.Key}:");
                var links = group.ToList();

                if (links.Count == 1)
                {
                    var l = links[0];
                    sb.AppendLine($"                        builder.AddJoin(");
                    sb.AppendLine($"                            EntityId.{info.ModelType.Name},");
                    sb.AppendLine($"                            StorageEntityId.{l.ParentEntityName},");
                    sb.AppendLine($"                            EntityId.{l.ChildModelName},");
                    sb.AppendLine($"                            StorageEntityId.{l.ChildEntityName},");
                    sb.AppendLine($"                            ColumnId.{l.ParentEntityName}.{l.ParentJoinColumn},");
                    sb.AppendLine($"                            ColumnId.{l.ChildEntityName}.{l.ChildJoinColumn},");
                    sb.AppendLine($"                            JoinKind.Left, child.OutputAlias);");
                }
                else
                {
                    for (var i = 0; i < links.Count; i++)
                    {
                        var l  = links[i];
                        var kw = i == 0 ? "if" : "else if";
                        sb.AppendLine($"                        {kw} (child.OutputAlias == \"{l.NavigationName}\")");
                        sb.AppendLine($"                        {{");
                        sb.AppendLine($"                            builder.AddJoin(");
                        sb.AppendLine($"                                EntityId.{info.ModelType.Name},");
                        sb.AppendLine($"                                StorageEntityId.{l.ParentEntityName},");
                        sb.AppendLine($"                                EntityId.{l.ChildModelName},");
                        sb.AppendLine($"                                StorageEntityId.{l.ChildEntityName},");
                        sb.AppendLine($"                                ColumnId.{l.ParentEntityName}.{l.ParentJoinColumn},");
                        sb.AppendLine($"                                ColumnId.{l.ChildEntityName}.{l.ChildJoinColumn},");
                        sb.AppendLine($"                                JoinKind.Left, child.OutputAlias);");
                        sb.AppendLine($"                        }}");
                    }
                }

                sb.AppendLine($"                        {group.Key}Planner.Build(child, ref builder);");
                sb.AppendLine("                        break;");
            }

            sb.AppendLine("                }");
            sb.AppendLine("            }");
        }

        private static string ToCamel(string name) =>
            string.IsNullOrEmpty(name) ? name : char.ToLowerInvariant(name[0]) + name.Substring(1);

        // ---------------------------------------------------------------
        // BuildMutation
        // ---------------------------------------------------------------

        private static void EmitBuildMutation(
            StringBuilder sb,
            MappingClassInfo info,
            ImmutableArray<MappingClassInfo> allMappings,
            List<MappingClassInfo> models,
            NavigationResolutionResult? navResult,
            bool composite)
        {
            sb.AppendLine("        public static void BuildMutation(in MutationIR node, ref MutationPlanBuilder builder)");
            sb.AppendLine("        {");

            if (composite)
            {
                EmitCompositeMutation(sb, info, allMappings, models);
            }
            else
            {
                var childLinks = ComputeChildLinks(info, allMappings, navResult)
                    .Where(l =>
                    {
                        var childInfo = allMappings.FirstOrDefault(m =>
                            string.Equals(m.ModelType.Name, l.ChildModelName,
                                System.StringComparison.Ordinal));
                        return childInfo != null && !IsCompositeInfo(childInfo);
                    })
                    .ToList();

                EmitSimpleMutation(sb, info, childLinks);
            }

            sb.AppendLine("        }");
        }

        // ---------------------------------------------------------------
        // Composite mutation
        // ---------------------------------------------------------------

        private static void EmitCompositeMutation(
            StringBuilder sb,
            MappingClassInfo info,
            ImmutableArray<MappingClassInfo> allMappings,
            List<MappingClassInfo> models)
        {
            var ownedEntityNames = new HashSet<string>(
                info.ModelToEntity
                    .Where(k => k.EntityType != null)
                    .Select(k => k.EntityType!.Name),
                System.StringComparer.Ordinal);

            var childModels = models
                .Where(m =>
                    !IsCompositeInfo(m) &&
                    !string.Equals(m.ModelType.Name, info.ModelType.Name,
                        System.StringComparison.Ordinal) &&
                    m.EntityType != null &&
                    ownedEntityNames.Contains(m.EntityType.Name))
                .Select(m => m.ModelType.Name)
                .Distinct(System.StringComparer.Ordinal)
                .OrderBy(n => n, System.StringComparer.Ordinal)
                .ToList();

            var primaryLink       = info.ModelToEntity.FirstOrDefault(k => k.IsPrimary);
            var primaryEntityName = primaryLink?.EntityType?.Name
                                    ?? throw new InvalidOperationException(
                                        $"Composite model {info.ModelType.Name} has no primary storage entity.");

            var primarySchema = allMappings
                .FirstOrDefault(m => m.EntityType != null &&
                    string.Equals(m.EntityType.Name, primaryEntityName, System.StringComparison.Ordinal))
                ?.Schema ?? info.Schema;

            var primaryFields = ComputeFieldMappingsEager(info, composite: true)
                .Where(f => string.Equals(f.EntityTypeName, primaryEntityName, System.StringComparison.Ordinal))
                .ToList();

            var conflictKeys = info.UpsertKeys
                .Where(k => !string.IsNullOrWhiteSpace(k.Key))
                .Select(k => k.Key)
                .Distinct(System.StringComparer.OrdinalIgnoreCase)
                .ToList();

            if (conflictKeys.Count == 0)
                conflictKeys = info.ModelToEntity
                    .Where(k => k.IsPrimary && !string.IsNullOrWhiteSpace(k.ToColumn))
                    .Select(k => k.ToColumn!)
                    .Distinct(System.StringComparer.OrdinalIgnoreCase)
                    .ToList();

            var conflictLiteral = conflictKeys.Count == 0
                ? "ImmutableArray<string>.Empty"
                : "ImmutableArray.Create(" + string.Join(", ", conflictKeys.Select(k => $"\"{k}\"")) + ")";

            var cteEntries = info.CteUpdateMeta;

            if (childModels.Count > 0)
            {
                sb.AppendLine("            foreach (var child in node.Children)");
                sb.AppendLine("            {");
                sb.AppendLine("                switch (child.EntityId)");
                sb.AppendLine("                {");

                foreach (var childName in childModels)
                {
                    sb.AppendLine($"                    case EntityId.{childName}:");
                    sb.AppendLine($"                        {childName}Planner.BuildMutation(child, ref builder);");
                    sb.AppendLine("                        break;");
                }

                sb.AppendLine("                }");
                sb.AppendLine("            }");
                sb.AppendLine();
            }

            sb.AppendLine("            var edgeValues = ImmutableArray.CreateBuilder<FieldValue>(node.Values.Length);");
            sb.AppendLine("            foreach (var v in node.Values)");
            sb.AppendLine("            {");
            sb.AppendLine("                switch (v.FieldId)");
            sb.AppendLine("                {");

            foreach (var fm in primaryFields)
            {
                sb.AppendLine($"                    case FieldId.{info.ModelType.Name}.{fm.FieldName}:");
                sb.AppendLine($"                        edgeValues.Add(new FieldValue(");
                sb.AppendLine($"                            ColumnId.{fm.EntityTypeName}.{fm.ColumnName},");
                sb.AppendLine($"                            v.RawValue));");
                sb.AppendLine("                        break;");
            }

            sb.AppendLine("                }");
            sb.AppendLine("            }");
            sb.AppendLine();

            sb.AppendLine($"            var cteChildren = ImmutableArray.CreateBuilder<MutationCteNode>({cteEntries.Count});");

            if (cteEntries.Count > 0)
            {
                sb.AppendLine("            foreach (var child in node.Children)");
                sb.AppendLine("            {");

                foreach (var cte in cteEntries)
                {
                    sb.AppendLine($"                if (string.Equals(child.OutputAlias, \"{cte.NavigationAlias}\", System.StringComparison.OrdinalIgnoreCase))");
                    sb.AppendLine("                {");
                    sb.AppendLine("                    string? nk = null;");
                    sb.AppendLine("                    foreach (var cv in child.Values)");
                    sb.AppendLine($"                        if (cv.FieldId == FieldId.{cte.RelatedEntityTypeName}.{cte.RelatedNaturalKeyColumn})");
                    sb.AppendLine("                        { nk = cv.RawValue; break; }");
                    sb.AppendLine("                    if (nk != null)");
                    sb.AppendLine("                        cteChildren.Add(new MutationCteNode(");
                    sb.AppendLine($"                            EntityId.{cte.RelatedEntityTypeName},");
                    sb.AppendLine($"                            StorageEntityId.{cte.RelatedEntityTypeName},");
                    sb.AppendLine($"                            \"{cte.NavigationAlias}\",");
                    sb.AppendLine($"                            ImmutableArray.Create(new FieldValue(ColumnId.{cte.RelatedEntityTypeName}.{cte.RelatedNaturalKeyColumn}, nk)),");
                    sb.AppendLine("                            ImmutableArray<MutationCteNode>.Empty));");
                    sb.AppendLine("                }");
                }

                sb.AppendLine("            }");
                sb.AppendLine();
            }

            sb.AppendLine("            builder.AddCteRoot(new MutationCteNode(");
            sb.AppendLine($"                EntityId.{info.ModelType.Name},");
            sb.AppendLine($"                StorageEntityId.{primaryEntityName},");
            sb.AppendLine($"                node.OutputAlias,");
            sb.AppendLine($"                edgeValues.ToImmutable(),");
            sb.AppendLine($"                cteChildren.ToImmutable(),");
            sb.AppendLine($"                \"{primarySchema}\",");
            sb.AppendLine($"                \"{primaryEntityName}\",");
            sb.AppendLine($"                {conflictLiteral}));");
        }

        // ---------------------------------------------------------------
        // Simple mutation
        // ---------------------------------------------------------------

        private static void EmitSimpleMutation(
            StringBuilder sb,
            MappingClassInfo info,
            List<ChildLink> childLinks)
        {
            var fieldMappings   = ComputeFieldMappingsEager(info, composite: false);
            var storageTypeName = info.EntityType?.Name ?? info.ModelType.Name;

            if (fieldMappings.Count > 0)
            {
                sb.AppendLine("            var values = ImmutableArray.CreateBuilder<FieldValue>(node.Values.Length);");
                sb.AppendLine();
                sb.AppendLine("            foreach (var v in node.Values)");
                sb.AppendLine("            {");
                sb.AppendLine("                switch (v.FieldId)");
                sb.AppendLine("                {");

                foreach (var fm in fieldMappings)
                {
                    sb.AppendLine($"                    case FieldId.{info.ModelType.Name}.{fm.FieldName}:");
                    sb.AppendLine($"                        values.Add(new FieldValue(");
                    sb.AppendLine($"                            ColumnId.{fm.EntityTypeName}.{fm.ColumnName},");
                    sb.AppendLine($"                            v.RawValue));");
                    sb.AppendLine("                        break;");
                }

                sb.AppendLine("                }");
                sb.AppendLine("            }");
                sb.AppendLine();
                sb.AppendLine($"            builder.AddRow(");
                sb.AppendLine($"                EntityId.{info.ModelType.Name},");
                sb.AppendLine($"                StorageEntityId.{storageTypeName},");
                sb.AppendLine($"                node.OutputAlias,");
                sb.AppendLine($"                values.ToImmutable());");
            }
            else
            {
                sb.AppendLine($"            builder.AddRow(");
                sb.AppendLine($"                EntityId.{info.ModelType.Name},");
                sb.AppendLine($"                StorageEntityId.{storageTypeName},");
                sb.AppendLine($"                node.OutputAlias,");
                sb.AppendLine($"                ImmutableArray<FieldValue>.Empty);");
            }

            if (childLinks.Count > 0)
            {
                sb.AppendLine();
                sb.AppendLine("            foreach (var child in node.Children)");
                sb.AppendLine("            {");
                sb.AppendLine("                switch (child.EntityId)");
                sb.AppendLine("                {");

                foreach (var group in childLinks.GroupBy(l => l.ChildModelName, System.StringComparer.Ordinal))
                {
                    sb.AppendLine($"                    case EntityId.{group.Key}:");
                    sb.AppendLine($"                        {group.Key}Planner.BuildMutation(child, ref builder);");
                    sb.AppendLine("                        break;");
                }

                sb.AppendLine("                }");
                sb.AppendLine("            }");
            }
        }

        // ---------------------------------------------------------------
        // Registry
        // ---------------------------------------------------------------

        private static void EmitRegistry(StringBuilder sb, List<MappingClassInfo> models)
        {
            sb.AppendLine("    /// <summary>");
            sb.AppendLine("    /// Single entry point for plan building.");
            sb.AppendLine("    /// </summary>");
            sb.AppendLine("    public static class PlannerRegistry");
            sb.AppendLine("    {");
            sb.AppendLine($"        public const ushort PlannerCount = {models.Count};");
            sb.AppendLine();

            sb.AppendLine("        public static void Build(ushort entityId, in SelectionIR selection, ref QueryPlanBuilder builder)");
            sb.AppendLine("        {");
            sb.AppendLine("            switch (entityId)");
            sb.AppendLine("            {");
            foreach (var m in models)
            {
                sb.AppendLine($"                case EntityId.{m.ModelType.Name}:");
                sb.AppendLine($"                    {m.ModelType.Name}Planner.Build(selection, ref builder);");
                sb.AppendLine("                    return;");
            }
            sb.AppendLine("                default: ThrowUnknownEntity(entityId); return;");
            sb.AppendLine("            }");
            sb.AppendLine("        }");
            sb.AppendLine();

            sb.AppendLine("        public static void BuildMutation(ushort entityId, in MutationIR mutation, ref MutationPlanBuilder builder)");
            sb.AppendLine("        {");
            sb.AppendLine("            switch (entityId)");
            sb.AppendLine("            {");
            foreach (var m in models)
            {
                sb.AppendLine($"                case EntityId.{m.ModelType.Name}:");
                sb.AppendLine($"                    {m.ModelType.Name}Planner.BuildMutation(mutation, ref builder);");
                sb.AppendLine("                    return;");
            }
            sb.AppendLine("                default: ThrowUnknownEntity(entityId); return;");
            sb.AppendLine("            }");
            sb.AppendLine("        }");
            sb.AppendLine();

            sb.AppendLine("        public static bool IsValidEntity(ushort entityId) => entityId < PlannerCount;");
            sb.AppendLine();

            sb.AppendLine("        public static string GetEntityName(ushort entityId) => entityId switch");
            sb.AppendLine("        {");
            foreach (var m in models)
                sb.AppendLine($"            EntityId.{m.ModelType.Name} => \"{m.ModelType.Name}\",");
            sb.AppendLine("            _ => $\"<unknown:{entityId}>\",");
            sb.AppendLine("        };");
            sb.AppendLine();

            sb.AppendLine("        private static void ThrowUnknownEntity(ushort entityId) =>");
            sb.AppendLine("            throw new global::System.InvalidOperationException(");
            sb.AppendLine("                $\"No planner registered for entity {entityId} ({GetEntityName(entityId)}).\");");
            sb.AppendLine("    }");
        }

        // ---------------------------------------------------------------
        // Field mappings
        // ---------------------------------------------------------------

        private sealed record FieldMapping(string FieldName, string EntityTypeName, string ColumnName);

        private static List<FieldMapping> ComputeFieldMappingsEager(MappingClassInfo info, bool composite)
        {
            var result = new List<FieldMapping>();

            if (!composite && info.EntityType is null) return result;

            var manualByField = new Dictionary<string, FieldInfo>(System.StringComparer.OrdinalIgnoreCase);
            foreach (var f in info.FieldMaps)
                if (!f.IsGenerated && !manualByField.ContainsKey(f.SourceName))
                    manualByField[f.SourceName] = f;

            var fkColumnSet = new HashSet<string>(System.StringComparer.OrdinalIgnoreCase);
            if (!composite && info.EntityType is not null)
                foreach (var k in info.ModelToEntity)
                    if (!SymbolEqualityComparer.Default.Equals(k.EntityType, info.EntityType) &&
                        k.FromColumn is not null)
                        fkColumnSet.Add(k.FromColumn);

            var entityProps = new Dictionary<string, Dictionary<string, IPropertySymbol>>(System.StringComparer.Ordinal);
            var seenEntities = new HashSet<string>(System.StringComparer.Ordinal);

            foreach (var link in info.ModelToEntity)
            {
                if (link.EntityType is null) continue;
                var eName = link.EntityType.Name;
                if (!seenEntities.Add(eName)) continue;

                var props = new Dictionary<string, IPropertySymbol>(System.StringComparer.OrdinalIgnoreCase);
                foreach (var member in link.EntityType.GetMembers())
                    if (member is IPropertySymbol p && p.GetMethod is not null && !p.IsStatic)
                        props[p.Name] = p;

                entityProps[eName] = props;
            }

            var modelProps = new List<IPropertySymbol>();
            foreach (var member in info.ModelType.GetMembers())
                if (member is IPropertySymbol p && p.GetMethod is not null && !p.IsStatic &&
                    IdEmitter.IsScalarProperty(p.Type))
                    modelProps.Add(p);

            modelProps.Sort((a, b) => string.Compare(a.Name, b.Name, System.StringComparison.Ordinal));

            foreach (var modelProp in modelProps)
            {
                if (fkColumnSet.Contains(modelProp.Name)) continue;

                if (manualByField.TryGetValue(modelProp.Name, out var manual))
                {
                    result.Add(new FieldMapping(
                        modelProp.Name,
                        manual.DestinationEntity ?? info.EntityType?.Name ?? string.Empty,
                        manual.DestinationName ?? modelProp.Name));
                    continue;
                }

                foreach (var kvp in entityProps)
                {
                    if (kvp.Value.TryGetValue(modelProp.Name, out var entityProp) &&
                        IdEmitter.IsScalarProperty(entityProp.Type))
                    {
                        result.Add(new FieldMapping(modelProp.Name, kvp.Key, entityProp.Name));
                        break;
                    }
                }
            }

            return result;
        }

        // ---------------------------------------------------------------
        // EntityId name resolution for composite models
        // ---------------------------------------------------------------

        private static string ResolveEntityIdName(
            string entityTypeName,
            MappingClassInfo currentModel,
            ImmutableArray<MappingClassInfo> allMappings)
        {
            if (currentModel.ModelToEntity.Any(link =>
                    string.Equals(link.EntityType?.Name, entityTypeName,
                        System.StringComparison.Ordinal)))
                return currentModel.ModelType.Name;

            var owner = allMappings
                .Where(m => !IsCompositeInfo(m))
                .FirstOrDefault(m =>
                    m.ModelToEntity.Any(link =>
                        string.Equals(link.EntityType?.Name, entityTypeName,
                            System.StringComparison.Ordinal)));

            return owner?.ModelType.Name ?? entityTypeName;
        }

        // ---------------------------------------------------------------
        // Child links
        // ---------------------------------------------------------------

        internal sealed record ChildLink(
            string NavigationName, string ChildModelName,
            string ParentEntityName, string ParentJoinColumn,
            string ChildEntityName, string ChildJoinColumn,
            bool IsCollection);

        internal static IEnumerable<ChildLink> ComputeChildLinks(
            MappingClassInfo info,
            ImmutableArray<MappingClassInfo> allMappings,
            NavigationResolutionResult? navResult)
        {
            if (info.EntityType is null) yield break;

            var seen = new HashSet<string>(System.StringComparer.OrdinalIgnoreCase);

            if (navResult is not null)
            {
                foreach (var nav in navResult.Navigations)
                {
                    var childMapping = allMappings.FirstOrDefault(m =>
                        m.IsModel &&
                        (SymbolEqualityComparer.Default.Equals(m.EntityType, nav.RelatedEntityType) ||
                         m.ModelToEntity.Any(link =>
                             link.IsPrimary &&
                             SymbolEqualityComparer.Default.Equals(link.EntityType, nav.RelatedEntityType))));

                    if (childMapping is null) continue;

                    var key = $"{childMapping.ModelType.Name}|{nav.NavigationName}";
                    if (!seen.Add(key)) continue;

                    var parentProps = new HashSet<string>(
                        info.EntityType.GetMembers()
                            .OfType<IPropertySymbol>()
                            .Select(p => p.Name),
                        System.StringComparer.OrdinalIgnoreCase);

                    var childProps = new HashSet<string>(
                        nav.RelatedEntityType.GetMembers()
                            .OfType<IPropertySymbol>()
                            .Select(p => p.Name),
                        System.StringComparer.OrdinalIgnoreCase);

                    var parentJoinCol = !string.IsNullOrWhiteSpace(nav.PrincipalKeyProperty)
                                        && parentProps.Contains(nav.PrincipalKeyProperty)
                        ? nav.PrincipalKeyProperty
                        : info.EntityType.Name + "Key";

                    string? childJoinCol = null;
                    if (!string.IsNullOrWhiteSpace(nav.ForeignKeyProperty)
                        && childProps.Contains(nav.ForeignKeyProperty))
                        childJoinCol = nav.ForeignKeyProperty;
                    else if (childProps.Contains(nav.NavigationName + "Id"))
                        childJoinCol = nav.NavigationName + "Id";
                    childJoinCol ??= parentJoinCol;

                    if (!parentProps.Contains(parentJoinCol) || !childProps.Contains(childJoinCol))
                        continue;

                    yield return new ChildLink(
                        NavigationName:   nav.NavigationName,
                        ChildModelName:   childMapping.ModelType.Name,
                        ParentEntityName: info.EntityType.Name,
                        ParentJoinColumn: parentJoinCol,
                        ChildEntityName:  nav.RelatedEntityType.Name,
                        ChildJoinColumn:  childJoinCol,
                        IsCollection:     nav.IsCollection);
                }
            }

            var parentKeyName = info.EntityType.Name + "Key";
            var parentHasKey  = info.EntityType.GetMembers().OfType<IPropertySymbol>()
                .Any(p => p.Name == parentKeyName);

            if (!parentHasKey) yield break;

            var modelProps = info.ModelType.GetMembers().OfType<IPropertySymbol>()
                .Where(p => p.GetMethod is not null && !p.IsStatic);

            foreach (var prop in modelProps)
            {
                var elementType = UnwrapCollection(prop.Type);
                var unwrapped   = UnwrapNullable(elementType);
                if (unwrapped is not INamedTypeSymbol related) continue;
                if (IdEmitter.IsScalarProperty(related)) continue;
                if (SymbolEqualityComparer.Default.Equals(related, info.ModelType)) continue;
                if (related.Name == "Wrapper") continue;

                var childMapping = allMappings.FirstOrDefault(m =>
                    SymbolEqualityComparer.Default.Equals(m.ModelType, related));
                if (childMapping is null) continue;

                var childEntityType = childMapping.EntityType
                    ?? childMapping.ModelToEntity
                           .FirstOrDefault(k => k.IsPrimary)?.EntityType;
                if (childEntityType is null) continue;

                var key = $"{childMapping.ModelType.Name}|{prop.Name}";
                if (!seen.Add(key)) continue;

                var hasFkOnChild = childEntityType.GetMembers().OfType<IPropertySymbol>()
                    .Any(p => p.Name == parentKeyName);
                if (!hasFkOnChild) continue;

                yield return new ChildLink(
                    NavigationName:   prop.Name,
                    ChildModelName:   childMapping.ModelType.Name,
                    ParentEntityName: info.EntityType.Name,
                    ParentJoinColumn: parentKeyName,
                    ChildEntityName:  childEntityType.Name,
                    ChildJoinColumn:  parentKeyName,
                    IsCollection:     IsCollectionType(prop.Type));
            }
        }

        internal static List<(string FieldName, string EntityTypeName, string ColumnName)> ComputeFieldMappingsEagerPublic(
            MappingClassInfo info, bool composite)
        {
            return ComputeFieldMappingsEager(info, composite)
                .Select(fm => (fm.FieldName, fm.EntityTypeName, fm.ColumnName))
                .ToList();
        }

        // ---------------------------------------------------------------
        // Type helpers
        // ---------------------------------------------------------------

        private static ITypeSymbol UnwrapCollection(ITypeSymbol type) =>
            type is INamedTypeSymbol { IsGenericType: true } n &&
            n.TypeArguments.Length == 1 &&
            n.Name is "List" or "IEnumerable" or "ICollection" or "IList"
                ? n.TypeArguments[0] : type;

        private static bool IsCollectionType(ITypeSymbol type) =>
            type is INamedTypeSymbol { IsGenericType: true } n &&
            n.TypeArguments.Length == 1 &&
            n.Name is "List" or "IEnumerable" or "ICollection" or "IList";

        private static ITypeSymbol UnwrapNullable(ITypeSymbol type) =>
            type is INamedTypeSymbol { OriginalDefinition.SpecialType: SpecialType.System_Nullable_T } n
                ? n.TypeArguments[0] : type;
    }
}