using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using CoffeeBeanery.GraphQL.Core.Mapping.Generators.Model;
using Microsoft.CodeAnalysis;

namespace CoffeeBeanery.GraphQL.Core.Mapping.Generators.Emit;

internal static class QueryMaterializerEmitter
{
    public static string Emit(ImmutableArray<MappingClassInfo> mappings)
    {
        var sb = new StringBuilder();

        sb.AppendLine("#nullable enable");
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine();

        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Data.Common;");
        sb.AppendLine("using CoffeeBeanery.GraphQL.Core.Runtime;");

        var namespaces =
            mappings
                .Where(x => x.ModelType != null)
                .Select(x => x.ModelType!.ContainingNamespace.ToDisplayString())
                .Where(x => !string.IsNullOrWhiteSpace(x))
                .Distinct()
                .OrderBy(x => x);

        foreach (var ns in namespaces)
        {
            sb.AppendLine($"using {ns};");
        }

        sb.AppendLine();

        sb.AppendLine("namespace CoffeeBeanery.GraphQL.Core.Runtime;");
        sb.AppendLine();

        var models =
            mappings
                .Where(x => x.ModelType != null)
                .OrderBy(x => x.ModelType!.Name)
                .ToList();


        foreach (var info in models)
        {
            EmitRowMaterializer(sb, info);
            sb.AppendLine();

            EmitResultBuilder(sb, info);
            sb.AppendLine();
        }


        EmitRegistries(sb, models);

        return sb.ToString();
    }


    private static void EmitRowMaterializer(
        StringBuilder sb,
        MappingClassInfo info)
    {
        var model = info.ModelType!.Name;

        sb.AppendLine($"public static class {model}RowMaterializer");
        sb.AppendLine("{");

        sb.AppendLine($"    public static {model} Materialize(DbDataReader reader, ushort[] columnMap)");
        sb.AppendLine("    {");
        sb.AppendLine($"        var model = new {model}();");
        sb.AppendLine();

        foreach (var field in info.FieldMaps)
        {
            if (field.IsNavigationKey)
                continue;

            sb.AppendLine("        {");
            sb.AppendLine($"            var ordinal = columnMap[ColumnId.{field.DestinationEntity}.{field.DestinationName}];");
            sb.AppendLine();
            sb.AppendLine("            if (ordinal != ushort.MaxValue)");
            sb.AppendLine($"                model.{field.SourceName} = {ReadValue(field)};");
            sb.AppendLine();
            sb.AppendLine("        }");
            sb.AppendLine();
        }

        sb.AppendLine("        return model;");
        sb.AppendLine("    }");
        sb.AppendLine("}");
    }
    
    private static string ReadValue(FieldInfo field)
    {
        var type = field.PropertyType;

        var isNullable = false;
        ITypeSymbol underlying = type;


        if (type is INamedTypeSymbol named &&
            named.OriginalDefinition.SpecialType == SpecialType.System_Nullable_T)
        {
            isNullable = true;
            underlying = named.TypeArguments[0];
        }


        if (underlying.TypeKind == TypeKind.Enum)
        {
            var enumName =
                underlying.ToDisplayString(
                    SymbolDisplayFormat.FullyQualifiedFormat);

            if (isNullable)
            {
                return
                    $"reader.IsDBNull(ordinal) " +
                    $"? default({type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)}) " +
                    $": ({enumName})Convert.ToInt32(reader.GetValue(ordinal))";
            }


            return
                $"reader.IsDBNull(ordinal) " +
                $"? default({enumName}) " +
                $": ({enumName})Convert.ToInt32(reader.GetValue(ordinal))";
        }


        var display =
            type.ToDisplayString(
                SymbolDisplayFormat.FullyQualifiedFormat);


        return
            $"reader.IsDBNull(ordinal) " +
            $"? default({display}) " +
            $": ({display})reader.GetValue(ordinal)";
    }



    private static void EmitResultBuilder(
    StringBuilder sb,
    MappingClassInfo info)
{
    var model = info.ModelType!.Name;

    sb.AppendLine($"public static class {model}ResultBuilder");
    sb.AppendLine("{");

    sb.AppendLine($"    public static List<{model}> Build(");
    sb.AppendLine("        RowLayout layout,");
    sb.AppendLine("        List<object?[]> rows)");
    sb.AppendLine("    {");

    sb.AppendLine($"        var results = new List<{model}>();");
    sb.AppendLine();

    sb.AppendLine("        foreach (var row in rows)");
    sb.AppendLine("        {");

    sb.AppendLine($"            var model = new {model}();");
    sb.AppendLine();

    sb.AppendLine($"            var rootIndex = layout.IndexOf(\"{model}\");");
    sb.AppendLine("            if (rootIndex >= 0 && row[rootIndex] != null)");
    sb.AppendLine("            {");
    sb.AppendLine($"                model = ({model})row[rootIndex]!;");
    sb.AppendLine("            }");
    sb.AppendLine();

    var emittedProperties = new HashSet<string>(StringComparer.OrdinalIgnoreCase);

    var children =
        info.ModelChildren
            .Where(x => x.To != "GraphModel")
            .ToList();

    foreach (var child in children)
    {
        var property = ResolveNavigationProperty(info, child.NavigationName);

        if (property == null)
            continue;

        if (!emittedProperties.Add(property))
            continue;

        var variable = "childIndex_" + property;

        // Use the navigation alias (e.g. "InnerCustomer"/"OuterCustomer"),
        // not the target model name (e.g. "Customer") — RowLayout
        // segments are keyed by output alias. Two navigations to the
        // same target model (as here, both to Customer) would otherwise
        // collide on the same layout.IndexOf("Customer") lookup and
        // both resolve to the same (or no) segment.
        sb.AppendLine($"            var {variable} = layout.IndexOf(\"{child.NavigationName}\");");
        sb.AppendLine();

        sb.AppendLine($"            if ({variable} >= 0 && row[{variable}] != null)");
        sb.AppendLine("            {");

        var propertySymbol =
            info.ModelType!
                .GetMembers()
                .OfType<IPropertySymbol>()
                .FirstOrDefault(x => x.Name == property);

        if (propertySymbol != null &&
            propertySymbol.Type is INamedTypeSymbol named &&
            named.IsGenericType &&
            (
                named.ConstructedFrom.ToDisplayString() == "System.Collections.Generic.List<T>" ||
                named.ConstructedFrom.ToDisplayString() == "System.Collections.Generic.ICollection<T>" ||
                named.ConstructedFrom.ToDisplayString() == "System.Collections.Generic.IEnumerable<T>"
            ))
        {
            sb.AppendLine($"                model.{property}.Add(({child.To})row[{variable}]!);");
        }
        else
        {
            sb.AppendLine($"                model.{property} = ({child.To})row[{variable}]!;");
        }

        sb.AppendLine("            }");
        sb.AppendLine();
    }

    sb.AppendLine("            results.Add(model);");
    sb.AppendLine("        }");
    sb.AppendLine();
    sb.AppendLine("        return results;");
    sb.AppendLine("    }");
    sb.AppendLine("}");
}
    
        private static string? ResolveNavigationProperty(
        MappingClassInfo info,
        string navigation)
    {
        var property =
            info.ModelType!
                .GetMembers()
                .OfType<IPropertySymbol>()
                .FirstOrDefault(x =>
                    string.Equals(
                        x.Name,
                        navigation,
                        StringComparison.OrdinalIgnoreCase));


        if (property == null)
            return null;


        return property.Name;
    }



    private static void EmitRegistries(
        StringBuilder sb,
        List<MappingClassInfo> models)
    {
        EmitMaterializerRegistry(sb, models);

        sb.AppendLine();

        EmitResultBuilderRegistry(sb, models);
    }



    private static void EmitMaterializerRegistry(
        StringBuilder sb,
        List<MappingClassInfo> models)
    {
        sb.AppendLine(
            "public static class MaterializerRegistry");

        sb.AppendLine("{");


        sb.AppendLine(
            "    public static object Materialize(");

        sb.AppendLine(
            "        ushort storageEntityId,");

        sb.AppendLine(
            "        System.Data.Common.DbDataReader reader,");

        sb.AppendLine(
            "        ushort[] columnMap)");

        sb.AppendLine("    {");


        sb.AppendLine(
            "        switch(storageEntityId)");

        sb.AppendLine(
            "        {");


        var entities =
            models
                .Where(x => x.EntityType != null)
                .GroupBy(x => x.EntityType!.Name)
                .Select(x => x.First());


        foreach (var info in entities)
        {
            var model =
                info.ModelType!.Name;


            sb.AppendLine(
                $"            case StorageEntityId.{info.EntityType!.Name}:");


            sb.AppendLine(
                $"                return {model}RowMaterializer.Materialize(reader, columnMap);");
        }


        sb.AppendLine();


        sb.AppendLine(
            "            default:");

        sb.AppendLine(
            "                throw new ArgumentException($\"Unknown storage entity id {storageEntityId}\");");


        sb.AppendLine(
            "        }");


        sb.AppendLine(
            "    }");


        sb.AppendLine(
            "}");

    }



    private static void EmitResultBuilderRegistry(
        StringBuilder sb,
        List<MappingClassInfo> models)
    {
        sb.AppendLine(
            "public static class ResultBuilderRegistry");

        sb.AppendLine("{");


        sb.AppendLine(
            "    public static List<T> Build<T>(");


        sb.AppendLine(
            "        ushort rootEntityId,");


        sb.AppendLine(
            "        RowLayout layout,");


        sb.AppendLine(
            "        List<object?[]> rows)");


        sb.AppendLine("    {");


        sb.AppendLine(
            "        switch(rootEntityId)");

        sb.AppendLine(
            "        {");


        var entities =
            models
                .GroupBy(x => x.ModelType!.Name)
                .Select(x => x.First());


        foreach (var info in entities)
        {
            var model =
                info.ModelType!.Name;


            sb.AppendLine(
                $"            case EntityId.{model}:");


            sb.AppendLine(
                $"                return (List<T>)(object){model}ResultBuilder.Build(layout, rows);");
        }


        sb.AppendLine();


        sb.AppendLine(
            "            default:");

        sb.AppendLine(
            "                throw new ArgumentException($\"Unknown entity runtime id {rootEntityId}\");");


        sb.AppendLine(
            "        }");


        sb.AppendLine(
            "    }");


        sb.AppendLine(
            "}");

    }
}