using System.ComponentModel;
using System.Text.Json;
using Foundgine.Execution;
using Foundgine.Intent.Json;
using ModelContextProtocol.Server;
using ExecutionContext = Foundgine.Execution.ExecutionContext;

namespace Foundgine.MCP;

/// <summary>
/// MCP transport adapter for the Foundgine semantic application contract.
/// MCP arguments are translated into Foundgine inputs; MCP never owns domain
/// semantics, authorization, planning, or provider execution.
/// </summary>
[McpServerToolType]
public sealed class FoundgineMcpTools
{
    private static readonly JsonSerializerOptions JsonOptions = new(JsonSerializerDefaults.Web);

    private readonly IFoundgine _foundgine;
    private readonly JsonReadIntentAdapter _adapter;
    private readonly Func<ExecutionContext> _contextFactory;

    public FoundgineMcpTools(
        IFoundgine foundgine,
        JsonReadIntentAdapter? adapter = null,
        Func<ExecutionContext>? contextFactory = null)
    {
        _foundgine = foundgine ?? throw new ArgumentNullException(nameof(foundgine));
        _adapter = adapter ?? new JsonReadIntentAdapter();
        _contextFactory = contextFactory ?? (() => new ExecutionContext());
    }

    /// <summary>
    /// Returns the canonical capability contract generated by Foundgine for the
    /// current caller. Discovery does not grant authorization.
    /// </summary>
    [McpServerTool(Name = "foundgine_capabilities")]
    [Description("Discover the Foundgine semantic capability contract available to the current caller. Discovery is descriptive; authorization is re-evaluated during execution.")]
    public string DescribeCapabilities() =>
        JsonSerializer.Serialize(_foundgine.DescribeCapabilityContract(), JsonOptions);

    /// <summary>
    /// Executes provider-neutral read intent through the Foundgine pipeline.
    /// Authentication, tenant and authorization context remain host-owned.
    /// </summary>
    [McpServerTool(Name = "foundgine_query")]
    [Description("Execute a provider-neutral Foundgine read intent as JSON. Use only entities, fields and relationships from foundgine_capabilities. Never supply tenant, identity, authorization predicates, SQL, provider or connection details.")]
    public async Task<string> ExecuteQueryAsync(
        [Description("JSON read intent containing rootEntity, selections, and optional filter/order/limit/offset/after. Do not include authentication, tenant or authorization context.")] string intentJson,
        CancellationToken cancellationToken = default)
    {
        if (string.IsNullOrWhiteSpace(intentJson))
            throw new ArgumentException("Intent JSON is required.", nameof(intentJson));

        var intent = _adapter.Parse(intentJson);
        var result = await _foundgine.ExecuteAsync(
            intent,
            _contextFactory(),
            cancellationToken);

        return JsonSerializer.Serialize(new
        {
            rows = result.Rows.Select(row => row.Values).ToArray(),
            pageInfo = result.PageInfo,
            evidence = result.Evidence,
            receipt = result.Receipt
        }, JsonOptions);
    }
}
