<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>Foundgine.Aot</RootNamespace>
    <AssemblyName>Foundgine.Aot</AssemblyName>
    <IsPackable>true</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Foundgine.Abstractions/Foundgine.Abstractions.csproj" />
    <ProjectReference Include="../Foundgine.Metadata/Foundgine.Metadata.csproj" />
  </ItemGroup>
</Project>
