@startuml
card GraphQL
card JSON
card MCP
card AI
card Code
card Foundgine
card "Foundgine.Providers.Storage.Sql / Foundgine.Providers.Storage.InMemory / ..." as Provider
GraphQL --> Foundgine
JSON --> Foundgine
MCP --> Foundgine
AI --> Foundgine
Code --> Foundgine
Foundgine --> Provider
@enduml
