name: Build & Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.0.x"

      - name: Restore
        run: dotnet restore Foundgine.sln

      - name: Build
        run: dotnet build Foundgine.sln --no-restore --configuration Release

      - name: Test
        run: dotnet test Foundgine.sln --no-build --configuration Release --verbosity normal


      - name: Pack (NuGet validation)
        run: ./eng/pack.sh
